\getenv migration_password RUNTIME_MIGRATOR_PASSWORD

CREATE ROLE law_schema_migrator LOGIN NOINHERIT PASSWORD :'migration_password';
ALTER DATABASE law_contract_runtime OWNER TO law_schema_migrator;

CREATE ROLE law_app_command NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE law_app_worker NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE law_app_query NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE ROLE law_audit_append NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
