"""Exact F05 transport addition; old contracts retain their original pins."""
from copy import deepcopy
import hashlib,json
def digest(value):return hashlib.sha256(json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
PATHS={'/api/v1/opportunities/{opportunityId}/followup-attempts': 'b92e4dfd2a48d370c07d79a602fa4de3cd198bb12d992185426584d259053b94', '/api/v1/opportunities/{opportunityId}/quotes/followup-attempts': 'a6ee14a1f09e892a17e50cc896f76638cf2a7b34e02e89f47eadce6903943dd3'}
SCHEMAS={'FollowupAttemptFactRefV1': 'ad8c0b513d0a5ed5374cb88bbd28788af186b9dff3ba577a866126e0dff7c485', 'RecordFollowupAttemptV1': 'afae4dd4de41de5ddff2da581e3c09165d234d5185876f8dc01c38355d8b5a67', 'FollowupAttemptReceiptV1': '7a51ca3b3390cdec0599edd5991020f8955f3c7478e25bea98bd69d88c171142', 'FollowupAttemptContextV1': '107d3e0638c8be7d7e4aa80fac071d792e3dc967d7d61dd49397f40e66268ec1'}
CHANGED={'PublicFactRef': '32256a02526d071656c4e39e38e84c2d67f950e0f67f059a1fba683ddcb687b8'}
PREVIOUS={'PublicFactRef': {'oneOf': [{'$ref': '#/components/schemas/R2ContractPreparationRequestFactRefV1'}, {'$ref': '#/components/schemas/R2ContractPreparationDecisionFactRefV1'}, {'$ref': '#/components/schemas/R2ContractFactRefV1'}, {'$ref': '#/components/schemas/R2ContractDraftFactRefV1'}, {'$ref': '#/components/schemas/R2ContractRevisionFactRefV1'}, {'$ref': '#/components/schemas/R2ContractReviewRequestFactRefV1'}, {'$ref': '#/components/schemas/R2ContractReviewDecisionFactRefV1'}, {'$ref': '#/components/schemas/R2ContractApprovalRequestFactRefV1'}, {'$ref': '#/components/schemas/R2ContractApprovalDecisionFactRefV1'}, {'$ref': '#/components/schemas/OpportunityMaterialUploadFactRefV1'}, {'$ref': '#/components/schemas/OpportunityMaterialVersionFactRefV1'}, {'$ref': '#/components/schemas/OpportunityCustomerDraftFactRefV1'}, {'$ref': '#/components/schemas/OpportunityCustomerConfirmationFactRefV1'}, {'$ref': '#/components/schemas/OpportunityClosureFactRefV1'}, {'$ref': '#/components/schemas/OwnerExceptionFactRefV1'}, {'$ref': '#/components/schemas/OwnerExceptionValidationFactRefV1'}, {'$ref': '#/components/schemas/IdentityPrincipalFactRefV1'}, {'$ref': '#/components/schemas/OrganizationUnitFactRefV1'}, {'$ref': '#/components/schemas/AppointmentFactRefV1'}, {'$ref': '#/components/schemas/AuthorityGrantFactRefV1'}, {'$ref': '#/components/schemas/LeadFactRef'}, {'$ref': '#/components/schemas/ActionDraftFactRef'}, {'$ref': '#/components/schemas/TaskOccurrenceFactRef'}, {'$ref': '#/components/schemas/DecisionRecordFactRef'}, {'$ref': '#/components/schemas/LeadAssignmentFactRef'}, {'$ref': '#/components/schemas/LeadContactResultFactRef'}, {'$ref': '#/components/schemas/OpportunityProgressFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteDraftFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteRevisionFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteApprovalRequestFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteApprovalDecisionFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteIssueFactRefV1'}, {'$ref': '#/components/schemas/R2QuoteResponseFactRefV1'}, {'$ref': '#/components/schemas/ContractPreparationWorkflowFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureDraftFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureArrangementFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureSubmissionFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureVerificationFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureArchiveFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureRevisionReturnFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureWorkflowFactRefV1'}, {'$ref': '#/components/schemas/R2ContractSignatureHandoffFactRefV1'}, {'$ref': '#/components/schemas/R2QuotePreparationIntentFactRefV1'}]}}
def attempt_projection(document):
 try:
  from scripts.baseline.r2_quote_termination_transport_contract import termination_projection
 except ModuleNotFoundError:
  from r2_quote_termination_transport_contract import termination_projection
 result=termination_projection(document);paths=result['paths'];schemas=result['components']['schemas']
 if not any(k in paths for k in PATHS) and not any(k in schemas for k in SCHEMAS):return result
 for section,pins in ((paths,PATHS),(schemas,SCHEMAS)):
  for key,pin in pins.items():
   if digest(section.pop(key,None))!=pin:raise ValueError('F05 exact attempt contract required: '+key)
 for key,pin in CHANGED.items():
  if digest(schemas[key])!=pin:raise ValueError('F05 exact attempt addition required: '+key)
  schemas[key]=deepcopy(PREVIOUS[key])
 return result
