"""Exact additive R2_OPPORTUNITY_SUBMIT_V1 paths and typed payloads."""
from copy import deepcopy
import json
PROFILE='R2_OPPORTUNITY_SUBMIT_V1'
PATHS={'/api/v1/tasks/{taskId}/opportunity-progress-draft': {'put': {'tags': ['R2OpportunityCommands'],
                                                               'operationId': 'saveOpportunityProgressDraft',
                                                               'summary': 'Save the current opportunity progress draft',
                                                               'security': [{'publicBearer': []}],
                                                               'x-on-behalf-selection': 'ACCEPT_VALID_HUMAN',
                                                               'x-tenant-source': 'ACTOR_CONTEXT',
                                                               'x-subject-binding': 'TASK_AND_DRAFT',
                                                               'x-precondition-mode': 'exactly-one-of-if-none-match-star-or-if-match-draft-etag',
                                                               'x-error-codes': ['VALIDATION_FAILED',
                                                                                 'IDEMPOTENCY_KEY_REQUIRED',
                                                                                 'IDEMPOTENCY_KEY_INVALID',
                                                                                 'UNAUTHENTICATED',
                                                                                 'NOT_AUTHORIZED',
                                                                                 'APPOINTMENT_INACTIVE',
                                                                                 'NOT_FOUND',
                                                                                 'COMMAND_PAYLOAD_CONFLICT',
                                                                                 'TASK_NOT_OPEN',
                                                                                 'TASK_ALREADY_COMPLETED',
                                                                                 'DRAFT_DIGEST_MISMATCH',
                                                                                 'STALE_TASK',
                                                                                 'STALE_DRAFT',
                                                                                 'STALE_SUBJECT',
                                                                                 'DRAFT_PRECONDITION_REQUIRED',
                                                                                 'RATE_LIMITED',
                                                                                 'INTERNAL_ERROR',
                                                                                 'SERVICE_UNAVAILABLE'],
                                                               'parameters': [{'$ref': '#/components/parameters/TaskIdPath'},
                                                                              {'$ref': '#/components/parameters/IdempotencyKey'},
                                                                              {'$ref': '#/components/parameters/DraftIfMatch'},
                                                                              {'$ref': '#/components/parameters/DraftCreateIfNoneMatch'},
                                                                              {'$ref': '#/components/parameters/AppointmentSelection'},
                                                                              {'$ref': '#/components/parameters/OnBehalfAppointmentSelection'}],
                                                               'requestBody': {'required': True,
                                                                               'content': {'application/json': {'schema': {'$ref': '#/components/schemas/SaveOpportunityProgressDraftV1'}}}},
                                                               'responses': {'200': {'description': 'Existing Draft '
                                                                                                    'updated.',
                                                                                     'headers': {'Location': {'$ref': '#/components/headers/ReceiptLocation'},
                                                                                                 'ETag': {'$ref': '#/components/headers/DraftETagHeader'}},
                                                                                     'content': {'application/json': {'schema': {'$ref': '#/components/schemas/OpportunityProgressDraftWriteResultV1'}}}},
                                                                             '201': {'description': 'Draft created.',
                                                                                     'headers': {'Location': {'$ref': '#/components/headers/ReceiptLocation'},
                                                                                                 'ETag': {'$ref': '#/components/headers/DraftETagHeader'}},
                                                                                     'content': {'application/json': {'schema': {'$ref': '#/components/schemas/OpportunityProgressDraftWriteResultV1'}}}},
                                                                             '400': {'$ref': '#/components/responses/BadRequestProblem'},
                                                                             '401': {'$ref': '#/components/responses/PublicUnauthorizedProblem'},
                                                                             '403': {'$ref': '#/components/responses/ForbiddenProblem'},
                                                                             '404': {'$ref': '#/components/responses/NotFoundProblem'},
                                                                             '409': {'$ref': '#/components/responses/ConflictProblem'},
                                                                             '412': {'$ref': '#/components/responses/PreconditionFailedProblem'},
                                                                             '428': {'$ref': '#/components/responses/PreconditionRequiredProblem'},
                                                                             '429': {'$ref': '#/components/responses/RateLimitedProblem'},
                                                                             '500': {'$ref': '#/components/responses/InternalProblem'},
                                                                             '503': {'$ref': '#/components/responses/UnavailableProblem'}}}},
 '/api/v1/tasks/{taskId}/commands/record-opportunity-progress': {'post': {'tags': ['R2OpportunityCommands'],
                                                                          'operationId': 'recordOpportunityProgress',
                                                                          'summary': 'Confirm saved opportunity '
                                                                                     'progress and schedule its '
                                                                                     'successor',
                                                                          'security': [{'publicBearer': []}],
                                                                          'x-on-behalf-selection': 'ACCEPT_VALID_HUMAN',
                                                                          'x-tenant-source': 'ACTOR_CONTEXT',
                                                                          'x-subject-binding': 'TASK_AND_OPPORTUNITY',
                                                                          'x-error-codes': ['VALIDATION_FAILED',
                                                                                            'IDEMPOTENCY_KEY_REQUIRED',
                                                                                            'IDEMPOTENCY_KEY_INVALID',
                                                                                            'UNAUTHENTICATED',
                                                                                            'NOT_AUTHORIZED',
                                                                                            'APPOINTMENT_INACTIVE',
                                                                                            'NOT_FOUND',
                                                                                            'COMMAND_PAYLOAD_CONFLICT',
                                                                                            'TASK_NOT_OPEN',
                                                                                            'TASK_ALREADY_COMPLETED',
                                                                                            'DRAFT_DIGEST_MISMATCH',
                                                                                            'STALE_TASK',
                                                                                            'STALE_DRAFT',
                                                                                            'STALE_SUBJECT',
                                                                                            'TASK_PRECONDITION_REQUIRED',
                                                                                            'RATE_LIMITED',
                                                                                            'INTERNAL_ERROR',
                                                                                            'SERVICE_UNAVAILABLE'],
                                                                          'parameters': [{'$ref': '#/components/parameters/TaskIdPath'},
                                                                                         {'$ref': '#/components/parameters/IdempotencyKey'},
                                                                                         {'$ref': '#/components/parameters/TaskIfMatch'},
                                                                                         {'$ref': '#/components/parameters/AppointmentSelection'},
                                                                                         {'$ref': '#/components/parameters/OnBehalfAppointmentSelection'}],
                                                                          'requestBody': {'required': True,
                                                                                          'content': {'application/json': {'schema': {'$ref': '#/components/schemas/RecordOpportunityProgressV1'}}}},
                                                                          'responses': {'200': {'description': 'The '
                                                                                                               'Task '
                                                                                                               'command '
                                                                                                               'completed '
                                                                                                               'with a '
                                                                                                               'Lead '
                                                                                                               'Contact '
                                                                                                               'Result '
                                                                                                               'digest '
                                                                                                               'fact.',
                                                                                                'headers': {'Location': {'$ref': '#/components/headers/ReceiptLocation'}},
                                                                                                'content': {'application/json': {'schema': {'$ref': '#/components/schemas/OpportunityProgressCommandReceiptV1'}}}},
                                                                                        '400': {'$ref': '#/components/responses/BadRequestProblem'},
                                                                                        '401': {'$ref': '#/components/responses/PublicUnauthorizedProblem'},
                                                                                        '403': {'$ref': '#/components/responses/ForbiddenProblem'},
                                                                                        '404': {'$ref': '#/components/responses/NotFoundProblem'},
                                                                                        '409': {'$ref': '#/components/responses/ConflictProblem'},
                                                                                        '412': {'$ref': '#/components/responses/PreconditionFailedProblem'},
                                                                                        '422': {'$ref': '#/components/responses/UnprocessableProblem'},
                                                                                        '428': {'$ref': '#/components/responses/PreconditionRequiredProblem'},
                                                                                        '429': {'$ref': '#/components/responses/RateLimitedProblem'},
                                                                                        '500': {'$ref': '#/components/responses/InternalProblem'},
                                                                                        '503': {'$ref': '#/components/responses/UnavailableProblem'}}}}}
SCHEMAS={'OpportunityProgressValuesV1': {'type': 'object',
                                 'additionalProperties': False,
                                 'required': ['progressTypeCode', 'progressSummary', 'occurredAt', 'nextCheckAt'],
                                 'properties': {'progressTypeCode': {'type': 'string',
                                                                     'enum': ['PHONE_CONNECTED',
                                                                              'CLIENT_VISIT',
                                                                              'MEETING',
                                                                              'SITE_VISIT',
                                                                              'WECHAT_CONNECTED']},
                                                'progressSummary': {'$ref': '#/components/schemas/SafeText2000'},
                                                'occurredAt': {'$ref': '#/components/schemas/Instant'},
                                                'nextCheckAt': {'$ref': '#/components/schemas/Instant'}}},
 'SaveOpportunityProgressDraftV1': {'type': 'object',
                                    'additionalProperties': False,
                                    'required': ['actionCode', 'schemaVersion', 'values'],
                                    'properties': {'actionCode': {'type': 'string',
                                                                  'const': 'RECORD_OPPORTUNITY_PROGRESS'},
                                                   'schemaVersion': {'$ref': '#/components/schemas/SchemaVersionV1'},
                                                   'values': {'$ref': '#/components/schemas/OpportunityProgressValuesV1'}}},
 'RecordOpportunityProgressV1': {'type': 'object',
                                 'additionalProperties': False,
                                 'required': ['progressTypeCode',
                                              'progressSummary',
                                              'occurredAt',
                                              'nextCheckAt',
                                              'draftId',
                                              'expectedDraftRevision',
                                              'draftDigest'],
                                 'properties': {'progressTypeCode': {'type': 'string',
                                                                     'enum': ['PHONE_CONNECTED',
                                                                              'CLIENT_VISIT',
                                                                              'MEETING',
                                                                              'SITE_VISIT',
                                                                              'WECHAT_CONNECTED']},
                                                'progressSummary': {'$ref': '#/components/schemas/SafeText2000'},
                                                'occurredAt': {'$ref': '#/components/schemas/Instant'},
                                                'nextCheckAt': {'$ref': '#/components/schemas/Instant'},
                                                'draftId': {'$ref': '#/components/schemas/Uuid'},
                                                'expectedDraftRevision': {'$ref': '#/components/schemas/Revision'},
                                                'draftDigest': {'$ref': '#/components/schemas/Digest32'}}},
 'OpportunityProgressDraftProjectionV1': {'type': 'object',
                                          'additionalProperties': False,
                                          'required': ['draftId',
                                                       'draftRevision',
                                                       'actionCode',
                                                       'schemaVersion',
                                                       'values',
                                                       'digest',
                                                       'updatedAt',
                                                       'editable'],
                                          'properties': {'draftId': {'$ref': '#/components/schemas/Uuid'},
                                                         'draftRevision': {'$ref': '#/components/schemas/Revision'},
                                                         'actionCode': {'type': 'string',
                                                                        'const': 'RECORD_OPPORTUNITY_PROGRESS'},
                                                         'schemaVersion': {'$ref': '#/components/schemas/SchemaVersionV1'},
                                                         'values': {'$ref': '#/components/schemas/OpportunityProgressValuesV1'},
                                                         'digest': {'$ref': '#/components/schemas/Digest32'},
                                                         'updatedAt': {'$ref': '#/components/schemas/Instant'},
                                                         'editable': {'type': 'boolean'}}},
 'OpportunityProgressDraftWriteResultV1': {'type': 'object',
                                           'additionalProperties': False,
                                           'required': ['receipt', 'draft', 'preconditions'],
                                           'properties': {'receipt': {'$ref': '#/components/schemas/ActionDraftCommandReceipt'},
                                                          'draft': {'$ref': '#/components/schemas/OpportunityProgressDraftProjectionV1'},
                                                          'preconditions': {'$ref': '#/components/schemas/PreconditionTokens'}}},
 'OpportunityProgressCommandReceiptV1': {'type': 'object',
                                         'additionalProperties': False,
                                         'required': ['commandId', 'receiptId', 'outcome', 'completedAt', 'resultFact'],
                                         'properties': {'commandId': {'$ref': '#/components/schemas/Uuid'},
                                                        'receiptId': {'$ref': '#/components/schemas/Uuid'},
                                                        'outcome': {'type': 'string',
                                                                    'enum': ['SUCCEEDED', 'NO_CHANGE']},
                                                        'completedAt': {'$ref': '#/components/schemas/Instant'},
                                                        'resultFact': {'$ref': '#/components/schemas/OpportunityProgressFactRefV1'}}}}
def submit_transport_projection(document):
    result=deepcopy(document)
    schemas=result['components']['schemas']
    if not any(p in result['paths'] for p in PATHS) and not any(n in schemas for n in SCHEMAS):return result
    for actual,expected in ((result['paths'],PATHS),(schemas,SCHEMAS)):
        for name,value in expected.items():
            if json.dumps(actual.pop(name,None),sort_keys=True)!=json.dumps(value,sort_keys=True):raise ValueError(f'{PROFILE}: exact {name} required')
    return result
