import { useEffect, useRef, useState } from 'react';
import type { Candidate, DispositionInput, OwnerException, OwnerExceptionTransport } from '../../lib/ownerExceptionTransport';
import type { WorkbenchSession } from '../../lib/api';
import { deadline } from './OwnerExceptionDetail';
export function OwnerExceptionDisposition({detail,api,session,blocked,onSubmit,onFailure,onEditingChange}:{detail:OwnerException;api:OwnerExceptionTransport;session:WorkbenchSession;blocked:boolean;onSubmit:(kind:'transfer'|'coordinate',body:DispositionInput)=>void;onFailure:()=>void;onEditingChange?:(editing:boolean)=>void}){
 const [mode,setMode]=useState<'detail'|'transfer'|'coordinate'|'confirm'>('detail');const [candidates,setCandidates]=useState<Candidate[]>([]);const [cursor,setCursor]=useState<string>();const [loading,setLoading]=useState(false);const [receiver,setReceiver]=useState('');const [reason,setReason]=useState('');const [due,setDue]=useState('');const [error,setError]=useState('');const abort=useRef(new AbortController());
 useEffect(()=>{onEditingChange?.(mode!=='detail');return()=>onEditingChange?.(false);},[mode,onEditingChange]);
 useEffect(()=>{abort.current=new AbortController();return()=>abort.current.abort();},[]);
 const load=async(more=false)=>{setLoading(true);setError('');try{const p=await api.candidates(session,detail,abort.current.signal,more?cursor:undefined);if(abort.current.signal.aborted)return;if(p.exception.id!==detail.exception.id||p.exception.revision!==detail.exception.revision)throw Error();setCandidates(old=>more?[...old,...p.items]:p.items);setCursor(p.nextCursor);setMode('transfer');}catch{if(!abort.current.signal.aborted)onFailure();}finally{setLoading(false);}};
 const submit=(kind:'transfer'|'coordinate')=>{if(detail.exception.revision===undefined||detail.opportunity.revision===undefined){onFailure();return;}onSubmit(kind,{opportunityId:detail.opportunity.id,expectedOpportunityRevision:detail.opportunity.revision,exceptionId:detail.exception.id,expectedExceptionRevision:detail.exception.revision,expectedBasis:detail.basis,expectedTask:detail.task??null,expectedWait:detail.wait??null,reason:reason.trim(),...(kind==='transfer'?{receiverAppointmentId:receiver}:{reviewDueAt:new Date(due).toISOString()})});};
 if(blocked)return null;
 if(detail.state==='RESOLVED')return <p>此异常已处理，无需再次安排接手人。业务事项按当前责任继续办理。</p>;
 if(detail.state==='NO_LONGER_APPLICABLE')return <p>此异常已不适用，无需再次处置。</p>;
 if(!detail.allowedActions.length)return <p>你可以查看此事项；由有权主管安排接手人。</p>;
 return <div className="compact-confirm">{mode==='detail'?<>{detail.allowedActions.includes('TRANSFER')&&<button className="primary-action" disabled={loading} onClick={()=>void load()}>{loading?'正在读取合格接手人…':'安排接手人'}</button>}{detail.allowedActions.includes('COORDINATE')&&<button className={detail.allowedActions.includes('TRANSFER')?'link-button':'primary-action'} onClick={()=>setMode('coordinate')}>登记协调安排</button>}</>:mode==='confirm'?<><h3>请确认本次交接</h3><p>接手人：{candidates.find(c=>c.appointmentId===receiver)?.displayName||'已选择的合格接手人'}</p><p>{deadline(detail)}</p><p>{reason}</p><button className="primary-action" onClick={()=>submit('transfer')}>确认交接</button><button onClick={()=>setMode('transfer')}>返回修改</button><p className="help">交接不会把业务事项标记为已完成。</p></>:<><h3>{mode==='transfer'?'安排接手人':'登记协调安排'}</h3>{mode==='transfer'&&(candidates.length?<><label>接手人<select value={receiver} onChange={e=>setReceiver(e.target.value)}><option value="">请选择合格接手人</option>{candidates.map(c=><option key={c.appointmentId} value={c.appointmentId}>{c.displayName||'任职信息暂不可用'}{c.organizationLabel?` · ${c.organizationLabel}`:''}</option>)}</select></label>{cursor&&<button disabled={loading} onClick={()=>void load(true)}>读取更多接手人</button>}<p>仅列出当前可以承接此事项的人。</p></>:<><p>当前没有合格接手人。</p>{detail.allowedActions.includes('COORDINATE')&&<button onClick={()=>setMode('coordinate')}>登记协调安排</button>}</>)}{(mode==='coordinate'||candidates.length>0)&&<><label>{mode==='coordinate'?'协调说明':'处置说明'}<textarea value={reason} maxLength={2000} onChange={e=>setReason(e.target.value)} /></label>{mode==='coordinate'&&<><label>下次核对时间<input type="datetime-local" value={due} onChange={e=>setDue(e.target.value)}/></label><p>记录安排后，该异常继续保留。</p></>}<button className="primary-action" disabled={!reason.trim()||(mode==='transfer'?!receiver:!due)} onClick={()=>{if(mode==='transfer')setMode('confirm');else if(new Date(due).getTime()<=Date.now())setError('请选择未来的核对时间。');else submit('coordinate');}}>{mode==='transfer'?'核对本次交接':'记录协调安排'}</button></>}{error&&<p role="alert">{error}</p>}<button onClick={()=>{setMode('detail');setReason('');setReceiver('');setDue('');}}>返回详情</button></>}</div>;
}


