import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {describe,it,expect,vi} from 'vitest';
import {OwnerExceptionPage} from './OwnerExceptionPage';
import type {OwnerException,OwnerExceptionTransport} from '../../lib/ownerExceptionTransport';
import {testSession} from '../../test/fixtures';
import {TransportError} from '../../lib/sessionTransport';
import {RecoveryStore} from '../session/recoveryMarker';
const id='11111111-1111-4111-8111-111111111111';
export const detail:OwnerException={exception:{type:'OPPORTUNITY_OWNER_EXCEPTION',id,revision:1},opportunity:{type:'OPPORTUNITY',id,revision:0},basis:{type:'OPPORTUNITY',id,revision:0},currentOwnerAppointmentId:id,frozenOwnerAppointmentId:id,opportunityLabel:'海宁公司',currentOwnerLabel:'陈晓',frozenOwnerLabel:'陈晓',state:'ACTIVE',reasonCodes:['OWNER_INACTIVE'],firstObservedAt:'2026-09-15T01:00:00Z',lastObservedAt:'2026-09-15T01:00:00Z',allowedActions:['TRANSFER','COORDINATE'],etag:'tag'};
function api(d=detail){return {recovery:new RecoveryStore(sessionStorage),list:vi.fn().mockResolvedValue({items:[d]}),detail:vi.fn().mockResolvedValue(d),candidates:vi.fn().mockResolvedValue({items:[{appointmentId:id,displayName:'王蕾'}],exception:d.exception,etag:'tag'}),operations:vi.fn().mockResolvedValue({items:[]}),write:vi.fn().mockResolvedValue({}),receipt:vi.fn().mockResolvedValue({})} satisfies OwnerExceptionTransport;}
async function select(){fireEvent.click(await screen.findByRole('button',{name:'海宁公司'}));await screen.findByRole('heading',{name:'海宁公司'});}
async function confirmation(){await select();fireEvent.click(screen.getByRole('button',{name:'安排接手人'}));fireEvent.change(await screen.findByLabelText('接手人'),{target:{value:id}});fireEvent.change(screen.getByLabelText('处置说明'),{target:{value:'继续跟进'}});fireEvent.click(screen.getByRole('button',{name:'核对本次交接'}));}
describe('owner exception management',()=>{
 it('requires candidate selection then one explicit transfer and sends exact versions',async()=>{const a=api();render(<OwnerExceptionPage session={testSession()} api={a}/>);await confirmation();expect(a.write).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'确认交接'}));await waitFor(()=>expect(a.write).toHaveBeenCalledTimes(1));expect(a.write.mock.calls[0]?.[1]).toMatchObject({kind:'transfer',body:{expectedExceptionRevision:1,expectedTask:null,expectedWait:null,receiverAppointmentId:id,reason:'继续跟进'}});});
 it('unknown result exposes only original result recovery, no new submission',async()=>{const a=api();a.write.mockRejectedValue(new TypeError('network'));render(<OwnerExceptionPage session={testSession()} api={a}/>);await confirmation();fireEvent.click(screen.getByRole('button',{name:'确认交接'}));await screen.findByRole('button',{name:'核对原结果'});expect(screen.queryByRole('button',{name:'安排接手人'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'核对原结果'}));await waitFor(()=>expect(a.receipt).toHaveBeenCalledTimes(1));expect(a.write).toHaveBeenCalledTimes(1);});
 it('read-only has no disposition controls and preserves waiting explanation',async()=>{const a=api({...detail,allowedActions:[],resumeDueAt:'2026-09-16T07:00:00Z'});render(<OwnerExceptionPage session={testSession()} api={a}/>);await select();expect(screen.getByText(/不提前开始办理/)).toBeVisible();expect(screen.queryByRole('button',{name:'安排接手人'})).toBeNull();expect(a.candidates).not.toHaveBeenCalled();});
 it('empty authorized candidates only allow coordination',async()=>{const a=api();a.candidates.mockResolvedValue({items:[],exception:detail.exception,etag:'tag'});render(<OwnerExceptionPage session={testSession()} api={a}/>);await select();fireEvent.click(screen.getByRole('button',{name:'安排接手人'}));await screen.findByText('当前没有合格接手人。');expect(screen.queryByRole('button',{name:'核对本次交接'})).toBeNull();expect(screen.getByRole('button',{name:'登记协调安排'})).toBeVisible();});
 it('operations uses only separate restricted endpoint',async()=>{const a=api();render(<OwnerExceptionPage session={testSession()} api={a} operations/>);await screen.findByRole('heading',{name:'当前授权范围内没有待处置异常'});expect(a.operations).toHaveBeenCalledTimes(1);expect(a.list).not.toHaveBeenCalled();expect(a.detail).not.toHaveBeenCalled();});
 it('identity change clears the previous detail immediately',async()=>{const a=api();const session=testSession();const {rerender}=render(<OwnerExceptionPage session={session} api={a}/>);await select();a.list.mockImplementation(()=>new Promise(()=>{}));rerender(<OwnerExceptionPage session={{...session,identityEpoch:session.identityEpoch+1}} api={a}/>);expect(screen.queryByRole('heading',{name:'海宁公司'})).toBeNull();});
 it('coordination sends future review without claiming resolution',async()=>{const a=api();render(<OwnerExceptionPage session={testSession()} api={a}/>);await select();fireEvent.click(screen.getByRole('button',{name:'登记协调安排'}));fireEvent.change(screen.getByLabelText('协调说明'),{target:{value:'核对当前授权'}});fireEvent.change(screen.getByLabelText('下次核对时间'),{target:{value:'2099-09-16T10:00'}});fireEvent.click(screen.getByRole('button',{name:'记录协调安排'}));await screen.findByText('协调安排已记录，该异常仍待解决。');expect(a.write.mock.calls[0]?.[1]).toMatchObject({kind:'coordinate',body:{reason:'核对当前授权'}});});
 it('proven stale write clears inputs and requires refresh',async()=>{const a=api();a.write.mockRejectedValue(new TransportError(412,'STALE_SUBJECT',true));render(<OwnerExceptionPage session={testSession()} api={a}/>);await confirmation();fireEvent.click(screen.getByRole('button',{name:'确认交接'}));await screen.findByText(/本次办理依据已变化，输入已清除/);expect(screen.queryByRole('button',{name:'核对原结果'})).toBeNull();expect(screen.getByRole('button',{name:'刷新列表'})).toBeEnabled();expect(screen.queryByDisplayValue('继续跟进')).toBeNull();});});


it('opens the exact team exception beyond the first page and guards return during disposition editing',async()=>{const a=api();a.list.mockResolvedValue({items:[]});const back=vi.fn();render(<OwnerExceptionPage session={testSession()} api={a} initialExceptionId={id} onReturn={back}/>);await screen.findByRole('heading',{name:'海宁公司'});expect(a.detail).toHaveBeenCalledTimes(1);expect(a.detail.mock.calls[0]?.[1]).toBe(id);expect(screen.getByRole('button',{name:'返回团队待办'})).toBeEnabled();fireEvent.click(screen.getByRole('button',{name:'登记协调安排'}));expect(screen.getByRole('button',{name:'返回团队待办'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'返回团队待办'}));expect(back).not.toHaveBeenCalled();expect(a.write).not.toHaveBeenCalled();});
