import {BusinessNavigation,BusinessNavigationContext} from '../workcard/BusinessNavigation';
import { useContext, useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { Scales } from '@phosphor-icons/react/Scales';
import type { WorkbenchSession } from '../../lib/api';
import { TransportError } from '../../lib/sessionTransport';
import { createOwnerExceptionTransport, type OwnerExceptionTransport, type OwnerException, type OperationsException, type OwnerExceptionWrite, type DispositionInput } from '../../lib/ownerExceptionTransport';
import { OwnerExceptionDetail, stateLabels, reasonLabels, when } from './OwnerExceptionDetail';
import { OwnerExceptionDisposition } from './OwnerExceptionDisposition';
import './ownerExceptions.css';
export function OwnerExceptionPage({session,api,sessionActions,operations=false,initialExceptionId,onReturn}:{session:WorkbenchSession;api?:OwnerExceptionTransport;sessionActions?:ReactNode;operations?:boolean;initialExceptionId?:string;onReturn?:()=>void}){return <OwnerExceptionSession key={`${session.actorScopeKey}:${session.identityEpoch}:${operations}`} session={session} api={api} sessionActions={sessionActions} operations={operations} initialExceptionId={initialExceptionId} onReturn={onReturn}/>;}
function OwnerExceptionSession({session,api,sessionActions,operations,initialExceptionId,onReturn}:{session:WorkbenchSession;api?:OwnerExceptionTransport;sessionActions?:ReactNode;operations:boolean;initialExceptionId?:string;onReturn?:()=>void}){
 const [editing,setEditing]=useState(false);const initialOpened=useRef(false);
 const transport=useRef(api??createOwnerExceptionTransport()).current;const [items,setItems]=useState<OwnerException[]>([]);const [ops,setOps]=useState<OperationsException[]>([]);const [detail,setDetail]=useState<OwnerException>();const [cursor,setCursor]=useState<string>();const [busy,setBusy]=useState(false);const [unknown,setUnknown]=useState(false);const [message,setMessage]=useState('');const [failed,setFailed]=useState(false);const lock=useRef(false);const pending=useRef<OwnerExceptionWrite | undefined>(undefined);const lifetime=useRef(new AbortController());const readVersion=useRef(0);
 const {registerLeaveGuard}=useContext(BusinessNavigationContext);
 useEffect(()=>{registerLeaveGuard?.(next=>{if(!busy&&!unknown&&!editing)next();});return()=>registerLeaveGuard?.(null);},[registerLeaveGuard,busy,unknown,editing]);
 const current=()=>session.isCurrent()&&!lifetime.current.signal.aborted;
 const refresh=async(more=false)=>{const version=++readVersion.current;setBusy(true);setFailed(false);setDetail(undefined);if(!more){setItems([]);setOps([]);}try{if(operations){const p=await transport.operations(session,lifetime.current.signal,more?cursor:undefined);if(!current()||version!==readVersion.current)return;setOps(old=>more?[...old,...p.items]:p.items);setCursor(p.nextCursor);}else{const p=await transport.list(session,lifetime.current.signal,more?cursor:undefined);if(!current()||version!==readVersion.current)return;setItems(old=>more?[...old,...p.items]:p.items);setCursor(p.nextCursor);if(initialExceptionId&&!initialOpened.current){initialOpened.current=true;await select(initialExceptionId);}}}catch{if(current()){setItems([]);setOps([]);setFailed(true);setMessage('暂时无法读取团队异常，请重新读取或核对当前访问权限。');}}finally{if(current()&&version===readVersion.current)setBusy(false);}};
 useEffect(()=>{lifetime.current=new AbortController();try{const marker=transport.recovery.read();if(marker){setUnknown(true);setMessage('仍有未确认的操作，请先核对原结果。');}else void refresh();}catch{setUnknown(true);setMessage('恢复线索不可用，请核对原结果。');}return()=>lifetime.current.abort();},[]);
 useEffect(()=>{const protect=(e:BeforeUnloadEvent)=>{if(unknown||busy){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[unknown,busy]);
 const select=async(id:string)=>{const version=++readVersion.current;setDetail(undefined);setMessage('');setBusy(true);try{const d=await transport.detail(session,id,lifetime.current.signal);if(current()&&version===readVersion.current){setDetail(d);setItems(old=>old.some(item=>item.exception.id===d.exception.id)?old:[d,...old]);}}catch{if(current()){setItems([]);setFailed(true);setMessage('当前记录不可用，请重新读取当前事项。');}}finally{if(current()&&version===readVersion.current)setBusy(false);}};
 const write=async(kind:'transfer'|'coordinate',body:DispositionInput)=>{if(lock.current||unknown)return;lock.current=true;const original={key:crypto.randomUUID(),kind,body:structuredClone(body)};pending.current=original;setBusy(true);setMessage('正在确认本次安排…');try{await transport.write(session,original,lifetime.current.signal);if(!current())return;pending.current=undefined;setMessage(kind==='transfer'?'交接已确认，业务事项继续办理。':'协调安排已记录，该异常仍待解决。');await refresh();}catch(e){if(current()){setUnknown(!(e instanceof TransportError&&e.provenOutcome));setDetail(undefined);setItems([]);setFailed(e instanceof TransportError&&e.provenOutcome);setMessage(e instanceof TransportError&&e.provenOutcome?"本次办理依据已变化，输入已清除，请刷新列表后重新核对。":e instanceof TransportError&&[401,403,404].includes(e.status)?'当前无法核对结果，请使用有权任职核对原结果。':'本次结果尚未确认。请核对原结果，不要重新提交。');}}finally{lock.current=false;if(current())setBusy(false);}};
 const recover=async()=>{if(lock.current)return;lock.current=true;setBusy(true);try{await transport.receipt(session,lifetime.current.signal);if(!current())return;setUnknown(false);pending.current=undefined;setMessage('原结果已确认，正在重新读取当前事项。');await refresh();}catch(e){if(current()){if(e instanceof TransportError&&e.provenOutcome){setUnknown(false);setFailed(true);setMessage('原请求未成功，请刷新列表后重新核对。');}else setMessage('原结果仍无法确认。请稍后继续核对原结果。');}}finally{lock.current=false;if(current())setBusy(false);}};
 return <><header className="app-header"><div className="brand"><Scales size={30} aria-hidden="true"/><span>律所工作助手</span></div><div className="session-actions">{sessionActions??session.displayName}{onReturn&&<button disabled={busy||unknown||editing} onClick={onReturn}>返回团队待办</button>}</div></header><div className="owner-exceptions admin-shell"><BusinessNavigation active="team" disabled={busy||unknown||editing} onTeam={onReturn}/><main className="admin-main"><div className="admin-heading"><div><h1>团队待办</h1><p>{operations?'仅显示当前授权组织范围内的运行异常摘要。':'定位未能继续办理的事项，落实下一位接手人。'}</p></div>{!unknown&&<button disabled={busy} onClick={()=>void refresh()}>刷新列表</button>}</div>{message&&<p role={failed||unknown?'alert':'status'} className="feedback">{message}</p>}{unknown?<button className="primary-action" disabled={busy} onClick={()=>void recover()}>核对原结果</button>:busy?<p role="status">正在读取当前事项…</p>:failed?null:!items.length&&!ops.length?<section className="empty"><h2>当前授权范围内没有待处置异常</h2><p>这不代表全部业务已完成。后续异常出现时在此显示。</p></section>:<div className="ledger-split"><section className="list-pane" aria-label="团队事项列表"><table className="record-table"><thead><tr><th>{operations?'异常编号':'待办事项'}</th><th>状态</th></tr></thead><tbody>{operations?ops.map((o,i)=><tr key={o.exceptionId}><td>异常 {i+1}<small>{o.reasonCodes.map(x=>reasonLabels[x]||'责任依据待核对').join('；')}</small></td><td>{stateLabels[o.state]}</td></tr>):items.map(d=><tr key={d.exception.id} className={detail?.exception.id===d.exception.id?'selected':''}><td><button onClick={()=>void select(d.exception.id)}>{d.opportunityLabel||'商机责任异常'}</button></td><td data-label="状态">{stateLabels[d.state]}</td></tr>)}</tbody></table>{cursor&&<button onClick={()=>void refresh(true)}>读取更多事项</button>}<p className="list-foot">仅显示当前授权范围内的事项。</p></section><section className="detail-pane" aria-label="当前记录详情">{operations?<>{ops.map((o,i)=><article key={o.exceptionId}><h2>异常 {i+1}</h2><p>{o.reasonCodes.map(x=>reasonLabels[x]||'责任依据待核对').join('；')}</p><p>组织范围：{o.organizationLabel}</p><p>发现时间：{when(o.firstObservedAt)}</p><p>最近核对：{when(o.lastObservedAt)}</p><p>{o.repairGuidance}</p></article>)}</>:detail?<><OwnerExceptionDetail detail={detail}/><OwnerExceptionDisposition key={`${detail.exception.id}:${detail.exception.revision}`} detail={detail} api={transport} session={session} onEditingChange={setEditing} blocked={busy||unknown} onSubmit={(k,b)=>void write(k,b)} onFailure={()=>{setDetail(undefined);setMessage('本次办理依据已变化，旧人选与处置说明已清除，请重新读取当前事项。');}}/></>:<p>请选择一项团队待办。</p>}</section></div>}</main></div></>;
}



