import {it,expect,vi} from 'vitest';
import {createContractsTransport,validContractContext,type ContractWrite} from './contractsTransport';
import {RecoveryStore} from '../features/session/recoveryMarker';
import {testSession,taskId,selectorId} from '../test/fixtures';
const context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{id:taskId,revision:0},customerConfirmation:{id:taskId,revision:0},contract:null,draft:null,workflow:null,preparation:null,review:null,approvals:[],allowedActions:['REQUEST_CONTRACT_PREPARATION'],blockers:[],history:[],receiptBoundary:null,customerName:'合成客户',readonly:false};
const write:ContractWrite={key:taskId,opportunityId:selectorId,command:'REQUEST_CONTRACT_PREPARATION',body:{expectedOpportunityRevision:0,responsibilityBasis:context.responsibilityBasis,customerConfirmation:context.customerConfirmation,expectedContract:null,expectedDraft:null,expectedVersion:null,expectedWorkflow:null,values:{reason:'私密申请原因'}}};
it('requires exact independent review state before rendering a termination card',()=>{
 const termination={selector:context.opportunity,state:'REVIEW_REQUIRED',summary:'待核对',occurredAt:'2026-09-25T00:00:00Z',task:context.opportunity,ownerAppointmentId:taskId,ownerLabel:'主管',dueAt:null,history:[],independentBasis:'a'.repeat(64),independentState:{paymentRecorded:true,executionRecorded:false,transferRecorded:false}};
 expect(validContractContext({...context,termination},selectorId)).toBe(true);
 expect(validContractContext({...context,termination:{...termination,independentState:null}},selectorId)).toBe(false);
 expect(validContractContext({...context,termination:{...termination,independentBasis:null}},selectorId)).toBe(false);
});
it.each(['END_CONTRACT_NEGOTIATION','REQUEST_CONTRACT_TERMINATION_REVIEW','RECORD_CONTRACT_TERMINATION_REVIEW'] as const)('%s recovers its immutable disposition receipt without repeating the write',async command=>{
 const recovery=new RecoveryStore(sessionStorage),s=testSession();recovery.reserveWrite(taskId,command,s.actorScopeKey,{});const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-25T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_NEGOTIATION_DISPOSITION',factRef:'r'.repeat(43),revision:0}})));
 await createContractsTransport(recovery,fetcher).receipt(s,new AbortController().signal);expect(recovery.read()).toBeNull();expect(fetcher).toHaveBeenCalledOnce();expect(fetcher.mock.calls[0][1]?.method).toBe('GET');
});
it.each(['VALIDATION_FAILED','CONTRACT_RESPONSIBILITY_REQUIRED','CONTRACT_HANDLING_PAUSED','STALE_SUBJECT'])('a proven %s receipt releases recovery without an automatic resubmit',async rejectionCode=>{
 const recovery=new RecoveryStore(sessionStorage),s=testSession();recovery.reserveWrite(taskId,'RECORD_CONTRACT_TERMINATION_REVIEW',s.actorScopeKey,{});const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-25T00:00:00Z',outcome:'REJECTED',rejectionCode})));
 await expect(createContractsTransport(recovery,fetcher).receipt(s,new AbortController().signal)).rejects.toMatchObject({provenOutcome:true});expect(recovery.read()).toBeNull();expect(fetcher).toHaveBeenCalledOnce();
});
it('rejects wrong target, missing authority and malformed document before rendering',()=>{expect(validContractContext(context,selectorId)).toBe(true);expect(validContractContext(context,taskId)).toBe(false);expect(validContractContext({...context,responsibilityBasis:null},selectorId)).toBe(false);expect(validContractContext({...context,allowedActions:['SIGN_CONTRACT']},selectorId)).toBe(false);expect(validContractContext({...context,draft:{selector:context.opportunity,document:{commercial:{lines:'bad'}}}},selectorId)).toBe(false);});
it('unknown contract write persists only recovery identity and recovers original receipt',async()=>{const receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-21T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_PREPARATION_REQUEST',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(new Response(JSON.stringify(receipt))),recovery=new RecoveryStore(sessionStorage),api=createContractsTransport(recovery,fetcher),s=testSession();await expect(api.write(s,write,new AbortController().signal)).rejects.toThrow();expect(fetcher.mock.calls[0][0]).toBe('/api/v1/opportunities/'+selectorId+'/contracts/preparation-requests');expect(fetcher.mock.calls[0][1]?.headers).toMatchObject({'Idempotency-Key':taskId});expect(Object.keys(recovery.read()!).sort()).toEqual(['actorScopeKey','commandId','commandType','recordedAt']);expect(sessionStorage.getItem('r1.pending-command')).not.toContain('私密');await api.receipt(s,new AbortController().signal);expect(fetcher.mock.calls[1][0]).toBe('/api/v1/commands/'+taskId+'/receipt');expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();});
it('pending receipt cannot terminate the original recovery marker',async()=>{const recovery=new RecoveryStore(sessionStorage),s=testSession(),fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({state:'PENDING'}),{status:202})),api=createContractsTransport(recovery,fetcher);recovery.reserveWrite(taskId,write.command,s.actorScopeKey,{});await expect(api.receipt(s,new AbortController().signal)).rejects.toThrow();expect(recovery.read()?.commandId).toBe(taskId);});
it('stale contract evidence receipt is terminal without resending',async()=>{const recovery=new RecoveryStore(sessionStorage),s=testSession(),fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-21T00:00:00Z',outcome:'REJECTED',rejectionCode:'STALE_EVIDENCE'}))),api=createContractsTransport(recovery,fetcher);recovery.reserveWrite(taskId,'FORM_CONTRACT',s.actorScopeKey,{});await expect(api.receipt(s,new AbortController().signal)).rejects.toMatchObject({status:412,provenOutcome:true});expect(recovery.read()).toBeNull();expect(fetcher).toHaveBeenCalledOnce();});
it('task resolution validates its authority-scoped context rather than trusting a route',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({opportunityId:selectorId,context:{...context,opportunity:{id:taskId,revision:0}}}))),api=createContractsTransport(new RecoveryStore(sessionStorage),fetcher);await expect(api.taskContext(testSession(),taskId,new AbortController().signal)).rejects.toThrow('合同责任无法核对');});
it('document download names the exact contract and version',async()=>{const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response('exact bytes')),api=createContractsTransport(new RecoveryStore(sessionStorage),fetcher);await api.download(testSession(),selectorId,{contractId:taskId,versionId:selectorId},new AbortController().signal);expect(fetcher.mock.calls[0][0]).toBe('/api/v1/opportunities/'+selectorId+'/contracts/'+taskId+'/versions/'+selectorId+'/document');expect(fetcher.mock.calls[0][1]?.cache).toBe('no-store');});

it('accepts a real started anchor with no formed revision and commercial-only content',()=>{const commercial={currency:'CNY',scope:'范围',lines:[{description:'费用',amountMinor:1,discount:false}],conditionalFee:null,paymentTerms:'付款约定'};expect(validContractContext({...context,partySnapshotDigest:null,contract:{selector:context.opportunity,currentRevision:null,version:0,document:{commercial},source:{kind:'ACCEPTED_QUOTE',selector:{id:selectorId,hash:'A'.repeat(43)}},stage:'PREPARE'}},selectorId)).toBe(true);});

it('accepted quote source requires its exact digest instead of a fabricated revision',()=>{const commercial={currency:'CNY',scope:'范围',lines:[{description:'费用',amountMinor:1,discount:false}],conditionalFee:null,paymentTerms:'付款'};const contract={selector:context.opportunity,currentRevision:null,version:0,document:{commercial},source:{kind:'ACCEPTED_QUOTE',selector:context.opportunity},stage:'PREPARE'};expect(validContractContext({...context,contract},selectorId)).toBe(false);expect(validContractContext({...context,contract:{...contract,source:{kind:'ACCEPTED_QUOTE',selector:{id:selectorId,hash:'f'.repeat(64)}}}},selectorId)).toBe(false);expect(validContractContext({...context,contract:{...contract,source:{kind:'DIRECT_AUTHORIZATION',selector:context.opportunity}}},selectorId)).toBe(true);});
it('rejects malformed signature context instead of rendering untrusted signing actions',()=>{expect(validContractContext({...context,signature:{workflow:{selector:context.opportunity,stage:'MADE_UP'},parties:[],arrangements:[],submissions:[],draft:null,handoff:null}},selectorId)).toBe(false);});
it('recovers exact signature receipt without resending material or signing command',async()=>{const receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-21T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_SIGNATURE_SUBMISSION',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(new Response(JSON.stringify(receipt))),recovery=new RecoveryStore(sessionStorage),api=createContractsTransport(recovery,fetcher),s=testSession();await expect(api.write(s,{...write,command:'SUBMIT_CONTRACT_SIGNATURE'},new AbortController().signal)).rejects.toThrow();expect(fetcher.mock.calls[0][0]).toContain('/signature-submissions');await api.receipt(s,new AbortController().signal);expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();});
it('a signature receipt with a fabricated mutable revision cannot clear recovery',async()=>{const recovery=new RecoveryStore(sessionStorage),s=testSession();recovery.reserveWrite(taskId,'SUBMIT_CONTRACT_SIGNATURE',s.actorScopeKey,{});const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-21T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_SIGNATURE_SUBMISSION',factRef:'r'.repeat(43),revision:1}})));await expect(createContractsTransport(recovery,fetcher).receipt(s,new AbortController().signal)).rejects.toThrow();expect(recovery.read()?.commandId).toBe(taskId);});

it('validates immutable firm bindings and history before rendering',()=>{
 const signature={workflow:{selector:context.opportunity,stage:'ARRANGE',task:null,ownerAppointmentId:null},parties:[{id:selectorId,label:'本律所',templateSigningPartyId:taskId}],arrangements:[],submissions:[],draft:null,handoff:null,historyEntries:[]};
 expect(validContractContext({...context,signature},selectorId)).toBe(true);
 expect(validContractContext({...context,signature:{...signature,parties:[{...signature.parties[0],templateSigningPartyId:'invalid'}]}},selectorId)).toBe(false);
 expect(validContractContext({...context,signature:{...signature,historyEntries:[{id:taskId,label:'核验',summary:'VERIFIED',occurredAt:'invalid',actorLabel:'核验人'}]}},selectorId)).toBe(false);
});

it('a disposition receipt cannot invent a mutable revision',async()=>{
 const recovery=new RecoveryStore(sessionStorage),s=testSession();recovery.reserveWrite(taskId,'END_CONTRACT_NEGOTIATION',s.actorScopeKey,{});
 const fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-25T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_NEGOTIATION_DISPOSITION',factRef:'r'.repeat(43),revision:1}})));
 await expect(createContractsTransport(recovery,fetcher).receipt(s,new AbortController().signal)).rejects.toThrow();expect(recovery.read()?.commandId).toBe(taskId);
});

it('execution verification recovers the original receipt without resending a lost response',async()=>{
 sessionStorage.clear();const recovery=new RecoveryStore(sessionStorage),s=testSession();
 const receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-26T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_EXECUTION_VERIFICATION',factRef:'r'.repeat(43),revision:0}};
 const fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(new Response(JSON.stringify(receipt)));
 const api=createContractsTransport(recovery,fetcher);
 await expect(api.write(s,{...write,command:'VERIFY_CONTRACT_EXECUTION_CONDITIONS',body:{...write.body,values:{expectedExecutionWorkflow:context.opportunity,approvedConditionsChecked:true,archiveAndConditionsComplete:true}}},new AbortController().signal)).rejects.toThrow();
 expect(fetcher.mock.calls[0][0]).toBe('/api/v1/opportunities/'+selectorId+'/contracts/execution-verifications');expect(recovery.read()?.commandType).toBe('VERIFY_CONTRACT_EXECUTION_CONDITIONS');
 await api.receipt(s,new AbortController().signal);expect(fetcher).toHaveBeenCalledTimes(2);expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();
});

it('rejects malformed finance chains before exposing payment actions',()=>{expect(validContractContext({...context,payments:[{stage:'COMPLETE',allowedActions:['RECORD_CONTRACT_RECEIPT_REVIEW']}]},selectorId)).toBe(false);});
it('recovers a receipt review without resending the money confirmation',async()=>{const receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-27T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'CONTRACT_PAYMENT_REVIEW',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(new Response(JSON.stringify(receipt))),recovery=new RecoveryStore(sessionStorage),api=createContractsTransport(recovery,fetcher),s=testSession();await expect(api.write(s,{...write,command:'RECORD_CONTRACT_RECEIPT_REVIEW'},new AbortController().signal)).rejects.toThrow();expect(fetcher.mock.calls[0][0]).toContain('/receipt-reviews');await api.receipt(s,new AbortController().signal);expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();});

it('sends contract filters and cursor to the server with a bounded default page',async()=>{
 const fetcher=vi.fn<typeof fetch>().mockImplementation(async()=>new Response(JSON.stringify({items:[],nextCursor:null})));
 const api=createContractsTransport(new RecoveryStore(sessionStorage),fetcher),s=testSession(),signal=new AbortController().signal;
 await api.list(s,signal,'opaque-next',{search:'远方客户 & 公司',state:'待审批'});
 const query=new URL(String(fetcher.mock.calls[0][0]),'https://local.test').searchParams;
 expect(query.get('limit')).toBe('20');expect(query.get('cursor')).toBe('opaque-next');
 expect(query.get('search')).toBe('远方客户 & 公司');expect(query.get('state')).toBe('待审批');
});
