import {createSessionTransport, TransportError, matchesReceipt, type WorkbenchSession} from './sessionTransport';
import {RecoveryStore,uuidPattern} from '../features/session/recoveryMarker';
import {provenWriteOutcome} from '../features/session/recoveryOutcome';

type S=import('../generated/api/schema').components['schemas'];
export type CustomerSelector=S['OpportunityCustomerSelectorV1'];
export type CustomerParty=S['OpportunityCustomerPartyV1'];
export type CustomerParticipant=S['OpportunityCustomerParticipantV1'];
export type CustomerDocument=S['OpportunityCustomerDocumentV1'];
export type CustomerEntry=S['OpportunityCustomerVersionV1'];
export type CustomerContext=S['OpportunityCustomerContextV1'];
export type CustomerCommand='SAVE_OPPORTUNITY_CUSTOMER_DRAFT'|'CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS';
export class CustomerValidationError extends TransportError {
 readonly fieldMessages:string[];
 constructor(fields:unknown){super(400,'VALIDATION_FAILED',true);const labels:Record<string,string>={participants:'参与方',party:'准确主体',newParty:'新主体',profileChange:'共用主体修改',name:'主体名称',distinctIdentityConfirmed:'独立主体核实',sharedProfileImpactConfirmed:'共用资料影响核实',matterName:'事项名称',customerGoal:'客户目标',serviceScope:'拟服务范围',knownConstraints:'已知限制',unverifiedOpponentName:'对方名称（待核实）',contactName:'联系人',contactPhone:'联系电话'};const reasons:Record<string,string>={REQUIRED:'请补齐',INVALID_FORMAT:'格式不正确',OUT_OF_RANGE:'超出允许范围',NOT_ALLOWED:'当前不能采用',CONDITION_FAILED:'请重新核实'};this.fieldMessages=Array.isArray(fields)?fields.flatMap(f=>{if(!obj(f)||typeof f.pointer!=='string')return [];const part=f.pointer.split('/').reverse().find(p=>labels[p]);return part?[labels[part]+'：'+(reasons[String(f.code)]??'请重新核实')]:[];}):[];}
}
export interface CustomerWrite {key:string;opportunityId:string;command:CustomerCommand;body:{expectedOpportunityRevision:number;responsibilityBasis:CustomerContext['responsibilityBasis'];expectedDraft:CustomerSelector|null;expectedConfirmation?:CustomerSelector|null;document?:CustomerDocument}}
const obj=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,names:string[])=>Object.keys(v).every(k=>names.includes(k));
const str=(v:unknown)=>typeof v==='string';
const sel=(v:unknown)=>obj(v)&&exact(v,['id','revision'])&&typeof v.id==='string'&&uuidPattern.test(v.id)&&Number.isSafeInteger(v.revision)&&Number(v.revision)>=0;
export const validCustomerParty=(v:unknown):v is CustomerParty=>obj(v)&&exact(v,['selector','kind','name'])&&sel(v.selector)&&['ORGANIZATION','NATURAL_PERSON'].includes(String(v.kind))&&str(v.name)&&!!v.name;
export function validCustomerDocument(v:unknown):v is CustomerDocument {return obj(v)&&exact(v,['participants','unknownOpponent','unverifiedOpponentName','matterName','customerGoal','serviceScope','knownConstraints','contactName','contactPhone'])&&['matterName','customerGoal','serviceScope','knownConstraints','contactName','contactPhone'].every(k=>str(v[k]))&&(v.unverifiedOpponentName==null||(typeof v.unverifiedOpponentName==='string'&&v.unverifiedOpponentName.length<=200))&&typeof v.unknownOpponent==='boolean'&&Array.isArray(v.participants)&&v.participants.every(p=>obj(p)&&exact(p,['role','party','newParty','profileChange'])&&['CLIENT','OPPONENT','OTHER'].includes(String(p.role))&&(p.party===null||sel(p.party))&&(p.newParty===null||(obj(p.newParty)&&exact(p.newParty,['kind','name','distinctIdentityConfirmed'])&&['ORGANIZATION','NATURAL_PERSON'].includes(String(p.newParty.kind))&&str(p.newParty.name)&&typeof p.newParty.distinctIdentityConfirmed==='boolean'))&&(p.profileChange===null||(obj(p.profileChange)&&exact(p.profileChange,['name','sharedProfileImpactConfirmed'])&&str(p.profileChange.name)&&typeof p.profileChange.sharedProfileImpactConfirmed==='boolean')));}
const entry=(v:unknown)=>obj(v)&&exact(v,['selector','factRef','document','actorAppointmentId','createdAt','partySnapshots'])&&typeof v.factRef==='string'&&v.factRef.length>=16&&v.factRef.length<=512&&Array.isArray(v.partySnapshots)&&v.partySnapshots.every(validCustomerParty)&&sel(v.selector)&&validCustomerDocument(v.document)&&str(v.actorAppointmentId)&&str(v.createdAt)&&Number.isFinite(Date.parse(String(v.createdAt)));
export function validCustomerContext(v:unknown,id:string):v is CustomerContext {return obj(v)&&exact(v,['opportunity','responsibilityBasis','editable','closed','currentOwnerAppointmentId','currentOwnerLabel','canCreateParty','canMaintainSharedParty','source','draft','draftConsumed','confirmation','history','parties'])&&sel(v.opportunity)&&(v.opportunity as CustomerSelector).id===id&&(v.responsibilityBasis===null||sel(v.responsibilityBasis))&&['editable','closed','canCreateParty','canMaintainSharedParty','draftConsumed'].every(k=>typeof v[k]==='boolean')&&str(v.currentOwnerAppointmentId)&&(v.currentOwnerLabel===undefined||str(v.currentOwnerLabel))&&(!v.editable||(!v.closed&&v.responsibilityBasis!==null))&&obj(v.source)&&exact(v.source,['lead','party','name','contactPhone','contactName','legalNeed'])&&sel(v.source.lead)&&(v.source.party==null||validCustomerParty(v.source.party))&&['name','contactPhone','contactName','legalNeed'].every(k=>v.source&&((v.source as Record<string,unknown>)[k]==null||str((v.source as Record<string,unknown>)[k])))&&(v.draft==null||entry(v.draft))&&(v.confirmation==null||entry(v.confirmation))&&Array.isArray(v.history)&&v.history.every(entry)&&Array.isArray(v.parties)&&v.parties.every(validCustomerParty);}
export function createCustomerRequirementsTransport(recovery=new RecoveryStore(window.sessionStorage),fetcher:typeof fetch=fetch){
 const {auth,assertCurrent,checked}=createSessionTransport(false);
 const base=(id:string)=>'/api/v1/opportunities/'+encodeURIComponent(id)+'/customer-requirements';
 async function request(s:WorkbenchSession,path:string,signal:AbortSignal,w?:CustomerWrite){const headers=await auth(s,signal);const marker=w?recovery.reserveWrite(w.key,w.command,s.actorScopeKey,w):null;const response=await fetcher(path,{method:w?'POST':'GET',headers:{...headers,...(w?{'Content-Type':'application/json','Idempotency-Key':w.key}:{})},body:w?JSON.stringify(w.body):undefined,cache:'no-store',signal});assertCurrent(s,signal);const data:unknown=await response.json();assertCurrent(s,signal);if(marker&&!response.ok&&provenWriteOutcome(data,response.status,marker)){recovery.clear(marker);if(obj(data)&&data.code==='VALIDATION_FAILED')throw new CustomerValidationError(data.fieldErrors);throw new TransportError(response.status,(data as {code:string}).code,true);}return {response,data:checked(s,signal,{response,data,error:data}).data};}
 function terminal(data:unknown){const marker=recovery.read();if(!marker||!matchesReceipt(data,marker)||data.outcome==='NO_CHANGE'||(data.outcome==='SUCCEEDED'&&(!('revision' in data.resultFact)||data.resultFact.revision!==0)))throw Error('结果尚未确认');recovery.clear(marker);if(data.outcome==='REJECTED'){const status=data.rejectionCode==='VALIDATION_FAILED'?400:['NOT_AUTHORIZED','APPOINTMENT_INACTIVE'].includes(data.rejectionCode)?403:data.rejectionCode==='NOT_FOUND'?404:data.rejectionCode==='OPPORTUNITY_CLOSED'?409:412;throw new TransportError(status,data.rejectionCode,true);}return data;}
 return {recovery,async context(s:WorkbenchSession,id:string,signal:AbortSignal){const {data}=await request(s,base(id),signal);if(!validCustomerContext(data,id))throw Error('资料读取结果无法核对');return data;},async search(s:WorkbenchSession,id:string,q:string,signal:AbortSignal){const {data}=await request(s,base(id)+'/parties?q='+encodeURIComponent(q),signal);if(!obj(data)||!exact(data,['items','hasMore'])||typeof data.hasMore!=='boolean'||!Array.isArray(data.items)||data.items.length>50||!data.items.every(validCustomerParty))throw Error('主体查询结果无法核对');return {items:data.items,hasMore:data.hasMore};},async write(s:WorkbenchSession,w:CustomerWrite,signal:AbortSignal){const {response,data}=await request(s,base(w.opportunityId)+(w.command==='SAVE_OPPORTUNITY_CUSTOMER_DRAFT'?'/draft':'/confirm'),signal,w);if(![200,201].includes(response.status))throw Error('结果尚未确认');return terminal(data);},async receipt(s:WorkbenchSession,signal:AbortSignal){const marker=recovery.read();if(!marker||!['SAVE_OPPORTUNITY_CUSTOMER_DRAFT','CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS'].includes(marker.commandType)||marker.actorScopeKey!==s.actorScopeKey)throw new TransportError(403);const {response,data}=await request(s,'/api/v1/commands/'+encodeURIComponent(marker.commandId)+'/receipt',signal);if(response.status!==200)throw Error('结果尚未确认');return terminal(data);}};
}
export type CustomerRequirementsTransport=ReturnType<typeof createCustomerRequirementsTransport>;
