import {createSessionTransport,TransportError,matchesReceipt,type WorkbenchSession} from './sessionTransport';
import {RecoveryStore,uuidPattern} from '../features/session/recoveryMarker';
import {provenWriteOutcome} from '../features/session/recoveryOutcome';
type S=import('../generated/api/schema').components['schemas'];
export type MaterialContext=S['OpportunityMaterialsContextV1'];
export type MaterialVersion=S['OpportunityMaterialVersionV1'];
export type MaterialUpload=S['OpportunityMaterialUploadV1'];
export type MaterialPurpose=S['MaterialPurposeV1'];
export type MaterialCommand='OPEN_OPPORTUNITY_MATERIAL_UPLOAD'|'ACCEPT_OPPORTUNITY_MATERIAL';
export interface MaterialWrite {key:string;opportunityId:string;command:MaterialCommand;body:S['OpenOpportunityMaterialUploadV1']|S['AcceptOpportunityMaterialV1']}
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const exact=(v:Record<string,unknown>,keys:string[])=>Object.keys(v).every(k=>keys.includes(k));
const text=(v:unknown,n:number)=>typeof v==='string'&&v.length<=n&&!/[\u0000-\u001f\u007f]/.test(v);
const uuid=(v:unknown)=>typeof v==='string'&&uuidPattern.test(v);
const selector=(v:unknown)=>object(v)&&exact(v,['id','revision'])&&uuid(v.id)&&Number.isSafeInteger(v.revision)&&Number(v.revision)>=0;
const optionalSelector=(v:unknown)=>v==null||selector(v);
const purpose=(v:unknown)=>['CONTRACT_BUSINESS','CORRESPONDENCE','OTHER'].includes(String(v));
const media=(v:unknown)=>['application/pdf','image/png','image/jpeg'].includes(String(v));
const size=(v:unknown)=>Number.isSafeInteger(v)&&Number(v)>0&&Number(v)<=20971520;
const instant=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const fact=(v:unknown)=>text(v,512)&&String(v).length>=16;
export function validMaterialUpload(v:unknown):v is MaterialUpload{return object(v)&&exact(v,['selector','factRef','state','expiresAt','purpose','fileName','note','previousVersion','confirmation','sizeBytes','mediaType','resultCode'])&&selector(v.selector)&&fact(v.factRef)&&['OPEN','CHECKING','UNKNOWN','SCAN_UNAVAILABLE','PASSED','REJECTED','ACCEPTED','EXPIRED'].includes(String(v.state))&&instant(v.expiresAt)&&purpose(v.purpose)&&text(v.fileName,255)&&(v.note===null||typeof v.note==='string'&&v.note.length<=500)&&optionalSelector(v.previousVersion)&&optionalSelector(v.confirmation)&&(v.sizeBytes===undefined||size(v.sizeBytes))&&(v.mediaType===undefined||media(v.mediaType))&&(v.resultCode===undefined||text(v.resultCode,64))&&(v.state!=='PASSED'||size(v.sizeBytes)&&media(v.mediaType));}
export function validMaterialVersion(v:unknown):v is MaterialVersion{return object(v)&&exact(v,['selector','factRef','itemId','previousVersionId','purpose','fileName','note','sizeBytes','mediaType','receivedAt','receivedByAppointmentId','receivedByLabel','previewAllowed'])&&selector(v.selector)&&fact(v.factRef)&&uuid(v.itemId)&&(v.previousVersionId===null||uuid(v.previousVersionId))&&purpose(v.purpose)&&text(v.fileName,255)&&(v.note===null||typeof v.note==='string'&&v.note.length<=500)&&size(v.sizeBytes)&&media(v.mediaType)&&instant(v.receivedAt)&&uuid(v.receivedByAppointmentId)&&(v.receivedByLabel===undefined||text(v.receivedByLabel,200))&&typeof v.previewAllowed==='boolean'&&(!v.previewAllowed||v.mediaType!=='application/pdf');}
export function validMaterialsContext(v:unknown,id:string):v is MaterialContext{return object(v)&&exact(v,['opportunity','responsibilityBasis','editable','closed','versions','pendingUploads','currentOwnerLabel','confirmation'])&&selector(v.opportunity)&&(v.opportunity as {id:string}).id===id&&optionalSelector(v.responsibilityBasis)&&typeof v.editable==='boolean'&&typeof v.closed==='boolean'&&(!v.editable||!v.closed&&v.responsibilityBasis!==null)&&Array.isArray(v.versions)&&v.versions.every(validMaterialVersion)&&new Set(v.versions.map(x=>x.selector.id)).size===v.versions.length&&Array.isArray(v.pendingUploads)&&v.pendingUploads.every(validMaterialUpload)&&(v.currentOwnerLabel===undefined||text(v.currentOwnerLabel,200))&&optionalSelector(v.confirmation);}
export function createMaterialsTransport(recovery=new RecoveryStore(window.sessionStorage),fetcher:typeof fetch=fetch){
 const {auth,assertCurrent,checked}=createSessionTransport(false);
 const base=(id:string)=>'/api/v1/opportunities/'+encodeURIComponent(id);
 async function request(s:WorkbenchSession,path:string,signal:AbortSignal,w?:MaterialWrite){const headers=await auth(s,signal);const marker=w?recovery.reserveWrite(w.key,w.command,s.actorScopeKey,w):null;const response=await fetcher(path,{method:w?'POST':'GET',headers:{...headers,...(w?{'Content-Type':'application/json','Idempotency-Key':w.key}:{})},body:w?JSON.stringify(w.body):undefined,cache:'no-store',signal});assertCurrent(s,signal);const data:unknown=await response.json();assertCurrent(s,signal);if(marker&&!response.ok&&provenWriteOutcome(data,response.status,marker)){recovery.clear(marker);throw new TransportError(response.status,(data as {code:string}).code,true);}return {response,data:checked(s,signal,{response,data,error:data}).data};}
 function terminal(data:unknown){const marker=recovery.read();if(!marker||!matchesReceipt(data,marker)||data.outcome==='NO_CHANGE'||data.outcome==='SUCCEEDED'&&(!('revision' in data.resultFact)||data.resultFact.revision!==0))throw Error('结果尚未确认');recovery.clear(marker);if(data.outcome==='REJECTED')throw new TransportError(data.rejectionCode==='VALIDATION_FAILED'?400:['NOT_AUTHORIZED','APPOINTMENT_INACTIVE'].includes(data.rejectionCode)?403:data.rejectionCode==='NOT_FOUND'?404:data.rejectionCode==='OPPORTUNITY_CLOSED'?409:412,data.rejectionCode,true);return data;}
 return {recovery,
 async context(s:WorkbenchSession,id:string,signal:AbortSignal){const {data}=await request(s,base(id)+'/materials',signal);if(!validMaterialsContext(data,id))throw Error('材料读取结果无法核对');return data;},
 async status(s:WorkbenchSession,id:string,upload:string,signal:AbortSignal){const {data}=await request(s,base(id)+'/material-uploads/'+encodeURIComponent(upload),signal);if(!validMaterialUpload(data)||data.selector.id!==upload)throw Error('上传结果无法核对');return data;},
 async write(s:WorkbenchSession,w:MaterialWrite,signal:AbortSignal){const {response,data}=await request(s,base(w.opportunityId)+(w.command==='OPEN_OPPORTUNITY_MATERIAL_UPLOAD'?'/material-uploads':'/materials/accept'),signal,w);if(![200,201].includes(response.status))throw Error('结果尚未确认');return terminal(data);},
 async receipt(s:WorkbenchSession,signal:AbortSignal){const marker=recovery.read();if(!marker||!['OPEN_OPPORTUNITY_MATERIAL_UPLOAD','ACCEPT_OPPORTUNITY_MATERIAL'].includes(marker.commandType)||marker.actorScopeKey!==s.actorScopeKey)throw new TransportError(403);const {response,data}=await request(s,'/api/v1/commands/'+encodeURIComponent(marker.commandId)+'/receipt',signal);if(response.status!==200)throw Error('结果尚未确认');return terminal(data);},
 async upload(s:WorkbenchSession,id:string,upload:string,file:File,signal:AbortSignal){const headers=await auth(s,signal);const response=await fetcher(base(id)+'/material-uploads/'+encodeURIComponent(upload)+'/content',{method:'PUT',headers:{...headers,'Content-Type':'application/octet-stream'},body:file,signal,cache:'no-store'});assertCurrent(s,signal);const data:unknown=await response.json();assertCurrent(s,signal);checked(s,signal,{response,data,error:data});if(!validMaterialUpload(data)||data.selector.id!==upload)throw Error('上传结果无法核对');return data;},
 async content(s:WorkbenchSession,id:string,version:MaterialVersion,preview:boolean,signal:AbortSignal){const headers=await auth(s,signal);const response=await fetcher(base(id)+'/materials/versions/'+encodeURIComponent(version.selector.id)+'/content?disposition='+(preview?'inline':'attachment'),{headers,signal,cache:'no-store'});assertCurrent(s,signal);if(!response.ok){const error:unknown=await response.json();checked(s,signal,{response,error});throw Error('文件读取失败');}const blob=await response.blob();assertCurrent(s,signal);if(blob.size!==version.sizeBytes||blob.type!==version.mediaType||preview&&!version.previewAllowed)throw Error('文件版本无法核对');return blob;}
 };
}
export type MaterialsTransport=ReturnType<typeof createMaterialsTransport>;
