import {it,expect,vi} from 'vitest';
import {createOpportunityClosureTransport,validClosureContext,type ClosureWrite} from './opportunityClosureTransport';
import {RecoveryStore} from '../features/session/recoveryMarker';
import {testSession,taskId,selectorId} from '../test/fixtures';
const w:ClosureWrite={key:taskId,opportunityId:selectorId,body:{expectedOpportunityRevision:1,expectedResponsibility:{type:'OPPORTUNITY_RESPONSIBILITY',id:selectorId,revision:1},expectedTask:null,expectedWait:null,reasonCode:'CLIENT_DECLINED',summary:'private closure explanation'}};
const response=(factType='OPPORTUNITY_CLOSURE',revision=0)=>new Response(JSON.stringify({commandId:taskId,receiptId:selectorId,completedAt:'2026-09-15T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType,factRef:selectorId,revision}}),{status:200,headers:{'Content-Type':'application/json'}});
it('retains only shared clue on lost response; queries exact receipt without repeating the write',async()=>{const recovery=new RecoveryStore(sessionStorage),fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(response());const api=createOpportunityClosureTransport(recovery,fetcher);await expect(api.write(testSession(),w,new AbortController().signal)).rejects.toThrow();expect(recovery.read()?.commandType).toBe('CLOSE_OPPORTUNITY');expect(JSON.stringify(recovery.read())).not.toContain('private');await api.receipt(testSession(),new AbortController().signal);expect(fetcher.mock.calls[1][0]).toBe('/api/v1/commands/'+taskId+'/receipt');expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();});
it.each([['DECISION_RECORD',0],['OPPORTUNITY_CLOSURE',1]])('does not accept mismatched closure fact %s %s',async(fact,revision)=>{const recovery=new RecoveryStore(sessionStorage),api=createOpportunityClosureTransport(recovery,async()=>response(fact,Number(revision)));await expect(api.write(testSession(),w,new AbortController().signal)).rejects.toThrow();expect(recovery.read()).not.toBeNull();});
it('rejects private selectors in read-only context and accepts existing waiting digest encoding',()=>{expect(validClosureContext({opportunity:{id:selectorId,revision:1},status:'READ_ONLY',expectedResponsibility:w.body.expectedResponsibility},selectorId)).toBe(false);expect(validClosureContext({opportunity:{id:selectorId,revision:1},status:'READY',expectedResponsibility:w.body.expectedResponsibility,expectedTask:null,expectedWait:{type:'WAIT',id:taskId,hash:'a'.repeat(43)}},selectorId)).toBe(true);});
