import {it,expect,vi} from 'vitest';
import {testSession,taskId} from '../test/fixtures';
import {createPersonalWaitingTransport} from './personalWaitingTransport';
const row={id:taskId,customerLabel:'合成客户',purposeLabel:'联系客户',state:'WAIT_FUTURE',reason:'等待约定时间',resumeAt:'2026-09-30T02:00:00Z'};
const page={waitingItems:[row],totalCount:1,nextCursor:null,asOf:'2026-09-29T01:00:00Z'};
it('uses no-store authenticated personal GET, including explicitly selected delegation',async()=>{const f=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(page))),s={...testSession(),selectedOnBehalfAppointmentId:taskId};await createPersonalWaitingTransport(f).list(s,null,new AbortController().signal);const [url,options]=f.mock.calls[0];expect(String(url)).toBe('/api/v1/workbench/waiting?limit=20');expect(options?.cache).toBe('no-store');expect(options?.method).toBe('GET');expect(new Headers(options?.headers).get('X-On-Behalf-Appointment-Id')).toBe(taskId);});
it.each([{...page,totalCount:-1},{...page,totalCount:0},{...page,waitingItems:[{...row,state:'READY'}]},{...page,waitingItems:[row,row],totalCount:2},{...page,nextCursor:'invalid'},{...page,asOf:'bad'}])('rejects inconsistent wire results',async body=>{const f=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(body)));await expect(createPersonalWaitingTransport(f).list(testSession(),null,new AbortController().signal)).rejects.toThrow();});
it('rejects fabricated readiness and cross-task detail',async()=>{for(const patch of [{canHandle:true,state:'WAIT_DUE'},{id:'20000000-0000-4000-8000-000000000001'}]){const f=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({waitingDetail:{...row,ownerLabel:'本人',nextAction:'等待',history:[],canHandle:false,...patch},totalCount:1})));await expect(createPersonalWaitingTransport(f).detail(testSession(),taskId,new AbortController().signal)).rejects.toThrow();}});
it('rejects old identity replies and keeps object revocation local',async()=>{const s=testSession();s.invalidate=vi.fn();const f=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify({code:'NOT_AUTHORIZED'}),{status:403}));await expect(createPersonalWaitingTransport(f).list(s,null,new AbortController().signal)).rejects.toThrow();expect(s.invalidate).not.toHaveBeenCalled();const late=vi.fn<typeof fetch>().mockImplementation(async()=>{s.isCurrent=()=>false;return new Response(JSON.stringify(page));});await expect(createPersonalWaitingTransport(late).list(s,null,new AbortController().signal)).rejects.toThrow();});
