import {it,expect,vi} from 'vitest';
import {createQuotesTransport,validQuoteContext,moneyMinor,minorText} from './quotesTransport';
import {RecoveryStore} from '../features/session/recoveryMarker';
import {testSession,taskId,selectorId} from '../test/fixtures';
const context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{id:taskId,revision:0},customerConfirmation:{id:taskId,revision:0},draft:null,quote:null,workflow:null,allowedActions:['SAVE_QUOTE_DRAFT','FORM_QUOTE'],history:[],materials:[],approvers:[],customerName:'合成客户',readonly:false};
it('validates target and denies an editable context with no basis',()=>{expect(validQuoteContext(context,selectorId)).toBe(true);expect(validQuoteContext(context,taskId)).toBe(false);expect(validQuoteContext({...context,responsibilityBasis:null},selectorId)).toBe(false);expect(validQuoteContext({...context,allowedActions:['DELETE_QUOTE']},selectorId)).toBe(false);});
it('converts decimal text exactly without float rounding or truncation',()=>{expect(moneyMinor('100.01')).toBe(10001);expect(moneyMinor('-1.20')).toBe(-120);expect(moneyMinor('0')).toBe(0);expect(()=>moneyMinor('1.001')).toThrow();expect(()=>moneyMinor('900719925474099')).toThrow();expect(()=>moneyMinor('')).toThrow();});
it('unknown write stores only recovery identity and recovers through original receipt GET',async()=>{const receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-20T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'QUOTE_DRAFT',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockRejectedValueOnce(Error('lost')).mockResolvedValueOnce(new Response(JSON.stringify(receipt))),recovery=new RecoveryStore(sessionStorage),api=createQuotesTransport(recovery,fetcher),session=testSession();await expect(api.write(session,{key:taskId,opportunityId:selectorId,command:'SAVE_QUOTE_DRAFT',body:{expectedOpportunityRevision:0,responsibilityBasis:context.responsibilityBasis,customerConfirmation:context.customerConfirmation,expectedDraft:null,expectedQuote:null,expectedWorkflow:null,values:{scope:'private'}}},new AbortController().signal)).rejects.toThrow();expect(Object.keys(recovery.read()!).sort()).toEqual(['actorScopeKey','commandId','commandType','recordedAt']);await api.receipt(session,new AbortController().signal);expect(fetcher.mock.calls[1][0]).toBe('/api/v1/commands/'+taskId+'/receipt');expect(fetcher.mock.calls[1][1]?.method).toBe('GET');expect(recovery.read()).toBeNull();});

it('roundtrips large valid cent amounts without a floating point cent shift',()=>{for(const n of [9007199254740990,9007199254740991,-120,0,10001])expect(moneyMinor(minorText(n))).toBe(n);});

it('rejects malformed partial drafts before rendering their controls',()=>{expect(validQuoteContext({...context,draft:{selector:context.opportunity,document:{lines:'bad'}}},selectorId)).toBe(false);expect(validQuoteContext({...context,draft:{selector:context.opportunity,document:{scope:'partial'}}},selectorId)).toBe(true);});
it('a stale evidence rejection receipt terminates recovery without resending',async()=>{const recovery=new RecoveryStore(sessionStorage),s=testSession(),receipt={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-20T00:00:00Z',outcome:'REJECTED',rejectionCode:'STALE_EVIDENCE'},fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(receipt))),api=createQuotesTransport(recovery,fetcher);recovery.reserveWrite(taskId,'RECORD_QUOTE_DELIVERY',s.actorScopeKey,{});await expect(api.receipt(s,new AbortController().signal)).rejects.toMatchObject({status:412,provenOutcome:true});expect(recovery.read()).toBeNull();expect(fetcher).toHaveBeenCalledOnce();});
it('accepts exact historic records and rejects incomplete evidence references',()=>{const record={kind:'RESPONSE',quote:{id:taskId,hash:'q'.repeat(43)},version:1,selector:{id:taskId,hash:'r'.repeat(43)},actorAppointmentId:taskId,occurredAt:'2026-09-20T10:00:00Z',recordedAt:'2026-09-20T11:00:00Z',responseKind:'REJECTED',statement:'历史原意',evidence:{id:selectorId,revision:0}};expect(validQuoteContext({...context,records:[record]},selectorId)).toBe(true);expect(validQuoteContext({...context,records:[{...record,evidence:{id:selectorId}}]},selectorId)).toBe(false);});

it('explicit preparation uses its own endpoint and receipt fact',async()=>{
 const result={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-25T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'QUOTE_PREPARATION_INTENT',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(result))),recovery=new RecoveryStore(sessionStorage),api=createQuotesTransport(recovery,fetcher);
 await api.write(testSession(),{key:taskId,opportunityId:selectorId,command:'START_QUOTE_PREPARATION',body:{expectedOpportunityRevision:0,responsibilityBasis:context.responsibilityBasis,customerConfirmation:context.customerConfirmation,expectedDraft:null,expectedQuote:null,expectedWorkflow:null,values:{}}},new AbortController().signal);
 expect(fetcher.mock.calls[0][0]).toBe('/api/v1/opportunities/'+selectorId+'/quotes/preparation-intents');expect(recovery.read()).toBeNull();
});
it('termination uses its own endpoint and exact receipt type',async()=>{
 const result={commandId:taskId,receiptId:selectorId,completedAt:'2026-09-25T00:00:00Z',outcome:'SUCCEEDED',resultFact:{factType:'QUOTE_TERMINATION',factRef:'r'.repeat(43),revision:0}},fetcher=vi.fn<typeof fetch>().mockResolvedValue(new Response(JSON.stringify(result))),recovery=new RecoveryStore(sessionStorage),api=createQuotesTransport(recovery,fetcher);
 await api.write(testSession(),{key:taskId,opportunityId:selectorId,command:'END_QUOTE_NEGOTIATION',body:{expectedOpportunityRevision:0,responsibilityBasis:context.responsibilityBasis,customerConfirmation:context.customerConfirmation,expectedDraft:null,expectedQuote:null,expectedWorkflow:context.opportunity,values:{reasonCode:'OTHER',summary:'明确终止原因'}}},new AbortController().signal);
 expect(fetcher.mock.calls[0][0]).toBe('/api/v1/opportunities/'+selectorId+'/quotes/terminations');expect(recovery.read()).toBeNull();
});
