import {createSessionTransport,TransportError,matchesReceipt,type WorkbenchSession} from './sessionTransport';
import {RecoveryStore,uuidPattern} from '../features/session/recoveryMarker';
import {provenWriteOutcome} from '../features/session/recoveryOutcome';
export type QuoteSelector={id:string;revision:number};
export type QuoteDocument={currency:'CNY';scope:string;lines:{description:string;amountMinor:number;discount:boolean}[];paymentTerms:string;validUntil:string;conditionalFee:null|{basis:string;rateBasisPoints:number;capMinor:number}};
export const quoteCommands=['END_QUOTE_NEGOTIATION','START_QUOTE_PREPARATION','SAVE_QUOTE_DRAFT','FORM_QUOTE','REQUEST_QUOTE_APPROVAL','RECORD_QUOTE_DECISION','RECORD_QUOTE_DELIVERY','RECORD_QUOTE_RESPONSE'] as const;
export type QuoteCommand=typeof quoteCommands[number];
export type QuoteVersion={selector:{id:string;hash:string};version:number;document:QuoteDocument;totalMinor:number;validUntil:string};
export type QuoteStage='PREPARE'|'SUBMIT_APPROVAL'|'AWAIT_APPROVAL'|'DELIVER'|'AWAIT_REPLY'|'FOLLOW_UP'|'CLARIFY_REPLY'|'SALES_DISPOSITION'|'ACCEPTED'|'RETURNED'|'OWNER_EXCEPTION';
export type QuoteBusinessRecord={kind:'APPROVAL'|'DELIVERY'|'RESPONSE';quote:{id:string;hash:string};version:number;selector:QuoteSelector|{id:string;hash:string};actorAppointmentId:string;occurredAt:string;recordedAt:string;decision?:'APPROVED'|'RETURNED';reason?:string;recipient?:string;channel?:string;evidence?:QuoteSelector;responseKind?:'ACCEPTED'|'NOT_ACCEPTED'|'REJECTED'|'AMBIGUOUS';statement?:string};
export type QuoteContext={opportunity:QuoteSelector;responsibilityBasis:QuoteSelector|null;customerConfirmation:QuoteSelector|null;draft:{selector:QuoteSelector;document:Partial<QuoteDocument>}|null;quote:QuoteVersion|null;workflow:{selector:QuoteSelector;stage:QuoteStage;ownerAppointmentId:string|null;ownerLabel?:string;task:QuoteSelector|null;nextCheckAt?:string|null;dueAt?:string|null;message?:string|null}|null;records?:QuoteBusinessRecord[];allowedActions:QuoteCommand[];recipients?:{selector:QuoteSelector;name:string}[];history:QuoteVersion[];materials:{selector:QuoteSelector;fileName:string}[];approvers:{id?:string;appointmentId?:string;label?:string;displayName?:string}[];customerName:string;readonly:boolean;notice?:string|null};
export type QuoteWrite={key:string;opportunityId:string;command:QuoteCommand;body:{expectedOpportunityRevision:number;responsibilityBasis:QuoteSelector|null;customerConfirmation:QuoteSelector|null;expectedDraft:QuoteSelector|null;expectedQuote:{id:string;hash:string}|null;expectedWorkflow:QuoteSelector|null;values:Record<string,unknown>|Partial<QuoteDocument>}};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const selector=(v:unknown):v is QuoteSelector=>object(v)&&typeof v.id==='string'&&uuidPattern.test(v.id)&&Number.isSafeInteger(v.revision)&&Number(v.revision)>=0;
const nullableSelector=(v:unknown)=>v===null||selector(v);
const instant=(v:unknown)=>typeof v==='string'&&Number.isFinite(Date.parse(v));
const partialDocument=(v:unknown)=>object(v)&&(v.currency===undefined||v.currency==='CNY')&&(v.scope===undefined||typeof v.scope==='string')&&(v.paymentTerms===undefined||typeof v.paymentTerms==='string')&&(v.validUntil===undefined||typeof v.validUntil==='string')&&(v.lines===undefined||Array.isArray(v.lines)&&v.lines.every(l=>object(l)&&typeof l.description==='string'&&Number.isSafeInteger(l.amountMinor)&&typeof l.discount==='boolean'))&&(v.conditionalFee==null||object(v.conditionalFee)&&typeof v.conditionalFee.basis==='string'&&Number.isSafeInteger(v.conditionalFee.rateBasisPoints)&&Number.isSafeInteger(v.conditionalFee.capMinor));
const document=(v:unknown)=>object(v)&&v.currency==='CNY'&&typeof v.scope==='string'&&Array.isArray(v.lines)&&v.lines.every(l=>object(l)&&typeof l.description==='string'&&Number.isSafeInteger(l.amountMinor)&&typeof l.discount==='boolean')&&typeof v.paymentTerms==='string'&&instant(v.validUntil)&&(v.conditionalFee===null||object(v.conditionalFee)&&typeof v.conditionalFee.basis==='string'&&Number.isSafeInteger(v.conditionalFee.rateBasisPoints)&&Number.isSafeInteger(v.conditionalFee.capMinor));
const version=(v:unknown)=>object(v)&&object(v.selector)&&typeof v.selector.id==='string'&&uuidPattern.test(v.selector.id)&&typeof v.selector.hash==='string'&&/^[A-Za-z0-9_-]{43}$/.test(v.selector.hash)&&Number.isSafeInteger(v.version)&&Number(v.version)>0&&document(v.document)&&Number.isSafeInteger(v.totalMinor)&&Number(v.totalMinor)>=0&&instant(v.validUntil);
const hashSelector=(v:unknown)=>object(v)&&typeof v.id==='string'&&uuidPattern.test(v.id)&&typeof v.hash==='string'&&/^[A-Za-z0-9_-]{43}$/.test(v.hash);
const businessRecord=(v:unknown)=>object(v)&&['APPROVAL','DELIVERY','RESPONSE'].includes(String(v.kind))&&hashSelector(v.quote)&&(selector(v.selector)||hashSelector(v.selector))&&Number.isSafeInteger(v.version)&&Number(v.version)>0&&typeof v.actorAppointmentId==='string'&&uuidPattern.test(v.actorAppointmentId)&&instant(v.occurredAt)&&instant(v.recordedAt)&&(v.evidence===undefined||selector(v.evidence))&&['reason','recipient','channel','statement'].every(k=>v[k]===undefined||typeof v[k]==='string')&&(v.decision===undefined||['APPROVED','RETURNED'].includes(String(v.decision)))&&(v.responseKind===undefined||['ACCEPTED','NOT_ACCEPTED','REJECTED','AMBIGUOUS'].includes(String(v.responseKind)));
export function validQuoteContext(v:unknown,id:string):v is QuoteContext{return object(v)&&selector(v.opportunity)&&v.opportunity.id===id&&nullableSelector(v.responsibilityBasis)&&nullableSelector(v.customerConfirmation)&&typeof v.readonly==='boolean'&&(v.readonly||v.responsibilityBasis!==null)&&(v.draft===null||object(v.draft)&&selector(v.draft.selector)&&partialDocument(v.draft.document))&&(v.quote===null||version(v.quote))&&(v.workflow===null||object(v.workflow)&&selector(v.workflow.selector)&&['PREPARE','SUBMIT_APPROVAL','AWAIT_APPROVAL','DELIVER','AWAIT_REPLY','FOLLOW_UP','CLARIFY_REPLY','SALES_DISPOSITION','ACCEPTED','RETURNED','OWNER_EXCEPTION'].includes(String(v.workflow.stage))&&nullableSelector(v.workflow.task)&&(v.workflow.ownerAppointmentId===null||typeof v.workflow.ownerAppointmentId==='string'&&uuidPattern.test(v.workflow.ownerAppointmentId)))&&Array.isArray(v.allowedActions)&&v.allowedActions.every(a=>quoteCommands.includes(a as QuoteCommand))&&(v.records===undefined||Array.isArray(v.records)&&v.records.every(businessRecord))&&Array.isArray(v.history)&&v.history.every(version)&&Array.isArray(v.materials)&&v.materials.every(m=>object(m)&&selector(m.selector)&&typeof m.fileName==='string')&&(v.recipients===undefined||Array.isArray(v.recipients)&&v.recipients.every(r=>object(r)&&selector(r.selector)&&typeof r.name==='string'))&&Array.isArray(v.approvers)&&v.approvers.every(object)&&typeof v.customerName==='string';}
export function minorText(value:number):string{if(!Number.isSafeInteger(value))throw Error('金额超出范围');const n=BigInt(value),absolute=n<0n?-n:n;return (n<0n?'-':'')+(absolute/100n).toString()+'.'+(absolute%100n).toString().padStart(2,'0');}
export function moneyMinor(value:string):number{if(!/^-?\d+(?:\.\d{1,2})?$/.test(value))throw Error('金额最多保留两位小数');const negative=value.startsWith('-'),[whole,fraction='']=value.replace(/^-/,'').split('.'),number=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0')),signed=negative?-number:number;if(signed>BigInt(Number.MAX_SAFE_INTEGER)||signed<BigInt(Number.MIN_SAFE_INTEGER))throw Error('金额超出范围');return Number(signed);}
const paths:Record<QuoteCommand,string>={END_QUOTE_NEGOTIATION:'terminations',START_QUOTE_PREPARATION:'preparation-intents',SAVE_QUOTE_DRAFT:'draft',FORM_QUOTE:'form',REQUEST_QUOTE_APPROVAL:'approval-requests',RECORD_QUOTE_DECISION:'decisions',RECORD_QUOTE_DELIVERY:'deliveries',RECORD_QUOTE_RESPONSE:'responses'};
export function createQuotesTransport(recovery=new RecoveryStore(window.sessionStorage),fetcher:typeof fetch=fetch){const {auth,assertCurrent,checked}=createSessionTransport(false),base=(id:string)=>'/api/v1/opportunities/'+encodeURIComponent(id)+'/quotes';
 async function request(s:WorkbenchSession,path:string,signal:AbortSignal,w?:QuoteWrite){const headers=await auth(s,signal),marker=w?recovery.reserveWrite(w.key,w.command,s.actorScopeKey,w):null;const response=await fetcher(path,{method:w?'POST':'GET',headers:{...headers,...(w?{'Content-Type':'application/json','Idempotency-Key':w.key}:{})},body:w?JSON.stringify(w.body):undefined,cache:'no-store',signal});assertCurrent(s,signal);const data:unknown=await response.json();assertCurrent(s,signal);if(marker&&!response.ok&&provenWriteOutcome(data,response.status,marker)){recovery.clear(marker);throw new TransportError(response.status,(data as {code:string}).code,true);}checked(s,signal,{response,data,error:data});return {response,data};}
 function terminal(data:unknown){const marker=recovery.read();if(!marker||!matchesReceipt(data,marker)||data.outcome==='NO_CHANGE')throw Error('结果尚未确认');recovery.clear(marker);if(data.outcome==='REJECTED')throw new TransportError(data.rejectionCode==='VALIDATION_FAILED'?400:['NOT_AUTHORIZED','APPOINTMENT_INACTIVE'].includes(data.rejectionCode)?403:data.rejectionCode==='NOT_FOUND'?404:data.rejectionCode==='OPPORTUNITY_CLOSED'?409:412,data.rejectionCode,true);return data;}
 return {recovery,async taskContext(s:WorkbenchSession,taskId:string,signal:AbortSignal){const {data}=await request(s,'/api/v1/quote-tasks/'+encodeURIComponent(taskId)+'/context',signal);if(!object(data)||typeof data.opportunityId!=='string'||!validQuoteContext(data.context,data.opportunityId))throw Error('报价责任无法核对');return {opportunityId:data.opportunityId,context:data.context};},async context(s:WorkbenchSession,id:string,signal:AbortSignal){const {data}=await request(s,base(id),signal);if(!validQuoteContext(data,id))throw Error('报价读取结果无法核对');return data;},async write(s:WorkbenchSession,w:QuoteWrite,signal:AbortSignal){const {response,data}=await request(s,base(w.opportunityId)+'/'+paths[w.command],signal,w);if(![200,201].includes(response.status))throw Error('结果尚未确认');return terminal(data);},async receipt(s:WorkbenchSession,signal:AbortSignal){const marker=recovery.read();if(!marker||!quoteCommands.includes(marker.commandType as QuoteCommand)||marker.actorScopeKey!==s.actorScopeKey)throw new TransportError(403);const {response,data}=await request(s,'/api/v1/commands/'+encodeURIComponent(marker.commandId)+'/receipt',signal);if(response.status!==200)throw Error('结果尚未确认');return terminal(data);},async download(s:WorkbenchSession,id:string,q:{id:string;hash:string},signal:AbortSignal){const headers=await auth(s,signal),response=await fetcher(base(id)+'/'+encodeURIComponent(q.id)+'/document',{headers,signal,cache:'no-store'});assertCurrent(s,signal);if(!response.ok){const error:unknown=await response.json();checked(s,signal,{response,error});}const blob=await response.blob();assertCurrent(s,signal);return blob;}};
}
export type QuotesTransport=ReturnType<typeof createQuotesTransport>;






