import {createSessionTransport,TransportError,matchesReceipt,type WorkbenchSession} from './sessionTransport';
import {RecoveryStore,uuidPattern} from '../features/session/recoveryMarker';
import {provenWriteOutcome} from '../features/session/recoveryOutcome';
import type {components} from '../generated/api/schema';
export type ClassificationCorrectionContext={opportunityId:string;expectedOpportunityRevision:number;expectedWorkflow:{id:string;revision:number};customerName:string;matter:{id:string;number:string};category:'GENERAL'|'ENFORCEMENT'|'OTHER';recipient:{id:string;label:string}|null;receivers:{id:string;label:string}[]};
export type TransferContext=components['schemas']['TransferTaskContextV1'];
export const transferPaths={SUBMIT_TRANSFER:'submissions',RESUBMIT_TRANSFER:'supplements',RECORD_TRANSFER_CONFLICT_REVIEW:'conflict-reviews',RECORD_TRANSFER_INTAKE:'intake-decisions',CLASSIFY_MATTER:'classifications'} as const;
export type TransferCommand=keyof typeof transferPaths;
export type TransferWrite={key:string;opportunityId:string;command:TransferCommand;body:{expectedOpportunityRevision:number;expectedWorkflow:{id:string;revision:number};values:Record<string,unknown>}};
const object=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const id=(v:unknown):v is string=>typeof v==='string'&&uuidPattern.test(v);
const text=(v:unknown):v is string=>typeof v==='string'&&v.length<=4000;
const material=(v:unknown)=>object(v)&&id(v.versionId)&&typeof v.sha256==='string'&&/^[a-f0-9]{64}$/.test(v.sha256);
const stageActions={PREPARE:'SUBMIT_TRANSFER',SUPPLEMENT:'RESUBMIT_TRANSFER',REVIEW_TRANSFER:'RECORD_TRANSFER_CONFLICT_REVIEW',INTAKE:'RECORD_TRANSFER_INTAKE',CLASSIFY:'CLASSIFY_MATTER'} as const;
export function validTransferContext(v:unknown,task:string):v is TransferContext{
 if(!object(v)||v.taskId!==task||!id(v.opportunityId)||!Number.isSafeInteger(v.expectedOpportunityRevision)||Number(v.expectedOpportunityRevision)<0||!object(v.expectedWorkflow)||!id(v.expectedWorkflow.id)||v.expectedWorkflow.revision!==0||!Object.hasOwn(stageActions,String(v.stage))||v.allowedAction!==stageActions[v.stage as keyof typeof stageActions]||typeof v.dueAt!=='string'||!Number.isFinite(Date.parse(v.dueAt))||!text(v.customerName))return false;
 if(!object(v.contract)||!id(v.contract.id)||!Number.isSafeInteger(v.contract.version)||Number(v.contract.version)<1||!text(v.contract.scope)||!text(v.contract.paymentTerms)||!text(v.contract.signingRequirements)||typeof v.contract.receiptRequiredBeforeTransfer!=='boolean')return false;
 if(v.submission!==null&&(!object(v.submission)||!material(v.submission.clientIdentity)||!material(v.submission.signatureArchive)||!text(v.submission.explanation)||v.submission.consistencyChecked!==true||!Array.isArray(v.submission.corrections)||v.submission.corrections.length!==0))return false;
 if(v.stage!=='PREPARE'&&v.submission===null)return false;
 if(v.review!==null&&(!object(v.review)||!['CLEAR','NEED_INFO','BLOCKED'].includes(String(v.review.outcome))||!text(v.review.explanation)))return false;
 if(v.intake!==null&&(!object(v.intake)||!['ACCEPT','RETURN'].includes(String(v.intake.decision))||!text(v.intake.explanation)))return false;
 if(v.stage==='CLASSIFY'? !object(v.matter)||!id(v.matter.id)||!text(v.matter.number):v.matter!==null)return false;
 if(!Array.isArray(v.materials)||!v.materials.every(m=>object(m)&&id(m.id)&&text(m.fileName)&&material({versionId:m.id,sha256:m.sha256})))return false;
 if(!Array.isArray(v.returnItems)||!v.returnItems.every(i=>object(i)&&id(i.id)&&['CLIENT_IDENTITY','SIGNATURE_ARCHIVE','HANDOVER_EXPLANATION','OTHER_MATERIAL','RESOLVE_CONFLICT','COMPLETE_SUBJECT_EVIDENCE'].includes(String(i.requirement))&&text(i.label)&&text(i.reason)&&i.requiresMaterial===(i.requirement!=='HANDOVER_EXPLANATION'))||new Set(v.returnItems.map(i=>(i as Record<string,unknown>).id)).size!==v.returnItems.length)return false;
 if(v.stage==='SUPPLEMENT'&&v.returnItems.length===0)return false;
 if(v.reviewPreview!==null&&(!object(v.reviewPreview)||typeof v.reviewPreview.scopeComplete!=='boolean'||!Number.isSafeInteger(v.reviewPreview.candidateCount)||Number(v.reviewPreview.candidateCount)<0||!Array.isArray(v.reviewPreview.permittedOutcomes)||!v.reviewPreview.permittedOutcomes.every(o=>['CLEAR','NEED_INFO','BLOCKED'].includes(String(o)))))return false;
 if(v.stage==='REVIEW_TRANSFER'&&v.reviewPreview===null)return false;
 return Array.isArray(v.receivers)&&v.receivers.every(r=>object(r)&&id(r.id)&&text(r.label));
}
export function validClassificationCorrection(v:unknown,opportunityId:string):v is ClassificationCorrectionContext{
 const receiver=(r:unknown)=>object(r)&&id(r.id)&&text(r.label);
 return object(v)&&v.opportunityId===opportunityId&&id(v.opportunityId)&&Number.isSafeInteger(v.expectedOpportunityRevision)&&Number(v.expectedOpportunityRevision)>=0&&object(v.expectedWorkflow)&&id(v.expectedWorkflow.id)&&v.expectedWorkflow.revision===0&&text(v.customerName)&&object(v.matter)&&id(v.matter.id)&&text(v.matter.number)&&['GENERAL','ENFORCEMENT','OTHER'].includes(String(v.category))&&(v.recipient===null||receiver(v.recipient))&&Array.isArray(v.receivers)&&v.receivers.every(receiver)&&new Set(v.receivers.map(r=>(r as {id:string}).id)).size===v.receivers.length;
}
export function createTransfersTransport(recovery=new RecoveryStore(window.sessionStorage),fetcher:typeof fetch=fetch){
 const {auth,assertCurrent,checked}=createSessionTransport(false);
 async function request(s:WorkbenchSession,path:string,signal:AbortSignal,w?:TransferWrite){const headers=await auth(s,signal),marker=w?recovery.reserveWrite(w.key,w.command,s.actorScopeKey,w):null;const response=await fetcher(path,{method:w?'POST':'GET',headers:{...headers,...(w?{'Content-Type':'application/json','Idempotency-Key':w.key}:{})},body:w?JSON.stringify(w.body):undefined,cache:'no-store',signal});assertCurrent(s,signal);const data:unknown=await response.json();assertCurrent(s,signal);if(marker&&!response.ok&&provenWriteOutcome(data,response.status,marker)){recovery.clear(marker);throw new TransportError(response.status,(data as {code:string}).code,true);}checked(s,signal,{response,data,error:data});return {response,data};}
 function terminal(data:unknown){const marker=recovery.read();if(!marker||!Object.hasOwn(transferPaths,marker.commandType)||!matchesReceipt(data,marker)||data.outcome==='NO_CHANGE'||data.outcome==='SUCCEEDED'&&(!('revision' in data.resultFact)||data.resultFact.revision!==0))throw Error('结果尚未确认，请核对原回执。');recovery.clear(marker);if(data.outcome==='REJECTED')throw new TransportError(['NOT_AUTHORIZED','APPOINTMENT_INACTIVE'].includes(data.rejectionCode)?403:412,data.rejectionCode,true);return data;}
 return {recovery,async classificationContext(s:WorkbenchSession,id:string,signal:AbortSignal){const {data}=await request(s,'/api/v1/opportunities/'+encodeURIComponent(id)+'/transfers/classification-context',signal);if(!validClassificationCorrection(data,id))throw Error('分类及承接信息已变化，请重新读取。');return data;},async download(s:WorkbenchSession,task:string,version:string,signal:AbortSignal){const headers=await auth(s,signal);const response=await fetcher('/api/v1/transfer-tasks/'+encodeURIComponent(task)+'/materials/'+encodeURIComponent(version)+'/content',{headers,signal,cache:'no-store'});assertCurrent(s,signal);if(!response.ok){const error:unknown=await response.json();checked(s,signal,{response,error});}const data=await response.blob();assertCurrent(s,signal);return data;},async taskContext(s:WorkbenchSession,task:string,signal:AbortSignal){const {data}=await request(s,'/api/v1/transfer-tasks/'+encodeURIComponent(task)+'/context',signal);if(!validTransferContext(data,task))throw Error('转案责任无法核对，请重新读取。');return data;},async write(s:WorkbenchSession,w:TransferWrite,signal:AbortSignal){const {response,data}=await request(s,'/api/v1/opportunities/'+encodeURIComponent(w.opportunityId)+'/transfers/'+transferPaths[w.command],signal,w);if(response.status!==200)throw Error('结果尚未确认');return terminal(data);},async receipt(s:WorkbenchSession,signal:AbortSignal){const marker=recovery.read();if(!marker||marker.actorScopeKey!==s.actorScopeKey||!Object.hasOwn(transferPaths,marker.commandType))throw new TransportError(403);const {response,data}=await request(s,'/api/v1/commands/'+encodeURIComponent(marker.commandId)+'/receipt',signal);if(response.status!==200)throw Error('结果尚未确认');return terminal(data);}};
}
export type TransfersTransport=ReturnType<typeof createTransfersTransport>;
