package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.contract.*;import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.sql.*;import java.time.*;import java.util.*;import java.nio.*;import java.nio.charset.StandardCharsets;import java.security.*;import javax.crypto.Mac;import javax.crypto.spec.SecretKeySpec;
/** Metadata-only SERVICE candidate scan; cursor advances raw sources even if every row is restricted. */
final class ContractPreparationDiscovery {
 private final ContractWorkflowService service;private final byte[] key;private final R2TransferRecoveryService transfers;
 ContractPreparationDiscovery(ContractWorkflowService service,byte[] key){this(service,key,null);}
 ContractPreparationDiscovery(ContractWorkflowService service,byte[] key,R2TransferRecoveryService transfers){this.transfers=transfers;this.service=Objects.requireNonNull(service);if(key==null||key.length<32)throw new IllegalArgumentException();this.key=key.clone();}
 record Cursor(Instant observed,UUID after,boolean transfer){}
 Map<String,Object> list(Connection c,Actor actor,int limit,String encoded)throws SQLException{if(limit<1||limit>100)throw new R1ServiceReadRuntime.Failure(400,"VALIDATION_FAILED");return R1ServiceReadRuntime.read(c,actor,(tx,now)->{try(var sources=R2LedgerSourceFacts.open(tx,actor.tenantId());var scopedFacts=service.lockedLedgerFacts(tx,actor.tenantId());var opening=io.github.windyzhu3.ontologylaw.opportunity.EventOpportunityReader.databaseBacked().fencedReadScope(tx,actor.tenantId())){if(!R2OpportunityServiceScopeReader.databaseBacked().opportunityScope(tx,actor,"CONTRACT_TASK_RECOVER",now).authorized())throw new R1ServiceReadRuntime.Failure(403,"NOT_AUTHORIZED");var cursor=encoded==null?new Cursor(now,null,false):decode(actor,encoded,now);if(cursor.transfer()&&(transfers==null||!transfers.configured(actor.tenantId())))throw new R1ServiceReadRuntime.Failure(400,"VALIDATION_FAILED");var page=cursor.transfer()?transfers.page(tx,actor,Math.min(limit,10),cursor.after()):service.recoveryPage(tx,actor,Math.min(limit,10),cursor.after());var items=new ArrayList<Map<String,Object>>();for(var candidate:page.candidates()){var binding=new CommandAuthorizationBinding.ContractRecovery(candidate.opportunity(),candidate.basis(),candidate.source(),candidate.workflow());var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),candidate.opportunity());var facts=cursor.transfer()?R2TransferRecoveryService.facts(tx,actor.tenantId(),candidate.opportunity().id()):service.protectedFacts(tx,actor.tenantId(),candidate.opportunity().id());if(org==null||!OpportunityOwnerExceptionAuthorityReader.databaseBacked().permitted(tx,actor,org,facts,"CONTRACT_TASK_RECOVER"))throw new R1ServiceReadRuntime.Failure(403,"NOT_AUTHORIZED");var row=new TreeMap<String,Object>();row.put("kind","CONTRACT_PREPARATION");row.put("sourceKind",binding.sourceKind());row.put("idempotencyKey",commandId(actor.tenantId(),binding).toString());row.put("opportunityId",candidate.opportunity().id().toString());row.put("expectedOpportunityRevision",candidate.opportunity().revision());row.put("responsibilityBasis",selector(candidate.basis()));row.put("source",selector(candidate.source()));row.put("expectedWorkflow",selector(candidate.workflow()));items.add(Collections.unmodifiableMap(row));}if(!R2OpportunityServiceScopeReader.databaseBacked().opportunityScope(tx,actor,"CONTRACT_TASK_RECOVER",R1ServiceReadRuntime.databaseTime(tx)).authorized())throw new R1ServiceReadRuntime.Failure(403,"NOT_AUTHORIZED");var result=new LinkedHashMap<String,Object>();result.put("candidates",List.copyOf(items));result.put("nextCursor",page.exhausted()?(!cursor.transfer()&&transfers!=null&&transfers.configured(actor.tenantId())?encode(actor,new Cursor(cursor.observed(),null,true)):null):encode(actor,new Cursor(cursor.observed(),page.lastScannedSource(),cursor.transfer())));return Collections.unmodifiableMap(result);}});}
 private static Map<String,Object> selector(Subject s){return s==null?null:Map.of("id",s.id().toString(),"revision",s.revision());}
 static UUID commandId(UUID tenant,CommandAuthorizationBinding.ContractRecovery binding){try{var sha=MessageDigest.getInstance("SHA-1");var ns=UUID.fromString("6ba7b811-9dad-11d1-80b4-00c04fd430c8");sha.update(ByteBuffer.allocate(16).putLong(ns.getMostSignificantBits()).putLong(ns.getLeastSignificantBits()).array());var hash=sha.digest(CommandScope.contractRecovery(tenant,binding).canonical().getBytes(StandardCharsets.UTF_8));hash[6]=(byte)((hash[6]&15)|0x50);hash[8]=(byte)((hash[8]&63)|0x80);var bytes=ByteBuffer.wrap(hash);return new UUID(bytes.getLong(),bytes.getLong());}catch(NoSuchAlgorithmException impossible){throw new IllegalStateException(impossible);}}
 private String encode(Actor actor,Cursor c){String raw="R2_CONTRACT_PREPARATION_CURSOR_V3\n"+actor.tenantId()+"\n"+actor.principalId()+"\n"+actor.appointmentId()+"\n"+c.observed()+"\n"+(c.after()==null?"-":c.after())+"\n"+(c.transfer()?"TRANSFER":"CONTRACT");byte[] data=raw.getBytes(StandardCharsets.UTF_8);return base64(data)+"."+base64(mac(data));}
 private Cursor decode(Actor actor,String encoded,Instant now){try{if(encoded.length()>2048)throw new IllegalArgumentException();var p=encoded.split("\\.",-1);if(p.length!=2)throw new IllegalArgumentException();byte[] data=Base64.getUrlDecoder().decode(p[0]),signature=Base64.getUrlDecoder().decode(p[1]);if(!base64(data).equals(p[0])||!base64(signature).equals(p[1])||!MessageDigest.isEqual(mac(data),signature))throw new IllegalArgumentException();var f=new String(data,StandardCharsets.UTF_8).split("\n",-1);if(f.length!=7||!f[0].equals("R2_CONTRACT_PREPARATION_CURSOR_V3")||!f[1].equals(actor.tenantId().toString())||!f[2].equals(actor.principalId().toString())||!f[3].equals(actor.appointmentId().toString()))throw new IllegalArgumentException();var at=Instant.parse(f[4]);if(at.isAfter(now)||!now.isBefore(at.plusSeconds(300)))throw new IllegalArgumentException();if(!Set.of("TRANSFER","CONTRACT").contains(f[6]))throw new IllegalArgumentException();return new Cursor(at,f[5].equals("-")?null:UUID.fromString(f[5]),f[6].equals("TRANSFER"));}catch(IllegalArgumentException|DateTimeException invalid){throw new R1ServiceReadRuntime.Failure(400,"VALIDATION_FAILED");}}
 private static String base64(byte[] value){return Base64.getUrlEncoder().withoutPadding().encodeToString(value);}
 private byte[] mac(byte[] value){try{var mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(key,"HmacSHA256"));return mac.doFinal(value);}catch(GeneralSecurityException impossible){throw new IllegalStateException(impossible);}}
}
