package io.github.windyzhu3.ontologylaw.api;

import io.github.windyzhu3.ontologylaw.execution.CommandEnvelope.Type;
import java.util.*;

/** Static operation/error binding from the single frozen OpenAPI contract. */
final class R1HttpOperations {
    record Operation(Type command,Set<String> errors){}
    private static Set<String> codes(String... groups){var result=new HashSet<String>();for(var group:groups)result.addAll(List.of(group.split(" ")));return Set.copyOf(result);}
    private static final String COMMON="UNAUTHENTICATED NOT_AUTHORIZED RATE_LIMITED INTERNAL_ERROR SERVICE_UNAVAILABLE";
    private static final String WRITE="VALIDATION_FAILED IDEMPOTENCY_KEY_REQUIRED IDEMPOTENCY_KEY_INVALID COMMAND_PAYLOAD_CONFLICT";
    private static final String TASK="APPOINTMENT_INACTIVE NOT_FOUND TASK_NOT_OPEN TASK_ALREADY_COMPLETED DRAFT_DIGEST_MISMATCH STALE_TASK STALE_DRAFT STALE_SUBJECT TASK_PRECONDITION_REQUIRED";
    private static final Set<String> READ=codes(COMMON,"NOT_FOUND VALIDATION_FAILED");
    private R1HttpOperations(){}
    static Operation find(String method,String path){
        if(method.equals("GET")&&path.matches("/api/v1/business-overview(?:/[^/]+)?"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("GET")&&path.matches("/api/v1/lead-management/(?:sources|leads(?:/[^/]+)?)"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("GET")&&path.matches("/api/v1/team-management/(?:tasks|waiting|exceptions|history)(?:/[^/]+)?"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("GET")&&path.matches("/api/v1/business-management/(?:payments|transfer)(?:/[^/]+)?"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("GET")&&path.matches("/api/v1/opportunities/[^/]+/transfers/classification-context"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("POST")&&path.equals("/internal/v1/sales-chain-repairs/restore-source-request-task"))return new Operation(Type.RESTORE_SOURCE_REQUEST_TASK,codes(COMMON,WRITE,"STALE_TASK STALE_SUBJECT STALE_DRAFT SUPERVISOR_UNRESOLVED"));
        if(method.equals("POST")&&path.equals("/internal/v1/sales-chain-repairs/repair-superseded-opportunity-task"))return new Operation(Type.REPAIR_SUPERSEDED_OPPORTUNITY_TASK,codes(COMMON,WRITE,"STALE_TASK STALE_SUBJECT STALE_DRAFT SUPERVISOR_UNRESOLVED"));
        if(method.equals("GET")&&path.matches("/api/v1/transfer-tasks/[^/]+/(?:context|materials/[^/]+/content)"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT STALE_EVIDENCE STALE_TRANSFER_REVIEW_BASIS"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/transfers/(?:submissions|supplements|conflict-reviews|intake-decisions|classifications)"))return new Operation(R2TransferApiDelegate.commandType(path.substring(path.lastIndexOf('/')+1)),codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_TASK STALE_EVIDENCE CUSTOMER_CONFIRMATION_REQUIRED OPPORTUNITY_CLOSED RECIPIENT_UNAVAILABLE STALE_CUSTOMER_BASIS STALE_REVIEW STALE_TRANSFER_PARTY STALE_TRANSFER_REVIEW_BASIS TRANSFER_REVIEW_OUTCOME_UNAVAILABLE"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/contracts/generate"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT STALE_EVIDENCE OPPORTUNITY_CLOSED CUSTOMER_CONFIRMATION_REQUIRED CONTRACT_PREPARATION_SOURCE_REQUIRED COMMERCIAL_AUTHORIZATION_REQUIRED CONTRACT_VERSION_BASIS_CHANGED CONTRACT_HANDLING_PAUSED"));
        if(method.equals("GET")&&path.equals("/internal/v1/contract-preparation/candidates"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("POST")&&path.equals("/internal/v1/opportunity-tasks/commands/reconcile-contract-preparation"))return new Operation(Type.RECONCILE_CONTRACT_PREPARATION,codes(COMMON,WRITE,"NOT_FOUND STALE_SUBJECT"));
        if(path.matches("/api/v1/opportunities/[^/]+/(?:quotes/)?followup-attempts")){
            if(method.equals("GET")&&!path.contains("/quotes/"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
            if(method.equals("POST"))return new Operation(path.contains("/quotes/")?Type.RECORD_QUOTE_FOLLOWUP_ATTEMPT:Type.RECORD_OPPORTUNITY_FOLLOWUP_ATTEMPT,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_TASK OPPORTUNITY_CLOSED OPPORTUNITY_HAS_DOWNSTREAM_FACTS"));
        }
        if(method.equals("GET")&&(path.equals("/api/v1/contracts")||path.matches("/api/v1/opportunities/[^/]+/contracts(?:/[^/]+/versions/[^/]+/document)?")||path.matches("/api/v1/contract-tasks/[^/]+/context")))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT STALE_EVIDENCE COMMERCIAL_AUTHORIZATION_REQUIRED CONTRACT_APPROVAL_POLICY_CHANGED CONTRACT_APPROVAL_POLICY_REQUIRED CONTRACT_REVIEW_REQUIRED CONTRACT_SOURCE_AMBIGUOUS CONTRACT_VERSION_BASIS_CHANGED CONTRACT_PREPARATION_SOURCE_REQUIRED CONTRACT_RESPONSIBILITY_REQUIRED CONTRACT_REVIEW_SCOPE_REQUIRED CONTRACT_REVIEW_NOT_CLEAR CONTRACT_REVIEW_SCOPE_COMPLETE CONTRACT_REVIEW_FINDING_REQUIRED CONTRACT_REVIEW_WAIVER_UNAVAILABLE CONTRACT_CONFLICT_DECISION_REQUIRED"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/contracts/(?:preparation-requests|preparation-decisions|start|draft|form|review-requests|review-decisions|approval-requests|decisions|signature-draft|signature-arrangements|signature-submissions|signature-verifications|signature-archive|signature-revision|signature-verification-revision|receipt-review-requests|receipt-reviews|receipt-supplements|execution-verifications|negotiation-end|termination-review-requests|termination-review-decisions)")){var action=path.substring(path.lastIndexOf('/')+1);var type=switch(action){case "receipt-review-requests"->Type.REQUEST_CONTRACT_RECEIPT_REVIEW;case "receipt-reviews"->Type.RECORD_CONTRACT_RECEIPT_REVIEW;case "receipt-supplements"->Type.SUPPLEMENT_CONTRACT_RECEIPT;case "execution-verifications"->Type.VERIFY_CONTRACT_EXECUTION_CONDITIONS;case "negotiation-end"->Type.END_CONTRACT_NEGOTIATION;case "termination-review-requests"->Type.REQUEST_CONTRACT_TERMINATION_REVIEW;case "termination-review-decisions"->Type.RECORD_CONTRACT_TERMINATION_REVIEW;case "signature-draft"->Type.SAVE_CONTRACT_SIGNATURE_DRAFT;case "signature-arrangements"->Type.CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT;case "signature-submissions"->Type.SUBMIT_CONTRACT_SIGNATURE;case "signature-verifications"->Type.RECORD_CONTRACT_SIGNATURE_VERIFICATION;case "signature-archive"->Type.ARCHIVE_CONTRACT_SIGNATURE;case "signature-verification-revision"->Type.RETURN_CONTRACT_SIGNATURE_FOR_REVISION;case "signature-revision"->Type.RETURN_CONTRACT_FOR_REVISION;case "preparation-requests"->Type.REQUEST_CONTRACT_PREPARATION;case "preparation-decisions"->Type.RECORD_CONTRACT_PREPARATION_DECISION;case "start"->Type.START_CONTRACT_PREPARATION;case "draft"->Type.SAVE_CONTRACT_DRAFT;case "form"->Type.FORM_CONTRACT;case "review-requests"->Type.REQUEST_CONTRACT_REVIEW;case "review-decisions"->Type.RECORD_CONTRACT_REVIEW;case "approval-requests"->Type.REQUEST_CONTRACT_APPROVAL;case "decisions"->Type.RECORD_CONTRACT_DECISION;default->throw new IllegalArgumentException();};return new Operation(type,codes(COMMON,WRITE,(action.startsWith("signature-")||action.equals("execution-verifications"))?"SIGNATURE_INCOMPLETE CONTRACT_TEMPLATE_SIGNING_PARTY_REQUIRED":"","PAYMENT_ALREADY_RECORDED PAYMENT_ACCOUNT_NOT_CONFIGURED CONTRACT_HANDLING_PAUSED APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_DRAFT STALE_TASK STALE_EVIDENCE CUSTOMER_CONFIRMATION_REQUIRED OPPORTUNITY_CLOSED COMMERCIAL_AUTHORIZATION_REQUIRED CONTRACT_APPROVAL_POLICY_CHANGED CONTRACT_APPROVAL_POLICY_REQUIRED CONTRACT_REVIEW_REQUIRED CONTRACT_SOURCE_AMBIGUOUS CONTRACT_VERSION_BASIS_CHANGED CONTRACT_PREPARATION_SOURCE_REQUIRED CONTRACT_RESPONSIBILITY_REQUIRED CONTRACT_REVIEW_SCOPE_REQUIRED CONTRACT_REVIEW_NOT_CLEAR CONTRACT_REVIEW_SCOPE_COMPLETE CONTRACT_REVIEW_FINDING_REQUIRED CONTRACT_REVIEW_WAIVER_UNAVAILABLE CONTRACT_CONFLICT_DECISION_REQUIRED"));}
        if(method.equals("GET")&&(path.matches("/api/v1/opportunities/[^/]+/quotes(?:/[^/]+/document)?")||path.matches("/api/v1/quote-tasks/[^/]+/context")))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/quotes/(?:terminations|preparation-intents|draft|form|approval-requests|decisions|deliveries|responses)")){var action=path.substring(path.lastIndexOf('/')+1);var type=switch(action){case "terminations"->Type.END_QUOTE_NEGOTIATION;case "preparation-intents"->Type.START_QUOTE_PREPARATION;case "draft"->Type.SAVE_QUOTE_DRAFT;case "form"->Type.FORM_QUOTE;case "approval-requests"->Type.REQUEST_QUOTE_APPROVAL;case "decisions"->Type.RECORD_QUOTE_DECISION;case "deliveries"->Type.RECORD_QUOTE_DELIVERY;case "responses"->Type.RECORD_QUOTE_RESPONSE;default->throw new IllegalArgumentException();};return new Operation(type,codes(COMMON,WRITE,(action.startsWith("signature-")||action.equals("execution-verifications"))?"SIGNATURE_INCOMPLETE CONTRACT_TEMPLATE_SIGNING_PARTY_REQUIRED":"","APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_DRAFT STALE_TASK STALE_EVIDENCE CUSTOMER_CONFIRMATION_REQUIRED OPPORTUNITY_CLOSED"));}
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/(?:material-uploads|materials/accept)"))return new Operation(path.endsWith("/accept")?Type.ACCEPT_OPPORTUNITY_MATERIAL:Type.OPEN_OPPORTUNITY_MATERIAL_UPLOAD,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT OPPORTUNITY_CLOSED"));
        if((method.equals("GET")||method.equals("PUT"))&&path.matches("/api/v1/opportunities/[^/]+/(?:materials(?:/versions/[^/]+/content)?|material-uploads/[^/]+(?:/content)?)"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("GET")&&path.matches("/api/v1/opportunities/[^/]+/customer-requirements(?:/parties)?"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_SUBJECT"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/customer-requirements/(?:draft|confirm)"))return new Operation(path.endsWith("/draft")?Type.SAVE_OPPORTUNITY_CUSTOMER_DRAFT:Type.CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_DRAFT OPPORTUNITY_CLOSED"));
        if(method.equals("GET")&&path.matches("/api/v1/opportunities/[^/]+/closure"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED STALE_SUBJECT"));
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/commands/close"))return new Operation(Type.CLOSE_OPPORTUNITY,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT STALE_TASK OPPORTUNITY_CLOSED OPPORTUNITY_HAS_DOWNSTREAM_FACTS"));
        if(method.equals("GET")&&(path.matches("/api/v1/opportunity-tasks/[^/]+/context")||path.equals("/api/v1/opportunities")||path.matches("/api/v1/opportunities/[^/]+")))return new Operation(null,codes(COMMON,"VALIDATION_FAILED STALE_SUBJECT"));
        if(method.equals("GET")&&(path.equals("/api/v1/opportunity-owner-exceptions")||path.equals("/api/v1/opportunity-owner-exceptions/operations")||path.matches("/api/v1/opportunity-owner-exceptions/[^/]+(?:/candidates)?")))return new Operation(null,codes(COMMON,"VALIDATION_FAILED STALE_SUBJECT"));
        if(method.equals("POST")&&(path.equals("/internal/v1/opportunity-owner-exceptions/commands/observe")||path.equals("/api/v1/opportunity-owner-exceptions/commands/transfer")||path.equals("/api/v1/opportunity-owner-exceptions/commands/coordinate"))){
            Type type=path.endsWith("/observe")?Type.OBSERVE_OPPORTUNITY_OWNER_EXCEPTION:path.endsWith("/transfer")?Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY:Type.RECORD_OPPORTUNITY_OWNER_COORDINATION;
            return new Operation(type,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND STALE_SUBJECT"));
        }
        if(method.equals("GET")&&path.equals("/internal/v1/opportunity-owner-exceptions/candidates"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED STALE_SUBJECT"));
        if(method.equals("GET")&&path.equals("/internal/v1/opportunity-tasks/candidates"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED"));
        if(method.equals("POST")&&path.startsWith("/internal/v1/opportunity-tasks/commands/")){
            Type type=switch(path){case "/internal/v1/opportunity-tasks/commands/activate-initial"->Type.ACTIVATE_INITIAL_OPPORTUNITY_TASK;case "/internal/v1/opportunity-tasks/commands/reopen-due"->Type.REOPEN_DUE_OPPORTUNITY_TASKS;default->null;};
            if(type!=null)return new Operation(type,codes(COMMON,WRITE,"NOT_FOUND STALE_TASK STALE_SUBJECT STALE_PROGRESS OPPORTUNITY_OPENING_SOURCE_INVALID OPPORTUNITY_NOT_FOUND STALE_OPPORTUNITY OPPORTUNITY_CLOSED"));
        }
        if(method.equals("GET")&&path.equals("/api/v1/leads/intake-sources"))return new Operation(null,codes("VALIDATION_FAILED UNAUTHENTICATED NOT_AUTHORIZED APPOINTMENT_INACTIVE SERVICE_UNAVAILABLE"));
        if(method.equals("PUT")&&path.matches("/api/v1/tasks/[^/]+/(opportunity-progress-draft|source-request-draft)"))return new Operation(Type.SAVE_ACTION_DRAFT,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND TASK_NOT_OPEN TASK_ALREADY_COMPLETED DRAFT_DIGEST_MISMATCH STALE_TASK STALE_DRAFT STALE_SUBJECT DRAFT_PRECONDITION_REQUIRED"));
        if(path.startsWith("/api/v1/admin/identity/"))return identity(method,path);
        if(method.equals("POST")&&path.matches("/api/v1/opportunities/[^/]+/ai-candidates/[^/]+(?:/recheck)?"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED STALE_SUBJECT"));
        if(method.equals("GET")&&path.equals("/api/v1/session/context"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED"));
        if(method.equals("GET")&&(path.equals("/api/v1/workcards/current")||path.matches("/api/v1/commands/[^/]+/receipt")))return new Operation(null,READ);
        if(method.equals("GET")&&(path.equals("/internal/v1/projections/r1/readiness")||path.equals("/internal/v1/tasks/due")))return new Operation(null,codes(COMMON,"VALIDATION_FAILED"));
        if(method.equals("POST")&&path.equals("/internal/v1/projections/r1/consume"))return new Operation(null,codes(COMMON,"VALIDATION_FAILED NOT_FOUND STALE_OUTBOX_CLAIM PROJECTION_EVENT_INVALID"));
        if(method.equals("POST")&&path.equals("/api/v1/leads"))return new Operation(Type.CAPTURE_LEAD,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE SUPERVISOR_UNRESOLVED"));
        if(method.equals("PUT")&&path.matches("/api/v1/tasks/[^/]+/draft"))return new Operation(Type.SAVE_ACTION_DRAFT,codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND TASK_NOT_OPEN TASK_ALREADY_COMPLETED DRAFT_DIGEST_MISMATCH STALE_TASK STALE_DRAFT DRAFT_PRECONDITION_REQUIRED"));
        if(!method.equals("POST"))return null;
        if(path.equals("/internal/v1/tasks/commands/reopen-due-source-request-tasks"))return new Operation(Type.REOPEN_DUE_SOURCE_REQUEST_TASKS,codes(COMMON,WRITE));
        if(path.equals("/internal/v1/tasks/commands/reopen-due-contact-tasks"))return new Operation(Type.REOPEN_DUE_CONTACT_TASKS,codes(COMMON,WRITE));
        if(path.equals("/internal/v1/tasks/commands/reopen-due-routing-review-tasks"))return new Operation(Type.REOPEN_DUE_ROUTING_REVIEW_TASKS,codes(COMMON,WRITE));
        if(!path.matches("/api/v1/tasks/[^/]+/commands/[^/]+"))return null;
        Type type=switch(path.substring(path.lastIndexOf('/')+1)){
            case "record-source-request-continuation"->Type.RECORD_SOURCE_REQUEST_CONTINUATION;case "record-opportunity-progress"->Type.RECORD_OPPORTUNITY_PROGRESS;case "resolve-duplicate-lead"->Type.RESOLVE_DUPLICATE_LEAD;case "complete-lead-ingress"->Type.COMPLETE_LEAD_INGRESS;case "assign-lead"->Type.ASSIGN_LEAD;case "record-routing-disposition"->Type.RECORD_ROUTING_DISPOSITION;case "acknowledge-source-intake-stop-request"->Type.ACKNOWLEDGE_SOURCE_INTAKE_STOP_REQUEST;case "record-contact-result"->Type.RECORD_CONTACT_RESULT;case "review-lead-validity"->Type.REVIEW_LEAD_VALIDITY;default->null;};
        if(type==null)return null;var errors=new HashSet<>(codes(COMMON,WRITE,TASK));
        if(Set.of(Type.RESOLVE_DUPLICATE_LEAD,Type.COMPLETE_LEAD_INGRESS,Type.RECORD_CONTACT_RESULT,Type.RECORD_SOURCE_REQUEST_CONTINUATION,Type.ACKNOWLEDGE_SOURCE_INTAKE_STOP_REQUEST).contains(type))errors.add("SUPERVISOR_UNRESOLVED");
        if(type==Type.COMPLETE_LEAD_INGRESS)errors.add("INGRESS_COMPLETION_ALREADY_RECORDED");
        if(type==Type.RECORD_ROUTING_DISPOSITION)errors.add("SOURCE_INTAKE_OWNER_UNRESOLVED");
        return new Operation(type,Set.copyOf(errors));
    }
    private static Operation identity(String method,String path) {
        String resource=path.substring("/api/v1/admin/identity/".length());
        if(method.equals("GET")&&Set.of("provider-users","options","principals","organizations","appointments","authority-grants").contains(resource))return new Operation(null,codes(COMMON,"VALIDATION_FAILED APPOINTMENT_INACTIVE NOT_FOUND"));
        String[] pieces=resource.split("/");String noun=switch(pieces[0]){case "principals"->"IDENTITY_PRINCIPAL";case "organizations"->"ORGANIZATION_UNIT";case "appointments"->"APPOINTMENT";case "authority-grants"->"AUTHORITY_GRANT";default->null;};if(noun==null)return null;
        String command=null;
        if(pieces.length==1&&method.equals("POST"))command="CREATE_"+noun;
        else if(pieces.length==3){String action=switch(pieces[2]){case "display-name"->method.equals("PATCH")?"RENAME":null;case "suspend","resume","disable","close","end","revoke"->method.equals("POST")?pieces[2].toUpperCase(Locale.ROOT):null;default->null;};if(action!=null)command=action+"_"+noun;}
        if(command==null||!io.github.windyzhu3.ontologylaw.identity.IdentityCommands.registered(command))return null;
        return new Operation(Type.valueOf(command),codes(COMMON,WRITE,"APPOINTMENT_INACTIVE NOT_FOUND IDENTITY_BINDING_CONFLICT IDENTITY_STATE_CONFLICT IDENTITY_SELF_LOCKOUT IDENTITY_LAST_ADMIN IDENTITY_ORGANIZATION_DEPENDENCY IDENTITY_RESPONSIBILITY_DEPENDENCY STALE_IDENTITY IDENTITY_PRECONDITION_REQUIRED"));
    }
}
