package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.audit.AuditAppender;import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.opportunity.*;
import io.github.windyzhu3.ontologylaw.contract.*;
import io.github.windyzhu3.ontologylaw.responsibility.CurrentTaskReader;
import java.sql.*;import java.util.*;
final class R2ContractReadService {
 private final ContractWorkflowService service;private final AuditAppender audit;private final OpportunityLedgerAuthorityReader authority=OpportunityLedgerAuthorityReader.databaseBacked();
 private final R2ManagementCursor cursor;
 R2ContractReadService(ContractWorkflowService service,AuditAppender audit){this(service,audit,new java.security.SecureRandom().generateSeed(32));}
 R2ContractReadService(ContractWorkflowService service,AuditAppender audit,byte[] key){this.service=Objects.requireNonNull(service);this.audit=audit;this.cursor=new R2ManagementCursor(key);}
 Map<String,Object> ledger(Connection c,Actor actor)throws SQLException{return ledger(c,actor,20,null,null,null);}
 Map<String,Object> ledger(Connection c,Actor actor,int limit,String encoded,String search,String state)throws SQLException {
  String query=search==null?"":search.strip().toLowerCase(Locale.ROOT),filter=state==null?"":state.strip();
  if(limit<1||limit>100||query.length()>200||filter.length()>80||query.chars().anyMatch(Character::isISOControl)||filter.chars().anyMatch(Character::isISOControl))throw new R1ServiceReadRuntime.Failure(400,"VALIDATION_FAILED");
  String scope=CanonicalJson.encode(Map.of("purpose","R25_CONTRACT_LEDGER_V1","tenant",actor.tenantId().toString(),"principal",actor.principalId().toString(),"appointment",actor.appointmentId().toString(),"limit",limit,"search",query,"state",filter));
  return ContractReadRuntime.read(c,actor,audit,(tx,now)->{try(var sourceScope=R2LedgerSourceFacts.open(tx,actor.tenantId());var factsScope=service.lockedLedgerFacts(tx,actor.tenantId());var quoteScope=QuoteWorkflowService.lockedLedgerFacts(tx,actor.tenantId());var opportunityScope=EventOpportunityReader.databaseBacked().fencedReadScope(tx,actor.tenantId())){
  UUID after=cursor.decode(encoded,scope,now),last=after;int consumed=0;
  var candidates=service.ledgerOpportunities(tx,actor.tenantId(),100,after);
  service.prepareLedgerCandidates(tx,actor.tenantId(),candidates,Math.min(limit,20));QuoteWorkflowService.prepareLedgerCandidates(tx,actor.tenantId(),candidates,Math.min(limit,20));
  var rows=new ArrayList<Map<String,Object>>();var ds=new ArrayList<AuditAppender.ContractDisclosureEntry>();var taskSnapshots=new ArrayList<CurrentTaskReader.Task>();
  for(var id:candidates){consumed++;last=id;var opening=EventOpportunityReader.databaseBacked().byId(tx,actor.tenantId(),id);if(opening==null)continue;var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),opening.selector());var fs=service.protectedFacts(tx,actor.tenantId(),id);if(org==null||fs.isEmpty())continue;var rowDisclosures=new ArrayList<AuditAppender.ContractDisclosureEntry>();var authorizations=R1AuthorityReader.databaseBacked().authorizeAll(tx,actor,fs,org,"OPPORTUNITY_OWNER","CONTRACT_READ");if(authorizations.size()!=fs.size())continue;for(int i=0;i<fs.size();i++)rowDisclosures.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),fs.get(i),authorizations.get(i),"HISTORY"));
   var value=ledgerContext(tx,actor,id,org,fs,rowDisclosures,taskSnapshots);var contract=(Map<?,?>)value.get("contract");if(contract==null)continue;var selector=(Map<?,?>)contract.get("selector");if(selector==null)throw fail("STALE_SUBJECT");var row=new LinkedHashMap<String,Object>();row.put("id",selector.get("id"));row.put("opportunityId",id.toString());row.put("customerLabel",value.getOrDefault("customerName",""));var version=contract.get("version");row.put("versionLabel",version==null||((Number)version).longValue()==0?"未形成版本":"第 "+version+" 版");var workflow=(Map<?,?>)value.get("workflow");Object stage=Boolean.TRUE.equals(value.get("financeSelected"))&&workflow!=null?workflow.get("stage"):value.get("termination") instanceof Map<?,?> handling&&!"CONTINUED".equals(handling.get("state"))?handling.get("state"):workflow==null?contract.get("stage"):workflow.get("stage");row.put("stateLabel",stageLabel(stage));row.put("ownerLabel",workflow==null||workflow.get("ownerLabel")==null?"":workflow.get("ownerLabel"));row.put("canHandle",!((List<?>)value.getOrDefault("allowedActions",List.of())).isEmpty());if(workflow!=null&&workflow.get("dueAt")!=null)row.put("dueAt",workflow.get("dueAt"));

   if("READY_TRANSFER".equals(String.valueOf(stage))){var transferLabel=R2TransferHistoryProjection.append(tx,actor,UUID.fromString((String)selector.get("id")),value,rowDisclosures,false);if(transferLabel!=null){row.put("stateLabel",transferLabel);if(value.get("transfer") instanceof Map<?,?> transfer)row.put("canHandle",transfer.get("canHandle"));row.put("ownerLabel","");row.remove("dueAt");}}
   // ContractReadRuntime retains the business fence and identity lock through commit.
   // Business facts cannot change under that fence; keep fresh-time permission and task
   // verification below rather than rebuilding the entire source graph a second time.
   ds.addAll(rowDisclosures);
   if(!String.valueOf(row.get("customerLabel")).toLowerCase(Locale.ROOT).contains(query)||!filter.isEmpty()&&!filter.equals(row.get("stateLabel")))continue;
   rows.add(Collections.unmodifiableMap(row));if(rows.size()==limit)break;
  }verifyTasks(tx,actor,taskSnapshots);for(var authorization:AuthorizationService.databaseBacked().evaluateAll(tx,ds.stream().map(d->d.authorization().request()).toList(),true))if(!authorization.allowed())throw fail("NOT_AUTHORIZED");var response=new LinkedHashMap<String,Object>();response.put("items",List.copyOf(rows));response.put("nextCursor",last!=null&&(consumed<candidates.size()||candidates.size()==100)?cursor.encode(last,scope,now):null);return new ContractReadRuntime.Prepared<>(Collections.unmodifiableMap(response),ds);
 }});}
 private static String stageLabel(Object raw){return switch(String.valueOf(raw)){case "CHECK_RECEIPT"->"待核对本笔收款";case "SUPPLEMENT_RECEIPT"->"待补充收款凭证";case "COMPLETE"->"本笔收款已核对";case "CHECK_CONDITIONS"->"待核对执行条件";case "WAIT_RECEIPT"->"等待约定首款到账";case "READY_TRANSFER"->"已具备转案条件";case "STOPPED"->"本次销售办理已停止";case "REVIEW_REQUIRED"->"终止签约待主管核对";case "ARRANGE"->"待核对签署安排";case "COLLECT"->"待提交签署材料";case "AWAIT_VERIFICATION"->"待签署核验";case "SUPPLEMENT"->"待补充签署材料";case "PARTIAL"->"部分签署完成";case "ARCHIVE"->"待签署归档";case "SIGNATURE_COMPLETE"->"签署归档完成";case "REVISION_REQUIRED"->"待修订合同";case "OWNER_EXCEPTION"->"合同责任待安排";case "DIRECT_REQUEST"->"待申请准备";case "DIRECT_REVIEW"->"待准备授权";case "DIRECT_RETURNED"->"准备申请已退回";case "PREPARE"->"待形成合同";case "SUBMIT_REVIEW"->"待提交签约前审查";case "AWAIT_REVIEW"->"待签约前审查";case "REVIEW_SUPPLEMENT"->"待补充审查资料";case "REVIEW_BLOCKED"->"审查阻断";case "SUBMIT_APPROVAL"->"待提交审批";case "AWAIT_APPROVAL"->"待审批";case "RETURNED"->"合同已退回";case "READY_FOR_SIGNATURE","AWAITING_NEXT_STAGE"->"签署准备已就绪";default->"待核实办理状态";};}
 Map<String,Object> read(Connection c,Actor actor,UUID id)throws SQLException{return disclose(c,actor,id,(tx,disclosures,taskSnapshots)->context(tx,actor,id,disclosures,taskSnapshots),"BODY");}
 byte[] document(Connection c,Actor actor,UUID id,UUID contract,UUID version)throws SQLException{return disclose(c,actor,id,(tx,disclosures,taskSnapshots)->service.document(tx,actor,id,contract,version),"DOWNLOAD");}
 ContractWorkflowService.Generation generation(Connection c,Actor actor,UUID id,Map<String,Object> payload)throws SQLException{return disclose(c,actor,id,(tx,disclosures,taskSnapshots)->service.generation(tx,actor,payload),"BODY");}
 Map<String,Object> task(Connection c,Actor actor,UUID taskId)throws SQLException{
  return ContractReadRuntime.read(c,actor,audit,(tx,now)->{try(var sourceScope=R2LedgerSourceFacts.open(tx,actor.tenantId());var factsScope=service.lockedLedgerFacts(tx,actor.tenantId());var opportunityScope=EventOpportunityReader.databaseBacked().fencedReadScope(tx,actor.tenantId())){var task=io.github.windyzhu3.ontologylaw.responsibility.TaskFactory.databaseBacked().read(tx,actor.tenantId(),taskId);if(task==null||!task.type().name().contains("CONTRACT")||!task.owner().equals(actor.appointmentId())||!"opportunity.opportunity".equals(task.subject().type()))throw fail("NOT_AUTHORIZED");
   var id=task.subject().id();var opening=EventOpportunityReader.databaseBacked().byId(tx,actor.tenantId(),id);if(opening==null)throw fail("NOT_FOUND");var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),opening.selector());var fs=new ArrayList<>(service.disclosureFacts(tx,actor,id));fs.add(task.selector());if(org==null||!authority.permitted(tx,actor,org,fs,"CONTRACT_READ"))throw fail("NOT_AUTHORIZED");var ds=new ArrayList<AuditAppender.ContractDisclosureEntry>();var taskSnapshots=new ArrayList<CurrentTaskReader.Task>();for(var f:fs){var a=authority.evidence(tx,actor,org,f,"CONTRACT_READ");if(a==null||!a.allowed())throw fail("NOT_AUTHORIZED");ds.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),f,a,"BODY"));}var context=context(tx,actor,id,ds,taskSnapshots);var freshTask=io.github.windyzhu3.ontologylaw.responsibility.TaskFactory.databaseBacked().read(tx,actor.tenantId(),taskId);var fresh=new ArrayList<>(service.disclosureFacts(tx,actor,id));if(freshTask==null||!freshTask.selector().equals(task.selector())||!freshTask.owner().equals(actor.appointmentId()))throw fail("STALE_SUBJECT");fresh.add(freshTask.selector());if(!new LinkedHashSet<>(fs).equals(new LinkedHashSet<>(fresh)))throw fail("STALE_SUBJECT");for(var d:ds)if(!AuthorizationService.databaseBacked().evaluate(tx,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");verifyTasks(tx,actor,taskSnapshots);return new ContractReadRuntime.Prepared<>(Map.of("opportunityId",id.toString(),"context",context),ds);}});
 }
 @SuppressWarnings("unchecked") private Map<String,Object> ledgerContext(Connection c,Actor actor,UUID id,UUID org,List<Subject> facts,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> tasks)throws SQLException {
  var result=new LinkedHashMap<String,Object>(service.ledgerContext(c,actor,id));if(result.get("contract")==null)return result;
  var permissions=new HashMap<String,Boolean>();var allowed=new ArrayList<String>();
  for(String action:(List<String>)result.get("allowedActions")){String code=R1CommandPolicy.contractAuthority(CommandEnvelope.Type.valueOf(action));Boolean permitted=permissions.get(code);if(permitted==null){permitted=authority.permitted(c,actor,org,facts,code);permissions.put(code,permitted);}if(permitted)allowed.add(action);}
  result.put("allowedActions",List.copyOf(allowed));if(result.get("signature") instanceof Map<?,?> signature && signature.get("workflow") instanceof Map<?,?> workflow)result.put("workflow",workflow);if(result.get("execution") instanceof Map<?,?> execution&&execution.get("workflow") instanceof Map<?,?> workflow)result.put("workflow",workflow);if(result.get("termination") instanceof Map<?,?> handling&&!"CONTINUED".equals(handling.get("state")))result.put("workflow","STOPPED".equals(handling.get("state"))?null:handling);if(allowed.isEmpty()&&result.get("payments") instanceof List<?> payments){for(Object item:payments){var payment=(Map<String,Object>)item;var financialActions=(List<String>)payment.get("allowedActions");if(!financialActions.isEmpty()){var permittedActions=new ArrayList<String>();for(String action:financialActions)if(authority.permitted(c,actor,org,facts,R1CommandPolicy.contractAuthority(CommandEnvelope.Type.valueOf(action))))permittedActions.add(action);if(!permittedActions.isEmpty()){result.put("workflow",payment);result.put("allowedActions",List.copyOf(permittedActions));result.put("financeSelected",true);break;}}}}
  presentResponsibility(c,actor,id,org,result,disclosures,tasks);return result;
 }
 @SuppressWarnings("unchecked") private Map<String,Object> context(Connection c,Actor actor,UUID id,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> taskSnapshots)throws SQLException{var result=new LinkedHashMap<String,Object>(service.context(c,actor,id));var opening=EventOpportunityReader.databaseBacked().byId(c,actor.tenantId(),id);var org=R2OpportunityOwnerExceptionAssembly.organization(c,actor.tenantId(),opening.selector());var fs=service.disclosureFacts(c,actor,id);var allowed=new ArrayList<String>();for(String action:(List<String>)result.get("allowedActions"))if(authority.permitted(c,actor,org,fs,R1CommandPolicy.contractAuthority(CommandEnvelope.Type.valueOf(action))))allowed.add(action);result.put("allowedActions",List.copyOf(allowed));presentPayments(c,actor,id,org,result,disclosures,taskSnapshots);presentExecution(c,actor,id,org,result,disclosures,taskSnapshots);presentTermination(c,actor,id,org,result,disclosures,taskSnapshots);presentResponsibility(c,actor,id,org,result,disclosures,taskSnapshots);presentSignatureHistory(c,actor,org,result,disclosures,"signatureHistory");if(result.get("signature") instanceof Map<?,?> signature){var rendered=new LinkedHashMap<String,Object>();signature.forEach((k,v)->rendered.put((String)k,v));presentResponsibility(c,actor,id,org,rendered,disclosures,taskSnapshots);presentSignatureHistory(c,actor,org,rendered,disclosures,"historyEntries");if(rendered.containsKey("allowedActions"))rendered.put("allowedActions",((List<?>)signature.get("allowedActions")).stream().filter(allowed::contains).toList());result.put("signature",Collections.unmodifiableMap(rendered));}if(result.get("contract") instanceof Map<?,?> contract&&contract.get("selector") instanceof Map<?,?> selector)R2TransferHistoryProjection.append(c,actor,UUID.fromString((String)selector.get("id")),result,disclosures);return result;}
 private void presentExecution(Connection c,Actor actor,UUID id,UUID org,Map<String,Object> result,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> snapshots)throws SQLException {
  if(!(result.get("execution") instanceof Map<?,?> execution))return;
  var rendered=new LinkedHashMap<String,Object>();execution.forEach((k,v)->rendered.put((String)k,v));
  presentResponsibility(c,actor,id,org,rendered,disclosures,snapshots);result.put("execution",Collections.unmodifiableMap(rendered));
 }
 private void presentTermination(Connection c,Actor actor,UUID id,UUID org,Map<String,Object> result,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> snapshots)throws SQLException {
  if(!(result.get("termination") instanceof Map<?,?> handling))return;var container=new LinkedHashMap<String,Object>();container.put("workflow",handling);presentResponsibility(c,actor,id,org,container,disclosures,snapshots);result.put("termination",container.get("workflow"));
 }
 private void presentSignatureHistory(Connection c,Actor actor,UUID organization,Map<String,Object> result,List<AuditAppender.ContractDisclosureEntry> disclosures,String key)throws SQLException {
  if(!(result.get(key) instanceof List<?> entries))return;
  var names=new HashMap<String,String>();var presented=new ArrayList<Map<String,Object>>();
  for(var raw:entries){if(!(raw instanceof Map<?,?> entry))continue;var item=new LinkedHashMap<String,Object>();entry.forEach((k,v)->item.put((String)k,v));
   if(entry.get("actorAppointmentId") instanceof String id){
    if(!names.containsKey(id)){String name="";var owner=WorkcardOwnerReader.databaseBacked().read(c,actor.tenantId(),UUID.fromString(id));
     if(owner!=null){var authorized=new ArrayList<AuditAppender.ContractDisclosureEntry>();for(var fact:List.of(owner.appointment().selector(),owner.principal().selector(),owner.organization().selector())){var evidence=authority.evidence(c,actor,organization,fact,"CONTRACT_READ");if(evidence==null||!evidence.allowed()){authorized.clear();break;}authorized.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),fact,evidence,"BODY"));}if(authorized.size()==3){name=owner.principal().displayName();disclosures.addAll(authorized);}}
     names.put(id,name);
    }if(!names.get(id).isEmpty())item.put("actorLabel",entry.get("actorLabel")+" · "+names.get(id));
   }presented.add(Collections.unmodifiableMap(item));
  }result.put(key,List.copyOf(presented));
 }
 @SuppressWarnings("unchecked") private void presentPayments(Connection c,Actor actor,UUID id,UUID org,Map<String,Object> result,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> snapshots)throws SQLException{
  if(!(result.get("payments") instanceof List<?> entries))return;var rendered=new ArrayList<Object>();
  for(Object entry:entries){var payment=(Map<String,Object>)entry;var container=new LinkedHashMap<String,Object>();container.put("workflow",payment);presentResponsibility(c,actor,id,org,container,disclosures,snapshots);rendered.add(container.get("workflow"));}result.put("payments",List.copyOf(rendered));
 }
 private void presentResponsibility(Connection c,Actor actor,UUID opportunity,UUID organization,Map<String,Object> result,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> snapshots)throws SQLException {
  if(!(result.get("workflow") instanceof Map<?,?> workflow)||!(workflow.get("task") instanceof Map<?,?> selector))return;
  var task=CurrentTaskReader.databaseBacked().read(c,actor.tenantId(),UUID.fromString((String)selector.get("id")));
  if(task==null||!task.type().isContract()||!task.subject().type().equals("opportunity.opportunity")||!task.subject().id().equals(opportunity)||!Objects.equals(task.selector().revision(),((Number)selector.get("revision")).longValue())||!Objects.equals(task.owner().toString(),workflow.get("ownerAppointmentId")))throw fail("STALE_SUBJECT");
  var rendered=new LinkedHashMap<String,Object>();workflow.forEach((k,v)->rendered.put((String)k,v));rendered.put("ownerLabel","负责人信息受限");
  var taskEvidence=authority.evidence(c,actor,organization,task.selector(),"CONTRACT_READ");
  if(taskEvidence!=null&&taskEvidence.allowed()){
   rendered.put("dueAt",task.slaDueAt().toString());snapshots.add(task);
   disclosures.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),task.selector(),taskEvidence,"BODY"));
   var owner=WorkcardOwnerReader.databaseBacked().read(c,actor.tenantId(),task.owner());
   if(owner!=null){var facts=List.of(owner.appointment().selector(),owner.principal().selector(),owner.organization().selector());var authorized=new ArrayList<AuditAppender.ContractDisclosureEntry>();
    for(var fact:facts){var evidence=authority.evidence(c,actor,organization,fact,"CONTRACT_READ");if(evidence==null||!evidence.allowed()){authorized.clear();break;}authorized.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),fact,evidence,"BODY"));}
    if(authorized.size()==3){rendered.put("ownerLabel",owner.principal().displayName());disclosures.addAll(authorized);}
   }
  }
  result.put("workflow",Collections.unmodifiableMap(rendered));
 }
 private static void verifyTasks(Connection c,Actor actor,List<CurrentTaskReader.Task> snapshots)throws SQLException {
  for(var prior:snapshots)if(!prior.equals(CurrentTaskReader.databaseBacked().read(c,actor.tenantId(),prior.selector().id())))throw fail("STALE_SUBJECT");
 }
 @FunctionalInterface interface Read<T>{T run(Connection connection,List<AuditAppender.ContractDisclosureEntry> disclosures,List<CurrentTaskReader.Task> tasks)throws SQLException;}
 private <T>T disclose(Connection c,Actor actor,UUID id,Read<T> read,String mode)throws SQLException{return ContractReadRuntime.read(c,actor,audit,(tx,now)->{try(var sourceScope=R2LedgerSourceFacts.open(tx,actor.tenantId());var factsScope=service.lockedLedgerFacts(tx,actor.tenantId());var opportunityScope=EventOpportunityReader.databaseBacked().fencedReadScope(tx,actor.tenantId())){var opening=EventOpportunityReader.databaseBacked().byId(tx,actor.tenantId(),id);if(opening==null)throw fail("NOT_FOUND");var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),opening.selector());var fs=service.disclosureFacts(tx,actor,id);if(org==null||fs.isEmpty()||!authority.permitted(tx,actor,org,fs,"CONTRACT_READ"))throw fail("NOT_AUTHORIZED");var disclosures=new ArrayList<AuditAppender.ContractDisclosureEntry>();for(var f:fs){var a=authority.evidence(tx,actor,org,f,"CONTRACT_READ");if(a==null||!a.allowed())throw fail("NOT_AUTHORIZED");disclosures.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),f,a,mode));}var taskSnapshots=new ArrayList<CurrentTaskReader.Task>();var result=read.run(tx,disclosures,taskSnapshots);verifyTasks(tx,actor,taskSnapshots);for(var d:disclosures)if(!AuthorizationService.databaseBacked().evaluate(tx,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");if(!new LinkedHashSet<>(fs).equals(new LinkedHashSet<>(service.disclosureFacts(tx,actor,id))))throw fail("STALE_SUBJECT");return new ContractReadRuntime.Prepared<>(result,disclosures);}});}
 private static R1ServiceReadRuntime.Failure fail(String code){return new R1ServiceReadRuntime.Failure(code.equals("NOT_FOUND")?404:code.equals("STALE_SUBJECT")?412:403,code);}
}
