package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.contract.*;
import java.sql.*;import java.util.*;
/** Exact SERVICE-only recovery; page reads never create a responsibility. */
final class R2ContractRecoveryCommand implements CommandHandler {
 private final OpportunityCommandReader opportunities;private final ContractWorkflowService service;private final R2TransferRecoveryService transfers;
 R2ContractRecoveryCommand(OpportunityProgressProtection protection,ContractWorkflowService service){this(protection,service,null);}
 R2ContractRecoveryCommand(OpportunityProgressProtection protection,ContractWorkflowService service,R2TransferRecoveryService transfers){this.opportunities=OpportunityCommandReader.databaseBacked(protection);this.service=Objects.requireNonNull(service);this.transfers=transfers;}
 public CommandEnvelope.Type type(){return CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION;}
 static CommandAuthorizationBinding.ContractRecovery input(CommandEnvelope e){try{if(e.type()!=CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION||e.taskPrecondition()!=null||e.draftPrecondition()!=null||e.identityPrecondition()!=null)throw new IllegalArgumentException();var p=(Map<?,?>)e.payload();if(!p.keySet().equals(Set.of("opportunityId","expectedOpportunityRevision","responsibilityBasis","sourceKind","source","expectedWorkflow")))throw new IllegalArgumentException();if(!Set.of("ACCEPTED_QUOTE","AUTHORITY_RETURN","SIGNATURE_READINESS","SIGNATURE_AUTHORITY_RETURN","TERMINATION_REVIEW","EXECUTION_HANDOFF","PAYMENT_HANDOFF","PAYMENT_RECOVERY","TRANSFER_HANDOFF","TRANSFER_RECOVERY").contains(p.get("sourceKind")))throw new IllegalArgumentException();var opportunity=new Subject("opportunity.opportunity",uuid(p.get("opportunityId")),revision(p.get("expectedOpportunityRevision")),null);var raw=(Map<?,?>)p.get("responsibilityBasis");var basis=selector(raw,uuid(raw.get("id")).equals(opportunity.id())?"opportunity.opportunity":"opportunity.responsibility_handoff",false);var b=new CommandAuthorizationBinding.ContractRecovery(opportunity,basis,selector(p.get("source"),sourceType((String)p.get("sourceKind")),true),p.get("expectedWorkflow")==null?null:selector(p.get("expectedWorkflow"),((String)p.get("sourceKind")).startsWith("TRANSFER_")?"transfer.workflow":((String)p.get("sourceKind")).startsWith("PAYMENT_")?"contract.payment_workflow":p.get("sourceKind").equals("EXECUTION_HANDOFF")?"contract.execution_workflow":p.get("sourceKind").equals("TERMINATION_REVIEW")?"contract.termination_review_assignment":((String)p.get("sourceKind")).startsWith("SIGNATURE_")?"contract.signature_workflow":"contract.preparation_workflow",true));CommandScope.contractRecovery(e.actor().tenantId(),b);return b;}catch(IllegalArgumentException|NullPointerException|ClassCastException invalid){throw new Rejected("VALIDATION_FAILED");}}
 private static String sourceType(String kind){return switch(kind){case "TRANSFER_HANDOFF"->"contract.execution_verification";case "TRANSFER_RECOVERY"->"transfer.workflow";case "PAYMENT_HANDOFF"->"contract.signature_archive";case "PAYMENT_RECOVERY"->"contract.payment_request";case "EXECUTION_HANDOFF"->"contract.signature_handoff";case "TERMINATION_REVIEW"->"contract.negotiation_disposition";case "AUTHORITY_RETURN"->"contract.preparation_workflow";case "SIGNATURE_READINESS"->"contract.signature_readiness";case "SIGNATURE_AUTHORITY_RETURN"->"contract.signature_workflow";default->"opportunity.contract_preparation_source";};}
 private static Subject selector(Object raw,String type,boolean zero){var p=(Map<?,?>)raw;if(!p.keySet().equals(Set.of("id","revision")))throw new IllegalArgumentException();long r=revision(p.get("revision"));if(zero&&r!=0)throw new IllegalArgumentException();return new Subject(type,uuid(p.get("id")),r,null);}
 private static UUID uuid(Object raw){var s=(String)raw;var id=UUID.fromString(s);if(!id.toString().equals(s))throw new IllegalArgumentException();return id;}
 private static long revision(Object raw){if(!(raw instanceof Integer||raw instanceof Long))throw new IllegalArgumentException();long n=((Number)raw).longValue();if(n<0||n>9007199254740991L)throw new IllegalArgumentException();return n;}
 public Context resolve(Connection c,CommandEnvelope e)throws SQLException{var b=input(e);var org=R2OpportunityOwnerExceptionAssembly.organization(c,e.actor().tenantId(),b.opportunity());require(org!=null,"NOT_FOUND");var request=R1AuthorityReader.databaseBacked().select(c,e.actor(),b.opportunity(),org,"SYSTEM_RECOVERY","CONTRACT_TASK_RECOVER");require(request!=null,"NOT_AUTHORIZED");return new Context(CommandScope.contractRecovery(e.actor().tenantId(),b),request,b);}
 public void lockRoots(Connection c,CommandEnvelope e,Context ctx)throws SQLException{opportunities.lock(c,e.actor().tenantId(),input(e).opportunity().id());}
 public void recoveryEligibility(Connection c,CommandEnvelope e,Context ctx)throws SQLException{validateBeforeWork(c,e,ctx);var binding=input(e);if(binding.sourceKind().startsWith("TRANSFER_")){require(transfers!=null,"NOT_AUTHORIZED");try{transfers.validateEligibility(c,e.actor(),binding);}catch(io.github.windyzhu3.ontologylaw.transfer.TransferWorkflowService.Blocked blocked){throw new Rejected(blocked.code());}catch(io.github.windyzhu3.ontologylaw.transfer.TransferSubmissionService.Blocked blocked){throw new Rejected(blocked.code());}}}
 public void validateBeforeWork(Connection c,CommandEnvelope e,Context ctx)throws SQLException{var b=input(e);var h=opportunities.header(c,e.actor().tenantId(),b.opportunity().id());require(h!=null&&(!h.closed()||b.sourceKind().startsWith("PAYMENT_"))&&h.selector().equals(b.opportunity()),"STALE_SUBJECT");}
 @SuppressWarnings("unchecked")public Result execute(Connection c,CommandEnvelope e,Context ctx)throws SQLException{try{var binding=input(e);if(binding.sourceKind().startsWith("TRANSFER_")){require(transfers!=null,"NOT_AUTHORIZED");return Result.succeeded(transfers.reconcile(c,e.actor(),binding),Event.TransferWorkflowReconciledV1);}var result=service.reconcile(c,e.actor(),(Map<String,Object>)e.payload());return Result.succeeded(result,result.type().equals("contract.payment_workflow")?Event.ContractPaymentReconciledV1:result.type().equals("contract.execution_workflow")?Event.ContractExecutionReconciledV1:result.type().equals("contract.termination_review_assignment")?Event.ContractTerminationReviewReconciledV1:result.type().equals("contract.signature_workflow")?Event.ContractSignatureReconciledV1:Event.ContractPreparationReconciledV1);}catch(io.github.windyzhu3.ontologylaw.transfer.TransferWorkflowService.Blocked blocked){throw new Rejected(blocked.code());}catch(ContractWorkflowService.Blocked blocked){throw new Rejected(blocked.code());}catch(ContractPreparationSources.Unavailable invalid){throw new Rejected("STALE_SUBJECT");}}
 public void validateBeforeCommit(Connection c,CommandEnvelope e,Context ctx,Result result)throws SQLException{var b=input(e);var fs=b.sourceKind().startsWith("TRANSFER_")?R2TransferRecoveryService.facts(c,e.actor().tenantId(),b.opportunity().id()):service.protectedFacts(c,e.actor().tenantId(),b.opportunity().id());require(fs.contains(result.fact()),"STALE_SUBJECT");R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),fs,"CONTRACT_TASK_RECOVER");}
 private static void require(boolean condition,String code){if(!condition)throw new Rejected(code);}
}
