package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;import io.github.windyzhu3.ontologylaw.opportunity.CustomerRequirementDocument;
import java.util.*;
public record R2CustomerRequirementsInput(Subject opportunity,Subject responsibility,Subject draft,Subject confirmation,Map<String,Object> document) {
 @SuppressWarnings("unchecked") public static R2CustomerRequirementsInput parse(CommandEnvelope e){try{require(e.type().customerRequirements()&&e.taskPrecondition()==null&&e.draftPrecondition()==null&&e.identityPrecondition()==null&&e.actor().onBehalfAppointmentId()==null);var p=(Map<?,?>)e.payload();var keys=new HashSet<>(Set.of("opportunityId","expectedOpportunityRevision","responsibilityBasis","expectedDraft","expectedConfirmation"));if(e.type()==CommandEnvelope.Type.SAVE_OPPORTUNITY_CUSTOMER_DRAFT)keys.add("document");require(p.keySet().equals(keys));var o=new Subject("opportunity.opportunity",uuid(p.get("opportunityId")),revision(p.get("expectedOpportunityRevision")),null);var b=(Map<?,?>)p.get("responsibilityBasis");require(b.keySet().equals(Set.of("id","revision")));var basis=new Subject(uuid(b.get("id")).equals(o.id())?"opportunity.opportunity":"opportunity.responsibility_handoff",uuid(b.get("id")),revision(b.get("revision")),null);require(Set.of("opportunity.opportunity","opportunity.responsibility_handoff").contains(basis.type()));var d=selector(p.get("expectedDraft"),"opportunity.customer_requirement_draft");var v=selector(p.get("expectedConfirmation"),"opportunity.customer_requirement_confirmation");Map<String,Object> doc=null;if(keys.contains("document")){doc=CustomerRequirementDocument.validate((Map<String,Object>)p.get("document"),false);}else require(d!=null);return new R2CustomerRequirementsInput(o,basis,d,v,doc);}catch(IllegalArgumentException|ClassCastException|NullPointerException invalid){throw new CommandHandler.Rejected("VALIDATION_FAILED");}}
 private static Subject selector(Object v,String type){if(v==null)return null;var p=(Map<?,?>)v;require(p.keySet().equals(Set.of("id","revision")));long r=revision(p.get("revision"));require(r==0);return new Subject(type,uuid(p.get("id")),r,null);}
 private static UUID uuid(Object v){var s=(String)v;var id=UUID.fromString(s);require(id.toString().equals(s));return id;}
 private static long revision(Object v){require(v instanceof Integer||v instanceof Long);long r=((Number)v).longValue();require(r>=0&&r<=9007199254740991L);return r;}
 private static void require(boolean v){if(!v)throw new IllegalArgumentException();}
 @Override public String toString(){return "R2CustomerRequirementsInput[protected]";}
}
