package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.api.adapter.generated.api.OpportunityCustomerApi;import io.github.windyzhu3.ontologylaw.api.adapter.generated.model.*;import io.github.windyzhu3.ontologylaw.execution.CommandEnvelope;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.http.ResponseEntity;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.web.bind.annotation.RestController;
@RestController
public class R2CustomerRequirementsApiDelegate implements OpportunityCustomerApi {
 private final ObjectProvider<R1ApiServices> services;public R2CustomerRequirementsApiDelegate(ObjectProvider<R1ApiServices> services){this.services=services;}
 private R1ApiServices service(){var s=services.getIfAvailable();if(s==null)throw new R1HttpFailure("SERVICE_UNAVAILABLE");return s;}
 private Actor actor(UUID behalf){var a=SecurityContextHolder.getContext().getAuthentication();if(a==null||behalf!=null||!(a.getPrincipal() instanceof Actor actor)||actor.principalKind()!=PrincipalKind.HUMAN||actor.onBehalfAppointmentId()!=null)throw new R1HttpFailure("NOT_AUTHORIZED");return actor;}
 public ResponseEntity<OpportunityCustomerContextV1> getOpportunityCustomerRequirements(UUID id,UUID own,UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").body(R1WireModels.model(service().customerRequirements(actor(behalf),id,null,false),OpportunityCustomerContextV1.class));}
 public ResponseEntity<OpportunityCustomerPartyPageV1> searchOpportunityParties(UUID id,UUID own,UUID behalf,String q){return ResponseEntity.ok().header("Cache-Control","no-store").body(R1WireModels.model(service().customerRequirements(actor(behalf),id,q,true),OpportunityCustomerPartyPageV1.class));}
 public ResponseEntity<OpportunityCustomerCommandReceiptV1> saveOpportunityCustomerDraft(UUID id,UUID key,SaveOpportunityCustomerDraftV1 body,UUID own,UUID behalf){return command(id,key,body,actor(behalf),CommandEnvelope.Type.SAVE_OPPORTUNITY_CUSTOMER_DRAFT);}
 public ResponseEntity<OpportunityCustomerCommandReceiptV1> confirmOpportunityCustomerRequirements(UUID id,UUID key,ConfirmOpportunityCustomerRequirementsV1 body,UUID own,UUID behalf){return command(id,key,body,actor(behalf),CommandEnvelope.Type.CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS);}
 @SuppressWarnings("unchecked") private ResponseEntity<OpportunityCustomerCommandReceiptV1> command(UUID id,UUID key,Object body,Actor actor,CommandEnvelope.Type type){var p=new TreeMap<String,Object>((Map<String,Object>)R1WireModels.payload(body));p.put("opportunityId",id.toString());p.putIfAbsent("expectedDraft",null);p.putIfAbsent("expectedConfirmation",null);var response=service().opportunityCommand(new CommandEnvelope(type,key,UUID.randomUUID(),actor,p));if(response.errorCode()!=null)throw new R1HttpFailure(response.errorCode(),response.receiptRef(),null,null);return ResponseEntity.status(response.status()).header("Cache-Control","no-store").header("Location","/api/v1/commands/"+key+"/receipt").body(R1WireModels.model(response.body(),OpportunityCustomerCommandReceiptV1.class));}
}
