package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.party.*;
import java.sql.*;import java.util.*;
final class R2CustomerRequirementsCommand implements CommandHandler {
 private final CommandEnvelope.Type type;private final OpportunityProgressProtection protection;private final OpportunityCustomerRequirementsService service;private final CustomerPartyProfiles parties=CustomerPartyProfiles.databaseBacked();
 R2CustomerRequirementsCommand(CommandEnvelope.Type type,OpportunityProgressProtection protection){this.type=type;this.protection=protection;service=R2CustomerRequirementsServices.create(protection);}
 public CommandEnvelope.Type type(){return type;}
 public Context resolve(Connection c,CommandEnvelope e)throws SQLException{var in=R2CustomerRequirementsInput.parse(e);var org=R2OpportunityOwnerExceptionAssembly.organization(c,e.actor().tenantId(),in.opportunity());require(org!=null,"NOT_FOUND");var request=R1AuthorityReader.databaseBacked().select(c,e.actor(),in.opportunity(),org,"OPPORTUNITY_OWNER","CUSTOMER_REQUIREMENTS_MANAGE");require(request!=null,"NOT_AUTHORIZED");return new Context(CommandScope.customerRequirements(e,in.opportunity(),in.responsibility(),in.draft(),in.confirmation()),request,new CommandAuthorizationBinding.CustomerRequirements(in.opportunity(),in.responsibility(),in.draft(),in.confirmation()));}
 public void recoveryEligibility(Connection c,CommandEnvelope e,Context ctx){}
 public void lockRoots(Connection c,CommandEnvelope e,Context ctx)throws SQLException{OpportunityCommandReader.databaseBacked(protection).lock(c,e.actor().tenantId(),R2CustomerRequirementsInput.parse(e).opportunity().id());}
 public void validateBeforeWork(Connection c,CommandEnvelope e,Context ctx)throws SQLException{var in=R2CustomerRequirementsInput.parse(e);var tenant=e.actor().tenantId();var h=OpportunityCommandReader.databaseBacked(protection).header(c,tenant,in.opportunity().id());require(h!=null&&h.selector().equals(in.opportunity()),"STALE_SUBJECT");require(!h.closed(),"OPPORTUNITY_CLOSED");var owner=OpportunityResponsibilityReader.databaseBacked().current(c,tenant,in.opportunity());require(owner.basis().equals(in.responsibility())&&owner.appointmentId().equals(e.actor().appointmentId()),"STALE_SUBJECT");R2OpportunityClosureCommand.validateSource(c,tenant,in.opportunity());var latest=service.latestDraft(c,tenant,in.opportunity().id(),in.responsibility(),e.actor().appointmentId());require(Objects.equals(in.draft(),latest==null?null:latest.selector()),"STALE_DRAFT");var history=service.history(c,tenant,in.opportunity().id());require(Objects.equals(in.confirmation(),history.isEmpty()?null:history.getFirst().selector()),"STALE_SUBJECT");if(type==CommandEnvelope.Type.CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS)require(history.stream().noneMatch(m->Objects.equals(m.draft(),in.draft())),"STALE_DRAFT");}
 @SuppressWarnings("unchecked") public Result execute(Connection c,CommandEnvelope e,Context ctx)throws SQLException{try{var in=R2CustomerRequirementsInput.parse(e);var tenant=e.actor().tenantId();var opening=EventOpportunityReader.databaseBacked().byId(c,tenant,in.opportunity().id());var lead=io.github.windyzhu3.ontologylaw.lead.OpportunityLedgerLeadReader.metadataOnly(c,tenant,opening.leadId()).selector();Map<String,Object> doc=in.document();if(type==CommandEnvelope.Type.CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS){R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),List.of(in.draft()),"CUSTOMER_REQUIREMENTS_MANAGE");var saved=service.read(c,tenant,in.draft());require(saved!=null&&saved.sourceLead().equals(lead),"STALE_SUBJECT");doc=saved.document();CustomerRequirementDocument.validate(doc,true);}
 var inputs=(List<Map<String,Object>>)doc.getOrDefault("participants",List.of());var selected=new TreeMap<UUID,Subject>();for(var p:inputs){var s=R2CustomerRequirementsServices.selected(p);if(s!=null){var prior=selected.putIfAbsent(s.id(),s);require(prior==null||prior.equals(s),"VALIDATION_FAILED");}}
 var profiles=new HashMap<UUID,CustomerPartyProfiles.Profile>();var visible=R2CustomerRequirementsReadService.visiblePartyIds(c,e.actor(),in.opportunity());for(var s:selected.values()){require(visible.contains(s.id()),"NOT_AUTHORIZED");R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),List.of(s),"CUSTOMER_REQUIREMENTS_MANAGE");var p=parties.current(c,tenant,s.id(),true);require(p!=null&&R2CustomerRequirementsServices.partySubject(p).equals(s),"STALE_SUBJECT");profiles.put(s.id(),p);}
 var input=new OpportunityCustomerRequirementsService.Input(in.opportunity(),in.responsibility(),e.actor().appointmentId(),in.draft(),in.confirmation(),doc);
 if(type==CommandEnvelope.Type.SAVE_OPPORTUNITY_CUSTOMER_DRAFT){var m=service.save(c,tenant,input,lead,profiles.values().stream().map(R2CustomerRequirementsServices::snapshot).toList());return Result.succeeded(m.selector(),Event.OpportunityCustomerDraftSavedV1);}
 var canonical=new LinkedHashMap<String,Object>(doc);var canonicalRows=new ArrayList<Map<String,Object>>();var rows=new ArrayList<OpportunityCustomerRequirementsService.Participant>();var changes=new TreeMap<UUID,String>();
 for(var p:inputs)if(p.get("profileChange")!=null){var selectedParty=R2CustomerRequirementsServices.selected(p);var change=(Map<String,Object>)p.get("profileChange");String name=(String)change.get("name");var old=changes.putIfAbsent(selectedParty.id(),name);require(old==null||old.equals(name),"VALIDATION_FAILED");}
 for(var change:changes.entrySet()){var profile=profiles.get(change.getKey());R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),List.of(R2CustomerRequirementsServices.partySubject(profile)),"PARTY_PROFILE_MANAGE");parties.snapshot(c,tenant,profile,e.actor().appointmentId());profile=parties.rename(c,tenant,profile.selector(),change.getValue());profiles.put(change.getKey(),profile);R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),List.of(R2CustomerRequirementsServices.partySubject(profile)),"PARTY_PROFILE_MANAGE");}
 for(var p:inputs){var selectedParty=R2CustomerRequirementsServices.selected(p);CustomerPartyProfiles.Profile profile;if(selectedParty==null){var fresh=(Map<String,Object>)p.get("newParty");profile=parties.create(c,tenant,(String)fresh.get("kind"),(String)fresh.get("name"));R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),List.of(R2CustomerRequirementsServices.partySubject(profile)),"CUSTOMER_REQUIREMENTS_MANAGE");}else profile=profiles.get(selectedParty.id());
 var snapshot=parties.snapshot(c,tenant,profile,e.actor().appointmentId());var canonicalRow=new LinkedHashMap<String,Object>();canonicalRow.put("party",R2CustomerRequirementsServices.selector(R2CustomerRequirementsServices.partySubject(profile)));canonicalRow.put("role",p.get("role"));canonicalRow.put("newParty",null);canonicalRow.put("profileChange",null);canonicalRows.add(canonicalRow);rows.add(new OpportunityCustomerRequirementsService.Participant(new Subject("party.profile_version",snapshot.selector().id(),snapshot.selector().revision(),null),R2CustomerRequirementsServices.snapshot(snapshot.party()),(String)p.get("role")));}
 canonical.put("participants",canonicalRows);var m=service.confirm(c,tenant,input,canonical,rows,lead);return Result.succeeded(m.selector(),Event.OpportunityCustomerRequirementsConfirmedV1);
 }catch(OpportunityCustomerRequirementsService.Blocked b){throw new Rejected(b.code());}catch(IllegalArgumentException b){throw new Rejected("VALIDATION_FAILED");}}
 public void validateBeforeCommit(Connection c,CommandEnvelope e,Context ctx,Result result)throws SQLException{var in=R2CustomerRequirementsInput.parse(e);var m=OpportunityCustomerRequirementsService.metadata(c,e.actor().tenantId(),result.fact());require(m!=null&&m.opportunity().equals(in.opportunity())&&m.responsibility().equals(in.responsibility())&&m.owner().equals(e.actor().appointmentId()),"STALE_SUBJECT");var owner=OpportunityResponsibilityReader.databaseBacked().current(c,e.actor().tenantId(),in.opportunity());require(owner.basis().equals(in.responsibility())&&owner.appointmentId().equals(e.actor().appointmentId()),"STALE_SUBJECT");R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),R2CustomerRequirementsServices.sourceFacts(c,e.actor().tenantId(),in.opportunity(),result.fact()),"CUSTOMER_REQUIREMENTS_MANAGE");}
 private static void require(boolean value,String code){if(!value)throw new Rejected(code);}
}
