package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.opportunity.*;
import java.sql.*;import java.util.*;
final class R2MaterialsCommand implements CommandHandler {
 private final CommandEnvelope.Type type;private final OpportunityProgressProtection cipher;
 R2MaterialsCommand(CommandEnvelope.Type type,OpportunityProgressProtection cipher){this.type=type;this.cipher=cipher;}
 public CommandEnvelope.Type type(){return type;}
 public Context resolve(Connection c,CommandEnvelope e)throws SQLException{var in=R2MaterialsInput.parse(e);var org=R2OpportunityOwnerExceptionAssembly.organization(c,e.actor().tenantId(),in.opportunity());R2MaterialsServices.require(org!=null,"NOT_FOUND");var request=R1AuthorityReader.databaseBacked().select(c,e.actor(),in.opportunity(),org,"OPPORTUNITY_OWNER","MATERIALS_MANAGE");R2MaterialsServices.require(request!=null,"NOT_AUTHORIZED");return new Context(CommandScope.materials(e,in.opportunity(),in.basis(),in.confirmation(),in.previous(),in.upload()),request,new CommandAuthorizationBinding.Materials(in.opportunity(),in.basis(),in.confirmation(),in.previous(),in.upload()));}
 public void recoveryEligibility(Connection c,CommandEnvelope e,Context ctx){}
 public void lockRoots(Connection c,CommandEnvelope e,Context ctx)throws SQLException{OpportunityCommandReader.databaseBacked(cipher).lock(c,e.actor().tenantId(),R2MaterialsInput.parse(e).opportunity().id());}
 public void validateBeforeWork(Connection c,CommandEnvelope e,Context ctx)throws SQLException{var in=R2MaterialsInput.parse(e);R2MaterialsServices.validate(c,e.actor(),in,cipher);if(in.upload()==null){var now=R1ServiceReadRuntime.databaseTime(c);for(var pending:R2MaterialsServices.evidence(cipher).pending(c,e.actor().tenantId(),in.opportunity().id(),e.actor().appointmentId()))R2MaterialsServices.require(!pending.responsibility().equals(in.basis())||!pending.expiresAt().isAfter(now)||!("CHECKING".equals(pending.checkState())||"UNKNOWN".equals(pending.checkState())),"VALIDATION_FAILED");}if(in.upload()!=null){var b=R2MaterialsServices.evidence(cipher).basis(c,e.actor().tenantId(),in.upload().id());R2MaterialsServices.require(b!=null&&b.opportunity().equals(in.opportunity())&&b.responsibility().equals(in.basis())&&b.owner().equals(e.actor().appointmentId())&&Objects.equals(b.confirmation(),in.confirmation())&&Objects.equals(b.previous(),in.previous()),"STALE_SUBJECT");R2MaterialsServices.require(b.expiresAt().isAfter(R1ServiceReadRuntime.databaseTime(c)),"STALE_SUBJECT");R2MaterialsServices.require("PASSED".equals(b.checkState())&&"OBJECT_RECEIVED".equals(b.state()),"VALIDATION_FAILED");}}
 public Result execute(Connection c,CommandEnvelope e,Context ctx)throws SQLException{var in=R2MaterialsInput.parse(e);var repo=R2MaterialsServices.evidence(cipher);var tenant=e.actor().tenantId();if(type==CommandEnvelope.Type.OPEN_OPPORTUNITY_MATERIAL_UPLOAD){var b=repo.open(c,tenant,in.opportunity(),in.basis(),e.actor().appointmentId(),in.confirmation(),in.previous(),in.purpose(),in.fileName(),in.note());return Result.succeeded(b.selector(),Event.OpportunityMaterialUploadOpenedV1);}var b=repo.basis(c,tenant,in.upload().id());var s=repo.accept(c,tenant,b);var protectedBody=repo.protectedBody(c,tenant,b.selector().id());var v=OpportunityMaterials.databaseBacked().accept(c,tenant,in.opportunity().id(),in.previous()==null?null:in.previous().id(),b.selector().id(),s.source(),s.submission(),s.binding(),b.purpose(),e.actor().appointmentId(),s.at(),protectedBody.ciphertext(),protectedBody.digest());return Result.succeeded(v.selector(),Event.OpportunityMaterialAcceptedV1);}
 public void validateBeforeCommit(Connection c,CommandEnvelope e,Context ctx,Result result)throws SQLException{var in=R2MaterialsInput.parse(e);var fact=R2MaterialsServices.fact(c,e.actor().tenantId(),result.fact());R2MaterialsServices.require(fact!=null&&fact.opportunity().equals(in.opportunity())&&fact.basis().equals(in.basis())&&fact.owner().equals(e.actor().appointmentId()),"STALE_SUBJECT");var owner=OpportunityResponsibilityReader.databaseBacked().current(c,e.actor().tenantId(),in.opportunity());R2MaterialsServices.require(owner.basis().equals(in.basis())&&owner.appointmentId().equals(e.actor().appointmentId()),"STALE_SUBJECT");var facts=R2MaterialsServices.facts(c,e.actor().tenantId(),in.opportunity(),result.fact());R2CustomerRequirementsServices.requireAuthority(c,e.actor(),ctx.authorization().scopeOrganizationId(),facts,"MATERIALS_MANAGE");}
}

