package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.evidence.*;import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.opportunity.*;
import java.sql.*;import java.util.*;
public final class R2MaterialsServices {
 private R2MaterialsServices(){}
 public static MaterialEvidence evidence(OpportunityProgressProtection cipher){return MaterialEvidence.databaseBacked(new MaterialProtection(){public byte[] encrypt(UUID t,UUID o,UUID f,String b){return cipher.encryptMaterial(t,o,f,b);}public String decrypt(UUID t,UUID o,UUID f,byte[] b){return cipher.decryptMaterial(t,o,f,b);}},new MaterialEvidence.Codec(){public String encode(Map<String,Object>b){return CanonicalJson.encode(b);}@SuppressWarnings("unchecked")public Map<String,Object> decode(String b){return tools.jackson.databind.json.JsonMapper.builder().build().readValue(b,Map.class);}});}
 public static MaterialEvidence metadata(){return evidence(null);}
 public static R1AuthorizationFacts.MaterialFact fact(Connection c,UUID tenant,Subject exact)throws SQLException{if(exact==null||!Long.valueOf(0).equals(exact.revision()))return null;MaterialEvidence.Basis b;if(MaterialEvidence.BASIS.equals(exact.type()))b=R2LedgerSourceFacts.materialBasis(c,tenant,exact.id());else if(OpportunityMaterials.VERSION.equals(exact.type())){var v=OpportunityMaterials.databaseBacked().version(c,tenant,exact.id());if(v==null)return null;b=R2LedgerSourceFacts.materialBasis(c,tenant,v.upload());}else return null;return b==null?null:new R1AuthorizationFacts.MaterialFact(exact,b.opportunity(),b.responsibility(),b.owner(),b.confirmation(),b.previous(),b.selector(),b.createdAt());}
 public static List<Subject> facts(Connection c,UUID tenant,Subject opportunity,Subject exact)throws SQLException{var base=R2CustomerRequirementsServices.sourceFacts(c,tenant,opportunity,null);if(base==null)return null;var out=new LinkedHashSet<Subject>(base);if(exact!=null){var f=fact(c,tenant,exact);if(f==null||!f.opportunity().id().equals(opportunity.id()))return null;out.add(f.selector());out.add(f.opportunity());out.add(f.basis());out.add(f.upload());if(f.confirmation()!=null){var cf=R2CustomerRequirementsServices.sourceFacts(c,tenant,opportunity,f.confirmation());if(cf==null)return null;out.addAll(cf);}if(f.previous()!=null)out.add(f.previous());if(OpportunityMaterials.VERSION.equals(exact.type())){var v=OpportunityMaterials.databaseBacked().version(c,tenant,exact.id());var chain=R2LedgerSourceFacts.evidenceReference(c,tenant,v.submission());if(chain==null||!chain.active()||!chain.binding().id().equals(v.binding())||!chain.target().equals(f.opportunity()))return null;out.add(chain.submission());out.add(chain.binding());}}return List.copyOf(out);}
 public static void validate(Connection c,Actor actor,R2MaterialsInput in,OpportunityProgressProtection cipher)throws SQLException{var h=OpportunityCommandReader.databaseBacked(cipher).header(c,actor.tenantId(),in.opportunity().id());require(h!=null&&h.selector().equals(in.opportunity()),"STALE_SUBJECT");require(!h.closed(),"OPPORTUNITY_CLOSED");var owner=OpportunityResponsibilityReader.databaseBacked().current(c,actor.tenantId(),in.opportunity());require(owner.basis().equals(in.basis())&&owner.appointmentId().equals(actor.appointmentId()),"STALE_SUBJECT");R2OpportunityClosureCommand.validateSource(c,actor.tenantId(),in.opportunity());var history=R2CustomerRequirementsServices.create(cipher).history(c,actor.tenantId(),in.opportunity().id());require(Objects.equals(in.confirmation(),history.isEmpty()?null:history.getFirst().selector()),"STALE_SUBJECT");if(in.previous()!=null){var v=OpportunityMaterials.databaseBacked().version(c,actor.tenantId(),in.previous().id());require(v!=null&&v.opportunity().equals(in.opportunity().id())&&OpportunityMaterials.databaseBacked().current(c,actor.tenantId(),v.selector().id())&&(in.purpose()==null||in.purpose().equals(v.purpose())),"STALE_SUBJECT");}}
 static void require(boolean b,String code){if(!b)throw new CommandHandler.Rejected(code);}
}
