package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.audit.AuditAppender;import io.github.windyzhu3.ontologylaw.evidence.*;import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.lead.LeadProtection;import io.github.windyzhu3.ontologylaw.opportunity.*;
import java.sql.*;import java.time.*;import java.util.*;import java.io.*;
public final class R2MaterialsReadService {
 public record Content(byte[] bytes,String fileName,String mediaType,boolean previewAllowed){@Override public String toString(){return "MaterialContent[protected]";}}
 private final R2OpportunityLedgerReadService ledger;private final OpportunityProgressProtection cipher;private final AuditAppender audit;private final MaterialObjectStore objects;private final MaterialEvidence evidence;private final OpportunityMaterials versions=OpportunityMaterials.databaseBacked();private final OpportunityLedgerAuthorityReader authority=OpportunityLedgerAuthorityReader.databaseBacked();
 public R2MaterialsReadService(byte[] key,LeadProtection leads,OpportunityProgressProtection cipher,AuditAppender audit,MaterialObjectStore objects){ledger=new R2OpportunityLedgerReadService(key,leads,cipher,audit);this.cipher=cipher;this.audit=audit;this.objects=objects;evidence=R2MaterialsServices.evidence(cipher);}
 private R2OpportunityLedgerReadService.Context context(Connection c,Actor actor,UUID id)throws SQLException{var x=ledger.context(c,actor,id);if(x==null)throw fail("NOT_AUTHORIZED");return x;}
 private String code(Connection c,Actor actor,R2OpportunityLedgerReadService.Context x,List<Subject> facts,boolean manage)throws SQLException{if(actor.appointmentId().equals(x.owner().appointmentId())&&authority.permitted(c,actor,x.organization(),facts,"MATERIALS_MANAGE"))return "MATERIALS_MANAGE";if(!manage&&authority.permitted(c,actor,x.organization(),facts,"MATERIALS_READ"))return "MATERIALS_READ";throw fail("NOT_AUTHORIZED");}
 private void disclose(Connection c,Actor actor,R2OpportunityLedgerReadService.Context x,List<Subject> facts,String code,String mode,List<AuditAppender.MaterialDisclosureEntry> out)throws SQLException{if(facts==null)throw fail("NOT_AUTHORIZED");for(var f:facts){var a=authority.evidence(c,actor,x.organization(),f,code);if(a==null||!a.allowed())throw fail("NOT_AUTHORIZED");out.add(new AuditAppender.MaterialDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),f,a,mode));}}
 public Map<String,Object> read(Connection connection,Actor actor,UUID opportunity)throws SQLException{return MaterialReadRuntime.read(connection,actor,audit,(c,now)->{var x=context(c,actor,opportunity);var ds=new ArrayList<AuditAppender.MaterialDisclosureEntry>();var facts=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),null);String code=code(c,actor,x,facts,false);disclose(c,actor,x,facts,code,"BODY",ds);var out=new LinkedHashMap<String,Object>();out.put("opportunity",selector(x.header().selector()));out.put("responsibilityBasis",selector(x.owner().basis()));out.put("closed",x.header().closed());out.put("editable",!x.header().closed()&&actor.appointmentId().equals(x.owner().appointmentId())&&authority.permitted(c,actor,x.organization(),facts,"MATERIALS_MANAGE"));var confirmations=R2CustomerRequirementsServices.create(cipher).history(c,actor.tenantId(),opportunity);if(!confirmations.isEmpty()){var confirmation=confirmations.getFirst().selector();var cf=R2CustomerRequirementsServices.sourceFacts(c,actor.tenantId(),x.header().selector(),confirmation);if(cf!=null&&authority.permitted(c,actor,x.organization(),cf,code)){disclose(c,actor,x,cf,code,"BODY",ds);out.put("confirmation",selector(confirmation));}else out.put("editable",false);}
 var all=new ArrayList<Map<String,Object>>();for(var v:versions.history(c,actor.tenantId(),opportunity)){var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),v.selector());if(fs!=null&&authority.permitted(c,actor,x.organization(),fs,code)){disclose(c,actor,x,fs,code,"BODY",ds);all.add(version(c,actor,x,v,code,ds));}}out.put("versions",all);
 var pending=new ArrayList<Map<String,Object>>();if(actor.appointmentId().equals(x.owner().appointmentId()))for(var b:evidence.pending(c,actor.tenantId(),opportunity,actor.appointmentId()))if(b.responsibility().equals(x.owner().basis())){var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),b.selector());if(fs!=null&&authority.permitted(c,actor,x.organization(),fs,code)){disclose(c,actor,x,fs,code,"UPLOAD_STATUS",ds);pending.add(upload(c,actor,b,now));}}out.put("pendingUploads",pending);if(!x.equals(ledger.context(c,actor,opportunity)))throw fail("STALE_SUBJECT");return new MaterialReadRuntime.Prepared<>(out,ds);});}
 public Map<String,Object> status(Connection connection,Actor actor,UUID opportunity,UUID upload)throws SQLException{return MaterialReadRuntime.read(connection,actor,audit,(c,now)->{var x=context(c,actor,opportunity);var b=evidence.basis(c,actor.tenantId(),upload);checkBasis(actor,x,b);var ds=new ArrayList<AuditAppender.MaterialDisclosureEntry>();var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),b.selector());var code=code(c,actor,x,fs,true);disclose(c,actor,x,fs,code,"UPLOAD_STATUS",ds);return new MaterialReadRuntime.Prepared<>(upload(c,actor,b,now),ds);});}
 private void checkBasis(Actor a,R2OpportunityLedgerReadService.Context x,MaterialEvidence.Basis b){if(b==null||!b.opportunity().id().equals(x.header().selector().id())||!b.owner().equals(a.appointmentId())||!b.responsibility().equals(x.owner().basis())||!a.appointmentId().equals(x.owner().appointmentId()))throw fail("NOT_AUTHORIZED");}
 public Map<String,Object> upload(Connection connection,Actor actor,UUID opportunity,UUID session,InputStream bytes)throws SQLException {
  record Started(MaterialEvidence.Basis basis,UUID check){}
  var started=MaterialReadRuntime.transport(connection,actor,audit,(c,now)->{OpportunityCommandReader.databaseBacked(cipher).lock(c,actor.tenantId(),opportunity);var x=context(c,actor,opportunity);var b=evidence.basis(c,actor.tenantId(),session);checkBasis(actor,x,b);if(x.header().closed()||!x.header().selector().equals(b.opportunity())||!b.expiresAt().isAfter(now))throw fail("STALE_SUBJECT");if(!"OPEN".equals(b.state())||b.checkState()!=null)throw fail("VALIDATION_FAILED");for(var other:evidence.pending(c,actor.tenantId(),opportunity,actor.appointmentId()))if(other.responsibility().equals(b.responsibility())&&other.expiresAt().isAfter(now)&&("CHECKING".equals(other.checkState())||"UNKNOWN".equals(other.checkState())))throw fail("VALIDATION_FAILED");var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),b.selector());var code=code(c,actor,x,fs,true);var ds=new ArrayList<AuditAppender.MaterialDisclosureEntry>();disclose(c,actor,x,fs,code,"UPLOAD_STATUS",ds);return new MaterialReadRuntime.Prepared<>(new Started(b,evidence.beginCheck(c,actor.tenantId(),b)),ds);});
  MaterialObjectStore.StoredObject stored=null;String state="PASSED",reason=null;try{if(objects==null)throw new MaterialRejectedException(MaterialRejectedException.Reason.SCAN_UNAVAILABLE);stored=objects.store(bytes);}catch(MaterialRejectedException rejected){reason=rejected.reason().name();state=reason.equals("SCAN_UNAVAILABLE")?"SCAN_UNAVAILABLE":"REJECTED";}catch(IOException unknown){state="UNKNOWN";reason="TRANSFER_UNKNOWN";}
  final var fixed=stored;final var outcome=state;final var why=reason;
  return MaterialReadRuntime.transport(connection,actor,audit,(c,now)->{OpportunityCommandReader.databaseBacked(cipher).lock(c,actor.tenantId(),opportunity);var x=context(c,actor,opportunity);var b=evidence.basis(c,actor.tenantId(),session);checkBasis(actor,x,b);if(x.header().closed()||!x.header().selector().equals(b.opportunity())||!b.expiresAt().isAfter(now))throw fail("STALE_SUBJECT");var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),b.selector());var code=code(c,actor,x,fs,true);var ds=new ArrayList<AuditAppender.MaterialDisclosureEntry>();disclose(c,actor,x,fs,code,"UPLOAD_STATUS",ds);evidence.completeCheck(c,actor.tenantId(),b,started.check(),fixed,outcome,why);return new MaterialReadRuntime.Prepared<>(upload(c,actor,evidence.basis(c,actor.tenantId(),session),now),ds);});
 }
 public Content content(Connection connection,Actor actor,UUID opportunity,UUID id,String disposition)throws SQLException{if(!Set.of("inline","attachment").contains(disposition))throw fail("VALIDATION_FAILED");return MaterialReadRuntime.read(connection,actor,audit,(c,now)->{var x=context(c,actor,opportunity);var v=versions.version(c,actor.tenantId(),id);if(v==null||!v.opportunity().equals(opportunity))throw fail("NOT_AUTHORIZED");var fs=R2MaterialsServices.facts(c,actor.tenantId(),x.header().selector(),v.selector());var code=code(c,actor,x,fs,false);var ds=new ArrayList<AuditAppender.MaterialDisclosureEntry>();disclose(c,actor,x,fs,code,"DOWNLOAD",ds);var b=evidence.basis(c,actor.tenantId(),v.upload());var body=evidence.body(c,actor.tenantId(),b);if(objects==null)throw fail("SERVICE_UNAVAILABLE");byte[] data;try{data=objects.read(b.objectVersion(),b.sha256());}catch(IOException e){throw new SQLException("Private material unavailable","58000");}if(!x.equals(ledger.context(c,actor,opportunity)))throw fail("STALE_SUBJECT");return new MaterialReadRuntime.Prepared<>(new Content(data,(String)body.get("fileName"),b.mediaType(),false),ds);});}
 private Map<String,Object> version(Connection c,Actor actor,R2OpportunityLedgerReadService.Context x,OpportunityMaterials.Version v,String code,List<AuditAppender.MaterialDisclosureEntry> ds)throws SQLException{var b=evidence.basis(c,actor.tenantId(),v.upload());var out=new LinkedHashMap<String,Object>(evidence.body(c,actor.tenantId(),b));out.put("selector",selector(v.selector()));out.put("factRef",PublicFactReferences.reference(actor,v.selector().type(),v.selector().id()));out.put("itemId",v.item().toString());out.put("previousVersionId",v.previous()==null?null:v.previous().id().toString());out.put("purpose",v.purpose());out.put("sizeBytes",b.sizeBytes());out.put("mediaType",b.mediaType());out.put("receivedAt",v.receivedAt().toString());out.put("receivedByAppointmentId",v.receivedBy().toString());out.put("previewAllowed",false);var owner=WorkcardOwnerReader.databaseBacked().read(c,actor.tenantId(),v.receivedBy());if(owner!=null){var identities=List.of(owner.appointment().selector(),owner.principal().selector(),owner.organization().selector());if(authority.permitted(c,actor,x.organization(),identities,code)){disclose(c,actor,x,identities,code,"BODY",ds);out.put("receivedByLabel",owner.principal().displayName());}}return out;}
 private Map<String,Object> upload(Connection c,Actor actor,MaterialEvidence.Basis b,Instant now)throws SQLException{var out=new LinkedHashMap<String,Object>(evidence.body(c,actor.tenantId(),b));out.put("selector",selector(b.selector()));out.put("factRef",PublicFactReferences.reference(actor,b.selector().type(),b.selector().id()));String state="FINALIZED".equals(b.state())?"ACCEPTED":!b.expiresAt().isAfter(now)?"EXPIRED":b.checkState()==null?"OPEN":b.checkState();out.put("state",state);out.put("expiresAt",b.expiresAt().toString());out.put("purpose",b.purpose());out.put("previousVersion",selector(b.previous()));out.put("confirmation",selector(b.confirmation()));if(b.sizeBytes()!=null)out.put("sizeBytes",b.sizeBytes());if(b.mediaType()!=null)out.put("mediaType",b.mediaType());if(b.resultCode()!=null)out.put("resultCode",b.resultCode());return out;}
 private static Map<String,Object> selector(Subject s){return R2CustomerRequirementsServices.selector(s);}
 private static R1ServiceReadRuntime.Failure fail(String code){return new R1ServiceReadRuntime.Failure(code.equals("NOT_AUTHORIZED")?403:code.equals("SERVICE_UNAVAILABLE")?503:412,code);}
}



