package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.audit.AuditAppender;import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.opportunity.*;
import java.sql.*;import java.util.*;
final class R2QuoteReadService {
 private final QuoteWorkflowService service;private final AuditAppender audit;private final OpportunityLedgerAuthorityReader authority=OpportunityLedgerAuthorityReader.databaseBacked();
 R2QuoteReadService(OpportunityProgressProtection protection,AuditAppender audit){this.service=R2QuoteServices.create(protection);this.audit=audit;}
 Map<String,Object> read(Connection c,Actor actor,UUID id)throws SQLException{return disclose(c,actor,id,()->context(c,actor,id),"BODY");}
 byte[] document(Connection c,Actor actor,UUID id,UUID quote)throws SQLException{return disclose(c,actor,id,()->service.document(c,actor,id,quote),"DOWNLOAD");}
 Map<String,Object> task(Connection c,Actor actor,UUID taskId)throws SQLException{
  return QuoteReadRuntime.read(c,actor,audit,(tx,now)->{var task=io.github.windyzhu3.ontologylaw.responsibility.TaskFactory.databaseBacked().read(tx,actor.tenantId(),taskId);if(task==null||!task.type().name().contains("QUOTE")||!task.owner().equals(actor.appointmentId())||!"opportunity.opportunity".equals(task.subject().type()))throw fail("NOT_AUTHORIZED");
   var id=task.subject().id();var opening=EventOpportunityReader.databaseBacked().byId(tx,actor.tenantId(),id);if(opening==null)throw fail("NOT_FOUND");var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),opening.selector());var fs=new ArrayList<>(service.protectedFacts(tx,actor.tenantId(),id));fs.add(task.selector());if(org==null||!authority.permitted(tx,actor,org,fs,"QUOTE_READ"))throw fail("NOT_AUTHORIZED");var ds=new ArrayList<AuditAppender.QuoteDisclosureEntry>();for(var f:fs){var a=authority.evidence(tx,actor,org,f,"QUOTE_READ");if(a==null||!a.allowed())throw fail("NOT_AUTHORIZED");ds.add(new AuditAppender.QuoteDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),f,a,"BODY"));}var context=context(tx,actor,id);var freshTask=io.github.windyzhu3.ontologylaw.responsibility.TaskFactory.databaseBacked().read(tx,actor.tenantId(),taskId);var fresh=new ArrayList<>(service.protectedFacts(tx,actor.tenantId(),id));if(freshTask==null||!freshTask.selector().equals(task.selector())||!freshTask.owner().equals(actor.appointmentId()))throw fail("STALE_SUBJECT");fresh.add(freshTask.selector());if(!new LinkedHashSet<>(fs).equals(new LinkedHashSet<>(fresh)))throw fail("STALE_SUBJECT");for(var d:ds)if(!AuthorizationService.databaseBacked().evaluate(tx,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");return new QuoteReadRuntime.Prepared<>(Map.of("opportunityId",id.toString(),"context",context),ds);});
 }
 @SuppressWarnings("unchecked") private Map<String,Object> context(Connection c,Actor actor,UUID id)throws SQLException{var result=new LinkedHashMap<String,Object>(service.context(c,actor,id));var opening=EventOpportunityReader.databaseBacked().byId(c,actor.tenantId(),id);var org=R2OpportunityOwnerExceptionAssembly.organization(c,actor.tenantId(),opening.selector());var fs=service.protectedFacts(c,actor.tenantId(),id);var allowed=new ArrayList<String>();for(String action:(List<String>)result.get("allowedActions"))if(authority.permitted(c,actor,org,fs,R1CommandPolicy.quoteAuthority(CommandEnvelope.Type.valueOf(action))))allowed.add(action);result.put("allowedActions",List.copyOf(allowed));return result;}
 @FunctionalInterface interface Read<T>{T run()throws SQLException;}
 private <T>T disclose(Connection c,Actor actor,UUID id,Read<T> read,String mode)throws SQLException{return QuoteReadRuntime.read(c,actor,audit,(tx,now)->{var opening=EventOpportunityReader.databaseBacked().byId(tx,actor.tenantId(),id);if(opening==null)throw fail("NOT_FOUND");var org=R2OpportunityOwnerExceptionAssembly.organization(tx,actor.tenantId(),opening.selector());var fs=service.protectedFacts(tx,actor.tenantId(),id);if(org==null||fs.isEmpty()||!authority.permitted(tx,actor,org,fs,"QUOTE_READ"))throw fail("NOT_AUTHORIZED");var disclosures=new ArrayList<AuditAppender.QuoteDisclosureEntry>();for(var f:fs){var a=authority.evidence(tx,actor,org,f,"QUOTE_READ");if(a==null||!a.allowed())throw fail("NOT_AUTHORIZED");disclosures.add(new AuditAppender.QuoteDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),f,a,mode));}var result=read.run();for(var d:disclosures)if(!AuthorizationService.databaseBacked().evaluate(tx,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");if(!new LinkedHashSet<>(fs).equals(new LinkedHashSet<>(service.protectedFacts(tx,actor.tenantId(),id))))throw fail("STALE_SUBJECT");return new QuoteReadRuntime.Prepared<>(result,disclosures);});}
 private static R1ServiceReadRuntime.Failure fail(String code){return new R1ServiceReadRuntime.Failure(code.equals("NOT_FOUND")?404:code.equals("STALE_SUBJECT")?412:403,code);}
}
