package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.CommandEnvelope;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.http.ResponseEntity;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.web.bind.annotation.*;
@RestController
public class R2QuoteApiDelegate {
 private final ObjectProvider<R1ApiServices> services;public R2QuoteApiDelegate(ObjectProvider<R1ApiServices> services){this.services=services;}
 private R1ApiServices service(){var s=services.getIfAvailable();if(s==null)throw new R1HttpFailure("SERVICE_UNAVAILABLE");return s;}
 private Actor actor(UUID behalf){var a=SecurityContextHolder.getContext().getAuthentication();if(a==null||behalf!=null||!(a.getPrincipal() instanceof Actor actor)||actor.principalKind()!=PrincipalKind.HUMAN||actor.onBehalfAppointmentId()!=null)throw new R1HttpFailure("NOT_AUTHORIZED");return actor;}
 @GetMapping("/api/v1/opportunities/{id}/quotes") public ResponseEntity<Map<String,Object>> context(@PathVariable UUID id,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").body(service().quotes(actor(behalf),id));}
 @GetMapping("/api/v1/quote-tasks/{taskId}/context") public ResponseEntity<Map<String,Object>> task(@PathVariable UUID taskId,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").body(service().quoteTask(actor(behalf),taskId));}
 @GetMapping("/api/v1/opportunities/{id}/quotes/{quoteId}/document") public ResponseEntity<byte[]> document(@PathVariable UUID id,@PathVariable UUID quoteId,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").header("Content-Type","text/html; charset=UTF-8").header("X-Content-Type-Options","nosniff").header("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox").header("Content-Disposition","attachment; filename=quote-"+quoteId+".html").body(service().quoteDocument(actor(behalf),id,quoteId));}
 @PostMapping("/api/v1/opportunities/{id}/quotes/{action:terminations|preparation-intents|draft|form|approval-requests|decisions|deliveries|responses}") public ResponseEntity<Map<String,Object>> command(@PathVariable UUID id,@PathVariable String action,@RequestHeader("Idempotency-Key") UUID key,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf,@RequestBody Map<String,Object> body){var type=switch(action){case "terminations"->CommandEnvelope.Type.END_QUOTE_NEGOTIATION;case "preparation-intents"->CommandEnvelope.Type.START_QUOTE_PREPARATION;case "draft"->CommandEnvelope.Type.SAVE_QUOTE_DRAFT;case "form"->CommandEnvelope.Type.FORM_QUOTE;case "approval-requests"->CommandEnvelope.Type.REQUEST_QUOTE_APPROVAL;case "decisions"->CommandEnvelope.Type.RECORD_QUOTE_DECISION;case "deliveries"->CommandEnvelope.Type.RECORD_QUOTE_DELIVERY;case "responses"->CommandEnvelope.Type.RECORD_QUOTE_RESPONSE;default->throw new R1HttpFailure("NOT_FOUND");};if(body.containsKey("opportunityId"))throw new R1HttpFailure("VALIDATION_FAILED");var p=new TreeMap<String,Object>(body);p.put("opportunityId",id.toString());for(String field:List.of("customerConfirmation","expectedDraft","expectedQuote","expectedWorkflow"))p.putIfAbsent(field,null);var envelope=new CommandEnvelope(type,key,UUID.randomUUID(),actor(behalf),p);try{R2QuoteInput.parse(envelope);}catch(io.github.windyzhu3.ontologylaw.execution.CommandHandler.Rejected invalid){throw new R1HttpFailure(invalid.code());}var response=service().opportunityCommand(envelope);if(response.errorCode()!=null)throw new R1HttpFailure(response.errorCode(),response.receiptRef(),null,null);return ResponseEntity.status(response.status()).header("Cache-Control","no-store").header("Location","/api/v1/commands/"+key+"/receipt").body(response.body());}
}
