package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.transfer.*;import java.sql.*;import java.util.*;
final class R2TransferCommand implements CommandHandler {
 private final CommandEnvelope.Type type;private final OpportunityProgressProtection protection;private final TransferWorkflowService service;
 R2TransferCommand(CommandEnvelope.Type type,OpportunityProgressProtection protection,TransferWorkflowService service){if(!type.transfers())throw new IllegalArgumentException();this.type=type;this.protection=protection;this.service=Objects.requireNonNull(service);}
 public CommandEnvelope.Type type(){return type;}
 public Context resolve(Connection c,CommandEnvelope e)throws SQLException{var b=R2TransferInput.parse(e).binding();var facts=R2TransferServices.authorization(c,e.actor().tenantId(),b,type);require(facts!=null,"NOT_FOUND");var r=R1AuthorityReader.databaseBacked().select(c,e.actor(),b.opportunity(),facts.organization(),"OPPORTUNITY_OWNER",R1CommandPolicy.transferAuthority(type));require(r!=null,"NOT_AUTHORIZED");return new Context(CommandScope.transfers(e,b),r,b);}
 public void recoveryEligibility(Connection c,CommandEnvelope e,Context ctx){}
 public void lockRoots(Connection c,CommandEnvelope e,Context ctx)throws SQLException{OpportunityCommandReader.databaseBacked(protection).lock(c,e.actor().tenantId(),((CommandAuthorizationBinding.Transfers)ctx.binding()).opportunity().id());}
 public void validateBeforeWork(Connection c,CommandEnvelope e,Context ctx)throws SQLException{
  var parsed=R2TransferInput.parse(e);var b=parsed.binding();var h=OpportunityCommandReader.databaseBacked(protection).header(c,e.actor().tenantId(),b.opportunity().id());require(h!=null&&h.selector().equals(b.opportunity()),"STALE_SUBJECT");require(!h.closed(),"OPPORTUNITY_CLOSED");
  var reader=TransferWorkflowReader.databaseBacked();var state=reader.workflow(c,e.actor().tenantId(),b.workflow().id());require(state!=null&&state.equals(reader.current(c,e.actor().tenantId(),state.request().id())),"STALE_SUBJECT");
  if(type==CommandEnvelope.Type.SUBMIT_TRANSFER)require(state.stage().equals("PREPARE"),"STALE_SUBJECT");if(type==CommandEnvelope.Type.RESUBMIT_TRANSFER)require(state.stage().equals("SUPPLEMENT"),"STALE_SUBJECT");if(type==CommandEnvelope.Type.CLASSIFY_MATTER)require(state.matterId()!=null&&state.matterId().toString().equals(parsed.values().get("matterId")),"STALE_SUBJECT");
 }
 public Result execute(Connection c,CommandEnvelope e,Context ctx)throws SQLException{var p=R2TransferInput.parse(e);try{var fact=switch(type){case SUBMIT_TRANSFER,RESUBMIT_TRANSFER->service.submit(c,e.actor(),p.binding().workflow(),(TransferSubmissionInput)p.input());case RECORD_TRANSFER_CONFLICT_REVIEW->service.review(c,e.actor(),p.binding().workflow(),(TransferConflictReviewInput)p.input());case RECORD_TRANSFER_INTAKE->service.intake(c,e.actor(),p.binding().workflow(),(TransferIntakeInput)p.input());case CLASSIFY_MATTER->service.classify(c,e.actor(),p.binding().workflow(),(TransferClassificationInput)p.input());default->throw new IllegalArgumentException();};require(R1CommandPolicy.transferResultType(type).equals(fact.type()),"VALIDATION_FAILED");return Result.succeeded(fact,R1EventPolicy.transferEvent(type));}catch(TransferWorkflowService.Blocked blocked){throw new Rejected(blocked.code());}catch(IllegalArgumentException invalid){throw new Rejected("VALIDATION_FAILED");}}
 public void validateBeforeCommit(Connection c,CommandEnvelope e,Context ctx,Result result)throws SQLException{var b=(CommandAuthorizationBinding.Transfers)ctx.binding();require(R2TransferServices.result(c,e,b,result.fact()),"STALE_SUBJECT");var current=R2TransferServices.authorization(c,e.actor().tenantId(),b,type);require(current!=null&&current.protectedFacts().contains(result.fact()),"STALE_SUBJECT");R2CustomerRequirementsServices.requireAuthority(c,e.actor(),current.organization(),current.protectedFacts(),R1CommandPolicy.transferAuthority(type));R2CustomerRequirementsServices.requireAuthority(c,e.actor(),current.organization(),current.protectedFacts(),"CONTRACT_READ");}
 private static void require(boolean value,String code){if(!value)throw new Rejected(code);}
}
