package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.audit.AuditAppender;
import io.github.windyzhu3.ontologylaw.contract.*;
import io.github.windyzhu3.ontologylaw.execution.*;
import io.github.windyzhu3.ontologylaw.identity.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import io.github.windyzhu3.ontologylaw.opportunity.*;
import io.github.windyzhu3.ontologylaw.responsibility.TaskFactory;
import io.github.windyzhu3.ontologylaw.transfer.*;
import java.sql.*;import java.util.*;
/** Exact-task disclosure shares the contract read fence and audit boundary. */
final class R2TransferReadService {
 private final ContractProtection protection;private final OpportunityProgressProtection materials;private final ContractWorkflowService contracts;private final ContractWorkflowPorts contractPorts;private final TransferWorkflowPorts ports;private final AuditAppender audit;
 private final TransferWorkflowReader reader=TransferWorkflowReader.databaseBacked();private final OpportunityLedgerAuthorityReader authority=OpportunityLedgerAuthorityReader.databaseBacked();
 R2TransferReadService(ContractProtection protection,OpportunityProgressProtection materials,ContractWorkflowService contracts,ContractWorkflowPorts contractPorts,TransferWorkflowPorts ports,AuditAppender audit){this.protection=protection;this.materials=materials;this.contracts=contracts;this.contractPorts=contractPorts;this.ports=ports;this.audit=audit;}
 Map<String,Object> task(Connection connection,Actor actor,UUID taskId)throws SQLException{return ContractReadRuntime.read(connection,actor,audit,(c,now)->prepare(c,actor,taskId));}
 Map<String,Object> classificationCorrection(Connection connection,Actor actor,UUID opportunity)throws SQLException{return ContractReadRuntime.read(connection,actor,audit,(c,now)->{
  if(actor.principalKind()!=PrincipalKind.HUMAN||actor.onBehalfAppointmentId()!=null)throw fail("NOT_AUTHORIZED");
  var states=reader.forOpportunity(c,actor.tenantId(),opportunity);if(states.size()!=1)throw fail("STALE_SUBJECT");var state=states.getFirst();
  if(!"COMPLETE".equals(state.stage())||state.matterId()==null||state.classification()==null)throw fail("STALE_SUBJECT");
  try{ports.authorize(c,actor,state.opportunity(),"MATTER_CLASSIFY",List.of(state.workflow(),state.intake()));}catch(TransferWorkflowService.Blocked e){throw fail(e.code());}
  if(!actor.appointmentId().equals(ports.owner(c,actor,state.opportunity(),state.request().id(),"CLASSIFY",null,null)))throw fail("NOT_AUTHORIZED");
  var facts=new LinkedHashSet<Subject>(R2ContractServices.facts(c,actor.tenantId(),opportunity));facts.addAll(reader.facts(c,actor.tenantId(),state.request().id()));facts.add(state.workflow());facts.add(state.request());facts.add(state.opportunity());
  var ds=new ArrayList<AuditAppender.ContractDisclosureEntry>();disclose(c,actor,state.toOrganization(),facts,ds);
  var receivers=new ArrayList<Map<String,Object>>();
  for(var id:contractPorts.eligible(c,actor.tenantId(),state.toOrganization(),List.copyOf(facts),"MATTER_RECEIVE")){
   try{ports.validateRecipient(c,actor,state.opportunity(),state.request().id(),new TransferClassificationInput(state.category(),id,"读取当前分类承接候选"));}catch(TransferWorkflowService.Blocked unavailable){continue;}
   var owner=WorkcardOwnerReader.databaseBacked().read(c,actor.tenantId(),id);if(owner==null)continue;var ownerFacts=List.of(owner.appointment().selector(),owner.principal().selector(),owner.organization().selector());
   if(!authority.permitted(c,actor,state.toOrganization(),ownerFacts,"CONTRACT_READ"))continue;disclose(c,actor,state.toOrganization(),ownerFacts,ds);receivers.add(Map.of("id",id.toString(),"label",owner.principal().displayName()+" · "+owner.organization().displayName()));
  }
  var result=new LinkedHashMap<String,Object>();result.put("opportunityId",opportunity.toString());result.put("expectedOpportunityRevision",state.opportunity().revision());result.put("expectedWorkflow",Map.of("id",state.workflow().id().toString(),"revision",state.workflow().revision()));result.put("customerName",contractPorts.customerName(c,actor.tenantId(),opportunity));result.put("matter",Map.of("id",state.matterId().toString(),"number",state.matterNumber()));result.put("category",state.category());result.put("recipient",receivers.stream().filter(r->r.get("id").equals(state.recipient().toString())).findFirst().orElse(null));result.put("receivers",receivers);
  if(!state.equals(reader.current(c,actor.tenantId(),state.request().id())))throw fail("STALE_SUBJECT");for(var d:ds)if(!AuthorizationService.databaseBacked().evaluate(c,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");
  return new ContractReadRuntime.Prepared<>(Collections.unmodifiableMap(result),ds);
 });}
 private ContractReadRuntime.Prepared<Map<String,Object>> prepare(Connection c,Actor actor,UUID taskId)throws SQLException{
  var state=reader.forTask(c,actor.tenantId(),taskId);var task=TaskFactory.databaseBacked().read(c,actor.tenantId(),taskId);
  if(state==null||task==null||!task.type().isTransfer()||!actor.appointmentId().equals(state.owner())||!actor.appointmentId().equals(task.owner())||!Set.of("OPEN","CLAIMED").contains(task.state()))throw fail("NOT_AUTHORIZED");
  UUID org=Set.of("PREPARE","SUPPLEMENT").contains(state.stage())?state.fromOrganization():state.toOrganization();
  var facts=new LinkedHashSet<Subject>(R2ContractServices.facts(c,actor.tenantId(),state.opportunity().id()));facts.addAll(reader.facts(c,actor.tenantId(),state.request().id()));facts.add(state.request());facts.add(state.opportunity());facts.add(task.selector());
  var items=reader.returnItems(c,actor.tenantId(),state);items.forEach(i->facts.add(i.selector()));
  String code=R1CommandPolicy.transferAuthority(CommandEnvelope.Type.valueOf(task.type().command));
  if(!authority.permitted(c,actor,org,List.copyOf(facts),code))throw fail("NOT_AUTHORIZED");
  var ds=new ArrayList<AuditAppender.ContractDisclosureEntry>();disclose(c,actor,org,facts,ds);
  var result=new LinkedHashMap<String,Object>();result.put("opportunityId",state.opportunity().id().toString());result.put("expectedOpportunityRevision",state.opportunity().revision());result.put("expectedWorkflow",Map.of("id",state.workflow().id().toString(),"revision",state.workflow().revision()));result.put("stage",state.stage());result.put("taskId",taskId.toString());result.put("dueAt",state.dueAt().toString());result.put("allowedAction",task.type().command);
  result.put("customerName",contractPorts.customerName(c,actor.tenantId(),state.opportunity().id()));
  var contractContext=contracts.context(c,actor,state.opportunity().id());var contract=(Map<?,?>)contractContext.get("contract");if(contract==null)throw fail("STALE_SUBJECT");var document=(Map<?,?>)contract.get("document");var terms=(Map<?,?>)document.get("commercial");var signing=(Map<?,?>)document.get("signing");var gate=(Map<?,?>)document.get("paymentGate");result.put("contract",Map.of("id",state.contractId().toString(),"version",contract.get("version"),"scope",terms.get("scope"),"paymentTerms",terms.get("paymentTerms"),"signingRequirements",signing.get("requirements"),"receiptRequiredBeforeTransfer",gate.get("receiptRequiredBeforeTransfer")));
  var submission=body(c,actor,state.submission());result.put("submission",submission==null?null:submissionInput(submission));var review=body(c,actor,state.review());result.put("review",review==null?null:Map.of("outcome",review.get("outcome"),"explanation",review.get("explanation")));var intake=body(c,actor,state.intake());result.put("intake",intake==null?null:Map.of("decision",intake.get("decision"),"explanation",intake.get("explanation")));
  result.put("matter",state.matterId()==null?null:Map.of("id",state.matterId().toString(),"number",state.matterNumber()));
  var returns=new ArrayList<Map<String,Object>>();for(var item:items){var reason=state.intake()==null?review:intake;returns.add(Map.of("id",item.selector().id().toString(),"requirement",item.requirement(),"label",requirementLabel(item.requirement()),"reason",reason==null?"":reason.getOrDefault("explanation",""),"requiresMaterial",!"HANDOVER_EXPLANATION".equals(item.requirement())));}result.put("returnItems",returns);
  var documents=new ArrayList<Map<String,Object>>();var versions=OpportunityMaterials.databaseBacked();var evidence=R2MaterialsServices.evidence(materials);
  for(var version:versions.history(c,actor.tenantId(),state.opportunity().id())){if(!versions.current(c,actor.tenantId(),version.selector().id()))continue;var f=contractPorts.documentFacts(c,actor.tenantId(),version.selector().id());if(f.isEmpty()||!authority.permitted(c,actor,org,f,"CONTRACT_READ"))continue;var basis=evidence.basis(c,actor.tenantId(),version.upload());if(basis==null||!contractPorts.documentUsable(c,actor.tenantId(),version.selector().id(),basis.sha256()))continue;disclose(c,actor,org,f,ds);var metadata=evidence.body(c,actor.tenantId(),basis);documents.add(Map.of("id",version.selector().id().toString(),"fileName",metadata.get("fileName"),"sha256",basis.sha256()));}result.put("materials",documents);
  result.put("reviewPreview",null);if("REVIEW_TRANSFER".equals(state.stage())){var scan=ports.reviewPreview(c,actor.tenantId(),state.submission().id());var scanFacts=new LinkedHashSet<Subject>();for(var party:scan.scope()){scanFacts.add(new Subject(party.sourceType(),party.sourceId(),null,Base64.getUrlEncoder().withoutPadding().encodeToString(HexFormat.of().parseHex(party.digest()))));scanFacts.add(new Subject("party.party",party.partyId(),party.revision(),null));}for(var party:scan.corpus()){scanFacts.add(new Subject(party.sourceType(),party.sourceId(),null,Base64.getUrlEncoder().withoutPadding().encodeToString(HexFormat.of().parseHex(party.digest()))));scanFacts.add(new Subject("party.party",party.partyId(),party.revision(),null));}disclose(c,actor,org,scanFacts,ds);result.put("reviewPreview",Map.of("scopeComplete",scan.scopeComplete(),"candidateCount",scan.candidates().size(),"permittedOutcomes",scan.permittedOutcomes()));}
  var receivers=new ArrayList<Map<String,Object>>();if("CLASSIFY".equals(state.stage()))for(var id:contractPorts.eligible(c,actor.tenantId(),org,List.copyOf(facts),"MATTER_RECEIVE")){try{ports.validateRecipient(c,actor,state.opportunity(),state.request().id(),new TransferClassificationInput("OTHER",id,"读取当前合格承接人"));}catch(TransferWorkflowService.Blocked unavailable){continue;}var owner=WorkcardOwnerReader.databaseBacked().read(c,actor.tenantId(),id);if(owner==null)continue;var ownerFacts=List.of(owner.appointment().selector(),owner.principal().selector(),owner.organization().selector());if(!authority.permitted(c,actor,org,ownerFacts,"CONTRACT_READ"))continue;disclose(c,actor,org,ownerFacts,ds);receivers.add(Map.of("id",id.toString(),"label",owner.principal().displayName()+" · "+owner.organization().displayName()));}result.put("receivers",receivers);
  if(!state.equals(reader.forTask(c,actor.tenantId(),taskId)))throw fail("STALE_SUBJECT");for(var d:ds)if(!AuthorizationService.databaseBacked().evaluate(c,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");
  return new ContractReadRuntime.Prepared<>(Collections.unmodifiableMap(result),ds);
 }
 byte[] document(Connection connection,Actor actor,UUID taskId,UUID version)throws SQLException{return ContractReadRuntime.read(connection,actor,audit,(c,now)->{
  var prepared=prepare(c,actor,taskId);var state=reader.forTask(c,actor.tenantId(),taskId);if(state==null)throw fail("STALE_SUBJECT");
  boolean included=((List<?>)prepared.value().get("materials")).stream().anyMatch(m->version.toString().equals(((Map<?,?>)m).get("id")));
  if(prepared.value().get("submission") instanceof Map<?,?> submission)for(String key:List.of("clientIdentity","signatureArchive"))included|=version.toString().equals(((Map<?,?>)submission.get(key)).get("versionId"));
  if(!included)throw fail("NOT_AUTHORIZED");UUID org=Set.of("PREPARE","SUPPLEMENT").contains(state.stage())?state.fromOrganization():state.toOrganization();var facts=contractPorts.documentFacts(c,actor.tenantId(),version);if(facts.isEmpty())throw fail("STALE_EVIDENCE");var ds=new ArrayList<>(prepared.disclosures());disclose(c,actor,org,facts,ds);byte[] data=contractPorts.document(c,actor,state.opportunity().id(),version);
  if(!state.equals(reader.forTask(c,actor.tenantId(),taskId)))throw fail("STALE_SUBJECT");for(var d:ds)if(!AuthorizationService.databaseBacked().evaluate(c,d.authorization().request(),true).allowed())throw fail("NOT_AUTHORIZED");return new ContractReadRuntime.Prepared<>(data,ds.stream().map(d->new AuditAppender.ContractDisclosureEntry(d.id(),d.correlationId(),d.disclosedSource(),d.authorization(),"DOWNLOAD")).toList());
 });}
 @SuppressWarnings("unchecked") private Map<String,Object> body(Connection c,Actor actor,Subject fact)throws SQLException{if(fact==null)return null;var protectedFact=reader.body(c,actor.tenantId(),fact);if(protectedFact==null)throw fail("STALE_SUBJECT");return tools.jackson.databind.json.JsonMapper.builder().build().readValue(protection.open(actor.tenantId(),protectedFact.opportunity(),fact.id(),ContractProtection.Kind.TRANSFER,protectedFact.ciphertext()),Map.class);}
 private static Map<String,Object> submissionInput(Map<String,Object> body){var result=new LinkedHashMap<String,Object>();for(String key:List.of("clientIdentity","signatureArchive")){var material=(Map<?,?>)body.get(key);result.put(key,Map.of("versionId",material.get("id"),"sha256",material.get("sha256")));}result.put("explanation",body.get("explanation"));result.put("consistencyChecked",body.get("consistencyChecked"));result.put("corrections",List.of());return result;}
 private void disclose(Connection c,Actor actor,UUID org,Collection<Subject> facts,List<AuditAppender.ContractDisclosureEntry> ds)throws SQLException{for(var fact:facts){var evidence=authority.evidence(c,actor,org,fact,"CONTRACT_READ");if(evidence==null||!evidence.allowed())throw fail("NOT_AUTHORIZED");ds.add(new AuditAppender.ContractDisclosureEntry(UUID.randomUUID(),UUID.randomUUID(),fact,evidence,"BODY"));}}
 private static String requirementLabel(String code){return switch(code){case "CLIENT_IDENTITY"->"委托主体证明";case "SIGNATURE_ARCHIVE"->"完整签署归档";case "HANDOVER_EXPLANATION"->"交接说明";case "RESOLVE_CONFLICT"->"冲突处理依据";case "COMPLETE_SUBJECT_EVIDENCE"->"主体与审查材料";default->"补充材料";};}
 private static R1ServiceReadRuntime.Failure fail(String code){return new R1ServiceReadRuntime.Failure(code.equals("NOT_AUTHORIZED")?403:412,code);}
}
