package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import java.util.*;import org.springframework.beans.factory.ObjectProvider;import org.springframework.http.ResponseEntity;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.web.bind.annotation.*;
@RestController public class R2TransferApiDelegate {
 private final ObjectProvider<R1ApiServices> services;public R2TransferApiDelegate(ObjectProvider<R1ApiServices> services){this.services=services;}
 private R1ApiServices service(){var s=services.getIfAvailable();if(s==null)throw new R1HttpFailure("SERVICE_UNAVAILABLE");return s;}
 private Actor actor(UUID behalf){var auth=SecurityContextHolder.getContext().getAuthentication();if(auth==null||behalf!=null||!(auth.getPrincipal() instanceof Actor actor)||actor.principalKind()!=PrincipalKind.HUMAN||actor.onBehalfAppointmentId()!=null)throw new R1HttpFailure("NOT_AUTHORIZED");return actor;}
 @GetMapping("/api/v1/opportunities/{opportunityId}/transfers/classification-context")
 public ResponseEntity<Map<String,Object>> classificationContext(@PathVariable UUID opportunityId,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").body(service().classificationCorrection(actor(behalf),opportunityId));}
 @GetMapping("/api/v1/transfer-tasks/{taskId}/context")
 public ResponseEntity<Map<String,Object>> context(@PathVariable UUID taskId,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").body(service().transferTask(actor(behalf),taskId));}
 @GetMapping("/api/v1/transfer-tasks/{taskId}/materials/{versionId}/content")
 public ResponseEntity<byte[]> document(@PathVariable UUID taskId,@PathVariable UUID versionId,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf){return ResponseEntity.ok().header("Cache-Control","no-store").header("Content-Type","application/octet-stream").header("X-Content-Type-Options","nosniff").header("Content-Security-Policy","default-src 'none'; sandbox").header("Content-Disposition","attachment; filename=transfer-material-"+versionId+".bin").body(service().transferDocument(actor(behalf),taskId,versionId));}
 static CommandEnvelope.Type commandType(String action){return switch(action){case "submissions"->CommandEnvelope.Type.SUBMIT_TRANSFER;case "supplements"->CommandEnvelope.Type.RESUBMIT_TRANSFER;case "conflict-reviews"->CommandEnvelope.Type.RECORD_TRANSFER_CONFLICT_REVIEW;case "intake-decisions"->CommandEnvelope.Type.RECORD_TRANSFER_INTAKE;case "classifications"->CommandEnvelope.Type.CLASSIFY_MATTER;default->throw new R1HttpFailure("NOT_FOUND");};}
 @PostMapping("/api/v1/opportunities/{id}/transfers/{action:submissions|supplements|conflict-reviews|intake-decisions|classifications}")
 public ResponseEntity<Map<String,Object>> command(@PathVariable UUID id,@PathVariable String action,@RequestHeader("Idempotency-Key") UUID key,@RequestHeader(value="X-On-Behalf-Appointment-Id",required=false) UUID behalf,@RequestBody Map<String,Object> body){
  if(body.containsKey("opportunityId"))throw new R1HttpFailure("VALIDATION_FAILED");var p=new TreeMap<String,Object>(body);p.put("opportunityId",id.toString());var envelope=new CommandEnvelope(commandType(action),key,UUID.randomUUID(),actor(behalf),p);try{R2TransferInput.parse(envelope);}catch(CommandHandler.Rejected invalid){throw new R1HttpFailure(invalid.code());}var response=service().contractCommand(envelope);if(response.errorCode()!=null)throw new R1HttpFailure(response.errorCode(),response.receiptRef(),null,null);return ResponseEntity.status(response.status()).header("Cache-Control","no-store").header("Location","/api/v1/commands/"+key+"/receipt").body(response.body());
 }
}
