import {chromium} from '@playwright/test';import assert from 'node:assert/strict';import {login,save,runtime} from './browser.mjs';
if(!runtime.endsWith('haihua-uat-runtime'))throw Error('Original business facts required');
const browser=await chromium.launch({channel:'chrome',headless:true}),results=[];let page;
try{for(const username of ['sales01','sales02','sales03','sales04','sales05','sales_manager01','sales_manager02','finance01','case_admin01']){
 const actor=await login(browser,username);page=actor.page;await page.getByRole('button',{name:'业务管理',exact:true}).click();const summaryResponse=page.waitForResponse(r=>r.request().method()==='GET'&&new URL(r.url()).pathname==='/api/v1/business-overview');await page.locator('aside.business-navigation').getByRole('button',{name:'经营概览',exact:true}).click();const response=await summaryResponse;assert.equal(response.status(),200);const summary=await response.json();assert.equal(summary.metrics.length,5);await page.getByRole('region',{name:'五项经营指标',exact:true}).waitFor();const metrics=[];
 for(const metric of summary.metrics){const row=page.getByRole('region',{name:'五项经营指标',exact:true}).locator('tbody tr').filter({hasText:metric.label});if(metric.status==='FORBIDDEN'){assert.equal(metric.count,null);assert.equal(await row.locator('strong').innerText(),'不可查看');assert.equal(await row.getByRole('button',{name:'查看明细',exact:true}).count(),0);metrics.push({...metric,detailState:'FORBIDDEN'});continue;}
  assert.equal(await row.locator('strong').innerText(),String(metric.count));let detailResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/v1/business-overview/'+metric.key);await row.getByRole('button',{name:'查看明细',exact:true}).click();const items=[],visited=[];
  for(let index=0;index<100;index++){const r=await detailResponse;assert.equal(r.status(),200);const data=await r.json();assert.equal(data.metric,metric.key);assert.equal(data.month,summary.month);await page.getByText('正在重新核对本项明细…',{exact:true}).waitFor({state:'hidden'});const pane=page.getByRole('region',{name:'同口径明细',exact:true});await pane.getByRole('heading',{name:metric.label+'明细',exact:true}).waitFor();await page.waitForFunction(count=>document.querySelector('section[aria-label="同口径明细"] tbody')?.children.length===count,data.items.length);assert.equal(await pane.locator('tbody tr').count(),data.items.length);items.push(...data.items);visited.push({index,asOf:data.asOf,count:data.items.length,hasNext:!!data.nextCursor});if(!data.nextCursor)break;if(index===99)throw Error('Overview cursor traversal incomplete');detailResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/v1/business-overview/'+metric.key&&new URL(r.url()).searchParams.has('cursor'));await pane.getByRole('button',{name:'下一页',exact:true}).click();}
  assert.equal(new Set(items.map(x=>x.id)).size,items.length);assert.equal(items.length,metric.count);metrics.push({...metric,items,visited,uniqueDetailCount:items.length});
 }
 results.push({username,month:summary.month,asOf:summary.asOf,metrics});save('overview-ui-results.json',results);await actor.context.close();console.log(username+' five overview metrics and complete unique detail counts verified');
}save('overview-ui-PASS.json',{status:'PASS',actors:9,scope:'Actual UI summary and complete authorized detail count agreement; independent source reconciliation remains separate'});
}catch(e){if(page)save('overview-ui-failure.txt',await page.locator('body').innerText());throw e;}finally{await browser.close();}
