import {chromium} from '@playwright/test';import path from 'node:path';import fs from 'node:fs';
import {login,save,runtime} from './browser.mjs';import {selectTask} from './business-browser.mjs';
const [sales,code,slot='1',mode]=process.argv.slice(2);const browser=await chromium.launch({channel:'chrome',headless:true});let page;
if(mode==='future-date'&&(code!=='HH-B24-20261001-R2'||sales!=='sales04'||fs.existsSync(path.join(runtime,code+'-sign-slot'+slot+'-future-date-submit-receipt.json'))))throw Error('Approved original future-date negative only');
const field=(name)=>page.locator('label.field').filter({has:page.locator('.field-label').filter({hasText:new RegExp('^'+name+'$')})}).locator('select');
try{({page}=await login(browser,sales));page.setDefaultTimeout(60000);await selectTask(page,code,'签署');
await page.getByRole('heading',{name:/^(提交当前版本的完整材料|已完成事项保留，继续剩余要求)$/}).waitFor();
for(const file of [...(mode==='missing-signature'?[]:[code+'-SYNTHETIC-signed-exact-body.pdf']),code+'-authority-SYNTHETIC-NOT-LEGAL.pdf']){
if(await field('签字件').locator('option').filter({hasText:file}).count())continue;
await page.getByLabel('上传签字件或权限依据',{exact:true}).setInputFiles(path.join(runtime,'fixtures',file));await page.getByRole('button',{name:'上传并检查材料',exact:true}).click();await page.getByText('正在核对提交结果…',{exact:true}).waitFor({state:'hidden'});
for(let attempt=0;attempt<20;attempt++){const poll=page.getByRole('button',{name:'查询材料检查结果',exact:true});if(await poll.isVisible()){await poll.click();await page.getByText('正在核对提交结果…',{exact:true}).waitFor({state:'hidden'});}if(await field('签字件').locator('option').filter({hasText:file}).count())break;await page.waitForTimeout(2000);}
await field('签字件').locator('option').filter({hasText:file}).waitFor({state:'attached'});
}
if(await field('本次签署事项').isDisabled()){if(await field('本次签署事项').inputValue()!==slot)throw Error('Supplement must preserve original signing slot');}else await field('本次签署事项').selectOption(slot);let signedLabel=code+'-SYNTHETIC-signed-exact-body.pdf';if(mode==='missing-signature'){const generation=JSON.parse(fs.readFileSync(path.join(runtime,code+'-generation-metadata.json'),'utf8'));signedLabel='contract-generated-'+generation.sha256+'.pdf';}await field('签字件').selectOption({label:signedLabel});await field('代表权限依据').selectOption({label:code+'-authority-SYNTHETIC-NOT-LEGAL.pdf'});await page.getByLabel('签署人姓名',{exact:true}).fill(slot==='1'?'Synthetic Client Signer '+Number(sales.slice(-2)):'Synthetic Firm Signer');await page.getByLabel('实际签署日期',{exact:true}).fill(mode==='future-date'?'2026-10-02':'2026-10-01');await page.getByLabel('已核对签字件对应本版批准合同',{exact:true}).check();const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/contracts/signature-submissions'));await page.getByRole('button',{name:'提交签署核验',exact:true}).click();const r=await response,receipt=await r.json();save(code+'-sign-slot'+slot+'-'+(mode??'complete')+'-submit-receipt.json',{actor:sales,status:r.status(),receipt,fixtureMode:mode??'complete',commandId:r.request().headers()['idempotency-key'],requestBody:r.request().postDataJSON()});if(mode==='future-date'){if(r.status()!==400||receipt.code!=='VALIDATION_FAILED')throw Error('Future date must be rejected exactly');console.log(code+' future signing date actual UI rejected PASS');}else if(r.status()!==200||receipt.outcome!=='SUCCEEDED')throw Error('signature submit rejected');if(mode!=='future-date')console.log(code+' exact signature slot '+slot+' submitted through UI');
}catch(e){if(page)save(code+'-sign-submit-failure.txt',await page.locator('body').innerText());throw e;}finally{await browser.close();}
