import {chromium} from '@playwright/test';
import {login,save} from './browser.mjs';import {selectTask} from './business-browser.mjs';
const [actor,code,step,category='GENERAL']=process.argv.slice(2);const headings={prepare:'核对合同、客户及转案材料',review:'核对本次转案的冲突审查范围',intake:'核对准确版本和材料完整性',classify:'为已接收案件确认分类及承接'};if(!headings[step])throw Error('explicit step required');
const browser=await chromium.launch({channel:'chrome',headless:true});let page;
try{({page}=await login(browser,actor));await selectTask(page,code,step==='prepare'?'转案':step==='review'?'审查':step==='intake'?'接收':'分类');await page.getByRole('heading',{name:headings[step],exact:true}).waitFor();
page.on('response',async r=>{const p=new URL(r.url()).pathname;if(r.request().method()==='GET'&&p.startsWith('/api/v1/transfer')&&r.ok())save(code+'-transfer-context-'+step+'.json',await r.json());});
let action;
if(step==='prepare'){for(const [name,file] of [['identity',code+(['HH-B22-20261001-R2','HH-B19-20261001-R2','HH-B24-20261001-R2'].includes(code)?'-SYNTHETIC-client-identity.pdf':'-authority-SYNTHETIC-NOT-LEGAL.pdf')],['archive',code+'-SYNTHETIC-signed-exact-body.pdf']]){const select=page.locator('select[name='+name+']');const option=await select.locator('option').evaluateAll(es=>es.map(e=>({id:e.value,label:e.text})));const match=option.filter(e=>e.label.startsWith(file+' ·'));if(match.length!==1)throw Error('exact accepted material required');await select.selectOption(match[0].id);}await page.locator('textarea[name=explanation]').fill('纯合成完整交接：核对准确主体、批准范围、同版双方签署归档和权限依据，交案管独立审查接收。');await page.locator('input[name=checked]').check();action='提交案管接收';}
if(step==='review'){await page.locator('select[name=outcome]').selectOption('CLEAR');await page.locator('textarea[name=explanation]').fill('合成独立审查：完整主体范围与准确材料已核对，当前无阻断候选。');await page.locator('input[name=checked]').check();action='记录本次审查结果';}
if(step==='intake'){await page.locator('input[name=checked]').check();await page.locator('textarea[name=explanation]').fill('合成案管接收：独立审查通过、准确合同与材料完整，接收后生成唯一案件。');action='记录接收结果';}
if(step==='classify'){await page.locator('select[name=classification]').selectOption(category);const select=page.locator('select[name=receiver]');const ids=await select.locator('option').evaluateAll(es=>es.map(e=>e.value).filter(Boolean));if(ids.length!==1)throw Error('one qualified receiver required');await select.selectOption(ids[0]);await page.locator('textarea[name=explanation]').fill('纯合成分类与承接：按已接收事项确认当前分类，交具备资格的案管员承接。');action='确认分类及承接';}
const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.includes('/transfers/'));await page.getByRole('button',{name:action,exact:true}).click();const r=await response,receipt=await r.json();save(code+'-transfer-'+step+'-receipt.json',{actor,status:r.status(),receipt});if(r.status()!==200||receipt.outcome!=='SUCCEEDED')throw Error('transfer '+step+' rejected');await page.getByRole('heading',{name:headings[step],exact:true}).waitFor({state:'hidden'});save(code+'-transfer-'+step+'-after.txt',await page.locator('body').innerText());console.log(code+' '+actor+' transfer '+step+' UI PASS');
}catch(e){if(page)save(code+'-transfer-'+step+'-failure.txt',await page.locator('body').innerText());throw e;}finally{await browser.close();}
