"""Append-only schema contract evolutions after the frozen v1 baseline."""

from .v850_lead_ingress_completion import EVOLUTION as V850_LEAD_INGRESS_COMPLETION
from .v860_lead_ingress_query_read_capability import EVOLUTION as V860_LEAD_INGRESS_QUERY_READ_CAPABILITY

from .v870_r2_lead_independent_names import EVOLUTION as V870_R2_LEAD_INDEPENDENT_NAMES

from .v880_r2_opportunity_progress import EVOLUTION as V880_R2_OPPORTUNITY_PROGRESS
from .v890_r2_opportunity_checkpoint import EVOLUTION as V890_R2_OPPORTUNITY_CHECKPOINT

from .v900_r2_owner_exception import EVOLUTION as V900_R2_OWNER_EXCEPTION

from .v910_r2_opportunity_closure import EVOLUTION as V910_R2_OPPORTUNITY_CLOSURE
from .v920_r2_customer_requirements import EVOLUTION as V920_R2_CUSTOMER_REQUIREMENTS
EVOLUTIONS = (V850_LEAD_INGRESS_COMPLETION, V860_LEAD_INGRESS_QUERY_READ_CAPABILITY, V870_R2_LEAD_INDEPENDENT_NAMES, V880_R2_OPPORTUNITY_PROGRESS, V890_R2_OPPORTUNITY_CHECKPOINT, V900_R2_OWNER_EXCEPTION, V910_R2_OPPORTUNITY_CLOSURE, V920_R2_CUSTOMER_REQUIREMENTS)

__all__ = ("EVOLUTIONS", "V850_LEAD_INGRESS_COMPLETION", "V860_LEAD_INGRESS_QUERY_READ_CAPABILITY")

from .v930_r2_materials import EVOLUTION as V930_R2_MATERIALS
EVOLUTIONS = (*EVOLUTIONS, V930_R2_MATERIALS)

from .v940_r2_quotes import EVOLUTION as V940_R2_QUOTES
EVOLUTIONS = (*EVOLUTIONS, V940_R2_QUOTES)

from .v950_r2_quote_runtime import EVOLUTION as V950_R2_QUOTE_RUNTIME
EVOLUTIONS = (*EVOLUTIONS, V950_R2_QUOTE_RUNTIME)

from .v960_r2_quote_transaction import EVOLUTION as V960_R2_QUOTE_TRANSACTION
EVOLUTIONS = (*EVOLUTIONS, V960_R2_QUOTE_TRANSACTION)

from .v970_r2_contract_preparation import EVOLUTION as V970_R2_CONTRACT_PREPARATION
EVOLUTIONS = (*EVOLUTIONS, V970_R2_CONTRACT_PREPARATION)

from .v980_r2_contract_versions import EVOLUTION as V980_R2_CONTRACT_VERSIONS
EVOLUTIONS = (*EVOLUTIONS, V980_R2_CONTRACT_VERSIONS)

from .v990_r2_manual_signature import EVOLUTION as V990_R2_MANUAL_SIGNATURE
EVOLUTIONS = (*EVOLUTIONS, V990_R2_MANUAL_SIGNATURE)

from .v1000_r2_quote_preparation_intent import EVOLUTION as V1000_R2_QUOTE_PREPARATION_INTENT
EVOLUTIONS = (*EVOLUTIONS, V1000_R2_QUOTE_PREPARATION_INTENT)

from .v1010_r2_followup_attempt import EVOLUTION as V1010_R2_FOLLOWUP_ATTEMPT
EVOLUTIONS = (*EVOLUTIONS, V1010_R2_FOLLOWUP_ATTEMPT)

from .v1020_r2_quote_termination import EVOLUTION as V1020_R2_QUOTE_TERMINATION
EVOLUTIONS = (*EVOLUTIONS, V1020_R2_QUOTE_TERMINATION)

from .v1030_r2_contract_negotiation import EVOLUTION as V1030_R2_CONTRACT_NEGOTIATION
EVOLUTIONS = (*EVOLUTIONS, V1030_R2_CONTRACT_NEGOTIATION)

from .v1040_r2_execution_conditions import EVOLUTION as V1040_R2_EXECUTION_CONDITIONS
EVOLUTIONS = (*EVOLUTIONS, V1040_R2_EXECUTION_CONDITIONS)

from .v1050_r2_transfer_workflow import EVOLUTION as V1050_R2_TRANSFER_WORKFLOW
EVOLUTIONS = (*EVOLUTIONS, V1050_R2_TRANSFER_WORKFLOW)

from .v1060_r25_contract_responsibility_recovery import EVOLUTION as V1060_R25_CONTRACT_RESPONSIBILITY_RECOVERY
EVOLUTIONS = (*EVOLUTIONS, V1060_R25_CONTRACT_RESPONSIBILITY_RECOVERY)
