"""Add missing Chinese metadata; preserve all existing schema and function semantics."""
from dataclasses import replace
from ..model import ContractEvolution

COLUMN_COMMENT = '协商处置类型：未签终止、请求复核、复核后终止或继续协商。'
FUNCTION_COMMENTS = {'contract.fn_check_negotiation_complete': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_check_negotiation_disposition': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_check_negotiation_member': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_execution_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_fee_term_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_participation_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_revision_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_contract_signature_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_execution_basis_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_execution_workflow_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_payment_gate_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_payment_negotiation_lock': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_payment_request_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_payment_review_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_payment_workflow_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_preparation_decision_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_preparation_draft_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_preparation_request_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_preparation_workflow_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_approval_decision_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_approval_request_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_approval_requirement_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_clause_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_review_binding_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_review_decision_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_revision_review_request_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_archive_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_arrangement_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_draft_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_handoff_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_plan_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_readiness_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_revision_return_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_submission_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_verification_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_signature_workflow_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_transfer_negotiation_guard': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'contract.fn_transfer_negotiation_lock': '合同事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'opportunity.fn_check_quote_termination': '商机事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'opportunity.fn_check_quote_termination_current': '商机事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'responsibility.fn_check_contract_task_resumption': '责任事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'responsibility.fn_contract_task_negotiation_guard': '责任事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_classification_completion_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_classification_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_intake_completion_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_intake_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_reclassification_completion_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_review_completion_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_review_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_review_return_item_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_submission_completion_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_submission_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。',
 'transfer.fn_workflow_guard': '转案事实一致性守卫：按既有约束核对关联事实及流程状态。'}


TRIGGER_COMMENTS = {('trg_contract__negotiation_guard', 'contract.contract'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_execution__negotiation_guard', 'contract.contract_execution'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_fee_term__negotiation_guard', 'contract.contract_fee_term'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_participation__negotiation_guard', 'contract.contract_participation'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_revision__negotiation_guard', 'contract.contract_revision'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_signature__negotiation_guard', 'contract.contract_signature'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_task_resumption__exact', 'responsibility.contract_task_resumption'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_task_resumption__immutable', 'responsibility.contract_task_resumption'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_contract_task_resumption__transaction', 'responsibility.contract_task_resumption'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_verification__basis', 'contract.execution_verification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_verification__immutable', 'contract.execution_verification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_verification__transaction', 'contract.execution_verification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_workflow__basis', 'contract.execution_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_workflow__exact', 'contract.execution_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_workflow__immutable', 'contract.execution_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_execution_workflow__transaction', 'contract.execution_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_cancelled_task__current', 'contract.negotiation_cancelled_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_cancelled_task__immutable', 'contract.negotiation_cancelled_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_cancelled_task__transaction', 'contract.negotiation_cancelled_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_disposition__complete', 'contract.negotiation_disposition'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_disposition__current', 'contract.negotiation_disposition'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_disposition__immutable', 'contract.negotiation_disposition'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_negotiation_disposition__transaction', 'contract.negotiation_disposition'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment__negotiation_lock', 'contract.payment_confirmation'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_gate__negotiation_guard', 'contract.payment_gate'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_request__exact', 'contract.payment_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_request__immutable', 'contract.payment_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_request__transaction', 'contract.payment_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_review__exact', 'contract.payment_review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_review__immutable', 'contract.payment_review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_review__transaction', 'contract.payment_review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_workflow__exact', 'contract.payment_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_workflow__immutable', 'contract.payment_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_payment_workflow__transaction', 'contract.payment_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_preparation_decision__negotiation_guard', 'contract.preparation_decision'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_preparation_draft__negotiation_guard', 'contract.preparation_draft'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_preparation_request__negotiation_guard', 'contract.preparation_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_preparation_workflow__negotiation_guard', 'contract.preparation_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination__complete', 'opportunity.quote_termination'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination__current', 'opportunity.quote_termination'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination__immutable', 'opportunity.quote_termination'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination__transaction', 'opportunity.quote_termination'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination_task__complete', 'opportunity.quote_termination_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination_task__current', 'opportunity.quote_termination_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination_task__immutable', 'opportunity.quote_termination_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_quote_termination_task__transaction', 'opportunity.quote_termination_task'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_approval_decision__negotiation_guard', 'contract.revision_approval_decision'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_approval_request__negotiation_guard', 'contract.revision_approval_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_approval_requirement__negotiation_guard', 'contract.revision_approval_requirement'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_clause__negotiation_guard', 'contract.revision_clause'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_review_binding__negotiation_guard', 'contract.revision_review_binding'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_review_decision__negotiation_guard', 'contract.revision_review_decision'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_revision_review_request__negotiation_guard', 'contract.revision_review_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_archive__negotiation_guard', 'contract.signature_archive'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_arrangement__negotiation_guard', 'contract.signature_arrangement'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_draft__negotiation_guard', 'contract.signature_draft'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_handoff__negotiation_guard', 'contract.signature_handoff'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_plan__negotiation_guard', 'contract.signature_plan'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_readiness__negotiation_guard', 'contract.signature_readiness'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_revision_return__negotiation_guard', 'contract.signature_revision_return'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_submission__negotiation_guard', 'contract.signature_submission'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_verification__negotiation_guard', 'contract.signature_verification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_signature_workflow__negotiation_guard', 'contract.signature_workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_task__contract_negotiation_guard', 'responsibility.task_occurrence'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_task__negotiation_complete', 'responsibility.task_occurrence'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_task__quote_termination', 'responsibility.task_occurrence'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_termination_review_assignment__current', 'contract.termination_review_assignment'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_termination_review_assignment__immutable', 'contract.termination_review_assignment'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_termination_review_assignment__transaction', 'contract.termination_review_assignment'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer__negotiation_guard', 'transfer.transfer_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer__negotiation_lock', 'transfer.transfer_request'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_classification__completion', 'transfer.classification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_classification__exact', 'transfer.classification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_classification__immutable', 'transfer.classification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_classification__transaction', 'transfer.classification'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_intake__completion', 'transfer.intake'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_intake__exact', 'transfer.intake'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_intake__immutable', 'transfer.intake'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_intake__transaction', 'transfer.intake'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review__completion', 'transfer.review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review__exact', 'transfer.review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review__immutable', 'transfer.review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review__transaction', 'transfer.review'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review_return_item__exact', 'transfer.review_return_item'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review_return_item__immutable', 'transfer.review_return_item'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_review_return_item__transaction', 'transfer.review_return_item'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_submission__completion', 'transfer.submission'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_submission__exact', 'transfer.submission'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_submission__immutable', 'transfer.submission'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_submission__transaction', 'transfer.submission'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_workflow__exact', 'transfer.workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_workflow__immutable', 'transfer.workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_workflow__reclassification', 'transfer.workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。',
 ('trg_transfer_workflow__transaction', 'transfer.workflow'): '按既有触发时点验证事实一致性、不可变性及准确流程依据。'}

ARGUMENT_FUNCTION_COMMENTS = {
    'contract.fn_assert_manual_execution(contract.contract_execution)': '人工履行条件守卫：验证既有合同执行事实的准确签署、材料及流程依据。',
}


def apply_evolution(schemas):
    return tuple(replace(schema, tables=tuple(
        replace(table, columns=tuple(replace(column, comment=COLUMN_COMMENT)
            if schema.name == 'contract' and table.name == 'negotiation_disposition' and column.name == 'kind'
            else column for column in table.columns)) for table in schema.tables)) for schema in schemas)


def render_sql(before, after):
    comments = [f"COMMENT ON FUNCTION {name}() IS '{comment}';" for name, comment in FUNCTION_COMMENTS.items()]
    comments.extend(f"COMMENT ON FUNCTION {signature} IS '{comment}';" for signature, comment in ARGUMENT_FUNCTION_COMMENTS.items())
    comments.extend(f"COMMENT ON TRIGGER {trigger} ON {table} IS '{comment}';" for (trigger, table), comment in TRIGGER_COMMENTS.items())
    comments.append(f"COMMENT ON COLUMN contract.negotiation_disposition.kind IS '{COLUMN_COMMENT}';")
    return '\n'.join(comments) + '\n' + """DO $v1080$ BEGIN
 UPDATE platform_meta.deployment_state SET schema_contract_version='52-plus-2-r2-v22',revision=revision+1,changed_at=clock_timestamp() WHERE deployment_state_key='PRIMARY' AND schema_contract_version='52-plus-2-r2-v21';
 IF NOT FOUND THEN RAISE EXCEPTION 'V1080 requires 52-plus-2-r2-v21' USING ERRCODE='55000'; END IF;
END;$v1080$;
"""


EVOLUTION = ContractEvolution(version=1080, migration_name='V1080__metadata_comments.sql',
    contract_version='52-plus-2-r2-v22', apply=apply_evolution, render_sql=render_sql)
