import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {WaitingSummary} from './WaitingSummary';
import {testSession,deferred} from '../../test/fixtures';
const id='10000000-0000-4000-8000-000000000001';
const row={id,customerLabel:'合成客户',purposeLabel:'按约联系',state:'WAIT_FUTURE' as const,reason:'等待约定时间',resumeAt:'2026-09-30T02:00:00Z'};
const detail={...row,ownerLabel:'本人 · 销售',nextAction:'到期核对',canHandle:false,history:[{label:'形成责任',at:'2026-09-29T01:00:00Z'}]};
function fixture(){return {api:{list:vi.fn().mockResolvedValue({waitingItems:[row],totalCount:1,nextCursor:null,asOf:'2026-09-29T01:00:00Z'}),detail:vi.fn().mockResolvedValue({waitingDetail:detail,totalCount:1})},session:testSession(),onSelect:vi.fn(),onNavigate:vi.fn((next:()=>void)=>next()),blocked:false,count:1,next:[]};}
it('opens readonly details on demand without selecting the workcard',async()=>{const p=fixture();render(<WaitingSummary {...p}/>);expect(p.api.list).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:/合成客户/}));expect(await screen.findByText('到期核对')).toBeVisible();expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:/收起/}));expect(screen.queryByText('到期核对')).toBeNull();expect(p.onSelect).not.toHaveBeenCalled();});
it('shows failed count as unknown and retries',async()=>{const p=fixture();p.api.list.mockRejectedValueOnce(Error('offline'));render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));expect(await screen.findByRole('alert')).toBeVisible();expect(screen.getByRole('button',{name:/等待 — 项/})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'重新查询'}));expect(await screen.findByRole('button',{name:/合成客户/})).toBeVisible();});
it('rechecks the target after the draft guard allows navigation',async()=>{const p=fixture();p.api.detail.mockResolvedValue({waitingDetail:{...detail,state:'READY',canHandle:true},totalCount:0});let leave:(()=>void)|undefined;p.onNavigate.mockImplementation(next=>{leave=next;});render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:/合成客户/}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));expect(p.api.detail).toHaveBeenCalledTimes(1);expect(p.onSelect).not.toHaveBeenCalled();leave!();await waitFor(()=>expect(p.onSelect).toHaveBeenCalledWith(id));expect(p.api.detail).toHaveBeenCalledTimes(2);});
it('clears revoked details instead of navigating',async()=>{const p=fixture();p.api.detail.mockResolvedValueOnce({waitingDetail:{...detail,state:'READY',canHandle:true},totalCount:0}).mockRejectedValueOnce(Error('revoked'));render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:/合成客户/}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));expect(await screen.findByRole('alert')).toBeVisible();expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();expect(p.onSelect).not.toHaveBeenCalled();});

it('rejects late responses after changing the selected appointment',async()=>{const p=fixture(),late=deferred<any>();p.api.list.mockReturnValueOnce(late.promise);const r=render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));r.rerender(<WaitingSummary {...p} session={{...p.session,identityEpoch:99,actorScopeKey:'changed'}}/>);await act(async()=>late.resolve({waitingItems:[row],totalCount:1,nextCursor:null,asOf:'2026-09-29T01:00:00Z'}));expect(screen.queryByRole('button',{name:/合成客户/})).toBeNull();});
it('paginates without dropping existing rows and distinguishes true empty results',async()=>{const p=fixture();p.api.list.mockResolvedValueOnce({waitingItems:[row],totalCount:2,nextCursor:'next',asOf:'2026-09-29T01:00:00Z'}).mockResolvedValueOnce({waitingItems:[{...row,id:'20000000-0000-4000-8000-000000000001',customerLabel:'第二客户'}],totalCount:2,nextCursor:null,asOf:'2026-09-29T01:00:00Z'});render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:'加载更多等待事项'}));expect(await screen.findByRole('button',{name:/第二客户/})).toBeVisible();expect(screen.getByRole('button',{name:/合成客户/})).toBeVisible();expect(screen.getByRole('button',{name:/等待 2 项/})).toBeVisible();});
it('keeps blocked writes from entering a ready task',async()=>{const p=fixture();p.api.detail.mockResolvedValue({waitingDetail:{...detail,state:'READY',canHandle:true},totalCount:0});render(<WaitingSummary {...p} blocked/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:/合成客户/}));expect(await screen.findByRole('button',{name:'前往办理'})).toBeDisabled();expect(p.onSelect).not.toHaveBeenCalled();});
it('shows a successful empty list as zero',async()=>{const p=fixture();p.api.list.mockResolvedValue({waitingItems:[],totalCount:0,nextCursor:null,asOf:'2026-09-29T01:00:00Z'});render(<WaitingSummary {...p}/>);fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));expect(await screen.findByText('当前任职没有等待事项。')).toBeVisible();expect(screen.getByRole('button',{name:/等待 0 项/})).toBeVisible();});
