package io.github.windyzhu3.ontologylaw.worker;
import java.util.*;import java.time.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class ContractPreparationCheckpointTest {
 @Test void production_checkpoint_key_accepts_contract_scan(){assertDoesNotThrow(()->new io.github.windyzhu3.ontologylaw.execution.R2OpportunityCheckpointPort.Key(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),"CONTRACT_PREPARATION"));}
 @Test void authority_return_checkpoint_preserves_discriminator_and_exact_head()throws Exception{var head=UUID.randomUUID();var c=new InternalApiClient.ContractPreparationCandidate(UUID.fromString("6ba7b810-9dad-51d1-80b4-00c04fd430c8"),UUID.randomUUID(),0,UUID.randomUUID(),0,head,head,"AUTHORITY_RETURN");var state=new R2OpportunityTaskScheduler.State();state.page=new InternalApiClient.OpportunityPage(200,List.of(c),null);state.active=true;var restored=new R2OpportunityTaskScheduler.State();R2OpportunityCheckpointCodec.restore(restored,R2OpportunityCheckpointCodec.encode(state,c.kind()),c.kind());assertEquals(c,restored.page.candidates().getFirst());assertThrows(IllegalArgumentException.class,()->new InternalApiClient.ContractPreparationCandidate(c.idempotencyKey(),c.opportunityId(),0,c.basisId(),0,head,UUID.randomUUID(),"AUTHORITY_RETURN"));}
 @Test void restart_keeps_exact_source_basis_workflow_and_uncertain_command()throws Exception{var s=new R2OpportunityTaskScheduler.State();var candidate=new InternalApiClient.ContractPreparationCandidate(UUID.fromString("6ba7b810-9dad-51d1-80b4-00c04fd430c8"),UUID.randomUUID(),2,UUID.randomUUID(),0,UUID.randomUUID(),UUID.randomUUID());s.page=new InternalApiClient.OpportunityPage(200,List.of(candidate),"cursor");s.active=true;s.uncertain=true;s.retryAt=Instant.parse("2026-09-21T00:00:00Z");s.publish(R2OpportunityTaskScheduler.Status.RETRY_WAIT);var bytes=R2OpportunityCheckpointCodec.encode(s,candidate.kind());var restored=new R2OpportunityTaskScheduler.State();R2OpportunityCheckpointCodec.restore(restored,bytes,candidate.kind());assertEquals(candidate,restored.page.candidates().getFirst());assertTrue(restored.uncertain);assertEquals(s.retryAt,restored.retryAt);bytes[10]^=1;assertThrows(java.io.IOException.class,()->R2OpportunityCheckpointCodec.restore(new R2OpportunityTaskScheduler.State(),bytes,candidate.kind()));}
 @Test void termination_review_restart_preserves_independent_request_and_assignment()throws Exception{var candidate=new InternalApiClient.ContractPreparationCandidate(UUID.fromString("6ba7b810-9dad-51d1-80b4-00c04fd430c8"),UUID.randomUUID(),0,UUID.randomUUID(),0,UUID.randomUUID(),UUID.randomUUID(),"TERMINATION_REVIEW");var state=new R2OpportunityTaskScheduler.State();state.page=new InternalApiClient.OpportunityPage(200,List.of(candidate),null);state.active=true;state.uncertain=true;var restored=new R2OpportunityTaskScheduler.State();R2OpportunityCheckpointCodec.restore(restored,R2OpportunityCheckpointCodec.encode(state,candidate.kind()),candidate.kind());assertEquals(candidate,restored.page.candidates().getFirst());assertTrue(restored.uncertain);assertThrows(IllegalArgumentException.class,()->new InternalApiClient.ContractPreparationCandidate(candidate.idempotencyKey(),candidate.opportunityId(),0,candidate.basisId(),0,candidate.sourceId(),null,"TERMINATION_REVIEW"));}

}
