package io.github.windyzhu3.ontologylaw.evidence.internal.persistence;
import io.github.windyzhu3.ontologylaw.evidence.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.sql.*;import java.time.*;import java.util.*;import java.security.*;
public final class JdbcMaterialEvidence implements MaterialEvidence {
 private final MaterialProtection cipher;private final Codec codec;
 public JdbcMaterialEvidence(MaterialProtection cipher,Codec codec){this.cipher=cipher;this.codec=codec;}
 private static final String SELECT="select b.*,s.expires_at,s.purpose_code,s.status,s.object_key,r.received_source_object_id,r.object_version,r.server_sha256,r.size_bytes,r.detected_media_type,k.status as check_status,k.result_code from evidence.material_upload_basis b join evidence.upload_session s on s.tenant_id=b.tenant_id and s.upload_session_id=b.upload_session_id left join evidence.received_source_object r on r.tenant_id=b.tenant_id and r.upload_session_id=b.upload_session_id left join evidence.material_upload_check k on k.tenant_id=b.tenant_id and k.upload_basis_id=b.material_upload_basis_id and not exists(select 1 from evidence.material_upload_check n where n.tenant_id=k.tenant_id and n.previous_check_id=k.material_upload_check_id) ";
 private static Subject exact(String type,UUID id){return id==null?null:new Subject(type,id,0L,null);}
 private static Basis row(ResultSet r)throws SQLException {var bytes=r.getBytes("server_sha256");String ov=r.getString("object_version");return new Basis(exact(BASIS,r.getObject("material_upload_basis_id",UUID.class)),new Subject("opportunity.opportunity",r.getObject("opportunity_id",UUID.class),r.getLong("opportunity_revision"),null),new Subject(r.getString("responsibility_type"),r.getObject("responsibility_id",UUID.class),r.getLong("responsibility_revision"),null),r.getObject("owner_appointment_id",UUID.class),exact("opportunity.customer_requirement_confirmation",r.getObject("customer_confirmation_id",UUID.class)),exact("opportunity.material_version",r.getObject("expected_previous_version_id",UUID.class)),r.getObject("created_at",OffsetDateTime.class).toInstant(),r.getObject("expires_at",OffsetDateTime.class).toInstant(),r.getString("purpose_code"),r.getString("status"),r.getString("check_status"),r.getString("result_code"),r.getObject("received_source_object_id",UUID.class),ov==null?null:UUID.fromString(ov),bytes==null?null:HexFormat.of().formatHex(bytes),(Long)r.getObject("size_bytes"),r.getString("detected_media_type"));}
 public ProtectedBody protectedBody(Connection c,UUID tenant,UUID basis)throws SQLException{try(var p=c.prepareStatement("select body_ciphertext,body_digest from evidence.material_upload_basis where tenant_id=? and material_upload_basis_id=?")){bind(p,tenant,basis);try(var r=p.executeQuery()){if(!r.next())throw new SQLException("Missing material basis");return new ProtectedBody(r.getBytes(1),r.getBytes(2));}}}
 public Basis basis(Connection c,UUID tenant,UUID id)throws SQLException {try(var p=c.prepareStatement(SELECT+"where b.tenant_id=? and b.material_upload_basis_id=?")){bind(p,tenant,id);try(var r=p.executeQuery()){return r.next()?row(r):null;}}}
 public List<Basis> pending(Connection c,UUID tenant,UUID opportunity,UUID owner)throws SQLException{var out=new ArrayList<Basis>();try(var p=c.prepareStatement(SELECT+"where b.tenant_id=? and b.opportunity_id=? and b.owner_appointment_id=? and s.status<>'FINALIZED' order by b.created_at desc")){bind(p,tenant,opportunity,owner);try(var r=p.executeQuery()){while(r.next())out.add(row(r));}}return List.copyOf(out);}
 public Basis open(Connection c,UUID tenant,Subject opportunity,Subject responsibility,UUID owner,Subject confirmation,Subject previous,String purpose,String fileName,String note)throws SQLException{var id=UUID.randomUUID();var doc=new LinkedHashMap<String,Object>();doc.put("fileName",fileName);doc.put("note",note);String body=codec.encode(doc);byte[] cap=new byte[32];new SecureRandom().nextBytes(cap);
  update(c,"insert into evidence.upload_session(tenant_id,upload_session_id,object_store_code,object_key,purpose_code,intake_contract_code,intake_contract_version,intake_contract_digest,upload_capability_hash,status,created_by_appointment_id,created_at,expires_at,revision,target_type,target_id,target_revision) values(?,?,'LOCAL_PRIVATE',?,?,'R2_MATERIAL_V1',1,?,?,'OPEN',?,clock_timestamp(),clock_timestamp()+interval '30 minutes',0,?,?,?)",tenant,id,UUID.randomUUID().toString(),purpose,digest("R2_MATERIAL_V1:PDF,JPEG,PNG:20971520:SCAN_REQUIRED"),cap,owner,opportunity.type(),opportunity.id(),opportunity.revision());
  update(c,"insert into evidence.material_upload_basis(tenant_id,material_upload_basis_id,revision,upload_session_id,opportunity_id,opportunity_revision,responsibility_type,responsibility_id,responsibility_revision,owner_appointment_id,customer_confirmation_id,expected_previous_version_id,body_ciphertext,body_digest,created_at) values(?,?,0,?,?,?,?,?,?,?,?,?,?,?,clock_timestamp())",tenant,id,id,opportunity.id(),opportunity.revision(),responsibility.type(),responsibility.id(),responsibility.revision(),owner,confirmation==null?null:confirmation.id(),previous==null?null:previous.id(),cipher.encrypt(tenant,opportunity.id(),id,body),digest(body));return basis(c,tenant,id);
 }
 public Map<String,Object> body(Connection c,UUID tenant,Basis b)throws SQLException{try(var p=c.prepareStatement("select body_ciphertext,body_digest from evidence.material_upload_basis where tenant_id=? and material_upload_basis_id=?")){bind(p,tenant,b.selector().id());try(var r=p.executeQuery()){if(!r.next())throw new SQLException("Missing upload metadata");try{String s=cipher.decrypt(tenant,b.opportunity().id(),b.selector().id(),r.getBytes(1));if(!MessageDigest.isEqual(digest(s),r.getBytes(2)))throw new IllegalArgumentException();return codec.decode(s);}catch(RuntimeException e){throw new SQLException("Invalid protected upload metadata","22000");}}}}
 public UUID beginCheck(Connection c,UUID tenant,Basis b)throws SQLException{var id=UUID.randomUUID();update(c,"insert into evidence.material_upload_check(tenant_id,material_upload_check_id,revision,upload_basis_id,status,created_at) values(?,?,0,?,'CHECKING',clock_timestamp())",tenant,id,b.selector().id());return id;}
 public void completeCheck(Connection c,UUID tenant,Basis b,UUID check,MaterialObjectStore.StoredObject stored,String status,String reason)throws SQLException{if(stored!=null){var received=UUID.randomUUID();update(c,"update evidence.upload_session set status='OBJECT_RECEIVED',received_at=clock_timestamp(),revision=revision+1 where tenant_id=? and upload_session_id=? and status='OPEN'",tenant,b.selector().id());update(c,"insert into evidence.received_source_object(tenant_id,received_source_object_id,upload_session_id,object_store_code,object_key,object_version,size_bytes,server_sha256,detected_media_type,scan_result,scan_engine_code,scan_contract_version,scanned_at,received_at) select ?,?,?,object_store_code,object_key,?,?,?,?,'PASSED',?,1,clock_timestamp(),received_at from evidence.upload_session where tenant_id=? and upload_session_id=?",tenant,received,b.selector().id(),stored.objectVersion().toString(),stored.byteSize(),HexFormat.of().parseHex(stored.sha256()),stored.mediaType(),stored.scannerEngine(),tenant,b.selector().id());}
  update(c,"insert into evidence.material_upload_check(tenant_id,material_upload_check_id,revision,upload_basis_id,previous_check_id,status,result_code,created_at) values(?,?,0,?,?,?,?,clock_timestamp())",tenant,UUID.randomUUID(),b.selector().id(),check,status,reason);
 }
 public Submission accept(Connection c,UUID tenant,Basis b)throws SQLException{if(!"OBJECT_RECEIVED".equals(b.state())||!"PASSED".equals(b.checkState())||b.receivedObject()==null)throw new SQLException("Material not checked","22000");var submission=UUID.randomUUID();var binding=UUID.randomUUID();Instant at;try(var p=c.prepareStatement("select clock_timestamp()")){try(var r=p.executeQuery()){r.next();at=r.getObject(1,OffsetDateTime.class).toInstant();}}var date=OffsetDateTime.ofInstant(at,ZoneOffset.UTC);
  update(c,"insert into evidence.evidence_submission(tenant_id,evidence_submission_id,received_source_object_id,submission_contract_code,submission_contract_version,submitted_by_appointment_id,submitted_at) values(?,?,?,'R2_MATERIAL_V1',1,?,?)",tenant,submission,b.receivedObject(),b.owner(),date);
  update(c,"insert into evidence.evidence_binding(tenant_id,evidence_binding_id,evidence_submission_id,purpose_code,bound_by_appointment_id,bound_at,revision,target_type,target_id,target_revision) values(?,?,?,?,?,?,0,?,?,?)",tenant,binding,submission,b.purpose(),b.owner(),date,b.opportunity().type(),b.opportunity().id(),b.opportunity().revision());
  update(c,"update evidence.upload_session set status='FINALIZED',finalized_at=?,revision=revision+1 where tenant_id=? and upload_session_id=? and status='OBJECT_RECEIVED'",date,tenant,b.selector().id());return new Submission(b.receivedObject(),submission,binding,at);
 }
 private static void bind(PreparedStatement p,Object...args)throws SQLException{for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);}
 private static void update(Connection c,String sql,Object...args)throws SQLException{try(var p=c.prepareStatement(sql)){bind(p,args);if(p.executeUpdate()!=1)throw new SQLException("Material state changed","40001");}}
 private static byte[] digest(String s){try{return MessageDigest.getInstance("SHA-256").digest(s.getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}


