package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class ContractPreparationRecoveryProtocolTest {
 @Test void authority_return_requires_exact_head_and_has_distinct_idempotency_scope(){var p=payload();var accepted=R2ContractRecoveryCommand.input(envelope(p));p.put("sourceKind","AUTHORITY_RETURN");assertThrows(CommandHandler.Rejected.class,()->R2ContractRecoveryCommand.input(envelope(p)));p.put("expectedWorkflow",p.get("source"));var returned=R2ContractRecoveryCommand.input(envelope(p));assertEquals("contract.preparation_workflow",returned.source().type());assertEquals(returned.source(),returned.workflow());assertNotEquals(ContractPreparationDiscovery.commandId(tenant,accepted),ContractPreparationDiscovery.commandId(tenant,returned));}
 private final UUID tenant=UUID.randomUUID(),id=UUID.randomUUID();private final Actor actor=new Actor(tenant,UUID.randomUUID(),UUID.randomUUID(),null,null,PrincipalKind.SERVICE);
 private Map<String,Object> payload(){var p=new LinkedHashMap<String,Object>();p.put("opportunityId",id.toString());p.put("expectedOpportunityRevision",1L);p.put("responsibilityBasis",Map.of("id",id.toString(),"revision",1L));p.put("sourceKind","ACCEPTED_QUOTE");p.put("source",Map.of("id",UUID.randomUUID().toString(),"revision",0L));p.put("expectedWorkflow",null);return p;}
 private CommandEnvelope envelope(Map<String,Object> p){return new CommandEnvelope(CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION,UUID.randomUUID(),UUID.randomUUID(),actor,p);}
 @Test void key_is_stable_for_exact_source_and_changes_when_exception_is_repaired(){var p=payload();var b=R2ContractRecoveryCommand.input(envelope(p));var key=ContractPreparationDiscovery.commandId(tenant,b);assertEquals(5,key.version());assertEquals(key,ContractPreparationDiscovery.commandId(tenant,R2ContractRecoveryCommand.input(envelope(p))));p.put("expectedWorkflow",Map.of("id",UUID.randomUUID().toString(),"revision",0L));assertNotEquals(key,ContractPreparationDiscovery.commandId(tenant,R2ContractRecoveryCommand.input(envelope(p))));}
 @Test void human_and_forged_source_revision_are_rejected(){var p=payload();var human=new Actor(tenant,UUID.randomUUID(),UUID.randomUUID(),null,null,PrincipalKind.HUMAN);assertThrows(IllegalArgumentException.class,()->new CommandEnvelope(CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION,UUID.randomUUID(),UUID.randomUUID(),human,p));p.put("source",Map.of("id",UUID.randomUUID().toString(),"revision",1L));assertThrows(CommandHandler.Rejected.class,()->R2ContractRecoveryCommand.input(envelope(p)));}
}
