package io.github.windyzhu3.ontologylaw.api;
import static org.junit.jupiter.api.Assertions.*;
import io.github.windyzhu3.ontologylaw.execution.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;import java.io.*;import java.lang.reflect.*;
import org.junit.jupiter.api.Test;import org.springframework.core.MethodParameter;import org.springframework.beans.factory.support.DefaultListableBeanFactory;import org.springframework.mock.web.MockHttpServletRequest;import org.springframework.http.*;
class ContractHttpBoundaryTest {
 @Test void contract_ledger_accepts_only_its_single_valued_query_parameters()throws Throwable {
  var beans=new DefaultListableBeanFactory();var target=new R1RequestBoundary(beans.getBeanProvider(R1ApiServices.class),beans.getBeanProvider(IdentityAdminController.Services.class));
  var method=R1RequestBoundary.class.getDeclaredMethod("check",jakarta.servlet.http.HttpServletRequest.class);method.setAccessible(true);
  var request=new MockHttpServletRequest("GET","/api/v1/contracts");request.addParameter("limit","20");request.addParameter("search","合成客户");request.addParameter("state","待审批");request.addParameter("cursor","opaque");
  assertDoesNotThrow(()->method.invoke(target,request));
  for(String bad:List.of("tenantId","appointmentId","limit")) {
   var invalid=new MockHttpServletRequest("GET","/api/v1/contracts");invalid.addParameter(bad,"one","two");
   var error=assertThrows(InvocationTargetException.class,()->method.invoke(target,invalid));assertInstanceOf(R1HttpFailure.class,error.getCause());
  }
  var detail=new MockHttpServletRequest("GET","/api/v1/opportunities/"+UUID.randomUUID()+"/contracts");detail.addParameter("search","not-a-list");
  assertInstanceOf(R1HttpFailure.class,assertThrows(InvocationTargetException.class,()->method.invoke(target,detail)).getCause());
 }
 @Test void generation_is_a_registered_read_operation_without_a_command_receipt(){var op=R1HttpOperations.find("POST","/api/v1/opportunities/"+UUID.randomUUID()+"/contracts/generate");assertNotNull(op);assertNull(op.command());assertTrue(op.errors().contains("CONTRACT_VERSION_BASIS_CHANGED"));}
 private void boundary(String path)throws Throwable{var beans=new DefaultListableBeanFactory();var target=new R1RequestBoundary(beans.getBeanProvider(R1ApiServices.class),beans.getBeanProvider(IdentityAdminController.Services.class));var request=new MockHttpServletRequest("POST",path);request.addHeader("Idempotency-Key",UUID.randomUUID().toString());var method=R1RequestBoundary.class.getDeclaredMethod("check",jakarta.servlet.http.HttpServletRequest.class);method.setAccessible(true);try{method.invoke(target,request);}catch(InvocationTargetException e){throw e.getCause();}}
 private byte[] body(Map<String,Object> value,boolean internal)throws Exception{var method=internal?R2OpportunityInternalDelegate.class.getMethod("reconcileContractPreparation",UUID.class,io.github.windyzhu3.ontologylaw.api.adapter.generated.model.ReconcileContractPreparationV1.class):R2ContractApiDelegate.class.getMethod("command",UUID.class,String.class,UUID.class,UUID.class,Map.class);byte[] bytes=CanonicalJson.encode(value).getBytes(java.nio.charset.StandardCharsets.UTF_8);var input=new HttpInputMessage(){public HttpHeaders getHeaders(){return new HttpHeaders();}public InputStream getBody(){return new ByteArrayInputStream(bytes);}};return new R1RequestBodyValidation().beforeBodyRead(input,new MethodParameter(method,internal?1:4),Map.class,null).getBody().readAllBytes();}
 private Map<String,Object> payload(){var p=new LinkedHashMap<String,Object>();p.put("expectedOpportunityRevision",0L);p.put("responsibilityBasis",Map.of("id",UUID.randomUUID().toString(),"revision",0L));for(String field:List.of("customerConfirmation","expectedContract","expectedDraft","expectedVersion","expectedWorkflow"))p.put(field,null);p.put("values",Map.of());return p;}
 @Test void all_nine_actions_use_exact_body_selectors_without_task_etag()throws Throwable{for(String action:List.of("preparation-requests","preparation-decisions","start","draft","form","review-requests","review-decisions","approval-requests","decisions")){boundary("/api/v1/opportunities/"+UUID.randomUUID()+"/contracts/"+action);assertDoesNotThrow(()->body(payload(),false));}}
 @Test void registered_content_nulls_pass_but_arbitrary_null_does_not()throws Exception{var p=payload();var values=new LinkedHashMap<String,Object>();values.put("commercial",Collections.singletonMap("conditionalFee",null));values.put("paymentGate",Collections.singletonMap("requiredMinor",null));p.put("values",values);assertDoesNotThrow(()->body(p,false));values.put("reason",null);assertThrows(R1HttpFailure.class,()->body(p,false));}
 @Test void service_reconcile_accepts_explicit_null_workflow_without_human_task_preconditions()throws Throwable{boundary("/internal/v1/opportunity-tasks/commands/reconcile-contract-preparation");var p=new LinkedHashMap<String,Object>();p.put("opportunityId",UUID.randomUUID().toString());p.put("expectedOpportunityRevision",0L);p.put("responsibilityBasis",Map.of("id",UUID.randomUUID().toString(),"revision",0L));p.put("source",Map.of("id",UUID.randomUUID().toString(),"revision",0L));p.put("sourceKind","ACCEPTED_QUOTE");p.put("expectedWorkflow",null);assertDoesNotThrow(()->body(p,true));}
 @Test void version_alias_is_normalized_only_for_owner_execution_and_preserves_original_payload(){var p=payload();UUID opportunity=UUID.fromString((String)((Map<?,?>)p.get("responsibilityBasis")).get("id"));p.put("opportunityId",opportunity.toString());String hex="ab".repeat(32),hash=Base64.getUrlEncoder().withoutPadding().encodeToString(HexFormat.of().parseHex(hex));p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"hash",hash));var actor=new Actor(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),null,null);var e=new CommandEnvelope(CommandEnvelope.Type.FORM_CONTRACT,UUID.randomUUID(),UUID.randomUUID(),actor,p);assertEquals(hex,((Map<?,?>)R2ContractInput.ownerPayload(e).get("expectedVersion")).get("hash"));assertEquals(hash,((Map<?,?>)((Map<?,?>)e.payload()).get("expectedVersion")).get("hash"));p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"hash",hex.toUpperCase(Locale.ROOT)));assertThrows(CommandHandler.Rejected.class,()->R2ContractInput.parse(new CommandEnvelope(CommandEnvelope.Type.FORM_CONTRACT,UUID.randomUUID(),UUID.randomUUID(),actor,p)));}
 @Test void execution_verification_uses_the_same_closed_command_boundary()throws Throwable {
  String path="/api/v1/opportunities/"+UUID.randomUUID()+"/contracts/execution-verifications";
  var operation=R1HttpOperations.find("POST",path);assertNotNull(operation);assertEquals(CommandEnvelope.Type.VERIFY_CONTRACT_EXECUTION_CONDITIONS,operation.command());
  boundary(path);var p=payload();p.put("values",Map.of("expectedExecutionWorkflow",Map.of("id",UUID.randomUUID().toString(),"revision",0L),"approvedConditionsChecked",true,"archiveAndConditionsComplete",true));
  assertDoesNotThrow(()->body(p,false));
 }
 @Test void execution_fact_is_projected_by_the_public_original_receipt_endpoint(){
  for(String type:List.of("CONTRACT_EXECUTION_VERIFICATION","CONTRACT_EXECUTION_WORKFLOW"))assertDoesNotThrow(()->R1WireModels.fact(Map.of("factType",type,"factRef",UUID.randomUUID().toString(),"revision",0L)));
 }

 @Test void finance_recovery_is_distinct_from_execution_recovery_for_the_same_contract(){var tenant=UUID.randomUUID();var opportunity=new Subject("opportunity.opportunity",UUID.randomUUID(),0L,null);var archive=new Subject("contract.signature_archive",UUID.randomUUID(),0L,null);var finance=new CommandAuthorizationBinding.ContractRecovery(opportunity,opportunity,archive,null);assertEquals("PAYMENT_HANDOFF",finance.sourceKind());assertEquals("contract.payment_workflow",finance.resultType());assertDoesNotThrow(()->CommandScope.contractRecovery(tenant,finance));}
 @Test void finance_recovery_receipt_binds_its_named_public_fact(){var body=Map.of("commandId",UUID.randomUUID().toString(),"receiptId",UUID.randomUUID().toString(),"outcome","SUCCEEDED","completedAt","2026-09-27T01:00:00Z","resultFact",Map.of("factType","CONTRACT_PAYMENT_WORKFLOW","factRef","opaque-payment-workflow-reference","revision",0));assertDoesNotThrow(()->R1WireModels.model(body,io.github.windyzhu3.ontologylaw.api.adapter.generated.model.ContractPreparationReconcileReceiptV1.class));assertDoesNotThrow(()->R1WireModels.receipt(body));}
 @Test void finance_commands_have_independent_authority_and_named_results(){for(var command:List.of("REQUEST_CONTRACT_RECEIPT_REVIEW","RECORD_CONTRACT_RECEIPT_REVIEW","SUPPLEMENT_CONTRACT_RECEIPT")){var type=CommandEnvelope.Type.valueOf(command);assertTrue(type.contracts());assertEquals(command.equals("RECORD_CONTRACT_RECEIPT_REVIEW")?"PAYMENT_CONFIRM":"PAYMENT_SUBMIT",R1CommandPolicy.contractAuthority(type));assertEquals(command.equals("REQUEST_CONTRACT_RECEIPT_REVIEW")?"contract.payment_request":"contract.payment_review",R1CommandPolicy.contractResultType(type));assertNotNull(R1EventPolicy.contractEvent(type));}}
 @Test void finance_http_paths_register_the_exact_commands(){for(var pair:Map.of("receipt-review-requests","REQUEST_CONTRACT_RECEIPT_REVIEW","receipt-reviews","RECORD_CONTRACT_RECEIPT_REVIEW","receipt-supplements","SUPPLEMENT_CONTRACT_RECEIPT").entrySet()){var operation=R1HttpOperations.find("POST","/api/v1/opportunities/"+UUID.randomUUID()+"/contracts/"+pair.getKey());assertNotNull(operation);assertEquals(pair.getValue(),operation.command().name());}}
}
