package io.github.windyzhu3.ontologylaw.api;
import static org.junit.jupiter.api.Assertions.*;import java.util.*;import org.junit.jupiter.api.Test;import tools.jackson.databind.json.JsonMapper;
class CustomerRequirementsJsonTest {
 final JsonMapper mapper=JsonMapper.builder().build();
 Map<String,Object> payload(){var p=new LinkedHashMap<String,Object>();p.put("expectedOpportunityRevision",0);p.put("responsibilityBasis",Map.of("id",UUID.randomUUID().toString(),"revision",0));p.put("expectedDraft",null);p.put("expectedConfirmation",null);var row=new LinkedHashMap<String,Object>();row.put("role","CLIENT");row.put("party",null);row.put("newParty",Map.of("kind","NATURAL_PERSON","name","","distinctIdentityConfirmed",false));row.put("profileChange",null);p.put("document",new LinkedHashMap<>(Map.of("participants",List.of(row),"unknownOpponent",true,"matterName","","customerGoal","","serviceScope","","knownConstraints","","contactName","","contactPhone","")));return p;}
 @Test void exact_nullable_draft_and_participant_fields_are_accepted(){var p=payload();assertDoesNotThrow(()->R2CustomerRequirementsJson.validate(mapper.valueToTree(p),true));}
 @SuppressWarnings("unchecked") @Test void missing_nullable_fields_are_not_invented_by_dto_binding(){for(var key:List.of("expectedDraft","expectedConfirmation")){var p=payload();p.remove(key);assertThrows(R1HttpFailure.class,()->R2CustomerRequirementsJson.validate(mapper.valueToTree(p),true));}var p=payload();var doc=(Map<String,Object>)p.get("document");var row=(Map<String,Object>)((List<?>)doc.get("participants")).getFirst();row.remove("party");assertThrows(R1HttpFailure.class,()->R2CustomerRequirementsJson.validate(mapper.valueToTree(p),true));}
 @SuppressWarnings("unchecked") @Test void unrelated_nulls_and_null_confirmation_draft_are_rejected(){var p=payload();((Map<String,Object>)p.get("document")).put("matterName",null);assertThrows(R1HttpFailure.class,()->R2CustomerRequirementsJson.validate(mapper.valueToTree(p),true));var confirmation=payload();confirmation.remove("document");assertThrows(R1HttpFailure.class,()->R2CustomerRequirementsJson.validate(mapper.valueToTree(confirmation),false));confirmation.put("expectedDraft",Map.of("id",UUID.randomUUID().toString(),"revision",0));assertDoesNotThrow(()->R2CustomerRequirementsJson.validate(mapper.valueToTree(confirmation),false));}
 @Test void command_receipt_selects_only_its_two_named_fact_variants(){for(var kind:List.of("OPPORTUNITY_CUSTOMER_DRAFT","OPPORTUNITY_CUSTOMER_CONFIRMATION")){var body=Map.of("commandId",UUID.randomUUID().toString(),"receiptId",UUID.randomUUID().toString(),"outcome","SUCCEEDED","completedAt","2026-09-18T10:00:00Z","resultFact",Map.of("factType",kind,"factRef","opaque-customer-fact-reference","revision",0));assertDoesNotThrow(()->R1WireModels.model(body,io.github.windyzhu3.ontologylaw.api.adapter.generated.model.OpportunityCustomerCommandReceiptV1.class));}}
 @Test void response_omits_only_optional_absent_fields_and_keeps_required_nullable_basis(){var json=JsonMapper.builder().addModule(R1JsonConfiguration.oneOfModule()).build();var ctx=new io.github.windyzhu3.ontologylaw.api.adapter.generated.model.OpportunityCustomerContextV1();ctx.setSource(new io.github.windyzhu3.ontologylaw.api.adapter.generated.model.OpportunityCustomerSourceV1());var tree=json.valueToTree(ctx);assertTrue(tree.has("responsibilityBasis"));assertTrue(tree.get("responsibilityBasis").isNull());assertFalse(tree.has("draft"));assertFalse(tree.has("confirmation"));assertFalse(tree.has("currentOwnerLabel"));assertFalse(tree.get("source").has("party"));assertFalse(tree.get("source").has("contactName"));}

}
