package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.execution.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class R2ContractInputTest {
 private final UUID opportunity=UUID.randomUUID();
 private final Actor actor=new Actor(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),null,null,PrincipalKind.HUMAN);
 private Map<String,Object> body(){var p=new LinkedHashMap<String,Object>();p.put("opportunityId",opportunity.toString());p.put("expectedOpportunityRevision",1L);p.put("responsibilityBasis",Map.of("id",opportunity.toString(),"revision",1L));for(String key:List.of("customerConfirmation","expectedContract","expectedDraft","expectedVersion","expectedWorkflow"))p.put(key,null);p.put("values",Map.of());return p;}
 private CommandEnvelope envelope(Map<String,Object> p){return new CommandEnvelope(CommandEnvelope.Type.valueOf("SAVE_CONTRACT_DRAFT"),UUID.randomUUID(),UUID.randomUUID(),actor,p);}
 @Test void exact_contract_version_selector_is_part_of_scope(){var p=body();p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])));var e=envelope(p);var parsed=R2ContractInput.parse(e);assertEquals("contract.contract_revision",parsed.binding().version().type());assertTrue(CommandScope.contracts(e,parsed.binding()).canonical().contains("contract.contract_revision"));}
 @Test void unknown_fields_and_wrong_selector_forms_fail_closed(){var p=body();p.put("approved",true);assertThrows(CommandHandler.Rejected.class,()->R2ContractInput.parse(envelope(p)));p.remove("approved");p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"revision",0));assertThrows(CommandHandler.Rejected.class,()->R2ContractInput.parse(envelope(p)));p.put("expectedVersion",null);p.put("expectedDraft",Map.of("id",UUID.randomUUID().toString(),"revision",1));assertThrows(CommandHandler.Rejected.class,()->R2ContractInput.parse(envelope(p)));}
 @Test void protocol_mappings_remain_exact_and_contract_version_receipt_keeps_digest(){
  for(var action:io.github.windyzhu3.ontologylaw.contract.ContractWorkflowProtocol.Action.values()){var type=CommandEnvelope.Type.valueOf(action.name());assertTrue(type.contracts());assertEquals(io.github.windyzhu3.ontologylaw.contract.ContractWorkflowProtocol.authority(action),R1CommandPolicy.contractAuthority(type));assertEquals(io.github.windyzhu3.ontologylaw.contract.ContractWorkflowProtocol.resultType(action),R1CommandPolicy.contractResultType(type));assertEquals(io.github.windyzhu3.ontologylaw.contract.ContractWorkflowProtocol.event(action),R1EventPolicy.contractEvent(type).name());}
  var hash=Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32]);var projected=R1WireModels.fact(Map.of("factType","CONTRACT_REVISION","factRef",UUID.randomUUID().toString(),"digest",hash));assertInstanceOf(io.github.windyzhu3.ontologylaw.api.adapter.generated.model.R2ContractRevisionFactRefV1.class,projected);
 }
 @Test void recovery_metadata_rejects_cross_kind_selector_and_preserves_exact_version(){
  var p=body();p.put("expectedContract",Map.of("id",UUID.randomUUID().toString(),"revision",4L));p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])));var e=envelope(p);var parsed=R2ContractInput.parse(e);var scope=tools.jackson.databind.json.JsonMapper.builder().build().readValue(CommandScope.contracts(e,parsed.binding()).canonical(),Map.class);var frozen=Map.of("profile","R1_COMMAND_RECEIPT_RECOVERY_V1","scope",scope,"binding",Map.of("kind","CONTRACTS"));var recovery=new io.github.windyzhu3.ontologylaw.audit.ReceiptRecoveryMetadata(e.type().name(),frozen);assertEquals(parsed.binding().opportunity(),recovery.lead());assertNotNull(recovery.contractsScope());var changed=new LinkedHashMap<String,Object>(scope);changed.put("version",Map.of("type","opportunity.quote_revision","id",UUID.randomUUID().toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])));assertThrows(IllegalArgumentException.class,()->new io.github.windyzhu3.ontologylaw.audit.ReceiptRecoveryMetadata(e.type().name(),Map.of("profile","R1_COMMAND_RECEIPT_RECOVERY_V1","scope",changed,"binding",Map.of("kind","CONTRACTS"))));
 }
 @Test void hexadecimal_http_version_is_normalized_to_exact_digest_selector(){var p=body();p.put("expectedVersion",Map.of("id",UUID.randomUUID().toString(),"hash","ab".repeat(32)));assertEquals(Base64.getUrlEncoder().withoutPadding().encodeToString(HexFormat.of().parseHex("ab".repeat(32))),R2ContractInput.parse(envelope(p)).binding().version().hash());}
}
