package io.github.windyzhu3.ontologylaw.api;
import static org.junit.jupiter.api.Assertions.*;import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.evidence.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.util.*;import java.nio.file.Path;import java.net.http.*;import java.io.ByteArrayOutputStream;import javax.crypto.spec.SecretKeySpec;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
class R2MaterialsHttpIT extends R1HttpFixture {
 @TempDir Path directory;
 @SuppressWarnings("unchecked") @Test void public_wire_upload_accept_history_and_authorized_download_are_exact()throws Exception{
  setupContact();opportunityProtection=OpportunityProgressProtection.aesGcm(t->new SecretKeySpec(new byte[32],"AES"));materialStore=MaterialObjectStore.localPrivate(directory,input->new MalwareScanner.ScanResult(MalwareScanner.Verdict.CLEAN,"HTTP-TEST-CLEAN"));var contact=execute(prepare(contact("CONNECTED_VALID")));Subject opportunity;try(var c=database.apiConnection()){opportunity=inTransaction(c,Capability.COMMAND,x->{grant(x,"SALES_OPPORTUNITY_OWNER");grant(x,"MATERIALS_MANAGE");grant(x,"MATERIALS_READ");return EventOpportunityReader.databaseBacked().forContact(x,seed.tenant(),contact.resultFact().id()).selector();});}
  String base="/api/v1/opportunities/"+opportunity.id();var image=new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB);var bytes=new ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"PNG",bytes);byte[] content=bytes.toByteArray();
  try(var http=new HttpHarness()){
   var initial=http.request("GET",base+"/materials",null,Map.of());assertEquals(200,initial.statusCode(),initial.body());var context=http.body(initial);assertEquals(true,context.get("editable"));assertFalse(context.containsKey("confirmation"));
   var body=new LinkedHashMap<String,Object>();body.put("expectedOpportunityRevision",opportunity.revision());body.put("responsibilityBasis",context.get("responsibilityBasis"));body.put("expectedConfirmation",null);body.put("expectedPreviousVersion",null);body.put("purpose","CONTRACT_BUSINESS");body.put("fileName","真实合成.png");body.put("note",null);String openKey=UUID.randomUUID().toString();
   var missing=new LinkedHashMap<>(body);missing.remove("expectedConfirmation");var invalid=http.request("POST",base+"/material-uploads",missing,Map.of("Idempotency-Key",UUID.randomUUID().toString()));assertEquals(400,invalid.statusCode(),invalid.body());
   var opened=http.request("POST",base+"/material-uploads",body,Map.of("Idempotency-Key",openKey));assertEquals(200,opened.statusCode(),opened.body());assertEquals("OPPORTUNITY_MATERIAL_UPLOAD",((Map<?,?>)http.body(opened).get("resultFact")).get("factType"));
   var afterOpen=http.body(http.request("GET",base+"/materials",null,Map.of()));var pending=(Map<String,Object>)((List<?>)afterOpen.get("pendingUploads")).getFirst();assertEquals(((Map<?,?>)http.body(opened).get("resultFact")).get("factRef"),pending.get("factRef"));var uploadSelector=(Map<String,Object>)pending.get("selector");String session=(String)uploadSelector.get("id");assertNull(pending.get("confirmation"));assertTrue(pending.containsKey("confirmation"));assertEquals("OPEN",pending.get("state"));
   var transport=http.client.send(HttpRequest.newBuilder(http.origin.resolve(base+"/material-uploads/"+session+"/content")).header("Authorization","Bearer "+http.bearer).header("Content-Type","application/octet-stream").PUT(HttpRequest.BodyPublishers.ofByteArray(content)).build(),HttpResponse.BodyHandlers.ofString());assertEquals(200,transport.statusCode(),transport.body());assertEquals("PASSED",http.body(transport).get("state"));assertEquals("image/png",http.body(transport).get("mediaType"));
   var acceptedBody=new LinkedHashMap<String,Object>(body);acceptedBody.remove("purpose");acceptedBody.remove("fileName");acceptedBody.remove("note");acceptedBody.put("uploadSession",uploadSelector);String acceptKey=UUID.randomUUID().toString();var accepted=http.request("POST",base+"/materials/accept",acceptedBody,Map.of("Idempotency-Key",acceptKey));assertEquals(200,accepted.statusCode(),accepted.body());assertEquals("OPPORTUNITY_MATERIAL_VERSION",((Map<?,?>)http.body(accepted).get("resultFact")).get("factType"));assertEquals(http.body(accepted),http.body(http.request("POST",base+"/materials/accept",acceptedBody,Map.of("Idempotency-Key",acceptKey))));
   var receipt=http.request("GET","/api/v1/commands/"+acceptKey+"/receipt",null,Map.of());assertEquals(200,receipt.statusCode(),receipt.body());
   var finalRead=http.request("GET",base+"/materials",null,Map.of());assertEquals(200,finalRead.statusCode(),finalRead.body());var version=(Map<String,Object>)((List<?>)http.body(finalRead).get("versions")).getFirst();assertEquals(((Map<?,?>)http.body(accepted).get("resultFact")).get("factRef"),version.get("factRef"));assertEquals(false,version.get("previewAllowed"));assertTrue(version.containsKey("note"));assertNull(version.get("note"));String id=(String)((Map<?,?>)version.get("selector")).get("id");
   var download=http.client.send(HttpRequest.newBuilder(http.origin.resolve(base+"/materials/versions/"+id+"/content?disposition=attachment")).header("Authorization","Bearer "+http.bearer).GET().build(),HttpResponse.BodyHandlers.ofByteArray());assertEquals(200,download.statusCode());assertArrayEquals(content,download.body());assertTrue(download.headers().firstValue("Content-Disposition").orElse("").startsWith("attachment"));assertEquals("no-store",download.headers().firstValue("Cache-Control").orElse(""));
   var duplicate=http.client.send(HttpRequest.newBuilder(http.origin.resolve(base+"/material-uploads/"+session+"/content")).header("Authorization","Bearer "+http.bearer).header("Content-Type","application/octet-stream").PUT(HttpRequest.BodyPublishers.ofByteArray(content)).build(),HttpResponse.BodyHandlers.ofString());assertEquals(400,duplicate.statusCode(),duplicate.body());   var next=http.request("POST",base+"/material-uploads",body,Map.of("Idempotency-Key",UUID.randomUUID().toString()));assertEquals(200,next.statusCode(),next.body());var pendingAgain=(Map<?,?>)((List<?>)http.body(http.request("GET",base+"/materials",null,Map.of())).get("pendingUploads")).getFirst();String overflowSession=(String)((Map<?,?>)pendingAgain.get("selector")).get("id");
   var tooLarge=HttpRequest.BodyPublishers.ofInputStream(()->new java.io.InputStream(){long remaining=MaterialObjectStore.MAX_BYTES+1;public int read(){if(remaining--<=0)return -1;return 0;}public int read(byte[] b,int off,int len){if(remaining<=0)return -1;int n=(int)Math.min(remaining,len);Arrays.fill(b,off,off+n,(byte)0);remaining-=n;return n;}});
   var oversized=http.client.send(HttpRequest.newBuilder(http.origin.resolve(base+"/material-uploads/"+overflowSession+"/content")).header("Authorization","Bearer "+http.bearer).header("Content-Type","application/octet-stream").PUT(tooLarge).build(),HttpResponse.BodyHandlers.ofString());assertEquals(200,oversized.statusCode(),oversized.body());assertEquals("REJECTED",http.body(oversized).get("state"));assertEquals("TOO_LARGE",http.body(oversized).get("resultCode"));
  }
 }
}

