package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.contract.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
class R2ManualSignatureWorkflowIT extends R2ContractWorkflowPersistenceIT {
 boolean twoParties=false,mappedFirm=true;
 @org.junit.jupiter.api.BeforeEach void resetSignatureFixture(){twoParties=false;mappedFirm=true;}
 @Override void registerTemplateSigners(java.sql.Connection c,UUID template)throws java.sql.SQLException{if(mappedFirm)registerSyntheticTemplateFirm(c,template);}

 @Override Map<String,Object> doc(){var d=super.doc();if(twoParties)d.put("participants",List.of(Map.of("role","CLIENT","newParty",Map.of("kind","ORGANIZATION","name","合成委托主体甲","distinctIdentityConfirmed",true)),Map.of("role","CLIENT","newParty",Map.of("kind","ORGANIZATION","name","合成委托主体乙","distinctIdentityConfirmed",true))));return d;}

 void ready()throws Exception{versionFixture();formThroughWorkflow();command("REQUEST_CONTRACT_REVIEW",payload(context(),Map.of()));command("RECORD_CONTRACT_REVIEW",payload(context(),Map.of("decision","CLEAR","reason","完整准确主体审查通过")));command("REQUEST_CONTRACT_APPROVAL",payload(context(),Map.of()));command("RECORD_CONTRACT_DECISION",payload(context(),Map.of("decision","APPROVED","reason","批准准确正文")));}
 @SuppressWarnings("unchecked") Map<String,Object> signature()throws Exception{return (Map<String,Object>)context().get("signature");}
 String stage()throws Exception{return (String)((Map<?,?>)signature().get("workflow")).get("stage");}
 Map<String,Object> signaturePayload(Map<String,Object> values)throws Exception{var v=new LinkedHashMap<>(values);v.put("expectedSignatureWorkflow",((Map<?,?>)signature().get("workflow")).get("selector"));return payload(context(),v);}
 Map<String,Object> signatureRecovery(Actor worker)throws Exception{try(var c=database.apiConnection()){return inTransaction(c,Capability.QUERY,x->{var candidates=service().recoveryPage(x,worker,100,null).candidates();assertEquals(1,candidates.size());var candidate=candidates.getFirst();var p=new LinkedHashMap<String,Object>();p.put("opportunityId",opportunity.id().toString());p.put("expectedOpportunityRevision",opportunity.revision());p.put("responsibilityBasis",Map.of("id",candidate.basis().id().toString(),"revision",candidate.basis().revision()));p.put("sourceKind",candidate.workflow()==null?"SIGNATURE_READINESS":"SIGNATURE_AUTHORITY_RETURN");p.put("source",Map.of("id",candidate.source().id().toString(),"revision",0L));p.put("expectedWorkflow",candidate.workflow()==null?null:Map.of("id",candidate.workflow().id().toString(),"revision",0L));return p;});}}
 void recover(Actor worker,Map<String,Object> p)throws Exception{try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->service().reconcile(x,worker,p));}}
 void start()throws Exception{ready();var worker=service("CONTRACT_TASK_RECOVER");recover(worker,signatureRecovery(worker));assertEquals("ARRANGE",stage());}
 Map<String,Object> slot(Map<?,?> party,int number){var slot=new LinkedHashMap<String,Object>();slot.put("slotNumber",number);slot.put("partyId",party.get("id"));if(party.get("participationId")!=null)slot.put("participationId",party.get("participationId"));else slot.put("templateSigningPartyId",party.get("templateSigningPartyId"));slot.put("authoritySlot","SIGNER_"+number);slot.put("required",true);slot.put("signatureRequired",true);slot.put("sealRequired",true);slot.put("clauseBasis","批准正文第十条签署要求");return slot;}
 void arrange()throws Exception{var slots=new ArrayList<Map<String,Object>>();for(Object party:(List<?>)signature().get("parties"))slots.add(slot((Map<?,?>)party,slots.size()+1));command("CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT",signaturePayload(Map.of("humanConfirmed",true,"slots",slots)));}
 void verifyAll()throws Exception{command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));for(int slot=2;stage().equals("PARTIAL");slot++){command("SUBMIT_CONTRACT_SIGNATURE",signaturePayload(Map.of("slotNumber",slot,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成代表"+slot,"signedAt","2026-01-01T00:00:00Z")));command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));}}
 void submit()throws Exception{command("SUBMIT_CONTRACT_SIGNATURE",signaturePayload(Map.of("slotNumber",1,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成签署代表","signedAt","2026-01-01T00:00:00Z")));}
 Map<String,Object> verification(String decision){return Map.of("decision",decision,"reason","人工核对准确正文、全部安排及权限依据","contentCorresponds",true,"arrangementComplete",true,"authorityVerified",true,"materialComplete",true,"signatureVerified",true,"sealVerified",true);}
 @Test void readiness_recovers_once_and_complete_requires_verification_and_archive()throws Exception{
  ready();var worker=service("CONTRACT_TASK_RECOVER");var p=signatureRecovery(worker);recover(worker,p);assertThrows(ContractWorkflowService.Blocked.class,()->recover(worker,p));arrange();submit();assertEquals("AWAIT_VERIFICATION",stage());assertEquals("0",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));verifyAll();assertEquals("ARCHIVE",stage());command("ARCHIVE_CONTRACT_SIGNATURE",signaturePayload(Map.of("materialVersionId",material.toString(),"materialSha256",bodySha,"reason","完整归档核对通过","archiveComplete",true)));assertEquals("SIGNATURE_COMPLETE",stage());assertEquals("1",scalar("select count(*) from contract.signature_handoff where tenant_id=?",seed.tenant()));assertTrue(((List<?>)context().get("signatureHistory")).size()>=6);assertEquals("0",scalar("select count(*) from contract.contract_execution where tenant_id=?",seed.tenant()));
 }
 @Test void supplement_keeps_evidence_and_correction_invalidates_old_arrangement()throws Exception{start();arrange();submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("NEED_INFO")));assertEquals("SUPPLEMENT",stage());submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("ARRANGEMENT_CORRECTION")));assertEquals("ARRANGE",stage());arrange();assertEquals("2",scalar("select count(*) from contract.signature_arrangement where tenant_id=?",seed.tenant()));assertEquals("2",scalar("select count(*) from contract.signature_submission where tenant_id=?",seed.tenant()));assertEquals("0",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));}
 @Test void stale_denied_and_audit_failure_are_atomic()throws Exception{start();arrange();var values=Map.<String,Object>of("slotNumber",1,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成签署代表","signedAt","2026-01-01T00:00:00Z");var p=signaturePayload(values);permitted=false;assertThrows(ContractWorkflowService.Blocked.class,()->command("SUBMIT_CONTRACT_SIGNATURE",p));permitted=true;try(var c=database.apiConnection()){assertThrows(IllegalStateException.class,()->inTransaction(c,Capability.COMMAND,x->{service().execute(x,"SUBMIT_CONTRACT_SIGNATURE",actor(),p);throw new IllegalStateException("audit rollback");}));}assertEquals("0",scalar("select count(*) from contract.signature_submission where tenant_id=?",seed.tenant()));command("SUBMIT_CONTRACT_SIGNATURE",p);assertThrows(ContractWorkflowService.Blocked.class,()->command("SUBMIT_CONTRACT_SIGNATURE",p));}
 @Test void content_change_returns_to_new_revision_preparation()throws Exception{start();arrange();submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("REVISION_REQUIRED")));assertNull(context().get("signature"));assertEquals("RETURNED",((Map<?,?>)context().get("workflow")).get("stage"));assertEquals("0",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));}
 @Test void draft_cas_and_authority_recovery_preserve_original_deadline()throws Exception{
  start();var v=new LinkedHashMap<String,Object>();v.put("signerName","");v.put("expectedSignatureDraft",signature().get("draftSelector"));var p=signaturePayload(v);Object task=((Map<?,?>)signature().get("workflow")).get("task");command("SAVE_CONTRACT_SIGNATURE_DRAFT",p);assertThrows(ContractWorkflowService.Blocked.class,()->command("SAVE_CONTRACT_SIGNATURE_DRAFT",p));assertEquals(task,((Map<?,?>)signature().get("workflow")).get("task"));arrange();submit();Object due=((Map<?,?>)signature().get("workflow")).get("dueAt");unavailableAuthorities.add("CONTRACT_SIGNATURE_VERIFY");var worker=service("CONTRACT_TASK_RECOVER");recover(worker,signatureRecovery(worker));assertEquals("OWNER_EXCEPTION",stage());unavailableAuthorities.clear();recover(worker,signatureRecovery(worker));assertEquals("AWAIT_VERIFICATION",stage());assertEquals(due,((Map<?,?>)signature().get("workflow")).get("dueAt"));assertEquals("1",scalar("select count(*) from responsibility.task_occurrence where tenant_id=? and business_purpose_code='VERIFY_CONTRACT_SIGNATURE' and state='OPEN'",seed.tenant()));
 }
 @Test void stale_approval_cannot_archive_but_verifier_can_return_for_revision()throws Exception{
  start();arrange();submit();verifyAll();assertEquals("ARCHIVE",stage());approversEligible=false;assertFalse(((List<?>)context().get("allowedActions")).contains("ARCHIVE_CONTRACT_SIGNATURE"));command("RETURN_CONTRACT_SIGNATURE_FOR_REVISION",signaturePayload(Map.of("reason","批准配置已变化，退回重走审查审批")));assertEquals("RETURNED",((Map<?,?>)context().get("workflow")).get("stage"));assertEquals("0",scalar("select count(*) from contract.signature_handoff where tenant_id=?",seed.tenant()));
 }
 @Test void invalid_evidence_and_incomplete_verification_do_not_create_signature()throws Exception{
  start();arrange();var values=new LinkedHashMap<String,Object>(Map.of("slotNumber",1,"materialVersionId",material.toString(),"materialSha256","ab".repeat(32),"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成代表","signedAt","2026-01-01T00:00:00Z"));var p=signaturePayload(values);assertThrows(ContractWorkflowService.Blocked.class,()->command("SUBMIT_CONTRACT_SIGNATURE",p));submit();var incomplete=new LinkedHashMap<>(verification("VERIFIED"));incomplete.put("sealVerified",false);var verificationPayload=signaturePayload(incomplete);assertThrows(ContractWorkflowService.Blocked.class,()->command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",verificationPayload));assertEquals("0",scalar("select count(*) from contract.signature_verification where tenant_id=?",seed.tenant()));assertEquals("0",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));
 }
 @Test void two_required_parties_must_each_verify_before_archive()throws Exception{
  start();arrange();assertEquals(2,((List<?>)signature().get("parties")).size());submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));assertEquals("PARTIAL",stage());assertFalse(((List<?>)context().get("allowedActions")).contains("ARCHIVE_CONTRACT_SIGNATURE"));command("SUBMIT_CONTRACT_SIGNATURE",signaturePayload(Map.of("slotNumber",2,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","第二合成代表","signedAt","2026-01-01T00:00:00Z")));command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));assertEquals("ARCHIVE",stage());assertEquals("2",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));
 }
 @Test void multiple_qualified_verifiers_route_deterministically_without_stalling()throws Exception{
  start();arrange();UUID principal=UUID.randomUUID(),appointment=UUID.randomUUID();mutate("insert into identity.principal(tenant_id,principal_id,principal_kind,identity_provider_code,external_subject_hmac,display_name,state,created_at) values(?,?,'HUMAN','FIXTURE',?,'Another qualified verifier','ACTIVE',clock_timestamp())",seed.tenant(),principal,ContractCanonicalJson.digest(principal.toString()));mutate("insert into identity.appointment(tenant_id,appointment_id,principal_id,organization_unit_id,role_code,effective_from,state,created_at) values(?,?,?,?,'OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),appointment,principal,seed.org());additionalSignatureVerifiers.add(appointment);submit();assertEquals("AWAIT_VERIFICATION",stage());String expected=List.of(seed.appointment().toString(),appointment.toString()).stream().sorted().findFirst().orElseThrow();assertEquals(expected,((Map<?,?>)signature().get("workflow")).get("ownerAppointmentId"));
 }
 @Test void old_unmapped_template_cannot_sign_and_can_return_without_fake_signature_task()throws Exception{
  mappedFirm=false;ready();var worker=service("CONTRACT_TASK_RECOVER");try(var c=database.apiConnection()){inTransaction(c,Capability.QUERY,x->{assertTrue(service().recoveryPage(x,worker,100,null).candidates().isEmpty());return null;});}assertEquals("0",scalar("select count(*) from contract.signature_workflow where tenant_id=?",seed.tenant()));command("RETURN_CONTRACT_FOR_REVISION",signaturePayload(Map.of("reason","原模板缺少准确律所主体绑定，选择新批准模板修订")));assertEquals("RETURNED",((Map<?,?>)context().get("workflow")).get("stage"));assertEquals("0",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));
 }
 @Test void corrected_arrangement_preserves_but_does_not_reuse_completed_signature()throws Exception{
  start();arrange();submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));assertEquals("PARTIAL",stage());command("SUBMIT_CONTRACT_SIGNATURE",signaturePayload(Map.of("slotNumber",2,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成律所代表","signedAt","2026-01-01T00:00:00Z")));command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("ARRANGEMENT_CORRECTION")));arrange();assertEquals("COLLECT",stage());assertTrue(((List<?>)signature().get("submissions")).isEmpty());assertTrue(((List<?>)context().get("signatureHistory")).size()>=6);submit();command("RECORD_CONTRACT_SIGNATURE_VERIFICATION",signaturePayload(verification("VERIFIED")));assertEquals("PARTIAL",stage());assertEquals("2",scalar("select count(*) from contract.contract_signature where tenant_id=?",seed.tenant()));
 }
 @Test void distinct_signed_bytes_keep_approved_body_and_signed_material_digests_separate()throws Exception{
  start();arrange();String approvedSha=bodySha;UUID signedMaterial=material(0xffffff);String signedSha=bodySha;bodySha=approvedSha;assertNotEquals(approvedSha,signedSha);command("SUBMIT_CONTRACT_SIGNATURE",signaturePayload(Map.of("slotNumber",1,"materialVersionId",signedMaterial.toString(),"materialSha256",signedSha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",approvedSha,"signerName","合成签署代表","signedAt","2026-01-01T00:00:00Z")));verifyAll();assertEquals("ARCHIVE",stage());assertEquals(approvedSha,scalar("select encode(approved_body_sha256,'hex') from contract.signature_submission where tenant_id=? and material_version_id=?",seed.tenant(),signedMaterial));assertEquals(signedSha,scalar("select encode(material_sha256,'hex') from contract.signature_submission where tenant_id=? and material_version_id=?",seed.tenant(),signedMaterial));
 }
 @Test void sales_revision_return_cancels_arrange_and_collect_instead_of_faking_completion()throws Exception{
  start();Object arrangementTask=((Map<?,?>)((Map<?,?>)signature().get("workflow")).get("task")).get("id");command("RETURN_CONTRACT_FOR_REVISION",signaturePayload(Map.of("reason","正文需补充后重新审批")));assertEquals("CANCELLED",scalar("select state from responsibility.task_occurrence where tenant_id=? and task_occurrence_id=?",seed.tenant(),UUID.fromString(arrangementTask.toString())));assertEquals("RETURNED",((Map<?,?>)context().get("workflow")).get("stage"));start();arrange();Object collectTask=((Map<?,?>)((Map<?,?>)signature().get("workflow")).get("task")).get("id");command("RETURN_CONTRACT_FOR_REVISION",signaturePayload(Map.of("reason","委托范围变化必须形成新版本")));assertEquals("CANCELLED",scalar("select state from responsibility.task_occurrence where tenant_id=? and task_occurrence_id=?",seed.tenant(),UUID.fromString(collectTask.toString())));assertEquals("RETURNED",((Map<?,?>)context().get("workflow")).get("stage"));
 }
 @Test void concurrent_signature_submissions_have_one_successor_and_one_task()throws Exception{
  start();arrange();var p=signaturePayload(Map.of("slotNumber",1,"materialVersionId",material.toString(),"materialSha256",bodySha,"authorityMaterialVersionId",material.toString(),"authorityMaterialSha256",bodySha,"signerName","合成代表","signedAt","2026-01-01T00:00:00Z"));try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){java.util.concurrent.Callable<Boolean> attempt=()->{try{command("SUBMIT_CONTRACT_SIGNATURE",p);return true;}catch(ContractWorkflowService.Blocked stale){return false;}};var outcomes=pool.invokeAll(List.of(attempt,attempt));int succeeded=0;for(var outcome:outcomes)if(outcome.get())succeeded++;assertEquals(1,succeeded);}assertEquals("1",scalar("select count(*) from contract.signature_submission where tenant_id=?",seed.tenant()));assertEquals("1",scalar("select count(*) from responsibility.task_occurrence where tenant_id=? and business_purpose_code='VERIFY_CONTRACT_SIGNATURE' and state='OPEN'",seed.tenant()));
 }
}
