package io.github.windyzhu3.ontologylaw.api;
import static org.junit.jupiter.api.Assertions.*;import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.lead.ContactFlowFixture;import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.evidence.*;import io.github.windyzhu3.ontologylaw.responsibility.*;import io.github.windyzhu3.ontologylaw.audit.AuditAppender;
import java.util.*;import java.time.*;import java.sql.*;import java.io.*;import java.nio.file.Path;import javax.crypto.spec.SecretKeySpec;import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;
class R2MaterialsIT extends ContactFlowFixture {
 @TempDir Path directory;final OpportunityProgressProtection cipher=OpportunityProgressProtection.aesGcm(t->new SecretKeySpec(new byte[32],"AES"));Subject opportunity;MaterialObjectStore store;
 void setup(boolean permission,boolean waiting)throws Exception{setupContact();var contact=execute(prepare(contact("CONNECTED_VALID")));try(var c=database.apiConnection()){opportunity=inTransaction(c,Capability.COMMAND,x->{grant(x,"SALES_OPPORTUNITY_OWNER");if(permission){grant(x,"MATERIALS_MANAGE");grant(x,"MATERIALS_READ");}var o=EventOpportunityReader.databaseBacked().forContact(x,seed.tenant(),contact.resultFact().id()).selector();if(waiting){var task=TaskFactory.databaseBacked().createInitialOpportunity(x,seed.tenant(),seed.appointment(),o,ZoneId.of("Asia/Shanghai"),businessAt);R2OpportunityProgressServices.create(cipher).record(x,seed.request().actor(),o,task.selector(),new OpportunityProgressInput("PHONE_CONNECTED","下周补材料",businessAt,Instant.now().plusSeconds(86400).truncatedTo(java.time.temporal.ChronoUnit.MICROS)),ZoneId.of("Asia/Shanghai"),businessAt.plusSeconds(60));}return o;});}runtime=R2OpportunityCommandRuntime.fromSourcePolicy(policies,protection,cipher,null,"T06_IT");store=MaterialObjectStore.localPrivate(directory,input->new MalwareScanner.ScanResult(MalwareScanner.Verdict.CLEAN,"TEST-CLEAN"));}
 CommandEnvelope command(Subject previous,Subject upload){var p=new TreeMap<String,Object>();p.put("opportunityId",opportunity.id().toString());p.put("expectedOpportunityRevision",opportunity.revision());p.put("responsibilityBasis",R2CustomerRequirementsServices.selector(opportunity));p.put("expectedConfirmation",null);p.put("expectedPreviousVersion",R2CustomerRequirementsServices.selector(previous));if(upload==null){p.put("purpose","CONTRACT_BUSINESS");p.put("fileName","合成测试.png");p.put("note","机密材料说明");}else p.put("uploadSession",R2CustomerRequirementsServices.selector(upload));return new CommandEnvelope(upload==null?CommandEnvelope.Type.OPEN_OPPORTUNITY_MATERIAL_UPLOAD:CommandEnvelope.Type.ACCEPT_OPPORTUNITY_MATERIAL,UUID.randomUUID(),UUID.randomUUID(),seed.request().actor(),p);}
 R2MaterialsReadService reads(){return new R2MaterialsReadService(new byte[32],protection,cipher,AuditAppender.databaseBacked("T06_READ"),store);}
 byte[] png()throws Exception{var image=new java.awt.image.BufferedImage(2,2,java.awt.image.BufferedImage.TYPE_INT_RGB);var bytes=new ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"PNG",bytes);return bytes.toByteArray();}
 Map<String,Object> upload(Subject s)throws Exception{try(var c=database.apiConnection()){return reads().upload(c,seed.request().actor(),opportunity.id(),s.id(),new ByteArrayInputStream(png()));}}
 Map<String,Object> read()throws Exception{try(var c=database.apiConnection()){return reads().read(c,seed.request().actor(),opportunity.id());}}
 @Test void complete_chain_is_atomic_idempotent_preconfirmation_and_keeps_waiting_sla()throws Exception{setup(true,true);String before=scalar("select task_occurrence_id::text||':'||revision||':'||state||':'||original_sla_due_at::text from responsibility.task_occurrence where tenant_id=? and subject_id=?",seed.tenant(),opportunity.id());var open=command(null,null);var opened=execute(open);assertEquals(CommandOutcome.Status.SUCCEEDED,opened.status(),opened.rejectionCode());assertEquals(opened,execute(open));assertEquals("PASSED",upload(opened.resultFact()).get("state"));var accept=command(null,opened.resultFact());var result=execute(accept);assertEquals(CommandOutcome.Status.SUCCEEDED,result.status(),result.rejectionCode());assertEquals(result,execute(accept));assertEquals(before,scalar("select task_occurrence_id::text||':'||revision||':'||state||':'||original_sla_due_at::text from responsibility.task_occurrence where tenant_id=? and subject_id=?",seed.tenant(),opportunity.id()));for(String table:List.of("evidence.evidence_submission","evidence.evidence_binding","opportunity.material_version"))assertEquals("1",scalar("select count(*) from "+table+" where tenant_id=?",seed.tenant()));assertEquals("0",scalar("select count(*) from party.party where tenant_id=?",seed.tenant()));assertEquals("0",scalar("select count(*) from audit.audit_entry_classified_v where tenant_id=? and change_summary::text like '%机密材料说明%'",seed.tenant()));try(var c=database.apiConnection()){assertEquals(200,new CommandReceiptRecoveryService(policies,protection,null,"T06_RECOVERY").read(c,seed.request().actor(),accept.commandId(),UUID.randomUUID()).status());assertArrayEquals(png(),reads().content(c,seed.request().actor(),opportunity.id(),result.resultFact().id(),"attachment").bytes());}assertEquals(1,((List<?>)read().get("versions")).size());}
 @Test void previous_versions_remain_readable_and_competing_successors_do_not_fork()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();upload(s);var first=execute(command(null,s)).resultFact();var a=execute(command(first,null)).resultFact();var b=execute(command(first,null)).resultFact();upload(a);upload(b);try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var calls=List.<java.util.concurrent.Callable<CommandOutcome>>of(()->execute(command(first,a)),()->execute(command(first,b)));var outcomes=pool.invokeAll(calls);int successes=0;for(var f:outcomes){var result=f.get();if(result.status()==CommandOutcome.Status.SUCCEEDED)successes++;else assertEquals("STALE_SUBJECT",result.rejectionCode());}assertEquals(1,successes);}assertEquals(2,((List<?>)read().get("versions")).size());try(var c=database.apiConnection()){assertArrayEquals(png(),reads().content(c,seed.request().actor(),opportunity.id(),first.id(),"attachment").bytes());}}
 @Test void unchecked_or_scan_unavailable_cannot_be_accepted_and_bytes_are_not_replayed()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();assertEquals(CommandOutcome.Status.REJECTED,execute(command(null,s)).status());store=MaterialObjectStore.localPrivate(directory.resolve("offline"),input->new MalwareScanner.ScanResult(MalwareScanner.Verdict.UNAVAILABLE,"TEST-OFFLINE"));assertEquals("SCAN_UNAVAILABLE",upload(s).get("state"));assertEquals(CommandOutcome.Status.REJECTED,execute(command(null,s)).status());assertThrows(R1ServiceReadRuntime.Failure.class,()->upload(s));assertEquals("0",scalar("select count(*) from opportunity.material_version where tenant_id=?",seed.tenant()));}
 @Test void transport_unknown_is_query_only_until_expiry()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();store=new MaterialObjectStore(){public StoredObject store(InputStream x)throws IOException{throw new IOException("simulated unknown");}public byte[] read(UUID x,String y)throws IOException{throw new IOException();}};assertEquals("UNKNOWN",upload(s).get("state"));var blocked=execute(command(null,null));assertEquals(CommandOutcome.Status.REJECTED,blocked.status());assertEquals("VALIDATION_FAILED",blocked.rejectionCode());assertThrows(R1ServiceReadRuntime.Failure.class,()->upload(s));try(var c=database.apiConnection()){assertEquals("UNKNOWN",reads().status(c,seed.request().actor(),opportunity.id(),s.id()).get("state"));}}
 @Test void authority_is_explicit_and_revocation_denies_content_and_receipt()throws Exception{setup(false,false);try(var c=database.apiConnection()){assertThrows(CommandHandler.Rejected.class,()->runtime.execute(c,command(null,null)));}try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{grant(x,"MATERIALS_MANAGE");return null;});}var s=execute(command(null,null)).resultFact();upload(s);var accept=command(null,s);var v=execute(accept);mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=? and authority_code='MATERIALS_MANAGE'",seed.tenant());try(var c=database.apiConnection()){assertThrows(R1ServiceReadRuntime.Failure.class,()->reads().content(c,seed.request().actor(),opportunity.id(),v.resultFact().id(),"attachment"));assertEquals(403,new CommandReceiptRecoveryService(policies,protection,null,"T06_REVOKED").read(c,seed.request().actor(),accept.commandId(),UUID.randomUUID()).status());}}
 @Test void disclosure_audit_failure_returns_no_content()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();upload(s);var v=execute(command(null,s)).resultFact();var bad=new AuditAppender(){public void append(Connection c,Entry e)throws SQLException{throw new SQLException("audit unavailable");}public void append(Connection c,MaterialDisclosureEntry e)throws SQLException{throw new SQLException("audit unavailable");}};try(var c=database.apiConnection()){assertThrows(SQLException.class,()->new R2MaterialsReadService(new byte[32],protection,cipher,bad,store).content(c,seed.request().actor(),opportunity.id(),v.id(),"attachment"));}}
 @Test void atomic_accept_rolls_back_evidence_and_version_on_audit_failure()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();upload(s);var bad=new AuditAppender(){public void append(Connection c,Entry e)throws SQLException{throw new SQLException("audit unavailable");}};var isolated=new CommandRuntime(List.of(new R2MaterialsCommand(CommandEnvelope.Type.ACCEPT_OPPORTUNITY_MATERIAL,cipher)),io.github.windyzhu3.ontologylaw.identity.AuthorizationService.databaseBacked(),bad,R2OpportunityCommandRuntime.authorization(io.github.windyzhu3.ontologylaw.lead.R1AuthorizationReaders.databaseBacked(policies)),R2OpportunityCommandRuntime.events(io.github.windyzhu3.ontologylaw.lead.R1EventReaders.databaseBacked(),cipher));try(var c=database.apiConnection()){assertThrows(SQLException.class,()->isolated.execute(c,command(null,s)));}for(String table:List.of("evidence.evidence_submission","evidence.evidence_binding","opportunity.material_version"))assertEquals("0",scalar("select count(*) from "+table+" where tenant_id=?",seed.tenant()));assertEquals("OBJECT_RECEIVED",scalar("select status from evidence.upload_session where tenant_id=? and upload_session_id=?",seed.tenant(),s.id()));}
 @Test void closed_opportunity_is_read_only_and_protected_metadata_cannot_cross_domains()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();upload(s);try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{var service=R2OpportunityClosureServices.create(cipher);var state=service.inspect(x,seed.tenant(),opportunity.id());service.close(x,seed.tenant(),new OpportunityClosureService.Input(state.opportunity(),state.responsibility().basis(),state.task(),state.waitReceipt(),seed.appointment(),"OTHER","结束销售"));return null;});}assertEquals(CommandOutcome.Status.REJECTED,execute(command(null,s)).status());assertEquals(false,read().get("editable"));byte[] body=cipher.encryptMaterial(seed.tenant(),opportunity.id(),s.id(),"secret");assertThrows(IllegalArgumentException.class,()->cipher.decrypt(seed.tenant(),opportunity.id(),s.id(),body));}
 @Test void transfer_never_hands_pending_upload_to_receiver_but_received_versions_remain_available()throws Exception{
  setup(true,false);try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{grant(x,"OPPORTUNITY_OWNER_EXCEPTION_READ");grant(x,"OPPORTUNITY_OWNER_EXCEPTION_RESOLVE");return null;});}
  var complete=execute(command(null,null)).resultFact();upload(complete);var accepted=execute(command(null,complete)).resultFact();var pending=execute(command(null,null)).resultFact();upload(pending);
  mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=? and grantee_appointment_id=? and authority_code='SALES_OPPORTUNITY_OWNER'",seed.tenant(),seed.appointment());
  var observer=service("OPPORTUNITY_OWNER_EXCEPTION_DISCOVER");var observed=execute(new CommandEnvelope(CommandEnvelope.Type.OBSERVE_OPPORTUNITY_OWNER_EXCEPTION,UUID.randomUUID(),UUID.randomUUID(),observer,Map.of("opportunityId",opportunity.id().toString(),"expectedOpportunityRevision",opportunity.revision())));
  OpportunityOwnerExceptionService.Snapshot snapshot;try(var c=database.apiConnection()){snapshot=inTransaction(c,Capability.QUERY,x->R2OpportunityOwnerExceptionAssembly.service().read(x,seed.tenant(),observed.resultFact()));}
  UUID principal=UUID.randomUUID(),appointment=UUID.randomUUID();
  mutate("insert into identity.principal (tenant_id,principal_id,principal_kind,identity_provider_code,external_subject_hmac,display_name,state,created_at) values (?,?,'HUMAN','FIXTURE',?,'T06 receiver','ACTIVE',clock_timestamp())",seed.tenant(),principal,CanonicalJson.digest(principal.toString()));
  mutate("insert into identity.appointment (tenant_id,appointment_id,principal_id,organization_unit_id,role_code,effective_from,state,created_at) values (?,?,?,?,'OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),appointment,principal,seed.org());
  for(String code:List.of("SALES_OPPORTUNITY_OWNER","MATERIALS_MANAGE","MATERIALS_READ"))mutate("insert into identity.authority_grant (tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values (?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),appointment,seed.appointment(),seed.org(),code);
  var transfer=new TreeMap<String,Object>();transfer.put("opportunityId",opportunity.id().toString());transfer.put("expectedOpportunityRevision",opportunity.revision());transfer.put("exceptionId",snapshot.selector().id().toString());transfer.put("expectedExceptionRevision",snapshot.selector().revision());transfer.put("expectedBasis",CommandScope.selector(snapshot.responsibility().basis()));transfer.put("expectedTask",CommandScope.selector(snapshot.task()));transfer.put("expectedWait",CommandScope.selector(snapshot.waitReceipt()));transfer.put("reason","材料接收移交测试");transfer.put("receiverAppointmentId",appointment.toString());
  var transferred=execute(new CommandEnvelope(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,UUID.randomUUID(),UUID.randomUUID(),seed.request().actor(),transfer));assertEquals(CommandOutcome.Status.SUCCEEDED,transferred.status(),transferred.rejectionCode());var receiver=new Actor(seed.tenant(),principal,appointment,null,null,PrincipalKind.HUMAN);
  try(var c=database.apiConnection()){var context=reads().read(c,receiver,opportunity.id());assertEquals(1,((List<?>)context.get("versions")).size());assertEquals(0,((List<?>)context.get("pendingUploads")).size());assertArrayEquals(png(),reads().content(c,receiver,opportunity.id(),accepted.id(),"attachment").bytes());assertThrows(R1ServiceReadRuntime.Failure.class,()->reads().status(c,receiver,opportunity.id(),pending.id()));assertThrows(CommandHandler.Rejected.class,()->runtime.execute(c,command(null,pending)));}
 } @Test void unknown_upload_cannot_be_hidden_by_more_than_fifty_preopened_sessions()throws Exception{setup(true,false);var oldest=execute(command(null,null)).resultFact();for(int i=0;i<50;i++)assertEquals(CommandOutcome.Status.SUCCEEDED,execute(command(null,null)).status());store=new MaterialObjectStore(){public StoredObject store(InputStream input)throws IOException{throw new IOException("unknown transport");}public byte[] read(UUID id,String hash)throws IOException{throw new IOException();}};assertEquals("UNKNOWN",upload(oldest).get("state"));var blocked=execute(command(null,null));assertEquals(CommandOutcome.Status.REJECTED,blocked.status());assertEquals("VALIDATION_FAILED",blocked.rejectionCode());assertEquals(51,((List<?>)read().get("pendingUploads")).size());} @Test void exact_binding_deny_blocks_download_listing_and_accepted_receipt()throws Exception{setup(true,false);var s=execute(command(null,null)).resultFact();upload(s);var accept=command(null,s);var v=execute(accept).resultFact();UUID binding=UUID.fromString(scalar("select evidence_binding_id from opportunity.material_version where tenant_id=? and material_version_id=?",seed.tenant(),v.id()));for(String code:List.of("MATERIALS_MANAGE","MATERIALS_READ"))mutate("insert into identity.object_access_grant(tenant_id,object_access_grant_id,grantee_principal_id,granted_by_appointment_id,access_code,effect_code,valid_from,state,created_at,object_subject_type,object_subject_id,object_subject_revision) values(?,?,?,?,?,'DENY',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp(),'evidence.evidence_binding',?,0)",seed.tenant(),UUID.randomUUID(),seed.request().actor().principalId(),seed.appointment(),code,binding);assertEquals(0,((List<?>)read().get("versions")).size());try(var c=database.apiConnection()){assertThrows(R1ServiceReadRuntime.Failure.class,()->reads().content(c,seed.request().actor(),opportunity.id(),v.id(),"attachment"));assertEquals(403,new CommandReceiptRecoveryService(policies,protection,null,"T06_BINDING_DENY").read(c,seed.request().actor(),accept.commandId(),UUID.randomUUID()).status());}}}





