package io.github.windyzhu3.ontologylaw.api;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.github.windyzhu3.ontologylaw.execution.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.util.*;
class R2OpportunityOwnerExceptionInputTest {
 private final Actor human=new Actor(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),null,null,PrincipalKind.HUMAN);
 private final Subject opportunity=new Subject("opportunity.opportunity",UUID.randomUUID(),0L,null);
 private Map<String,Object> decision(){var p=new TreeMap<String,Object>();p.put("opportunityId",opportunity.id().toString());p.put("expectedOpportunityRevision",0L);p.put("exceptionId",UUID.randomUUID().toString());p.put("expectedExceptionRevision",2L);p.put("expectedBasis",CommandScope.selector(opportunity));p.put("expectedTask",null);p.put("expectedWait",null);p.put("reason","Confirm receiver");p.put("receiverAppointmentId",UUID.randomUUID().toString());return p;}
 private CommandEnvelope envelope(Map<String,Object> p){return new CommandEnvelope(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,UUID.randomUUID(),UUID.randomUUID(),human,p);}
 @Test void direct_admin_command_binds_exact_exception_basis_and_actor_scope(){var e=envelope(decision());var in=R2OpportunityOwnerExceptionInput.parse(e);assertEquals(CommandEnvelope.Envelope.INTERNAL_ADMIN,e.envelope());assertEquals(opportunity,in.basis());assertNull(in.task());var scope=CommandScope.ownerException(e,in.opportunity(),in.exception(),in.basis(),in.task(),in.waitReceipt());assertNull(scope.taskId());assertEquals(human.appointmentId().toString(),scope.fields().get("appointmentId"));}
 @Test void task_headers_and_unknown_fields_cannot_change_admin_semantics(){var p=decision();p.put("grantAuthority",true);assertThrows(CommandHandler.Rejected.class,()->R2OpportunityOwnerExceptionInput.parse(envelope(p)));var valid=envelope(decision());assertThrows(CommandHandler.Rejected.class,()->R2OpportunityOwnerExceptionInput.parse(new CommandEnvelope(valid.type(),valid.commandId(),valid.correlationId(),human,valid.payload(),new CommandEnvelope.TaskPrecondition(UUID.randomUUID(),"arbitrary"))));}
 @Test void service_cannot_transfer_and_human_cannot_observe(){var service=new Actor(human.tenantId(),human.principalId(),human.appointmentId(),null,null,PrincipalKind.SERVICE);assertThrows(IllegalArgumentException.class,()->new CommandEnvelope(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,UUID.randomUUID(),UUID.randomUUID(),service,decision()));assertThrows(IllegalArgumentException.class,()->new CommandEnvelope(CommandEnvelope.Type.OBSERVE_OPPORTUNITY_OWNER_EXCEPTION,UUID.randomUUID(),UUID.randomUUID(),human,Map.of()));}
 @Test void noncanonical_reason_unsafe_revision_and_wait_without_task_rejected(){var p=decision();p.put("reason"," trailing ");var reason=p;assertThrows(CommandHandler.Rejected.class,()->R2OpportunityOwnerExceptionInput.parse(envelope(reason)));p=decision();p.put("expectedExceptionRevision",9007199254740992L);var revision=p;assertThrows(IllegalArgumentException.class,()->envelope(revision));p=decision();p.put("expectedWait",Map.of("type","responsibility.wait_receipt","id",UUID.randomUUID().toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])));var wait=p;assertThrows(CommandHandler.Rejected.class,()->R2OpportunityOwnerExceptionInput.parse(envelope(wait)));}
}
