package io.github.windyzhu3.ontologylaw.api;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
import io.github.windyzhu3.ontologylaw.execution.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import io.github.windyzhu3.ontologylaw.lead.ContactFlowFixture;
import io.github.windyzhu3.ontologylaw.opportunity.*;
import io.github.windyzhu3.ontologylaw.responsibility.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationIdentityReader;
import java.util.*;
import java.time.*;
import javax.crypto.spec.SecretKeySpec;
/** Migrated PostgreSQL formal commands, durable audit, replay and direct current authorization. */
class R2OpportunityOwnerExceptionCommandIT extends ContactFlowFixture {
 @Test void observation_reuses_identity_rows_while_holding_the_business_fence()throws Exception {
  setup(true);
  try(var c=database.apiConnection()) {
   var probe=new ReadConnectionProbe(c);var result=runtime.execute(probe.connection(),observation);
   assertEquals(CommandOutcome.Status.NO_CHANGE,assertInstanceOf(CommandOutcome.class,result).status());
   int fence=-1;for(int i=0;i<probe.statements.size();i++)if(probe.statements.get(i).contains("pg_advisory_xact_lock(")){fence=i;break;}
   assertTrue(fence>=0);var locked=probe.statements.subList(fence+1,probe.statements.size());
   long tenantReads=locked.stream().filter(q->q.contains("from \"identity\".\"tenant\"")).count();
   System.out.printf("OBSERVER_SQL count=%d lockedCount=%d lockedTenantReads=%d sqlMs=%.1f%n",probe.statements.size(),locked.size(),tenantReads,probe.sqlNanos.sum()/1e6);
   assertEquals(1,tenantReads,"Unchanged identity rows should be loaded once while the observation blocks business readers");
  }
 }
 private Subject opportunity;private Actor observer;private CommandEnvelope observation;
 private void setup(boolean healthy)throws Exception{
  setupContact();var contact=execute(prepare(contact("CONNECTED_VALID")));try(var c=database.apiConnection()){opportunity=inTransaction(c,Capability.COMMAND,x->{grant(x,"OPPORTUNITY_OWNER_EXCEPTION_READ");grant(x,"OPPORTUNITY_OWNER_EXCEPTION_RESOLVE");if(healthy)grant(x,"SALES_OPPORTUNITY_OWNER");return EventOpportunityReader.databaseBacked().forContact(x,seed.tenant(),contact.resultFact().id()).selector();});}
  observer=service("OPPORTUNITY_OWNER_EXCEPTION_DISCOVER");runtime=R2OpportunityCommandRuntime.fromSourcePolicy(policies,protection,OpportunityProgressProtection.aesGcm(t->new SecretKeySpec(new byte[32],"AES")),null,"T01_COMMAND_IT");
  observation=new CommandEnvelope(CommandEnvelope.Type.OBSERVE_OPPORTUNITY_OWNER_EXCEPTION,UUID.randomUUID(),UUID.randomUUID(),observer,Map.of("opportunityId",opportunity.id().toString(),"expectedOpportunityRevision",opportunity.revision()));
 }
 private OpportunityOwnerExceptionService.Snapshot snapshot(Subject ref)throws Exception{try(var c=database.apiConnection()){return inTransaction(c,Capability.QUERY,x->R2OpportunityOwnerExceptionAssembly.service().read(x,seed.tenant(),ref));}}
 private CommandEnvelope decision(CommandEnvelope.Type type,OpportunityOwnerExceptionService.Snapshot s,UUID receiver){var p=new TreeMap<String,Object>();p.put("opportunityId",s.opportunity().id().toString());p.put("expectedOpportunityRevision",s.opportunity().revision());p.put("exceptionId",s.selector().id().toString());p.put("expectedExceptionRevision",s.selector().revision());p.put("expectedBasis",CommandScope.selector(s.responsibility().basis()));p.put("expectedTask",CommandScope.selector(s.task()));p.put("expectedWait",CommandScope.selector(s.waitReceipt()));p.put("reason","Current supervisor reviewed responsibility");if(type==CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY)p.put("receiverAppointmentId",receiver.toString());else p.put("reviewDueAt",Instant.now().plusSeconds(3600).truncatedTo(java.time.temporal.ChronoUnit.MICROS).toString());return new CommandEnvelope(type,UUID.randomUUID(),UUID.randomUUID(),seed.request().actor(),p);}
 private UUID receiver()throws Exception{UUID principal=UUID.randomUUID(),appointment=UUID.randomUUID();mutate("insert into identity.principal (tenant_id,principal_id,principal_kind,identity_provider_code,external_subject_hmac,display_name,state,created_at) values (?,?,'HUMAN','FIXTURE',?,'Qualified receiver','ACTIVE',clock_timestamp())",seed.tenant(),principal,CanonicalJson.digest(principal.toString()));mutate("insert into identity.appointment (tenant_id,appointment_id,principal_id,organization_unit_id,role_code,effective_from,state,created_at) values (?,?,?,?,'OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),appointment,principal,seed.org());mutate("insert into identity.authority_grant (tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values (?,?,?,?,?,'SALES_OPPORTUNITY_OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),appointment,seed.appointment(),seed.org());return appointment;}
 @Test void healthy_observation_no_change_has_real_durable_audit_and_replays_without_new_rows()throws Exception{
  setup(true);var result=execute(observation);assertEquals(CommandOutcome.Status.NO_CHANGE,result.status());assertEquals("audit.audit_entry",result.resultFact().type());assertNotNull(result.resultFact().hash());assertEquals("0",scalar("select count(*) from opportunity.owner_exception where tenant_id=?",seed.tenant()));assertEquals("1",scalar("select count(*) from audit.audit_entry_classified_v where tenant_id=? and audit_entry_id=? and summary_schema_code='R2_OPPORTUNITY_OWNER_VALIDATION_V1'",seed.tenant(),result.resultFact().id()));var before=counts();assertEquals(result,execute(observation));assertEquals(before,counts());
 }
 @Test void observation_then_transfer_creates_one_receiver_task_and_get_receipt_recovers_exact_result()throws Exception{
  setup(false);var observed=execute(observation);assertEquals(CommandOutcome.Status.SUCCEEDED,observed.status());var before=snapshot(observed.resultFact());assertTrue(before.reasons().contains(OpportunityOwnerExceptionService.Reason.OWNER_AUTHORITY_MISSING));var receiver=receiver();var command=decision(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,before,receiver);var result=execute(command);assertEquals(CommandOutcome.Status.SUCCEEDED,result.status());var after=snapshot(result.resultFact());assertEquals(OpportunityOwnerExceptionService.State.RESOLVED,after.state());assertEquals(receiver,after.responsibility().appointmentId());assertEquals(seed.appointment().toString(),scalar("select owner_appointment_id from opportunity.opportunity where tenant_id=? and opportunity_id=?",seed.tenant(),opportunity.id()));var counts=counts();assertEquals(result,execute(command));assertEquals(counts,counts());
  try(var c=database.apiConnection()){var restored=new CommandReceiptRecoveryService(policies,protection,null,"T01_RECEIPT_IT").read(c,seed.request().actor(),command.commandId(),UUID.randomUUID());assertEquals(200,restored.status());assertEquals("OPPORTUNITY_OWNER_EXCEPTION",((Map<?,?>)restored.body().get("resultFact")).get("factType"));}
 }
 @Test void coordination_remains_active_and_stale_second_choice_is_rejected()throws Exception{
  setup(false);var s=snapshot(execute(observation).resultFact());var command=decision(CommandEnvelope.Type.RECORD_OPPORTUNITY_OWNER_COORDINATION,s,null);var result=execute(command);assertEquals(CommandOutcome.Status.SUCCEEDED,result.status());assertEquals(OpportunityOwnerExceptionService.State.COORDINATING,snapshot(result.resultFact()).state());assertEquals(result,execute(command));var stale=execute(decision(CommandEnvelope.Type.RECORD_OPPORTUNITY_OWNER_COORDINATION,s,null));assertEquals(CommandOutcome.Status.REJECTED,stale.status());assertEquals("STALE_SUBJECT",stale.rejectionCode());assertEquals("1",scalar("select count(*) from opportunity.owner_exception_disposition where tenant_id=?",seed.tenant()));assertEquals("0",scalar("select count(*) from responsibility.task_occurrence where tenant_id=? and subject_type='opportunity.opportunity'",seed.tenant()));
 }
 @Test void current_read_revocation_blocks_replay_and_get_recovery()throws Exception{
  setup(false);var command=decision(CommandEnvelope.Type.RECORD_OPPORTUNITY_OWNER_COORDINATION,snapshot(execute(observation).resultFact()),null);execute(command);mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=? and grantee_appointment_id=? and authority_code='OPPORTUNITY_OWNER_EXCEPTION_READ'",seed.tenant(),seed.appointment());try(var c=database.apiConnection()){assertThrows(CommandHandler.Rejected.class,()->runtime.execute(c,command));}try(var c=database.apiConnection()){assertEquals(403,new CommandReceiptRecoveryService(policies,protection,null,"T01_RECEIPT_DENY").read(c,seed.request().actor(),command.commandId(),UUID.randomUUID()).status());}
 }
 @Test void simultaneous_distinct_transfers_consume_one_exception_revision()throws Exception{
  setup(false);var s=snapshot(execute(observation).resultFact());var a=decision(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,s,receiver());var b=decision(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,s,receiver());try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var results=pool.invokeAll(List.<java.util.concurrent.Callable<CommandOutcome>>of(()->execute(a),()->execute(b)));var statuses=results.stream().map(f->{try{return f.get().status();}catch(Exception failure){throw new RuntimeException(failure);}}).toList();assertEquals(1,statuses.stream().filter(x->x==CommandOutcome.Status.SUCCEEDED).count());assertEquals(1,statuses.stream().filter(x->x==CommandOutcome.Status.REJECTED).count());}assertEquals("1",scalar("select count(*) from opportunity.responsibility_handoff where tenant_id=?",seed.tenant()));
 }
 @Test void transferred_owner_reads_empty_card_progresses_and_original_progress_receipt_survives_later_handoff()throws Exception {
  setup(false);var initialException=snapshot(execute(observation).resultFact());UUID firstReceiver=receiver();var transfer=execute(decision(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,initialException,firstReceiver));var handed=snapshot(transfer.resultFact());
  Actor firstActor;try(var c=database.apiConnection()){firstActor=inTransaction(c,Capability.QUERY,x->{var r=AuthorizationIdentityReader.databaseBacked().registration(x,seed.tenant(),firstReceiver);return new Actor(seed.tenant(),r.principalId(),firstReceiver,null,null,PrincipalKind.HUMAN);});}
  var cipher=OpportunityProgressProtection.aesGcm(t->new SecretKeySpec(new byte[32],"AES"));
  var ledger=new R2OpportunityLedgerReadService(new byte[32],protection,cipher,io.github.windyzhu3.ontologylaw.audit.AuditAppender.databaseBacked("T03_HANDOFF_IT"));
  try(var c=database.apiConnection()){var detail=ledger.read(c,firstActor,"detail",opportunity.id(),20,null,null,null);assertEquals("Qualified receiver",detail.get("ownerLabel"));assertEquals(true,detail.get("canHandle"));assertEquals(handed.task().id().toString(),((Map<?,?>)detail.get("task")).get("id"));}
  // Regaining sales authority does not restore historical ownership visibility.
  try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{grant(x,"SALES_OPPORTUNITY_OWNER");return null;});}
  try(var c=database.apiConnection()){assertEquals(List.of(),ledger.read(c,seed.request().actor(),"list",null,20,null,null,null).get("items"));}
  assertEquals(seed.appointment().toString(),scalar("select owner_appointment_id from opportunity.opportunity where tenant_id=? and opportunity_id=?",seed.tenant(),opportunity.id()));

  try(var c=database.apiConnection()){var response=new CurrentWorkCardDisclosureService(protection,policies,"T01_HANDOFF_CARD",cipher).read(c,firstActor,UUID.randomUUID(),null,handed.task().id());assertEquals(200,response.status(),response.errorCode());var card=(Map<?,?>)response.body().get("currentCard");assertNotNull(card);assertNull(card.get("actionDraft"));assertEquals(Map.of(),((Map<?,?>)card.get("commandForm")).get("values"));}
  Instant now=Instant.now().truncatedTo(java.time.temporal.ChronoUnit.MICROS);var values=Map.<String,Object>of("progressTypeCode","MEETING","progressSummary","Receiver confirmed the next consultation","occurredAt",now.minusSeconds(2).toString(),"nextCheckAt",now.plusSeconds(86400).toString());
  var save=new CommandEnvelope(CommandEnvelope.Type.SAVE_ACTION_DRAFT,UUID.randomUUID(),UUID.randomUUID(),firstActor,Map.of("actionCode","RECORD_OPPORTUNITY_PROGRESS","schemaVersion",1,"values",values),null,new CommandEnvelope.DraftPrecondition(handed.task().id(),null,"*"));assertEquals(CommandOutcome.Status.SUCCEEDED,execute(save).status());
  CommandEnvelope progress;try(var c=database.apiConnection()){progress=inTransaction(c,Capability.QUERY,x->{var draft=ActionDraftService.databaseBacked().read(x,seed.tenant(),handed.task().id());var task=TaskFactory.databaseBacked().read(x,seed.tenant(),handed.task().id());var body=new TreeMap<String,Object>(values);body.put("draftId",draft.selector().id().toString());body.put("expectedDraftRevision",draft.selector().revision());body.put("draftDigest",draft.digest());return new CommandEnvelope(CommandEnvelope.Type.RECORD_OPPORTUNITY_PROGRESS,UUID.randomUUID(),UUID.randomUUID(),firstActor,body,new CommandEnvelope.TaskPrecondition(task.selector().id(),R1ResourceTags.task(firstActor,task.selector(),task.state(),handed.responsibility().basis())));});}
  var progressed=execute(progress);assertEquals(CommandOutcome.Status.SUCCEEDED,progressed.status());assertEquals("1",scalar("select count(*) from responsibility.task_occurrence where tenant_id=? and subject_id=? and state='WAITING'",seed.tenant(),opportunity.id()));
  mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=? and grantee_appointment_id=? and authority_code='SALES_OPPORTUNITY_OWNER'",seed.tenant(),firstReceiver);
  var reobserve=new CommandEnvelope(observation.type(),UUID.randomUUID(),UUID.randomUUID(),observer,observation.payload());var secondException=snapshot(execute(reobserve).resultFact());var secondReceiver=receiver();var secondTransfer=execute(decision(CommandEnvelope.Type.TRANSFER_OPPORTUNITY_RESPONSIBILITY,secondException,secondReceiver));assertEquals(CommandOutcome.Status.SUCCEEDED,secondTransfer.status());
  mutate("insert into identity.authority_grant (tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values (?,?,?,?,?,'SALES_OPPORTUNITY_OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),firstReceiver,seed.appointment(),seed.org());
  try(var c=database.apiConnection()){var recovered=new CommandReceiptRecoveryService(policies,protection,null,"T01_PROGRESS_RECOVERY").read(c,firstActor,progress.commandId(),UUID.randomUUID());assertEquals(200,recovered.status(),recovered.errorCode());assertEquals("OPPORTUNITY_PROGRESS",((Map<?,?>)recovered.body().get("resultFact")).get("factType"));}
  assertEquals(progressed,execute(progress));
  mutate("insert into identity.object_access_grant (tenant_id,object_access_grant_id,grantee_principal_id,granted_by_appointment_id,access_code,effect_code,valid_from,state,created_at,object_subject_type,object_subject_id,object_subject_hash) values (?,?,?,?,'SALES_OPPORTUNITY_OWNER','DENY',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp(),'opportunity.opportunity_progress',?,?)",seed.tenant(),UUID.randomUUID(),firstActor.principalId(),seed.appointment(),progressed.resultFact().id(),Base64.getUrlDecoder().decode(progressed.resultFact().hash()));
  try(var c=database.apiConnection()){assertEquals(403,new CommandReceiptRecoveryService(policies,protection,null,"T01_PROGRESS_DENY").read(c,firstActor,progress.commandId(),UUID.randomUUID()).status());}
  try(var c=database.apiConnection()){assertThrows(CommandHandler.Rejected.class,()->runtime.execute(c,progress));}
 }

}
