package io.github.windyzhu3.ontologylaw.api;
import io.github.windyzhu3.ontologylaw.payment.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import io.github.windyzhu3.ontologylaw.responsibility.TaskFactory;
import io.github.windyzhu3.ontologylaw.contract.ContractProtection;
import java.sql.*;import java.time.*;import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
class R2PaymentWorkflowIT extends R2ContractExecutionHandoffIT {
 boolean financeAllowed=true,ownerAvailable=true;
 @org.junit.jupiter.api.BeforeEach void resetFinanceFixture(){financeAllowed=true;ownerAvailable=true;}
 PaymentWorkflowService payments(){return PaymentWorkflowService.databaseBacked(PaymentTransactionProtection.hmac(t->new javax.crypto.spec.SecretKeySpec(new byte[32],"HmacSHA256")),new PaymentWorkflowService.Ports(){
  public void lockAuthority(Connection c,Actor actor){}
  public Instant now(Connection c)throws SQLException{return tasks.now(c);}
  public Instant due(Instant start){return new ContractWorkflowPorts(cipher,null).signatureDue(start,ZoneId.of("Asia/Shanghai"));}
  public void authorize(Connection c,Actor a,Subject o,String authority,List<Subject> facts){if(!financeAllowed)throw new PaymentWorkflowService.Blocked("NOT_AUTHORIZED");}
  public UUID owner(Connection c,UUID t,Subject o,String stage){return ownerAvailable?seed.appointment():null;}
  public PaymentWorkflowService.Task task(Connection c,UUID t,UUID id)throws SQLException{var x=tasks.read(c,t,id);return x==null?null:new PaymentWorkflowService.Task(x.selector(),x.owner(),x.state());}
  public PaymentWorkflowService.Task create(Connection c,UUID t,Subject o,UUID owner,String stage,Instant now,Instant due)throws SQLException{var x=tasks.createSignatureTask(c,t,TaskFactory.Type.valueOf(stage.equals("CHECK_RECEIPT")?"CHECK_CONTRACT_RECEIPT":"SUPPLEMENT_CONTRACT_RECEIPT"),owner,o,ZoneId.of("Asia/Shanghai"),now,due);return new PaymentWorkflowService.Task(x.selector(),x.owner(),x.state());}
  public void complete(Connection c,UUID t,PaymentWorkflowService.Task task,Subject result,Instant now)throws SQLException{tasks.complete(c,t,tasks.read(c,t,task.selector().id()),result,now);}
  public void cancel(Connection c,UUID t,PaymentWorkflowService.Task task,Instant now)throws SQLException{tasks.cancelForContract(c,t,tasks.read(c,t,task.selector().id()),"CONTRACT_AUTHORITY_MISSING",now);}
  public void material(Connection c,Actor a,Subject o,UUID id,String sha,String authority)throws SQLException{if(!new ContractWorkflowPorts(cipher,null).documentUsable(c,a.tenantId(),id,sha))throw new PaymentWorkflowService.Blocked("STALE_EVIDENCE");}
  public PaymentWorkflowService.Account account(UUID t){return new PaymentWorkflowService.Account("SYNTHETIC_BANK","合成基本户");}
  public String encode(Map<String,Object> value){return io.github.windyzhu3.ontologylaw.execution.CanonicalJson.encode(value);}
  public Map<String,Object> open(UUID t,UUID o,UUID id,byte[] bytes){return codec().decode(protectedBodies.open(t,o,id,ContractProtection.Kind.PAYMENT,bytes));}
  public byte[] seal(UUID t,UUID o,UUID id,String clear){return protectedBodies.seal(t,o,id,ContractProtection.Kind.PAYMENT,clear);}
 });}
 Subject beginPayment()throws Exception{var source=executionSource();var worker=service("CONTRACT_TASK_RECOVER");try(var c=database.apiConnection()){return inTransaction(c,Capability.COMMAND,x->payments().start(x,worker,opportunity,UUID.fromString((String)((Map<?,?>)source.get("source")).get("id"))));}}
 PaymentReceiptInput receipt(long amount,String reference)throws Exception{return new PaymentReceiptInput(anchor.id(),UUID.fromString(scalar("select current_revision_id from contract.contract where tenant_id=?",seed.tenant())),material,bodySha,reference,amount,"CNY",Instant.parse("2026-01-01T00:00:00Z"),"已人工核对到账归属",true);}
 Subject confirm(Subject workflow,PaymentReceiptInput input)throws Exception{try(var c=database.apiConnection()){return inTransaction(c,Capability.COMMAND,x->payments().confirm(x,actor(),workflow,input));}}
 Subject latestPayment()throws Exception{return new Subject("contract.payment_workflow",UUID.fromString(scalar("select w.payment_workflow_id from contract.payment_workflow w where tenant_id=? and not exists(select 1 from contract.payment_workflow n where n.tenant_id=w.tenant_id and n.previous_workflow_id=w.payment_workflow_id)",seed.tenant())),0L,null);}
 @Test void wrong_contract_revision_or_material_digest_cannot_create_a_receipt()throws Exception{
  var workflow=beginPayment();var valid=receipt(100,"EXACT-ATTRIBUTION");
  for(int mismatch=0;mismatch<3;mismatch++){
   var invalid=new PaymentReceiptInput(mismatch==0?UUID.randomUUID():valid.contractId(),mismatch==1?UUID.randomUUID():valid.contractRevisionId(),valid.materialVersionId(),mismatch==2?(bodySha.equals("0".repeat(64))?"1".repeat(64):"0".repeat(64)):valid.materialSha256(),valid.transactionReference(),valid.amountMinor(),valid.currency(),valid.receivedAt(),valid.explanation(),true);
   assertThrows(PaymentWorkflowService.Blocked.class,()->confirm(workflow,invalid));
   assertEquals(workflow,latestPayment());
   assertEquals("0",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));
  }
  confirm(workflow,valid);assertEquals("1",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));
 }
 @Test void payment_nonprepay_closes_only_finance_and_retains_execution_conditions()throws Exception{var workflow=beginPayment();confirm(workflow,receipt(12345,"TX-1"));assertEquals("1",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));assertEquals("COMPLETE",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));assertEquals("0",scalar("select count(*) from contract.contract_execution where tenant_id=?",seed.tenant()));assertThrows(PaymentWorkflowService.Blocked.class,()->confirm(workflow,receipt(12345,"TX-1")));}
 @Test void payment_partial_retains_same_task_and_deadline_then_completes()throws Exception{receiptRequired=true;var w=beginPayment();String task=scalar("select task_id from contract.payment_workflow where tenant_id=?",seed.tenant());String due=scalar("select due_at from contract.payment_workflow where tenant_id=?",seed.tenant());confirm(w,receipt(4000,"PART1"));var next=latestPayment();try(var c=database.apiConnection()){var view=inTransaction(c,Capability.QUERY,x->payments().context(x,actor(),opportunity)).getFirst();assertEquals(4000L,view.get("confirmedMinor"));assertEquals(6000L,view.get("remainingMinor"));}assertEquals(task,scalar("select task_id from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),next.id()));assertEquals(due,scalar("select due_at from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),next.id()));confirm(next,receipt(6000,"PART2"));assertEquals("COMPLETE",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));assertEquals("10000",scalar("select sum(amount_minor) from contract.payment_confirmation where tenant_id=?",seed.tenant()));}
 @Test void payment_return_requires_no_fake_amount_and_sales_resubmission_creates_no_receipt()throws Exception{var w=beginPayment();try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->payments().returnForCorrection(x,actor(),w,"请补充流水归属"));}var correction=latestPayment();assertEquals("SUPPLEMENT_RECEIPT",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),correction.id()));try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->payments().supplement(x,actor(),correction,material,bodySha,"已补充账户流水"));}assertEquals("CHECK_RECEIPT",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));assertEquals("0",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));}
 @Test void payment_denial_and_audit_failure_leave_no_financial_fact()throws Exception{var w=beginPayment();var input=receipt(12345,"TX-ROLLBACK");financeAllowed=false;assertThrows(PaymentWorkflowService.Blocked.class,()->confirm(w,input));financeAllowed=true;try(var c=database.apiConnection()){assertThrows(IllegalStateException.class,()->inTransaction(c,Capability.COMMAND,x->{payments().confirm(x,actor(),w,input);throw new IllegalStateException("audit append failure");}));}assertEquals("0",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));confirm(w,input);}

 @Test void payment_missing_owner_recovers_without_resetting_original_due()throws Exception{ownerAvailable=false;var w=beginPayment();assertEquals("OWNER_EXCEPTION",scalar("select stage_code from contract.payment_workflow where tenant_id=?",seed.tenant()));String due=scalar("select due_at from contract.payment_workflow where tenant_id=?",seed.tenant());ownerAvailable=true;var worker=service("CONTRACT_TASK_RECOVER");try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->payments().recover(x,worker,w));}assertEquals(due,scalar("select due_at from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));assertEquals("CHECK_RECEIPT",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));}
 @Test void payment_duplicate_transaction_cannot_count_twice_in_partial_workflow()throws Exception{receiptRequired=true;var w=beginPayment();confirm(w,receipt(4000,"DUPLICATE"));var next=latestPayment();assertEquals("PAYMENT_ALREADY_RECORDED",assertThrows(PaymentWorkflowService.Blocked.class,()->confirm(next,receipt(4000,"DUPLICATE"))).code());assertEquals("4000",scalar("select sum(amount_minor) from contract.payment_confirmation where tenant_id=?",seed.tenant()));}

 @Test void payment_production_ports_require_current_finance_authority()throws Exception{executionSource();var real=new PaymentWorkflowPorts(protectedBodies,cipher,null,t->new PaymentWorkflowService.Account("SYNTHETIC_BANK","合成基本户"));try(var c=database.apiConnection()){assertThrows(PaymentWorkflowService.Blocked.class,()->inTransaction(c,Capability.COMMAND,x->{real.lockAuthority(x,actor());real.authorize(x,actor(),opportunity,"PAYMENT_CONFIRM",List.of());return null;}));}for(String code:List.of("PAYMENT_CONFIRM","CONTRACT_READ"))mutate("insert into identity.authority_grant(tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values(?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),seed.appointment(),seed.appointment(),seed.org(),code);try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{real.lockAuthority(x,actor());real.authorize(x,actor(),opportunity,"PAYMENT_CONFIRM",List.of());return null;});}}

 @Test void payment_context_retains_the_selected_finance_chain_after_completion()throws Exception{var w=beginPayment();String task=scalar("select task_id from contract.payment_workflow where tenant_id=?",seed.tenant());confirm(w,receipt(100,"CONTEXT"));try(var c=database.apiConnection()){var views=inTransaction(c,Capability.QUERY,x->payments().context(x,actor(),opportunity));assertEquals(1,views.size());assertEquals("COMPLETE",views.getFirst().get("stage"));assertTrue(((List<?>)views.getFirst().get("taskIds")).contains(task));assertFalse(views.toString().contains("CONTEXT"));assertEquals(List.of("REQUEST_CONTRACT_RECEIPT_REVIEW"),views.getFirst().get("allowedActions"));}}
 @Test void payment_stale_concurrent_confirmation_has_one_winner()throws Exception{var w=beginPayment();var input=receipt(100,"CONCURRENT");try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var call=(java.util.concurrent.Callable<Boolean>)()->{try{confirm(w,input);return true;}catch(PaymentWorkflowService.Blocked rejected){return false;}};var one=pool.submit(call);var two=pool.submit(call);assertNotEquals(one.get(),two.get());}assertEquals("1",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));}

 @Test void payment_worker_discovers_archive_then_only_changed_finance_authority()throws Exception{executionSource();var worker=service("CONTRACT_TASK_RECOVER");PaymentWorkflowService.Recovery first;try(var c=database.apiConnection()){first=inTransaction(c,Capability.QUERY,x->payments().recovery(x,worker,opportunity));assertNotNull(first);assertEquals("contract.signature_archive",first.source().type());assertNull(first.workflow());}try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->payments().reconcile(x,worker,opportunity,first));}try(var c=database.apiConnection()){assertNull(inTransaction(c,Capability.QUERY,x->payments().recovery(x,worker,opportunity)));}ownerAvailable=false;try(var c=database.apiConnection()){var next=inTransaction(c,Capability.QUERY,x->payments().recovery(x,worker,opportunity));assertEquals("contract.payment_request",next.source().type());inTransaction(c,Capability.COMMAND,x->payments().reconcile(x,worker,opportunity,next));}assertEquals("OWNER_EXCEPTION",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),latestPayment().id()));}

 @Test void payment_later_evidence_opens_a_distinct_request_without_reopening_the_closed_one()throws Exception{var first=beginPayment();confirm(first,receipt(100,"FIRST"));var closed=latestPayment();try(var c=database.apiConnection()){var result=inTransaction(c,Capability.COMMAND,x->payments().request(x,actor(),closed,material,bodySha,"后续到账凭证，交财务核对"));assertEquals("contract.payment_request",result.type());}assertEquals("2",scalar("select count(*) from contract.payment_request where tenant_id=?",seed.tenant()));assertEquals("COMPLETE",scalar("select stage_code from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),closed.id()));assertEquals("1",scalar("select count(*) from responsibility.task_occurrence where tenant_id=? and business_purpose_code='CHECK_CONTRACT_RECEIPT' and state='OPEN'",seed.tenant()));assertEquals("1",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));}
 @Test void payment_contract_composition_discovers_and_reconciles_finance_separately()throws Exception{
  executionSource();var worker=service("CONTRACT_TASK_RECOVER");
  var composed=R2ContractServices.create(protectedBodies,cipher,null,payments());
  try(var c=database.apiConnection()){
   var page=inTransaction(c,Capability.QUERY,x->composed.recoveryPage(x,worker,100,null));
   var candidate=page.candidates().stream().filter(v->v.source().type().equals("contract.signature_archive")).findFirst().orElseThrow();
   var payload=new LinkedHashMap<String,Object>();payload.put("opportunityId",opportunity.id().toString());payload.put("expectedOpportunityRevision",opportunity.revision());payload.put("responsibilityBasis",Map.of("id",candidate.basis().id().toString(),"revision",candidate.basis().revision()));payload.put("sourceKind","PAYMENT_HANDOFF");payload.put("source",Map.of("id",candidate.source().id().toString(),"revision",0));payload.put("expectedWorkflow",null);
   var result=inTransaction(c,Capability.COMMAND,x->composed.reconcile(x,worker,payload));assertEquals("contract.payment_workflow",result.type());
   var next=inTransaction(c,Capability.QUERY,x->composed.recoveryPage(x,worker,100,null));assertTrue(next.candidates().stream().noneMatch(v->v.source().type().equals("contract.signature_archive")));
  }
 }
 @Test void payment_recovery_runtime_replays_one_audited_receipt_and_one_event()throws Exception{
  var payload=executionSource();payload.put("sourceKind","PAYMENT_HANDOFF");payload.put("source",Map.of("id",scalar("select signature_archive_id from contract.signature_archive where tenant_id=?",seed.tenant()),"revision",0L));var worker=service("CONTRACT_TASK_RECOVER");
  var composed=R2ContractServices.create(protectedBodies,cipher,null,payments());
  var runtime=R2OpportunityCommandRuntime.fromSourcePolicy(policies,protection,cipher,null,"F10_FINANCE_RECOVERY_IT",composed);
  var envelope=new io.github.windyzhu3.ontologylaw.execution.CommandEnvelope(io.github.windyzhu3.ontologylaw.execution.CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION,UUID.randomUUID(),UUID.randomUUID(),worker,payload);
  try(var c=database.apiConnection()){
   var result=assertInstanceOf(io.github.windyzhu3.ontologylaw.execution.CommandOutcome.class,runtime.execute(c,envelope));assertEquals(io.github.windyzhu3.ontologylaw.execution.CommandOutcome.Status.SUCCEEDED,result.status(),result.rejectionCode());assertEquals(result,runtime.execute(c,envelope));assertEquals("contract.payment_workflow",result.resultFact().type());
  }
  assertEquals("1",scalar("select count(*) from contract.payment_request where tenant_id=?",seed.tenant()));assertEquals("1",scalar("select count(*) from execution.domain_event where tenant_id=? and command_id=? and event_type='ContractPaymentReconciledV1'",seed.tenant(),envelope.commandId()));
 }
 @Test void payment_human_runtime_confirms_once_with_audited_result()throws Exception{
  var workflow=beginPayment();for(String authority:List.of("PAYMENT_CONFIRM","CONTRACT_READ"))mutate("insert into identity.authority_grant(tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values(?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),seed.appointment(),seed.appointment(),seed.org(),authority);
  try(var c=database.apiConnection()){
   UUID taskId=UUID.fromString(scalar("select task_id from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),workflow.id()));var auth=io.github.windyzhu3.ontologylaw.identity.AuthorizationService.databaseBacked();var reader=new io.github.windyzhu3.ontologylaw.execution.SensitiveReadRuntime(auth,io.github.windyzhu3.ontologylaw.audit.AuditAppender.databaseBacked("F10_FINANCE_CARD_IT"));var sources=new CurrentWorkCardSources(auth,protection,policies,cipher);var card=reader.read(c,actor(),UUID.randomUUID(),null,(connection,now)->sources.read(connection,actor(),now,taskId));assertEquals("CHECK_CONTRACT_RECEIPT",((Map<?,?>)card.body().get("currentCard")).get("taskType"));
  }
  var values=new LinkedHashMap<String,Object>();values.put("expectedPaymentWorkflow",Map.of("id",workflow.id().toString(),"revision",0L));values.put("decision","CONFIRM");values.put("explanation","Receipt attribution manually checked");values.put("materialVersionId",material.toString());values.put("materialSha256",bodySha);values.put("transactionReference","RUNTIME-CONFIRM");values.put("amountMinor",100L);values.put("currency","CNY");values.put("receivedAt","2026-01-01T00:00:00Z");values.put("attributionChecked",true);
  var composed=R2ContractServices.create(protectedBodies,cipher,null,payments());try(var c=database.apiConnection()){var reader=new R2ContractReadService(composed,io.github.windyzhu3.ontologylaw.audit.AuditAppender.databaseBacked("F10_FINANCE_LEDGER_IT"));var ledger=reader.ledger(c,actor());assertEquals(true,((Map<?,?>)((List<?>)ledger.get("items")).getFirst()).get("canHandle"));UUID taskId=UUID.fromString(scalar("select task_id from contract.payment_workflow where tenant_id=? and payment_workflow_id=?",seed.tenant(),workflow.id()));var view=reader.task(c,actor(),taskId);assertEquals(1,((List<?>)((Map<?,?>)view.get("context")).get("payments")).size());}
  var runtime=R2OpportunityCommandRuntime.fromSourcePolicy(policies,protection,cipher,null,"F10_FINANCE_HUMAN_IT",composed);
  var envelope=new io.github.windyzhu3.ontologylaw.execution.CommandEnvelope(io.github.windyzhu3.ontologylaw.execution.CommandEnvelope.Type.valueOf("RECORD_CONTRACT_RECEIPT_REVIEW"),UUID.randomUUID(),UUID.randomUUID(),actor(),payload(context(),values));
  try(var c=database.apiConnection()){var result=assertInstanceOf(io.github.windyzhu3.ontologylaw.execution.CommandOutcome.class,runtime.execute(c,envelope));assertEquals(io.github.windyzhu3.ontologylaw.execution.CommandOutcome.Status.SUCCEEDED,result.status(),result.rejectionCode());assertEquals(result,runtime.execute(c,envelope));}
  assertEquals("1",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));assertEquals("1",scalar("select count(*) from execution.domain_event where tenant_id=? and command_id=? and event_type='ContractReceiptReviewRecordedV1'",seed.tenant(),envelope.commandId()));
 }
 @Test void payment_incumbent_finance_owner_is_retained_when_another_qualified_person_is_added()throws Exception{
  executionSource();UUID principal=UUID.randomUUID(),second=UUID.randomUUID();mutate("insert into identity.principal(tenant_id,principal_id,principal_kind,identity_provider_code,external_subject_hmac,display_name,state,created_at) values(?,?,'HUMAN','FIXTURE',?,'Second finance','ACTIVE',clock_timestamp())",seed.tenant(),principal,io.github.windyzhu3.ontologylaw.contract.ContractCanonicalJson.digest(principal.toString()));mutate("insert into identity.appointment(tenant_id,appointment_id,principal_id,organization_unit_id,role_code,effective_from,state,created_at) values(?,?,?,?,'OWNER',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),second,principal,seed.org());
  for(UUID appointment:List.of(seed.appointment(),second))for(String code:List.of("PAYMENT_CONFIRM","CONTRACT_READ"))mutate("insert into identity.authority_grant(tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values(?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),appointment,seed.appointment(),seed.org(),code);
  var real=new PaymentWorkflowPorts(protectedBodies,cipher,null,t->new PaymentWorkflowService.Account("SYNTHETIC_BANK","Synthetic account"));try(var c=database.apiConnection()){inTransaction(c,Capability.QUERY,x->{real.lockAuthority(x,actor());assertNull(real.owner(x,seed.tenant(),opportunity,"CHECK_RECEIPT"));assertEquals(seed.appointment(),real.owner(x,seed.tenant(),opportunity,"CHECK_RECEIPT",seed.appointment()));return null;});}
 }
}
