package io.github.windyzhu3.ontologylaw.api;
import static org.junit.jupiter.api.Assertions.*;
import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;
import io.github.windyzhu3.ontologylaw.execution.*;import io.github.windyzhu3.ontologylaw.opportunity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.util.*;import java.time.*;import javax.crypto.spec.SecretKeySpec;import org.junit.jupiter.api.Test;
class R2QuoteHttpIT extends R1HttpFixture {
 Subject opportunity;
 void setupQuote()throws Exception{setupContact();opportunityProtection=OpportunityProgressProtection.aesGcm(t->new SecretKeySpec(new byte[32],"AES"));var contact=execute(prepare(contact("CONNECTED_VALID")));try(var c=database.apiConnection()){opportunity=inTransaction(c,Capability.COMMAND,x->{for(String code:List.of("SALES_OPPORTUNITY_OWNER","CUSTOMER_REQUIREMENTS_MANAGE","QUOTE_READ","QUOTE_PREPARE","QUOTE_APPROVE","QUOTE_DELIVER","QUOTE_RESPONSE"))grant(x,code);return EventOpportunityReader.databaseBacked().forContact(x,seed.tenant(),contact.resultFact().id()).selector();});}runtime=R2OpportunityCommandRuntime.fromSourcePolicy(policies,protection,opportunityProtection,null,"T07_HTTP");var p=new LinkedHashMap<String,Object>();p.put("opportunityId",opportunity.id().toString());p.put("expectedOpportunityRevision",opportunity.revision());p.put("responsibilityBasis",R2CustomerRequirementsServices.selector(opportunity));p.put("expectedDraft",null);p.put("expectedConfirmation",null);p.put("document",Map.of("participants",List.of(Map.of("role","CLIENT","newParty",Map.of("kind","ORGANIZATION","name","T07 HTTP 客户","distinctIdentityConfirmed",true))),"unknownOpponent",true,"matterName","报价测试","customerGoal","确认销售报价","serviceScope","法律咨询","knownConstraints","","contactName","测试联系人","contactPhone",""));var saved=execute(new CommandEnvelope(CommandEnvelope.Type.SAVE_OPPORTUNITY_CUSTOMER_DRAFT,UUID.randomUUID(),UUID.randomUUID(),seed.request().actor(),p));assertEquals(CommandOutcome.Status.SUCCEEDED,saved.status());p.remove("document");p.put("expectedDraft",R2CustomerRequirementsServices.selector(saved.resultFact()));assertEquals(CommandOutcome.Status.SUCCEEDED,execute(new CommandEnvelope(CommandEnvelope.Type.CONFIRM_OPPORTUNITY_CUSTOMER_REQUIREMENTS,UUID.randomUUID(),UUID.randomUUID(),seed.request().actor(),p)).status());}
 Map<String,Object> commandBody(Map<String,Object> ctx,Map<String,Object> values){var p=new LinkedHashMap<String,Object>();p.put("expectedOpportunityRevision",((Map<?,?>)ctx.get("opportunity")).get("revision"));p.put("responsibilityBasis",ctx.get("responsibilityBasis"));p.put("customerConfirmation",ctx.get("customerConfirmation"));for(var pair:List.of(new String[]{"draft","expectedDraft"},new String[]{"quote","expectedQuote"},new String[]{"workflow","expectedWorkflow"})){var v=(Map<?,?>)ctx.get(pair[0]);p.put(pair[1],v==null?null:v.get("selector"));}p.put("values",values);return p;}
 // RFC3339 permits differing trailing fractional zeroes; every other receipt field stays exact.
 static void assertSameReceipt(Map<String,Object> a,Map<String,Object> b){var left=new LinkedHashMap<>(a);var right=new LinkedHashMap<>(b);for(var receipt:List.of(left,right))receipt.computeIfPresent("completedAt",(key,value)->Instant.parse(value.toString()).toString());assertEquals(left,right);}
 @Test void preparationIntentHttpAndOriginalReceiptAreReachable()throws Exception{setupQuote();String base="/api/v1/opportunities/"+opportunity.id()+"/quotes";try(var http=new HttpHarness()){
  var ctx=http.body(http.request("GET",base,null,Map.of()));String key=UUID.randomUUID().toString();var body=commandBody(ctx,Map.of());
  var started=http.request("POST",base+"/preparation-intents",body,Map.of("Idempotency-Key",key));assertEquals(200,started.statusCode(),started.body());
  assertEquals("QUOTE_PREPARATION_INTENT",((Map<?,?>)http.body(started).get("resultFact")).get("factType"));
  assertSameReceipt(http.body(started),http.body(http.request("POST",base+"/preparation-intents",body,Map.of("Idempotency-Key",key))));
  assertSameReceipt(http.body(started),http.body(http.request("GET","/api/v1/commands/"+key+"/receipt",null,Map.of())));
  ctx=http.body(http.request("GET",base,null,Map.of()));assertNull(ctx.get("quote"));assertEquals("PREPARE",((Map<?,?>)ctx.get("workflow")).get("stage"));
 }}
 @Test void authenticatedQuoteDraftReplayDocumentAndTaskContextAreReachable()throws Exception{setupQuote();String base="/api/v1/opportunities/"+opportunity.id()+"/quotes";try(var http=new HttpHarness()){
  var get=http.request("GET",base,null,Map.of());assertEquals(200,get.statusCode(),get.body());var ctx=http.body(get);assertEquals("no-store",get.headers().firstValue("Cache-Control").orElse(""));
  var commercial=Map.<String,Object>of("currency","CNY","scope","仅本次服务","lines",List.of(Map.of("description","服务费","amountMinor",10000,"discount",false)),"paymentTerms","按约定付款","validUntil",Instant.now().plusSeconds(86400).truncatedTo(java.time.temporal.ChronoUnit.MICROS).toString());var body=commandBody(ctx,commercial);var key=UUID.randomUUID().toString();
  assertEquals(400,http.request("POST",base+"/draft",body,Map.of()).statusCode());assertEquals(400,http.request("POST",base+"/draft",body,Map.of("Idempotency-Key",key,"If-Match","fake")).statusCode());
  var save=http.request("POST",base+"/draft",body,Map.of("Idempotency-Key",key));assertEquals(200,save.statusCode(),save.body());assertEquals("QUOTE_DRAFT",((Map<?,?>)http.body(save).get("resultFact")).get("factType"));assertSameReceipt(http.body(save),http.body(http.request("POST",base+"/draft",body,Map.of("Idempotency-Key",key))));
  var receipt=http.request("GET","/api/v1/commands/"+key+"/receipt",null,Map.of());assertEquals(200,receipt.statusCode(),receipt.body());
  ctx=http.body(http.request("GET",base,null,Map.of()));var formed=http.request("POST",base+"/form",commandBody(ctx,Map.of()),Map.of("Idempotency-Key",UUID.randomUUID().toString()));assertEquals(200,formed.statusCode(),formed.body());assertEquals("QUOTE_REVISION",((Map<?,?>)http.body(formed).get("resultFact")).get("factType"));
  ctx=http.body(http.request("GET",base,null,Map.of()));var quote=(Map<?,?>)ctx.get("quote");String qid=(String)((Map<?,?>)quote.get("selector")).get("id");var document=http.request("GET",base+"/"+qid+"/document",null,Map.of());assertEquals(200,document.statusCode(),document.body());assertTrue(document.body().contains("T07 HTTP 客户"));assertTrue(document.body().contains("100.00"));
  var workflow=(Map<?,?>)ctx.get("workflow");var task=(Map<?,?>)workflow.get("task");var taskContext=http.request("GET","/api/v1/quote-tasks/"+task.get("id")+"/context",null,Map.of());assertEquals(200,taskContext.statusCode(),taskContext.body());assertEquals(opportunity.id().toString(),http.body(taskContext).get("opportunityId"));
  var cardResponse=http.request("GET","/api/v1/workcards/current?taskId="+task.get("id"),null,Map.of());assertEquals(200,cardResponse.statusCode(),cardResponse.body());var card=(Map<?,?>)http.body(cardResponse).get("currentCard");assertEquals(task.get("id"),card.get("taskId"));assertTrue(((String)card.get("taskType")).contains("QUOTE"));
  // A progressed quote must not invalidate recovery of the original committed save.
  assertSameReceipt(http.body(save),http.body(http.request("GET","/api/v1/commands/"+key+"/receipt",null,Map.of())));
  mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=? and authority_code='QUOTE_READ'",seed.tenant());assertEquals(403,http.request("GET",base,null,Map.of()).statusCode());assertEquals(403,http.request("GET",base+"/"+qid+"/document",null,Map.of()).statusCode());
 }}
}
