package io.github.windyzhu3.ontologylaw.api;
import java.util.*;import java.nio.file.Files;import java.nio.file.Path;import static org.junit.jupiter.api.Assertions.*;import static io.github.windyzhu3.ontologylaw.execution.internal.persistence.CapabilityRoleExecutor.*;import io.github.windyzhu3.ontologylaw.identity.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;import io.github.windyzhu3.ontologylaw.transfer.*;import io.github.windyzhu3.ontologylaw.opportunity.EventOpportunityReader;
/** Continues the same HTTP-imported sales record; system preparation uses the same discovery/reconcile path as the worker. */
class R2TransferHttpIT extends R2ContractPaymentHttpIT {
 Actor intakeActor;UUID intakeOrganization;
 @Override UUID transferDestination(UUID tenant){return intakeOrganization;}
 @Override void registerActors(Actor entryApprover){super.registerActors(entryApprover);try{
  intakeOrganization=UUID.randomUUID();mutate("insert into identity.organization_unit(tenant_id,organization_unit_id,parent_organization_unit_id,unit_code,display_name,state,created_at) values(?,?,?,'F11_HTTP_INTAKE','Synthetic intake','ACTIVE',clock_timestamp())",seed.tenant(),intakeOrganization,seed.org());
  var credential=credentialActor(PrincipalKind.HUMAN,"F11 intake","TRANSFER_REVIEW");UUID appointment=UUID.randomUUID();mutate("insert into identity.appointment(tenant_id,appointment_id,principal_id,organization_unit_id,role_code,effective_from,state,created_at) values(?,?,?,?,'CONTACT_OPERATOR',clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),appointment,credential.principalId(),intakeOrganization);intakeActor=new Actor(seed.tenant(),credential.principalId(),appointment,null,null,PrincipalKind.HUMAN);
  for(String code:List.of("TRANSFER_REVIEW","TRANSFER_ACCEPT","MATTER_CLASSIFY","MATTER_RECEIVE","CONTRACT_READ"))mutate("insert into identity.authority_grant(tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values(?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),appointment,seed.appointment(),intakeOrganization,code);
  try(var c=database.apiConnection()){inTransaction(c,Capability.COMMAND,x->{grant(x,"TRANSFER_SUBMIT");return null;});}
  var registry=new ArrayList<io.github.windyzhu3.ontologylaw.api.security.ActorContextResolver.Registration>();for(var actor:List.of(seed.request().actor(),entryApprover,conflictReviewer,contractApprover,signatureVerifier,finance,intakeActor))registry.add(new io.github.windyzhu3.ontologylaw.api.security.ActorContextResolver.Registration(ISSUER,AUDIENCE,"FIXTURE",actor));realHumanResolver=new io.github.windyzhu3.ontologylaw.api.security.ActorContextResolver(database::apiConnection,new ExternalSubjectProtection(credentialKeys::get),List.of(new io.github.windyzhu3.ontologylaw.api.security.ActorContextResolver.Trust(ISSUER,AUDIENCE,(java.security.interfaces.RSAPublicKey)signing.getPublic())),registry);
 }catch(Exception e){throw new IllegalStateException(e);}}
 TransferWorkflowReader.State currentTransfer()throws Exception{UUID request=UUID.fromString(scalar("select transfer_request_id from transfer.transfer_request where tenant_id=?",seed.tenant()));try(var c=database.apiConnection()){return inTransaction(c,Capability.QUERY,x->TransferWorkflowReader.databaseBacked().current(x,seed.tenant(),request));}}
 Map<String,Object> transferStep(RoleHttp role,String action,Map<String,Object> values)throws Exception{var state=currentTransfer();var body=Map.<String,Object>of("expectedOpportunityRevision",state.opportunity().revision(),"expectedWorkflow",Map.of("id",state.workflow().id().toString(),"revision",0L),"values",values);String path="/api/v1/opportunities/"+opportunity.id()+"/transfers/"+action,key=UUID.randomUUID().toString();var result=role.request("POST",path,body,Map.of("Idempotency-Key",key));assertEquals(200,result.statusCode(),"POST "+action+": "+result.body());var replay=role.request("POST",path,body,Map.of("Idempotency-Key",key));assertEquals(200,replay.statusCode(),"REPLAY "+action+": "+replay.body());assertSameReceipt(role.body(result),role.body(replay));var receipt=role.request("GET","/api/v1/commands/"+key+"/receipt",null,Map.of());assertEquals(200,receipt.statusCode(),"RECEIPT "+action+": "+receipt.body());assertSameReceipt(role.body(result),role.body(receipt));return role.body(result);}
 @Override void continueContractPreparation(HttpHarness http)throws Exception{
  super.continueContractPreparation(http);var sales=new RoleHttp(http,SUBJECT);var intake=new RoleHttp(http,"F11 intake");byte[] pdf=Files.readAllBytes(Path.of(System.getProperty("ols.contract.fixtureTemplate")));var proof=acceptedMaterial(context(sales),pdf,"F11-synthetic-transfer-proof.pdf");var worker=service("CONTRACT_TASK_RECOVER");var services=http.context.getBean(R1ApiServices.class);
  Map<String,Object> candidate=null;String cursor=null;for(int page=0;page<20;page++){var found=services.contractCandidates(worker,20,cursor);for(var raw:(List<?>)found.get("candidates")){var row=(Map<String,Object>)raw;if("TRANSFER_HANDOFF".equals(row.get("sourceKind")))candidate=row;}cursor=(String)found.get("nextCursor");if(cursor==null)break;}
  assertNotNull(candidate,"Activated execution must yield an automatic transfer handoff");var payload=new LinkedHashMap<String,Object>(candidate);UUID commandId=UUID.fromString((String)payload.remove("idempotencyKey"));payload.remove("kind");var command=new io.github.windyzhu3.ontologylaw.execution.CommandEnvelope(io.github.windyzhu3.ontologylaw.execution.CommandEnvelope.Type.RECONCILE_CONTRACT_PREPARATION,commandId,UUID.randomUUID(),worker,payload);var prepared=services.contractCommand(command);assertEquals(200,prepared.status(),prepared.errorCode());assertEquals(prepared.body(),services.contractCommand(command).body());assertEquals("TRANSFER_WORKFLOW",((Map<?,?>)prepared.body().get("resultFact")).get("factType"));

  var material=Map.of("versionId",proof.id().toString(),"sha256",sha(pdf));transferStep(sales,"submissions",Map.of("clientIdentity",material,"signatureArchive",material,"explanation","Synthetic complete transfer","consistencyChecked",true,"corrections",List.of()));var review=currentTransfer();assertEquals("REVIEW_TRANSFER",review.stage());assertNull(review.matterId());var card=intake.request("GET","/api/v1/workcards/current?taskId="+review.taskId(),null,Map.of());assertEquals(200,card.statusCode(),card.body());assertEquals("REVIEW_TRANSFER",((Map<?,?>)intake.body(card).get("currentCard")).get("taskType"));
  transferStep(intake,"conflict-reviews",Map.of("outcome","CLEAR","explanation","Independent review confirmed","scopeChecked",true));assertNull(currentTransfer().matterId());var accept=new LinkedHashMap<String,Object>();accept.put("decision","ACCEPT");accept.put("requirement",null);accept.put("explanation","Case manager accepted");accept.put("acceptanceChecked",true);transferStep(intake,"intake-decisions",accept);var accepted=currentTransfer();assertNotNull(accepted.matterId());assertNull(accepted.category());transferStep(intake,"classifications",Map.of("matterId",accepted.matterId().toString(),"category","GENERAL","recipient",intakeActor.appointmentId().toString(),"explanation","Confirmed receiving appointment"));var complete=currentTransfer();assertEquals("COMPLETE",complete.stage());assertEquals(accepted.matterId(),complete.matterId());assertEquals("GENERAL",complete.category());assertEquals("2",scalar("select count(*) from contract.payment_confirmation where tenant_id=?",seed.tenant()));
 }
}
