import {useWorkcardMaster} from '../workcard/useWorkcardMaster';
import {useEffect,useRef,useState} from 'react';
import type {WorkbenchSession} from '../../lib/api';
import type {ClassificationCorrectionContext,TransfersTransport} from '../../lib/transfersTransport';
import {TransportError} from '../../lib/sessionTransport';
import {MatterClassification,type MatterClassificationInput} from './MatterClassification';
import {classificationPayload} from './transferPayload';
/** Approved Q1 correction, rendered inside the shared workbench frame. */
export function ClassificationCorrectionCard({session,opportunityId,api,onBack,onDirtyChange,onLockedChange}:{session:WorkbenchSession;opportunityId:string;api:TransfersTransport;onBack:()=>void;onDirtyChange:(dirty:boolean)=>void;onLockedChange:(locked:boolean)=>void}){
 useWorkcardMaster();
 const [loaded,setLoaded]=useState<{session:WorkbenchSession;id:string;value:ClassificationCorrectionContext}|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(!!api.recovery.read()),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const active=useRef(session);active.current=session;const sending=useRef(false),locked=useRef(onLockedChange);locked.current=onLockedChange;const valid=()=>active.current===session&&session.isCurrent();
 const context=loaded?.session===session&&loaded.id===opportunityId&&session.isCurrent()?loaded.value:null;
 useEffect(()=>{locked.current(busy||pending);return()=>locked.current(false);},[busy,pending]);
 useEffect(()=>{let live=true;const c=new AbortController();setLoaded(null);setError('');setPending(!!api.recovery.read());api.classificationContext(session,opportunityId,c.signal).then(value=>{if(live&&active.current===session&&session.isCurrent())setLoaded({session,id:opportunityId,value});}).catch(()=>{if(live)setError('当前分类或权限已变化，请重新读取或返回台账。');});return()=>{live=false;c.abort();};},[session,opportunityId,api,refresh]);
 function finish(){onDirtyChange(false);setLoaded(null);onBack();}
 async function submit(input:MatterClassificationInput){if(!context||sending.current||pending||!valid())return false;sending.current=true;setBusy(true);setError('');try{await api.write(session,{key:crypto.randomUUID(),opportunityId,command:'CLASSIFY_MATTER',body:{expectedOpportunityRevision:context.expectedOpportunityRevision,expectedWorkflow:context.expectedWorkflow,values:classificationPayload(input)}},new AbortController().signal);if(!valid())return false;finish();return true;}catch(e){if(!valid())return false;const unresolved=!!api.recovery.read();setPending(unresolved);setError(unresolved?'本次更正结果尚未确认，请核对原回执。':e instanceof Error?e.message:'更正未完成，请重新核对。');if(e instanceof TransportError&&[401,403,404,412].includes(e.status))setLoaded(null);return false;}finally{sending.current=false;setBusy(false);}}
 async function recover(){if(sending.current||!valid())return;sending.current=true;setBusy(true);try{await api.receipt(session,new AbortController().signal);if(valid()){setPending(false);finish();}}catch(e){if(valid()){setPending(!!api.recovery.read());setError(e instanceof Error?e.message:'原结果尚未确认');if(!api.recovery.read())setLoaded(null);}}finally{sending.current=false;setBusy(false);}}
 return <div className="embedded-workcard"><article className="work-card"><div className="context"><p className="eyebrow">当前办理</p><h1>更正案件分类及承接</h1>{context&&<><p className="subject">{context.customerName}</p><p className="owner-line">{session.displayName??'当前任职'}</p><p className="known-title">已知信息</p><ul className="facts"><li>已由案管接收并完成分类。</li><li>更正保留原案件编号和分类历史。</li></ul></>}</div><section className="card-action">{error&&<p role="alert">{error}</p>}{pending?<><h2>核对本次更正结果</h2><button className="primary" disabled={busy} onClick={()=>void recover()}>核对原回执</button></>:context?<MatterClassification key={context.expectedWorkflow.id} matter={context.matter} receivers={context.receivers} correction={{category:context.category,recipientId:context.recipient?.id??null,recipientLabel:context.recipient?.label??'原承接任职当前不可用，请重新选择'}} disabled={busy} submit={submit} onDirty={()=>onDirtyChange(true)}/>:<><p role="status">{error?'请重新核对当前分类。':'正在读取案件分类…'}</p>{error&&<button className="secondary" disabled={busy} onClick={()=>setRefresh(n=>n+1)}>重新读取</button>}</>}{!pending&&<button className="link-button" disabled={busy} onClick={()=>{if(valid())finish();}}>取消更正</button>}</section></article></div>;
}
