import {it,expect,vi,beforeEach} from 'vitest';
import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {TransferRuntimeCard} from './TransferRuntimeCard';
import {RecoveryStore} from '../session/recoveryMarker';
import type {TransferContext,TransfersTransport} from '../../lib/transfersTransport';
import {testSession,taskId,selectorId} from '../../test/fixtures';
beforeEach(()=>sessionStorage.clear());
const context:TransferContext={opportunityId:selectorId,expectedOpportunityRevision:0,expectedWorkflow:{id:selectorId,revision:0},taskId,stage:'CLASSIFY',dueAt:'2026-09-28T00:00:00Z',allowedAction:'CLASSIFY_MATTER',customerName:'合成客户',contract:{id:selectorId,version:1,scope:'委托范围',paymentTerms:'按合同约定',signingRequirements:'签署要求',receiptRequiredBeforeTransfer:false},submission:{clientIdentity:{versionId:selectorId,sha256:'a'.repeat(64)},signatureArchive:{versionId:selectorId,sha256:'a'.repeat(64)},explanation:'交接说明',consistencyChecked:true,corrections:[]},review:{outcome:'CLEAR',explanation:'独立核对'},intake:{decision:'ACCEPT',explanation:'已接收'},matter:{id:selectorId,number:'合成案件001'},materials:[],returnItems:[],reviewPreview:null,receivers:[{id:taskId,label:'合成承接人'}]};
function setup(value:TransferContext=context){const recovery=new RecoveryStore(sessionStorage),api={recovery,taskContext:vi.fn().mockResolvedValue(value),write:vi.fn().mockResolvedValue({outcome:'SUCCEEDED'}),receipt:vi.fn().mockResolvedValue({outcome:'SUCCEEDED'})} as unknown as TransfersTransport,onTasks=vi.fn(),dirty=vi.fn(),locked=vi.fn(),session=testSession();render(<TransferRuntimeCard session={session} taskId={taskId} api={api} onTasks={onTasks} onDirtyChange={dirty} onLockedChange={locked}/>);return {api,onTasks,dirty,locked,session};}
it('submits classification for the accepted case and leaves the completed form',async()=>{const {api,onTasks,dirty}=setup();await screen.findByText('合成案件001');fireEvent.change(screen.getByLabelText('业务分类'),{target:{value:'GENERAL'}});fireEvent.change(screen.getByLabelText('承接人'),{target:{value:taskId}});fireEvent.change(screen.getByLabelText('分类说明'),{target:{value:'确认承接'}});fireEvent.click(screen.getByRole('button',{name:'确认分类及承接'}));await waitFor(()=>expect(onTasks).toHaveBeenCalledOnce());expect(api.write).toHaveBeenCalledWith(expect.anything(),expect.objectContaining({command:'CLASSIFY_MATTER',body:{expectedOpportunityRevision:0,expectedWorkflow:context.expectedWorkflow,values:{matterId:selectorId,category:'GENERAL',recipient:taskId,explanation:'确认承接'}}}),expect.anything());expect(dirty).toHaveBeenLastCalledWith(false);expect(screen.queryByRole('button',{name:'确认分类及承接'})).not.toBeInTheDocument();});
it('locks an uncertain write and recovers its original receipt instead of submitting again',async()=>{const {api,onTasks,session}=setup();vi.mocked(api.write).mockImplementation(async(_s,w)=>{api.recovery.reserveWrite(w.key,w.command,session.actorScopeKey,w);throw Error('network lost');});await screen.findByText('合成案件001');fireEvent.change(screen.getByLabelText('业务分类'),{target:{value:'GENERAL'}});fireEvent.change(screen.getByLabelText('承接人'),{target:{value:taskId}});fireEvent.change(screen.getByLabelText('分类说明'),{target:{value:'确认承接'}});fireEvent.click(screen.getByRole('button',{name:'确认分类及承接'}));fireEvent.click(await screen.findByRole('button',{name:'核对原回执'}));await waitFor(()=>expect(onTasks).toHaveBeenCalledOnce());expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();});
