import {useWorkcardMaster} from '../workcard/useWorkcardMaster';
import {useEffect,useRef,useState} from 'react';
import type {WorkbenchSession} from '../../lib/api';
import {TransportError} from '../../lib/sessionTransport';
import type {TransferContext,TransferCommand,TransfersTransport} from '../../lib/transfersTransport';
import {TransferPreparation,type TransferPreparationInput} from './TransferPreparation';
import {TransferCorrection} from './TransferCorrection';
import {TransferConflictReview} from './TransferConflictReview';
import {TransferReview} from './TransferReview';
import {MatterClassification} from './MatterClassification';
import {correctionPayload,classificationPayload} from './transferPayload';
const titles={PREPARE:'准备转案材料',SUPPLEMENT:'补正转案材料',REVIEW_TRANSFER:'转案前独立冲突审查',INTAKE:'核对转案接收',CLASSIFY:'确认案件分类及承接'};
export function TransferRuntimeCard({session,taskId,api,onTasks,onDirtyChange,onLockedChange}:{session:WorkbenchSession;taskId:string;api:TransfersTransport;onTasks:()=>void;onDirtyChange:(dirty:boolean)=>void;onLockedChange:(locked:boolean)=>void}){
 useWorkcardMaster();
 const [loaded,setLoaded]=useState<{session:WorkbenchSession;taskId:string;value:TransferContext}|null>(null),[error,setError]=useState(''),[pending,setPending]=useState(false),[busy,setBusy]=useState(false),[refresh,setRefresh]=useState(0);
 const current=useRef(session);current.current=session;const sending=useRef(false);const lockedCallback=useRef(onLockedChange);lockedCallback.current=onLockedChange;
 const valid=()=>current.current===session&&session.isCurrent();
 useEffect(()=>{lockedCallback.current(busy||pending);return()=>lockedCallback.current(false);},[busy,pending]);
 useEffect(()=>{const controller=new AbortController();let live=true;setLoaded(null);setError('');const marker=api.recovery.read();setPending(!!marker);api.taskContext(session,taskId,controller.signal).then(value=>{if(live&&current.current===session&&session.isCurrent())setLoaded({session,taskId,value});}).catch(()=>{if(live)setError('当前责任或内容已变化，请重新读取或查看我的待办。');});return()=>{live=false;controller.abort();};},[session,taskId,api,refresh]);
 const context=loaded?.session===session&&loaded.taskId===taskId&&session.isCurrent()?loaded.value:null;
 async function submit(values:Record<string,unknown>){if(!context||sending.current||pending||!valid())return false;sending.current=true;setBusy(true);setError('');try{await api.write(session,{key:crypto.randomUUID(),opportunityId:context.opportunityId,command:context.allowedAction as TransferCommand,body:{expectedOpportunityRevision:context.expectedOpportunityRevision,expectedWorkflow:context.expectedWorkflow,values}},new AbortController().signal);if(!valid())return false;onDirtyChange(false);setLoaded(null);onTasks();return true;}catch(e){if(!valid()){setLoaded(null);return false;}const unresolved=!!api.recovery.read();setPending(unresolved);setError(unresolved?'本次提交结果尚未确认，请核对原回执。':e instanceof Error?e.message:'提交未完成，请核对后重试。');if(e instanceof TransportError&&[401,403,404,412].includes(e.status))setLoaded(null);return false;}finally{sending.current=false;setBusy(false);}}
 async function recover(){if(sending.current||!valid())return;sending.current=true;setBusy(true);try{await api.receipt(session,new AbortController().signal);if(valid()){setPending(false);onDirtyChange(false);setLoaded(null);onTasks();}}catch(e){if(valid()){setPending(!!api.recovery.read());setError(e instanceof Error?e.message:'原结果尚未确认');if(!api.recovery.read())setLoaded(null);}}finally{sending.current=false;setBusy(false);}}
 async function download(id:string,label:string){if(!context||!valid()||busy||pending)return;try{const blob=await api.download(session,taskId,id,new AbortController().signal);if(!valid())return;const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=context.materials.find(m=>m.id===id)?.fileName??label;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){if(valid()){setError(e instanceof Error?e.message:'材料读取失败');if(e instanceof TransportError&&[401,403,404].includes(e.status))setLoaded(null);}}}
 const changed=()=>onDirtyChange(true),disabled=busy||pending;
 return <div className="embedded-workcard"><article className="work-card"><div className="context"><p className="eyebrow">当前责任</p><h1>{context?titles[context.stage]:'转案办理'}</h1>{context&&<><p className="subject">{context.customerName}</p><p className="owner-line">{session.displayName??'当前任职'} · {new Date(context.dueAt).toLocaleString('zh-CN')}</p><p className="known-title">已知信息</p><ul className="facts"><li>当前合同 · 第 {context.contract.version} 版 · 签署已归档</li><li>{context.contract.receiptRequiredBeforeTransfer?'已按合同约定核对转案前到账条件':'本合同不要求先款；收款核对独立保留'}</li></ul><details className="history"><summary>合同与本次交接依据</summary><p>委托范围：{context.contract.scope}</p><p>付款约定：{context.contract.paymentTerms}</p><p>签署要求：{context.contract.signingRequirements}</p>{context.submission&&<><p>交接说明：{context.submission.explanation}</p><div className="ledger-detail-actions"><button className="link-button" disabled={disabled} onClick={()=>void download(context.submission!.clientIdentity.versionId,'委托主体证明.bin')}>查看本次委托主体证明</button><button className="link-button" disabled={disabled} onClick={()=>void download(context.submission!.signatureArchive.versionId,'完整签署归档.bin')}>查看本次签署归档</button></div></>}{context.review&&<p>审查说明：{context.review.explanation}</p>}{context.intake&&<p>案管说明：{context.intake.explanation}</p>}</details></>}</div><section className="card-action">
 {error&&<p role="alert">{error}</p>}{pending?<><h2>核对本次提交结果</h2><p>保留原请求，确认原回执后再继续办理。</p><button className="primary" disabled={busy} onClick={()=>void recover()}>核对原回执</button></>:!context?<><p role="status">{error?'请重新读取当前责任。':'正在读取转案资料…'}</p>{error&&<button className="secondary" disabled={busy} onClick={()=>setRefresh(n=>n+1)}>重新读取</button>}</>:<>
 {context.stage==='PREPARE'&&<TransferPreparation materials={context.materials} submit={submit} onDirty={changed} disabled={disabled}/>}
 {context.stage==='SUPPLEMENT'&&context.submission&&<TransferCorrection items={context.returnItems} materials={context.materials} submit={input=>submit(correctionPayload(context.submission as TransferPreparationInput,context.returnItems,input))} onDirty={changed} disabled={disabled}/>}
 {context.stage==='REVIEW_TRANSFER'&&context.reviewPreview&&<><p>{context.reviewPreview.scopeComplete?'本次主体范围已完整登记':'主体范围不完整，需补充后重新审查'} · 待核对冲突候选 {context.reviewPreview.candidateCount} 项</p><TransferConflictReview outcomes={context.reviewPreview.permittedOutcomes} submit={submit} onDirty={changed} disabled={disabled}/></>}
 {context.stage==='INTAKE'&&<TransferReview canAccept={context.review?.outcome==='CLEAR'} submit={input=>submit(input.decision==='ACCEPT'?{...input,requirement:null}:{...input,acceptanceChecked:false})} onDirty={changed} disabled={disabled}/>}
 {context.stage==='CLASSIFY'&&<MatterClassification matter={context.matter} receivers={context.receivers} submit={input=>submit(classificationPayload(input))} onDirty={changed} disabled={disabled}/>}
 </>}
 </section></article></div>;
}
