package io.github.windyzhu3.ontologylaw.party.internal.persistence;
import io.github.windyzhu3.ontologylaw.party.CustomerPartyProfiles;

import java.sql.*;import java.util.*;
public final class JdbcCustomerPartyProfiles implements CustomerPartyProfiles {
 public Profile current(Connection c,UUID tenant,UUID id,boolean lock)throws SQLException{try(var p=c.prepareStatement("select revision,party_type,canonical_name from party.party where tenant_id=? and party_id=? and status='ACTIVE' and merged_into_party_id is null"+(lock?" for update":""))){p.setObject(1,tenant);p.setObject(2,id);try(var r=p.executeQuery()){return r.next()?new Profile(new Selector(id,r.getLong(1)),"PERSON".equals(r.getString(2))?"NATURAL_PERSON":"ORGANIZATION",r.getString(3)):null;}}}
 public Profile create(Connection c,UUID tenant,String kind,String name)throws SQLException{var id=UUID.randomUUID();try(var p=c.prepareStatement("insert into party.party(tenant_id,party_id,party_type,canonical_name,status,revision) values(?,?,?,?,'ACTIVE',0)")){p.setObject(1,tenant);p.setObject(2,id);p.setString(3,"NATURAL_PERSON".equals(kind)?"PERSON":"ORGANIZATION");p.setString(4,name);p.executeUpdate();}return current(c,tenant,id,false);}
 public Profile rename(Connection c,UUID tenant,Selector exact,String name)throws SQLException{try(var p=c.prepareStatement("update party.party set canonical_name=?,revision=revision+1 where tenant_id=? and party_id=? and revision=? and status='ACTIVE' and revision<9007199254740991")){p.setString(1,name);p.setObject(2,tenant);p.setObject(3,exact.id());p.setLong(4,exact.revision());if(p.executeUpdate()!=1)throw new SQLException("Party changed","40001");}return current(c,tenant,exact.id(),false);}
 public Version snapshot(Connection c,UUID tenant,Profile profile,UUID actor)throws SQLException{try(var p=c.prepareStatement("select profile_version_id from party.profile_version where tenant_id=? and party_id=? and party_revision=?")){p.setObject(1,tenant);p.setObject(2,profile.selector().id());p.setLong(3,profile.selector().revision());try(var r=p.executeQuery()){if(r.next())return new Version(new Selector(r.getObject(1,UUID.class),0L),profile);}}
 var id=UUID.randomUUID();try(var p=c.prepareStatement("insert into party.profile_version(tenant_id,profile_version_id,revision,party_id,party_revision,party_type,canonical_name,created_by_appointment_id,created_at) values(?,?,0,?,?,?,?,?,clock_timestamp())")){Object[] a={tenant,id,profile.selector().id(),profile.selector().revision(),"NATURAL_PERSON".equals(profile.kind())?"PERSON":"ORGANIZATION",profile.name(),actor};for(int i=0;i<a.length;i++)p.setObject(i+1,a[i]);p.executeUpdate();}return new Version(new Selector(id,0L),profile);}
 public Version version(Connection c,UUID tenant,Selector exact)throws SQLException{try(var p=c.prepareStatement("select party_id,party_revision,party_type,canonical_name from party.profile_version where tenant_id=? and profile_version_id=? and revision=?")){p.setObject(1,tenant);p.setObject(2,exact.id());p.setLong(3,exact.revision());try(var r=p.executeQuery()){return r.next()?new Version(exact,new Profile(new Selector(r.getObject(1,UUID.class),r.getLong(2)),"PERSON".equals(r.getString(3))?"NATURAL_PERSON":"ORGANIZATION",r.getString(4))):null;}}}
}
