import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {ContractCard} from './ContractCard';
import type {ContractContext} from './types';
const selector={id:'signature',revision:1};
const base={opportunity:selector,responsibilityBasis:selector,customerConfirmation:selector,customerName:'签署测试客户',readonly:false,contract:null,draft:null,workflow:null,review:null,approvals:[],blockers:[],history:[],receiptBoundary:null,allowedActions:['CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT','SAVE_CONTRACT_SIGNATURE_DRAFT'],signature:{workflow:{selector,stage:'ARRANGE',task:selector,ownerAppointmentId:'owner'},parties:[{id:'party',label:'批准委托人'}],arrangements:[],submissions:[],draft:null,handoff:null}} as unknown as ContractContext;
function setup(context=base){const onCommand=vi.fn().mockResolvedValue({status:'UNKNOWN'}),onRecover=vi.fn().mockResolvedValue({status:'UNKNOWN'}),onTasks=vi.fn();return {...render(<ContractCard context={context} accessKey="sign" onCommand={onCommand} onRecover={onRecover} onReload={vi.fn()} onTasks={onTasks}/>),onCommand,onRecover,onTasks};}
it('firm arrangement carries the exact approved template binding without fabricating a customer participation',async()=>{
 const c={...base,signature:{...base.signature!,parties:[{id:'firm',label:'本律所',templateSigningPartyId:'approved-firm'}]}} as ContractContext;
 const {onCommand}=setup(c);fireEvent.change(screen.getByLabelText('条款依据'),{target:{value:'签署条款'}});fireEvent.click(screen.getByLabelText('已逐项对照批准正文，登记完整且未改变主体或条款'));fireEvent.click(screen.getByRole('button',{name:'确认安排并准备材料'}));
 await waitFor(()=>expect(onCommand).toHaveBeenCalled());
 expect(onCommand.mock.calls[0][1].slots[0]).toMatchObject({partyId:'firm',templateSigningPartyId:'approved-firm'});
 expect(onCommand.mock.calls[0][1].slots[0].participationId).toBeUndefined();
});
it('supplement remains bound to the returned submission even if an earlier slot is still unsigned',()=>{
 const slots=[1,2].map(n=>({slotNumber:n,partyId:'party'+n,authoritySlot:'PARTY_'+n,required:true,signatureRequired:true,sealRequired:false,clauseBasis:'签署条款'}));
 const c={...base,allowedActions:['SUBMIT_CONTRACT_SIGNATURE'],signature:{...base.signature!,workflow:{selector,stage:'SUPPLEMENT',task:selector,ownerAppointmentId:'owner'},arrangements:slots,submissions:[{selector,slotNumber:2,materialVersionId:'m',materialSha256:'a'.repeat(64),authorityMaterialVersionId:'a',authorityMaterialSha256:'b'.repeat(64),signerName:'代表',signedAt:'2026-01-01T00:00:00Z',decision:'NEED_INFO',reason:'补充第2页'}]}} as ContractContext;
 setup(c);const slot=screen.getByLabelText('本次签署事项');expect(slot).toHaveValue('2');expect(slot).toBeDisabled();
});
it('arrangement cannot submit without clause basis and explicit approved-body confirmation',async()=>{const {onCommand}=setup();fireEvent.click(screen.getByRole('button',{name:'确认安排并准备材料'}));expect(onCommand).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('条款依据'),{target:{value:'第八条'}});fireEvent.click(screen.getByLabelText('已逐项对照批准正文，登记完整且未改变主体或条款'));fireEvent.click(screen.getByRole('button',{name:'确认安排并准备材料'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledOnce());expect(await screen.findByRole('button',{name:'核对原结果'})).toBeVisible();expect(screen.queryByRole('button',{name:'确认安排并准备材料'})).toBeNull();});
it('signature edits use the shared unsaved switch guard',()=>{const {onTasks}=setup();fireEvent.change(screen.getByLabelText('条款依据'),{target:{value:'第八条'}});fireEvent.click(screen.getByRole('button',{name:'我的待办'}));expect(screen.getByRole('dialog')).toBeVisible();expect(onTasks).not.toHaveBeenCalled();});
it('signature completion does not claim execution or create editable forms',()=>{setup({...base,allowedActions:[],signature:{...(base as any).signature,workflow:{selector,stage:'SIGNATURE_COMPLETE'}}} as ContractContext);expect(screen.getByText(/不代表合同执行条件全部满足或已转案/)).toBeVisible();expect(screen.queryByLabelText('条款依据')).toBeNull();});
it('verifier must confirm arrangement completeness and evidence before a passing decision',async()=>{const c={...base,allowedActions:['RECORD_CONTRACT_SIGNATURE_VERIFICATION'],signature:{...(base as any).signature,workflow:{selector,stage:'AWAIT_VERIFICATION'}}} as ContractContext;const {onCommand}=setup(c);fireEvent.change(screen.getByLabelText('核验结果'),{target:{value:'VERIFIED'}});fireEvent.change(screen.getByLabelText('核验说明'),{target:{value:'逐项核对'}});fireEvent.click(screen.getByRole('button',{name:'记录本次核验结果'}));expect(onCommand).not.toHaveBeenCalled();for(const checkbox of screen.getAllByRole('checkbox'))fireEvent.click(checkbox);fireEvent.click(screen.getByRole('button',{name:'记录本次核验结果'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('RECORD_CONTRACT_SIGNATURE_VERIFICATION',expect.objectContaining({arrangementComplete:true,contentCorresponds:true,expectedSignatureWorkflow:selector}),c));});
it('same-body arrangement correction records the reason without signing confirmations',async()=>{const c={...base,allowedActions:['RECORD_CONTRACT_SIGNATURE_VERIFICATION'],signature:{...(base as any).signature,workflow:{selector,stage:'AWAIT_VERIFICATION'}}} as ContractContext;const {onCommand}=setup(c);fireEvent.change(screen.getByLabelText('核验结果'),{target:{value:'ARRANGEMENT_CORRECTION'}});fireEvent.change(screen.getByLabelText('核验说明'),{target:{value:'漏登记律所盖章'}});fireEvent.click(screen.getByRole('button',{name:'记录本次核验结果'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('RECORD_CONTRACT_SIGNATURE_VERIFICATION',expect.objectContaining({decision:'ARRANGEMENT_CORRECTION',reason:'漏登记律所盖章'}),c));expect(screen.queryByLabelText('条款依据')).toBeNull();});
it('read-only signature context exposes no draft or mutation even with stale permissions',()=>{setup({...base,readonly:true});expect(screen.queryByLabelText('条款依据')).toBeNull();expect(screen.queryByRole('button',{name:'保存草稿'})).toBeNull();});
it('signing permission revocation clears pending fields and customer content',()=>{const {rerender}=setup();fireEvent.change(screen.getByLabelText('条款依据'),{target:{value:'保密条款'}});rerender(<ContractCard context={base} accessKey="sign" permitted={false} onCommand={vi.fn()} onRecover={vi.fn()} onReload={vi.fn()} onTasks={vi.fn()}/>);expect(screen.queryByText('签署测试客户')).toBeNull();expect(screen.queryByDisplayValue('保密条款')).toBeNull();expect(screen.getByText(/客户、合同正文和操作已清除/)).toBeVisible();});
it('submission uses accepted material digests, precise actual date, and no arrangement fields',async()=>{const c={...base,documents:[{id:'signed',label:'签字文件',bodySha256:'signed-digest'},{id:'authority',label:'授权文件',bodySha256:'authority-digest'}],allowedActions:['SUBMIT_CONTRACT_SIGNATURE'],signature:{...(base as any).signature,workflow:{selector,stage:'COLLECT'},arrangements:[{slotNumber:1,partyId:'party',authoritySlot:'PARTY_1',required:true,signatureRequired:true,sealRequired:false,clauseBasis:'第八条'}]}} as ContractContext;const {onCommand}=setup(c);fireEvent.change(screen.getByLabelText('签字件'),{target:{value:'signed'}});fireEvent.change(screen.getByLabelText('代表权限依据'),{target:{value:'authority'}});fireEvent.change(screen.getByLabelText('签署人姓名'),{target:{value:'张三'}});fireEvent.change(screen.getByLabelText('实际签署日期'),{target:{value:'2026-09-23'}});fireEvent.click(screen.getByLabelText('已核对签字件对应本版批准合同'));fireEvent.click(screen.getByRole('button',{name:'提交签署核验'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledOnce());expect(onCommand.mock.calls[0][1]).toEqual({expectedSignatureWorkflow:selector,slotNumber:1,materialVersionId:'signed',materialSha256:'signed-digest',authorityMaterialVersionId:'authority',authorityMaterialSha256:'authority-digest',signerName:'张三',signedAt:'2026-09-23T00:00:00+08:00'});});
it('draft save carries the exact prior draft selector for concurrency protection',async()=>{const c={...base,signature:{...(base as any).signature,draftSelector:{id:'old-draft',revision:0}}} as ContractContext;const {onCommand}=setup(c);fireEvent.change(screen.getByLabelText('条款依据'),{target:{value:'未完成登记'}});fireEvent.click(screen.getByRole('button',{name:'保存草稿'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledOnce());expect(onCommand.mock.calls[0][1]).toMatchObject({expectedSignatureDraft:{id:'old-draft',revision:0},expectedSignatureWorkflow:selector});});
it('archive verifier can return changed evidence to revision with one primary action',async()=>{const c={...base,allowedActions:['ARCHIVE_CONTRACT_SIGNATURE','RETURN_CONTRACT_SIGNATURE_FOR_REVISION'],signature:{...(base as any).signature,workflow:{selector,stage:'ARCHIVE'}}} as unknown as ContractContext;const {onCommand}=setup(c);fireEvent.click(screen.getByRole('button',{name:'正文或主体需要修订'}));expect(screen.queryByRole('button',{name:'确认完整归档'})).toBeNull();fireEvent.change(screen.getByLabelText('修订原因'),{target:{value:'归档正文已变更'}});fireEvent.click(screen.getByRole('button',{name:'返回合同修订'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('RETURN_CONTRACT_SIGNATURE_FOR_REVISION',{expectedSignatureWorkflow:selector,reason:'归档正文已变更'},c));});

it('corrected arrangement keeps prior evidence and verifier history in the shared context column',()=>{
 const c={...base,signature:{...base.signature!,historyEntries:[{id:'old-review',label:'授权核验结论',summary:'ARRANGEMENT_CORRECTION',occurredAt:'2026-09-23T00:00:00Z',actorLabel:'授权核验人',reason:'遗漏律所盖章'}]}} as ContractContext;
 setup(c);const history=screen.getByText('签署材料与核验历史').closest('details')!;expect(history.closest('.context')).not.toBeNull();expect(history.textContent).toContain('遗漏律所盖章');expect(history.textContent).toContain('需要补正登记');expect(history.textContent).not.toContain('ARRANGEMENT_CORRECTION');
});

it('prior signing history remains visible after returning to contract preparation',()=>{
 const c={...base,signature:null,signatureHistory:[{id:'returned',label:'签署退回修订',summary:'批准正文需调整',occurredAt:'2026-09-23T00:00:00Z',actorLabel:'授权核验人'}]} as ContractContext;
 setup(c);expect(screen.getByText('签署材料与核验历史')).toBeVisible();expect(screen.getByText(/批准正文需调整/)).toBeInTheDocument();
});
