import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {describe,it,expect,vi} from 'vitest';
import {ContractCard} from './ContractCard';
import {readFileSync} from 'node:fs';
import {ContractLedger} from './ContractLedger';
import type {ContractContext,ContractDocument} from './types';
const selector={id:'opportunity',revision:1};
const document:ContractDocument={commercial:{currency:'CNY',scope:'审阅采购合同',lines:[{description:'固定服务费',amountMinor:2000000,discount:false}],conditionalFee:null,paymentTerms:'签署后支付'},document:{evidenceVersionId:'file',bodySha256:'digest',templateVersionId:'template',clauseVersionIds:[]},signing:{partySnapshotDigest:'party',requirements:'核对法定代表人权限并盖章归档'},paymentGate:{receiptRequiredBeforeTransfer:false,requiredMinor:null}};
const context:ContractContext={opportunity:selector,responsibilityBasis:selector,customerConfirmation:selector,customerName:'测试客户',readonly:false,contract:{selector,currentRevision:{id:'revision',hash:'hash'},version:1,document,source:{kind:'DIRECT_AUTHORIZATION',selector},stage:'PREPARE'},draft:null,workflow:{selector,stage:'PREPARE',task:selector,ownerAppointmentId:'owner'},review:null,approvals:[],allowedActions:['FORM_CONTRACT','SAVE_CONTRACT_DRAFT'],blockers:[],history:[],receiptBoundary:null,templates:[{id:'template',label:'受控委托模板',clauseVersionIds:[]}],documents:[{id:'file',label:'已确认合同正文',bodySha256:'digest'}],partySnapshotDigest:'party'};
function setup(patch:Partial<ContractContext>={}){const c={...context,...patch},onCommand=vi.fn().mockResolvedValue({status:'COMMITTED'}),onTasks=vi.fn(),onRecover=vi.fn().mockResolvedValue({status:'UNKNOWN'}),props={context:c,accessKey:'identity:task',onCommand,onTasks,onRecover,onReload:vi.fn().mockResolvedValue(c)};return {...render(<ContractCard {...props}/>),props,onCommand,onTasks,onRecover};}
it('execution conditions require both human checks and the exact execution responsibility',async()=>{
 const {onCommand}=setup({allowedActions:['VERIFY_CONTRACT_EXECUTION_CONDITIONS'] as ContractContext['allowedActions'],execution:{handoff:selector,workflow:{selector,stage:'CHECK_CONDITIONS',task:selector,ownerAppointmentId:'owner',ownerLabel:'销售负责人',dueAt:null,message:''}}});
 expect(screen.getByRole('heading',{name:'核对合同执行条件'})).toBeVisible();
 fireEvent.click(screen.getByRole('button',{name:'确认执行条件成立'}));expect(onCommand).not.toHaveBeenCalled();
 fireEvent.click(screen.getByLabelText('已对照批准正文核对生效日期及其他约定条件'));
 fireEvent.click(screen.getByLabelText('本版签署归档完整，当前没有未满足的执行条件'));
 fireEvent.click(screen.getByRole('button',{name:'确认执行条件成立'}));
 await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('VERIFY_CONTRACT_EXECUTION_CONDITIONS',{expectedExecutionWorkflow:selector,approvedConditionsChecked:true,archiveAndConditionsComplete:true},expect.anything()));
});
it('an unpaid prepay responsibility shows waiting instead of old preparation or human completion',()=>{
 setup({allowedActions:[],execution:{handoff:selector,workflow:{selector,stage:'WAIT_RECEIPT',task:selector,ownerAppointmentId:'owner',ownerLabel:'销售负责人',dueAt:null,message:'等待约定首款'}}});
 expect(screen.getByRole('heading',{name:'等待约定首款到账'})).toBeVisible();
 expect(screen.queryByRole('button',{name:'确认执行条件成立'})).toBeNull();
 expect(screen.queryByRole('heading',{name:'核对本次合同内容'})).toBeNull();
});
it('unsigned handling exits through its own confirmed purpose and shows retained history',async()=>{
 const c={...context,allowedActions:['END_CONTRACT_NEGOTIATION'] as ContractContext['allowedActions']};const stopped={...c,readonly:true,allowedActions:[],termination:{selector,state:'STOPPED',summary:'客户撤回本次委托',occurredAt:'2026-09-25T00:00:00Z',task:null,ownerAppointmentId:null,ownerLabel:'',dueAt:null,history:[]}};const onCommand=vi.fn().mockResolvedValue({status:'COMMITTED',context:stopped});
 render(<ContractCard context={c} accessKey="end" onCommand={onCommand} onRecover={vi.fn()} onReload={vi.fn()} onTasks={vi.fn()}/>);
 fireEvent.click(screen.getByRole('button',{name:'结束本次签约办理'}));expect(screen.getByRole('heading',{name:'核对未签署后结束办理'})).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'确认结束本次签约办理'}));expect(onCommand).not.toHaveBeenCalled();
 fireEvent.change(screen.getByLabelText('处理原因与依据'),{target:{value:'客户撤回本次委托'}});fireEvent.click(screen.getByLabelText('已核对处理范围，历史事实与独立责任保留'));fireEvent.click(screen.getByRole('button',{name:'确认结束本次签约办理'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('END_CONTRACT_NEGOTIATION',expect.objectContaining({summary:'客户撤回本次委托',humanConfirmed:true,expectedTermination:null,expectedSignatureWorkflow:null}),c));expect(await screen.findByRole('heading',{name:'本次销售办理已停止'})).toBeVisible();expect(screen.queryByRole('heading',{name:'核对本次合同内容'})).toBeNull();
});
it('signed evidence offers supervisor request and preserves outcome uncertainty',async()=>{
 const {onCommand}=setup({allowedActions:['REQUEST_CONTRACT_TERMINATION_REVIEW']});onCommand.mockResolvedValue({status:'UNKNOWN'});fireEvent.click(screen.getByRole('button',{name:'申请主管核对终止签约'}));fireEvent.change(screen.getByLabelText('处理原因与依据'),{target:{value:'客户暂停'}});fireEvent.click(screen.getByLabelText('已核对处理范围，历史事实与独立责任保留'));fireEvent.click(screen.getByRole('button',{name:'提交终止核对请求'}));expect(await screen.findByRole('button',{name:'核对原结果'})).toBeVisible();expect(screen.queryByRole('button',{name:'确认结束本次签约办理'})).toBeNull();expect(onCommand).toHaveBeenCalledTimes(1);
});
it('pending supervisor has one decision form and no old signature action',async()=>{
 const {onCommand}=setup({allowedActions:['RECORD_CONTRACT_TERMINATION_REVIEW'],termination:{selector,state:'REVIEW_REQUIRED',summary:'客户申请暂停',occurredAt:'2026-09-25T00:00:00Z',task:selector,ownerAppointmentId:'reviewer',ownerLabel:'主管',dueAt:null,resumeAvailable:true,history:[]}});expect(screen.getByRole('heading',{name:'核对终止签约请求'})).toBeVisible();fireEvent.change(screen.getByLabelText('本次决定'),{target:{value:'CONTINUE'}});fireEvent.change(screen.getByLabelText('核对依据与后续说明'),{target:{value:'对照材料后继续'}});fireEvent.click(screen.getByLabelText('已核对签署、执行、转案及尚存责任'));fireEvent.click(screen.getByRole('button',{name:'记录本次核对结果'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('RECORD_CONTRACT_TERMINATION_REVIEW',expect.objectContaining({decision:'CONTINUE',humanConfirmed:true,expectedTermination:selector}),expect.anything()));
});
it('unassigned review is visible without exposing an unauthorized decision',()=>{setup({allowedActions:[],termination:{selector,state:'REVIEW_REQUIRED',summary:'客户暂停',occurredAt:'2026-09-25T00:00:00Z',task:null,ownerAppointmentId:null,ownerLabel:'等待安排有权主管',dueAt:'2026-09-25T02:00:00Z',resumeAvailable:false,history:[]}});expect(screen.getByRole('heading',{name:'等待安排合格责任人'})).toBeVisible();expect(screen.queryByLabelText('本次决定')).toBeNull();});
it('repeated review presents the current request rather than the first historical request',()=>{
 setup({allowedActions:['RECORD_CONTRACT_TERMINATION_REVIEW'],termination:{selector,state:'REVIEW_REQUIRED',summary:'第二次申请依据',occurredAt:'2026-09-25T02:00:00Z',task:selector,ownerAppointmentId:'reviewer',ownerLabel:'主管',dueAt:null,resumeAvailable:true,history:[{selector:{id:'first',revision:0},kind:'REQUEST_REVIEW',summary:'第一次申请依据',occurredAt:'2026-09-25T00:00:00Z'},{selector:{id:'continue',revision:0},kind:'CONTINUE',summary:'已退回继续',occurredAt:'2026-09-25T01:00:00Z'},{selector,kind:'REQUEST_REVIEW',summary:'第二次申请依据',occurredAt:'2026-09-25T02:00:00Z'}]}});
 expect(screen.getByText('第二次申请依据')).toBeVisible();expect(screen.queryByText('第一次申请依据')).toBeNull();
});
it('supervisor sees actual independent facts without treating receipt presence as paid in full',()=>{
 setup({allowedActions:['RECORD_CONTRACT_TERMINATION_REVIEW'],termination:{selector,state:'REVIEW_REQUIRED',summary:'核对请求',occurredAt:'2026-09-25T02:00:00Z',task:selector,ownerAppointmentId:'reviewer',ownerLabel:'主管',dueAt:null,resumeAvailable:true,history:[],independentState:{paymentRecorded:true,executionRecorded:false,transferRecorded:false}} as ContractContext['termination']});
 expect(screen.getByText('已有收款记录，按财务原状态处理')).toBeVisible();expect(screen.getByText('未形成执行或转案事实')).toBeVisible();expect(screen.queryByText('首款已全部到账')).toBeNull();
});
it('generated contract requires manual confirmation and the shared checkbox style',async()=>{
 const onCommand=vi.fn().mockResolvedValue({status:'COMMITTED'}),onGenerate=vi.fn().mockResolvedValue({context,candidate:{generationProof:'proof',bodySha256:'a'.repeat(64),pdfBase64:'JVBERi0=',previewText:'完整已审核条款及本次填入内容',expiresAt:'2026-09-24T00:00:00Z'}});
 render(<ContractCard context={context} accessKey="generate" onCommand={onCommand} onGenerate={onGenerate} onRecover={vi.fn()} onReload={vi.fn()} onTasks={vi.fn()}/>);
 fireEvent.click(screen.getByRole('button',{name:'生成合同正文'}));expect(await screen.findByText('完整已审核条款及本次填入内容')).toBeVisible();fireEvent.click(screen.getByRole('button',{name:'确认并形成合同版本'}));expect(onCommand).not.toHaveBeenCalled();
 const confirm=screen.getByRole('checkbox',{name:'我已核对正文、主体、费用、付款及签署要求'});expect(confirm.closest('label')).toHaveClass('contract-checkbox');fireEvent.click(confirm);fireEvent.click(screen.getByRole('button',{name:'确认并形成合同版本'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('FORM_CONTRACT',expect.objectContaining({document:expect.objectContaining({generationProof:'proof',humanConfirmed:true})}),expect.anything()));
});
it('returning from generated preview discards the candidate before editing',async()=>{
 const onGenerate=vi.fn().mockResolvedValue({context,candidate:{generationProof:'proof',bodySha256:'a'.repeat(64),pdfBase64:'JVBERi0=',previewText:'本次完整正文',expiresAt:'2026-09-24T00:00:00Z'}});
 render(<ContractCard context={context} accessKey="edit-generated" onCommand={vi.fn()} onGenerate={onGenerate} onRecover={vi.fn()} onReload={vi.fn()} onTasks={vi.fn()}/>);fireEvent.click(screen.getByRole('button',{name:'生成合同正文'}));await screen.findByText('本次完整正文');expect(screen.getByRole('button',{name:'下载生成正文'})).toHaveClass('link-button');fireEvent.click(screen.getByRole('button',{name:'返回修改内容'}));expect(screen.queryByRole('button',{name:'确认并形成合同版本'})).toBeNull();expect(screen.getByRole('button',{name:'生成合同正文'})).toBeVisible();
});
describe('contract workcard',()=>{
 it('uses frozen inline checkbox dimensions despite global input minimum sizing',()=>{const globalStyle=window.document.createElement('style');globalStyle.textContent=['../../styles/workbench.css','../opportunities/ledgerMaster.css','./contractControls.css'].map(path=>readFileSync(new URL(path,import.meta.url),'utf8')).join('\n');window.document.head.append(globalStyle);try{setup();for(const name of ['明确折扣','包含条件性费用']){const input=screen.getByRole('checkbox',{name});const label=input.closest('label')!;expect(getComputedStyle(label).display).toBe('flex');expect(getComputedStyle(input).width).toBe('18px');expect(getComputedStyle(input).height).toBe('18px');expect(getComputedStyle(input).minHeight).toBe('18px');expect(getComputedStyle(input).padding).toBe('0px');}}finally{globalStyle.remove();}});
 it('readonly history exposes no editable action even if stale action names remain',()=>{setup({readonly:true});expect(screen.getByRole('heading',{name:'查看合同历史'})).toBeVisible();expect(screen.queryByRole('button',{name:'形成这份合同版本'})).toBeNull();expect(screen.queryByLabelText('服务范围')).toBeNull();});
 it('direct authority decision discloses the complete commercial basis',()=>{setup({contract:null,allowedActions:['RECORD_CONTRACT_PREPARATION_DECISION'],preparation:{selector,reason:'本次合成授权',commercial:{...document.commercial,conditionalFee:{basis:'仅达成约定结果后',rateBasisPoints:500,capMinor:100000}}}});expect(screen.getByText('签署后支付')).toBeVisible();expect(screen.getByText(/仅达成约定结果后；费率 5.00%；上限 ¥1000.00/)).toBeVisible();});
 it('submits exact commercial cents, controlled document and the current basis',async()=>{const {onCommand}=setup();fireEvent.change(screen.getByLabelText('金额（元）1'),{target:{value:'123.45'}});fireEvent.click(screen.getByRole('button',{name:'形成这份合同版本'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledOnce());expect(onCommand.mock.calls[0][0]).toBe('FORM_CONTRACT');expect(onCommand.mock.calls[0][1]).toMatchObject({commercial:{lines:[{amountMinor:12345}]},document:{evidenceVersionId:'file',bodySha256:'digest'},paymentGate:{receiptRequiredBeforeTransfer:false,requiredMinor:null}});expect(onCommand.mock.calls[0][2]).toEqual(context);expect(await screen.findByRole('button',{name:'查看下一责任安排'})).toBeVisible();expect(screen.queryByRole('button',{name:'形成这份合同版本'})).toBeNull();});
 it('prepares an unformed anchor without a fake document download or completed version',()=>{setup({contract:{...context.contract!,currentRevision:null,version:0,document:{commercial:document.commercial}}});expect(screen.getByLabelText('服务范围')).toHaveValue('审阅采购合同');expect(screen.queryByRole('button',{name:'查看准确合同正文'})).toBeNull();expect(screen.getByRole('button',{name:'形成这份合同版本'})).toBeVisible();});
 it('both authorization and form actions require explicit same-card mode switching',()=>{setup({allowedActions:['FORM_CONTRACT','REQUEST_CONTRACT_PREPARATION','SAVE_CONTRACT_DRAFT']});expect(screen.getByRole('button',{name:'形成这份合同版本'})).toBeVisible();expect(screen.queryByRole('button',{name:'提交直接准备申请'})).toBeNull();fireEvent.change(screen.getByLabelText('服务范围'),{target:{value:'新收费对应范围'}});fireEvent.click(screen.getByRole('button',{name:'申请本次范围和费用授权'}));expect(screen.getByRole('button',{name:'提交直接准备申请'})).toBeVisible();expect(screen.getByLabelText('服务范围')).toHaveValue('新收费对应范围');fireEvent.click(screen.getByRole('button',{name:'返回合同填写'}));expect(screen.getByLabelText('服务范围')).toHaveValue('新收费对应范围');});
 it('keeps an unknown outcome locked and recovers the original receipt',async()=>{const {onCommand,onRecover}=setup();onCommand.mockRejectedValue(new Error('network'));fireEvent.click(screen.getByRole('button',{name:'形成这份合同版本'}));await screen.findByRole('button',{name:'核对原结果'});expect(screen.getByRole('button',{name:'我的待办'})).toBeDisabled();expect(screen.queryByRole('button',{name:'形成这份合同版本'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'核对原结果'}));await waitFor(()=>expect(onRecover).toHaveBeenCalledOnce());expect(onCommand).toHaveBeenCalledOnce();expect(await screen.findByRole('button',{name:'核对原结果'})).toBeVisible();});
 it('uses server stage after receipt and does not invent an approval',async()=>{const {onCommand}=setup();onCommand.mockResolvedValue({status:'COMMITTED',context:{...context,workflow:{...context.workflow!,stage:'SUBMIT_REVIEW'},allowedActions:['REQUEST_CONTRACT_REVIEW']}});fireEvent.click(screen.getByRole('button',{name:'形成这份合同版本'}));expect(await screen.findByRole('button',{name:'提交签约前审查'})).toBeVisible();expect(screen.queryByText('合同审批已完成')).toBeNull();});
 it('requires controlled template and document rather than fabricating formal content',()=>{const {onCommand}=setup({templates:[],documents:[]});fireEvent.click(screen.getByRole('button',{name:'形成这份合同版本'}));expect(onCommand).not.toHaveBeenCalled();expect(screen.getByText('当前没有可用的受控模板，不能形成正式合同。')).toBeVisible();});
 it('clears sensitive form and context immediately when authority is revoked',()=>{const {rerender,props}=setup();fireEvent.change(screen.getByLabelText('服务范围'),{target:{value:'敏感草稿'}});rerender(<ContractCard {...props} permitted={false}/>);expect(screen.queryByText('测试客户')).toBeNull();expect(screen.queryByDisplayValue('敏感草稿')).toBeNull();expect(screen.getByText('当前事项不可办理')).toBeVisible();});
 it('asks only for dirty navigation and does not treat unsaved edits as saved',()=>{const {onTasks}=setup({allowedActions:['REQUEST_CONTRACT_PREPARATION']});fireEvent.change(screen.getByLabelText('服务范围'),{target:{value:'新范围'}});fireEvent.click(screen.getByRole('button',{name:'我的待办'}));expect(screen.getByRole('dialog')).toBeVisible();expect(screen.getByText('当前填写内容尚未提交。')).toBeVisible();expect(onTasks).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'继续填写'}));expect(screen.queryByRole('dialog')).toBeNull();expect(screen.getByLabelText('服务范围')).toHaveValue('新范围');});
 it('limits review outcomes to the disclosed scope and keeps supplement available',()=>{setup({workflow:{...context.workflow!,stage:'AWAIT_REVIEW'},allowedActions:['RECORD_CONTRACT_REVIEW'],reviewPreview:{scopeComplete:false,candidateCount:0,permittedOutcomes:['NEED_INFO']}});expect(screen.queryByRole('option',{name:'审查通过'})).toBeNull();expect(screen.queryByRole('option',{name:'阻断'})).toBeNull();expect(screen.getByRole('option',{name:'要求补充'})).toBeVisible();expect(screen.getByText(/审查范围尚未完整核对/)).toBeVisible();});
 it('requires explicit review decision and reason and sends only authorized command',async()=>{const {onCommand}=setup({workflow:{...context.workflow!,stage:'AWAIT_REVIEW'},allowedActions:['RECORD_CONTRACT_REVIEW'],reviewPreview:{scopeComplete:true,candidateCount:1,permittedOutcomes:['NEED_INFO','BLOCKED']},review:{selector,status:'OPEN',summary:'核对关联方身份',scopeHash:'scope'}});fireEvent.click(screen.getByRole('button',{name:'确认本次决定'}));expect(onCommand).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('本次决定'),{target:{value:'BLOCKED'}});fireEvent.change(screen.getByLabelText('决定说明'),{target:{value:'需要有权处置'}});fireEvent.click(screen.getByRole('button',{name:'确认本次决定'}));await waitFor(()=>expect(onCommand).toHaveBeenCalledWith('RECORD_CONTRACT_REVIEW',{decision:'BLOCKED',reason:'需要有权处置'},expect.anything()));});
});
it('contract ledger clears selected detail on filtering and hides it on revocation',()=>{const onSelect=vi.fn(),props={rows:[{id:'opportunity',customerLabel:'测试客户',versionLabel:'第 1 版',stateLabel:'合同准备',ownerLabel:'当前销售',canHandle:true}],detail:context,selectedId:'opportunity',onSelect,onHandle:vi.fn(),onTasks:vi.fn(),onReload:vi.fn()};const {rerender}=render(<ContractLedger {...props}/>);expect(screen.getByRole('button',{name:'前往办理'})).toBeVisible();fireEvent.change(screen.getByLabelText('搜索客户'),{target:{value:'其他'}});expect(onSelect).toHaveBeenCalledWith(null);expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();rerender(<ContractLedger {...props} permitted={false}/>);expect(screen.queryByText('测试客户')).toBeNull();expect(screen.getByLabelText('搜索客户')).toHaveValue('');expect(screen.queryByRole('option',{name:'合同准备'})).toBeNull();});

it('shows empty contract ledger text when the page supplies an empty error',()=>{render(<ContractLedger rows={[]} detail={null} selectedId={null} error="" onSelect={vi.fn()} onHandle={vi.fn()} onTasks={vi.fn()} onReload={vi.fn()}/>);expect(screen.getByText('暂无匹配的合同记录。')).toBeVisible();});

it('shows business approval labels without exposing internal slot codes',()=>{setup({approvals:[{slot:'LEGAL',status:'PENDING',selector},{slot:'PRIVATE_CODE',status:'PENDING',selector}]});expect(screen.getByText('法务审批')).toBeVisible();expect(screen.getByText('审批事项2')).toBeVisible();expect(screen.queryByText('PRIVATE_CODE')).toBeNull();});

it('supplement defaults to one review action and explicitly switches to version revision',()=>{setup({workflow:{...context.workflow!,stage:'REVIEW_SUPPLEMENT'},allowedActions:['FORM_CONTRACT','SAVE_CONTRACT_DRAFT','REQUEST_CONTRACT_REVIEW']});expect(screen.getByRole('button',{name:'提交补充资料并重新审查'})).toBeVisible();expect(screen.queryByRole('button',{name:'形成这份合同版本'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'需要修改合同正文'}));expect(screen.getByRole('button',{name:'形成这份合同版本'})).toBeVisible();expect(screen.getByRole('button',{name:'保存草稿'})).toBeVisible();expect(screen.queryByRole('button',{name:'提交补充资料并重新审查'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'返回补充说明'}));expect(screen.getByRole('button',{name:'提交补充资料并重新审查'})).toBeVisible();});

it('completed ledger contracts retain a read entry without empty owner fields',()=>{const onView=vi.fn();render(<ContractLedger rows={[{id:selector.id,customerLabel:'测试客户',versionLabel:'第 1 版',stateLabel:'签署准备已就绪',ownerLabel:'',canHandle:false}]} detail={{...context,readonly:true,allowedActions:[]}} selectedId={selector.id} onSelect={vi.fn()} onHandle={vi.fn()} onView={onView} onTasks={vi.fn()} onReload={vi.fn()}/>);expect(screen.queryByText('负责人')).toBeNull();expect(screen.queryByText('签署准备已就绪 ·')).toBeNull();expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'查看合同内容'}));expect(onView).toHaveBeenCalledOnce();});

it('return to the originating follow-up keeps the same unsaved-input guard',()=>{
 const onBack=vi.fn(),onTasks=vi.fn(),backRef={current:null} as {current:null|{back:()=>void}};
 render(<ContractCard context={context} accessKey="back" onCommand={vi.fn()} onRecover={vi.fn()} onReload={vi.fn()} onTasks={onTasks} onBack={onBack} backRef={backRef}/>);
 fireEvent.change(screen.getByLabelText('服务范围'),{target:{value:'本次未保存的范围'}});act(()=>backRef.current?.back());
 expect(screen.getByRole('dialog',{name:'保留当前填写内容'})).toBeVisible();expect(onBack).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole('button',{name:'放弃填写并切换'}));expect(onBack).toHaveBeenCalledOnce();expect(onTasks).not.toHaveBeenCalled();
});

it('selected finance duty keeps its own form despite parallel execution and stopped sales',()=>{
 const payment={selector,request:selector,stage:'CHECK_RECEIPT' as const,targetStage:'CHECK_RECEIPT' as const,task:selector,taskIds:[selector.id],ownerAppointmentId:'owner',ownerLabel:'财务核对责任人',dueAt:'2026-09-27T10:00:00Z',accountLabel:'合成基本户',explanation:null,allowedActions:['RECORD_CONTRACT_RECEIPT_REVIEW'] as ContractContext['allowedActions']};
 setup({readonly:true,allowedActions:[],selectedPayment:payment,payments:[payment],termination:{selector,state:'STOPPED',summary:'销售办理已停止',occurredAt:'2026-09-27T00:00:00Z',task:null,ownerAppointmentId:null,ownerLabel:'',dueAt:null,history:[]}});
 expect(screen.getByRole('heading',{name:'核对本笔收款',level:1})).toBeInTheDocument();expect(screen.getByLabelText('核对结果')).toBeEnabled();expect(screen.queryByRole('heading',{name:'查看合同历史',level:1})).not.toBeInTheDocument();
});

it('the existing ledger action opens an authorized transfer while contract editing stays read-only',()=>{
 const transferContext={...context,readonly:true,allowedActions:[],transfer:{stage:'CLASSIFY',canHandle:true,task:selector}};
 const onHandle=vi.fn();render(<ContractLedger rows={[{id:context.contract!.selector.id,customerLabel:'测试客户',versionLabel:'第1版',stateLabel:'已接收，待案件分类',ownerLabel:'',canHandle:true}]} detail={transferContext} selectedId={context.contract!.selector.id} onSelect={vi.fn()} onHandle={onHandle} onTasks={vi.fn()} onReload={vi.fn()}/>);
 fireEvent.click(screen.getByRole('button',{name:'前往办理'}));expect(onHandle).toHaveBeenCalledWith(transferContext);
});
it('completed classification exposes only the separate authorized correction entry',()=>{
 const completed={...context,readonly:true,allowedActions:[],transfer:{stage:'COMPLETE',task:null,canHandle:false,canCorrectClassification:true}},onCorrectClassification=vi.fn();const props={rows:[{id:selector.id,customerLabel:'测试客户',versionLabel:'第1版',stateLabel:'分类已完成',ownerLabel:'',canHandle:false}],detail:completed,selectedId:selector.id,onSelect:vi.fn(),onHandle:vi.fn(),onTasks:vi.fn(),onReload:vi.fn(),onCorrectClassification};const view=render(<ContractLedger {...props}/>);fireEvent.click(screen.getByRole('button',{name:'更正分类及承接'}));expect(onCorrectClassification).toHaveBeenCalledWith(selector.id);expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();view.rerender(<ContractLedger {...props} detail={{...completed,transfer:{...completed.transfer,canCorrectClassification:false}}}/>);expect(screen.queryByRole('button',{name:'更正分类及承接'})).toBeNull();
});
