import {useImperativeHandle,useState,type Ref} from 'react';
import type {ContractCommand,ContractContext,SignatureSlot,SignatureStage} from './types';
export const signatureLabels:Record<SignatureStage,string>={ARRANGE:'核对本版签署安排',COLLECT:'提交客户签字件',AWAIT_VERIFICATION:'核验客户签署',SUPPLEMENT:'补充本版签署材料',PARTIAL:'完成剩余签署事项',ARCHIVE:'核对签署归档',SIGNATURE_COMPLETE:'签署核验已完成',REVISION_REQUIRED:'处理签署内容变化',OWNER_EXCEPTION:'查看核验责任安排'};
export function ContractSignature({context,allowed,submit,onDirty,onMessage,draftRef,onUpload,onDocument,onApprovedDocument}:{context:ContractContext;allowed:(c:ContractCommand)=>boolean;submit:(c:ContractCommand,v:Record<string,unknown>,saving?:boolean)=>Promise<boolean>;onDirty:()=>void;onMessage:(s:string)=>void;draftRef:Ref<{saveDraft:()=>Promise<boolean>}>;onUpload?:(file:File|undefined,uploadId:string|undefined)=>Promise<void>;onDocument?:(id:string)=>void;onApprovedDocument?:()=>void}){
 const s=context.signature!,draft=s.draft??{},stage=s.workflow.stage;
 const first=()=>({slotNumber:1,partyId:s.parties[0]?.id??'',participationId:s.parties[0]?.participationId,templateSigningPartyId:s.parties[0]?.templateSigningPartyId,authoritySlot:'PARTY_1',required:true,signatureRequired:true,sealRequired:false,clauseBasis:''});
 const [slots,setSlots]=useState<SignatureSlot[]>(()=>Array.isArray(draft.slots)?draft.slots as SignatureSlot[]:s.arrangements.length?s.arrangements:[first()]);
 const [input,setInput]=useState<Record<string,unknown>>({...draft,slotNumber:(stage==='SUPPLEMENT'?[...s.submissions].reverse().find(v=>v.decision==='NEED_INFO')?.slotNumber:undefined)??draft.slotNumber??s.arrangements.find(a=>!s.submissions.some(v=>v.slotNumber===a.slotNumber&&v.decision==='VERIFIED'))?.slotNumber??1});
 const [file,setFile]=useState<File|undefined>();
 const [confirmed,setConfirmed]=useState(false),[revision,setRevision]=useState(false);
 const edit=(key:string,value:unknown)=>{setInput(v=>({...v,[key]:value}));onDirty();};
 const editSlot=(i:number,patch:Partial<SignatureSlot>)=>{setConfirmed(false);setSlots(rows=>rows.map((r,n)=>n===i?{...r,...patch}:r));onDirty();};
  const payload=(command:ContractCommand):Record<string,unknown>=>{
  const fields:Record<string,string[]>={SAVE_CONTRACT_SIGNATURE_DRAFT:['slotNumber','materialVersionId','materialSha256','authorityMaterialVersionId','authorityMaterialSha256','signerName','signedAt','reason'],SUBMIT_CONTRACT_SIGNATURE:['slotNumber','materialVersionId','materialSha256','authorityMaterialVersionId','authorityMaterialSha256','signerName','signedAt'],RECORD_CONTRACT_SIGNATURE_VERIFICATION:['decision','reason','contentCorresponds','arrangementComplete','authorityVerified','signatureVerified','sealVerified','materialComplete'],ARCHIVE_CONTRACT_SIGNATURE:['materialVersionId','materialSha256','reason','archiveComplete'],RETURN_CONTRACT_SIGNATURE_FOR_REVISION:['reason'],RETURN_CONTRACT_FOR_REVISION:['reason']};
  const result:Record<string,unknown>={expectedSignatureWorkflow:s.workflow.selector};
  for(const key of fields[command]??[])if(input[key]!==undefined)result[key]=input[key];
  if(command==='CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT'||command==='SAVE_CONTRACT_SIGNATURE_DRAFT')result.slots=slots;
  if(command==='SAVE_CONTRACT_SIGNATURE_DRAFT')result.expectedSignatureDraft=s.draftSelector??null;
  if(command==='CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT')result.humanConfirmed=confirmed;
  if(command==='SUBMIT_CONTRACT_SIGNATURE'&&typeof result.signedAt==='string')result.signedAt=result.signedAt+'T00:00:00+08:00';
  return result;
 };
 const save=()=>submit('SAVE_CONTRACT_SIGNATURE_DRAFT',payload('SAVE_CONTRACT_SIGNATURE_DRAFT'),true);
 useImperativeHandle(draftRef,()=>({saveDraft:save}));
 const text=(label:string,key:string,type='text')=><label className="field"><span className="field-label">{label}</span><input type={type} value={String(input[key]??'')} onChange={e=>edit(key,e.target.value)}/></label>;
 const check=(label:string,key:string)=><label className="checked-label contract-checkbox"><input type="checkbox" checked={input[key]===true} onChange={e=>edit(key,e.target.checked)}/>{label}</label>;
 const note=(label:string)=><label className="field"><span className="field-label">{label}</span><textarea rows={3} value={String(input.reason??'')} onChange={e=>edit('reason',e.target.value)}/></label>;
 const material=(label:string,key:string,digest:string)=><label className="field"><span className="field-label">{label}</span><select value={String(input[key]??'')} onChange={e=>{const d=context.documents?.find(x=>x.id===e.target.value);setInput(v=>({...v,[key]:d?.id??'',[digest]:d?.bodySha256??''}));onDirty();}}><option value="">请选择已检查并正式接收的材料</option>{context.documents?.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label>;
 const run=(command:ContractCommand)=>{const v=payload(command);if(command==='CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT'&&(!confirmed||!slots.some(a=>a.required)||slots.some(a=>!a.partyId||!a.clauseBasis.trim())||new Set(slots.map(a=>a.partyId)).size!==slots.length)){onMessage('请逐项登记条款依据、避免重复主体，至少保留一项必需要求，并确认登记完整。');return;}
 if(command==='SUBMIT_CONTRACT_SIGNATURE'&&(!input.materialVersionId||!input.authorityMaterialVersionId||!input.signerName||!input.signedAt||!input.contentCorresponds)){onMessage('请核对签字件、代表权限依据、签署人及实际签署日期。');return;}
 if(command==='RECORD_CONTRACT_SIGNATURE_VERIFICATION'&&(!input.decision||!String(input.reason??'').trim()||input.decision==='VERIFIED'&&['arrangementComplete','contentCorresponds','authorityVerified','signatureVerified','sealVerified','materialComplete'].some(k=>input[k]!==true))){onMessage('核验通过前请完整核对批准正文、登记安排、代表权限及本次签字盖章和材料，并填写说明。');return;}
 if(command==='ARCHIVE_CONTRACT_SIGNATURE'&&(!input.materialVersionId||!input.archiveComplete||!String(input.reason??'').trim())){onMessage('请选定完整归档材料，确认归档完整并填写说明。');return;}
 if(['RETURN_CONTRACT_FOR_REVISION','RETURN_CONTRACT_SIGNATURE_FOR_REVISION'].includes(command)&&!String(input.reason??'').trim()){onMessage('请说明正文或主体需要修订的原因。');return;}void submit(command,v);};
 const arrangements=allowed('CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT'),collect=allowed('SUBMIT_CONTRACT_SIGNATURE'),verify=allowed('RECORD_CONTRACT_SIGNATURE_VERIFICATION'),archive=allowed('ARCHIVE_CONTRACT_SIGNATURE'),revisionCommand:ContractCommand=allowed('RETURN_CONTRACT_SIGNATURE_FOR_REVISION')?'RETURN_CONTRACT_SIGNATURE_FOR_REVISION':'RETURN_CONTRACT_FOR_REVISION',revise=allowed(revisionCommand);
 const action=(command:ContractCommand,label:string)=><div className="ledger-detail-actions"><button className="primary" onClick={()=>run(command)}>{label}</button>{allowed('SAVE_CONTRACT_SIGNATURE_DRAFT')&&<button className="link-button" onClick={()=>void save()}>保存草稿</button>}</div>;
 const actionLabels:Record<SignatureStage,string>={ARRANGE:'对照批准正文登记签署安排',COLLECT:'提交当前版本的完整材料',AWAIT_VERIFICATION:'核对登记安排及签署证据',SUPPLEMENT:'提交当前版本的完整材料',PARTIAL:'已完成事项保留，继续剩余要求',ARCHIVE:'核对本版完整签署归档',SIGNATURE_COMPLETE:'本版签署要求已完成',REVISION_REQUIRED:'先处理合同版本变化',OWNER_EXCEPTION:'核验责任正在安排'};
 return <><h2>{context.readonly?'本版签署记录':actionLabels[stage]}</h2>{s.workflow.message&&<p className="feedback">{s.workflow.message}</p>}{context.contract&&<dl className="detail-facts"><div><dt>准确批准版本</dt><dd>第 {context.contract.version} 版</dd></div><div><dt>批准签署要求</dt><dd>{context.contract.document.signing?.requirements}</dd></div></dl>}{onApprovedDocument&&<button className="link-button" onClick={onApprovedDocument}>查看批准合同正文</button>}
 {!!s.arrangements.length&&!arrangements&&<dl className="detail-facts">{s.arrangements.map(a=><div key={a.slotNumber}><dt>{s.parties.find(p=>p.id===a.partyId)?.label??'批准主体'}</dt><dd>{a.signatureRequired?'签字':''}{a.signatureRequired&&a.sealRequired?'并':''}{a.sealRequired?'盖章':''} · {a.required?'必须完成':'非必需'} · {a.clauseBasis}</dd></div>)}</dl>}

 {arrangements&&!revision&&<><p>仅登记本版已批准条款；实际签署完成仍需授权核验。</p>{slots.map((a,i)=><fieldset key={i}><legend>签署要求 {i+1}</legend><label className="field"><span className="field-label">签署主体</span><select value={a.partyId} onChange={e=>{const party=s.parties.find(p=>p.id===e.target.value);editSlot(i,{partyId:party?.id??'',participationId:party?.participationId,templateSigningPartyId:party?.templateSigningPartyId});}}>{s.parties.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label><label className="field"><span className="field-label">批准合同要求</span><select value={a.signatureRequired?(a.sealRequired?'BOTH':'SIGN'):'SEAL'} onChange={e=>editSlot(i,{signatureRequired:e.target.value!=='SEAL',sealRequired:e.target.value!=='SIGN'})}><option value="SIGN">签字</option><option value="SEAL">盖章</option><option value="BOTH">签字并盖章</option></select></label><label className="checked-label contract-checkbox"><input type="checkbox" checked={a.required} onChange={e=>editSlot(i,{required:e.target.checked})}/>合同明确要求必须完成</label><label className="field"><span className="field-label">条款依据</span><input value={a.clauseBasis} onChange={e=>editSlot(i,{clauseBasis:e.target.value})}/></label>{slots.length>1&&<button className="link-button" onClick={()=>{setSlots(rows=>rows.filter((_,n)=>n!==i).map((r,n)=>({...r,slotNumber:n+1,authoritySlot:'PARTY_'+(n+1)})));onDirty();}}>删除要求 {i+1}</button>}</fieldset>)}<button className="link-button" onClick={()=>{setSlots(rows=>[...rows,{...first(),slotNumber:rows.length+1,authoritySlot:'PARTY_'+(rows.length+1)}]);onDirty();}}>添加签署要求</button><label className="checked-label contract-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);onDirty();}}/>已逐项对照批准正文，登记完整且未改变主体或条款</label>{action('CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT','确认安排并准备材料')}</>}
 {collect&&!revision&&<><p>上传和保存草稿不确认签署；补证保留原文件与意见。</p><label className="field"><span className="field-label">本次签署事项</span><select disabled={stage==='SUPPLEMENT'} value={String(input.slotNumber)} onChange={e=>edit('slotNumber',Number(e.target.value))}>{s.arrangements.map(a=><option value={a.slotNumber} key={a.slotNumber}>{s.parties.find(p=>p.id===a.partyId)?.label??'批准主体'} · {a.clauseBasis}</option>)}</select></label>{onUpload&&<><label className="field"><span className="field-label">上传签字件或权限依据</span><input type="file" accept=".pdf,.png,.jpg,.jpeg" onChange={e=>{setFile(e.target.files?.[0]);onDirty();}}/></label><button className="link-button" disabled={!file} onClick={()=>void onUpload(file,undefined).then(()=>setFile(undefined))}>上传并检查材料</button>{context.signatureUploads?.map(u=><p key={u.id}>{u.label} · {({OPEN:'等待上传',CHECKING:'正在检查',UNKNOWN:'检查结果待核对',SCAN_UNAVAILABLE:'检查服务暂不可用',PASSED:'检查通过待接收',REJECTED:'检查未通过',EXPIRED:'上传已过期',ACCEPTED:'已接收'} as Record<string,string>)[u.state]??'等待检查'}{!['REJECTED','EXPIRED','ACCEPTED'].includes(u.state)&&<button className="link-button" onClick={()=>void onUpload(u.state==='OPEN'?file:undefined,u.id)}>查询材料检查结果</button>}</p>)}</>}{material('签字件','materialVersionId','materialSha256')}{material('代表权限依据','authorityMaterialVersionId','authorityMaterialSha256')}{text('签署人姓名','signerName')}{text('实际签署日期','signedAt','date')}{note(stage==='SUPPLEMENT'?'本次补充说明':'签署情况说明')}{check('已核对签字件对应本版批准合同','contentCorresponds')}{action('SUBMIT_CONTRACT_SIGNATURE','提交签署核验')}</>}
 {verify&&<>{check('登记的主体、方式及必需项与批准正文完整一致','arrangementComplete')}{check('签署正文与批准版本一致','contentCorresponds')}{check('签署人身份及代表权限有效','authorityVerified')}{check('本次必需签字符合要求（无签字要求时确认不适用）','signatureVerified')}{check('本次必需盖章符合要求（无盖章要求时确认不适用）','sealVerified')}{check('本次文件完整清晰','materialComplete')}<label className="field"><span className="field-label">核验结果</span><select value={String(input.decision??'')} onChange={e=>edit('decision',e.target.value)}><option value="">请选择</option><option value="VERIFIED">本次签署核验通过</option><option value="ARRANGEMENT_CORRECTION">同版签署安排登记需补正</option><option value="NEED_INFO">同版本补充材料</option><option value="REVISION_REQUIRED">正文或主体变化，返回合同修订</option></select></label>{note('核验说明')}<button className="primary" onClick={()=>run('RECORD_CONTRACT_SIGNATURE_VERIFICATION')}>记录本次核验结果</button></>}
 {archive&&!revision&&<>{material('完整归档材料','materialVersionId','materialSha256')}{check('已核对正文、全部签字盖章及权限依据归档完整','archiveComplete')}{note('归档核对说明')}<button className="primary" onClick={()=>run('ARCHIVE_CONTRACT_SIGNATURE')}>确认完整归档</button></>}
 {revise&&!verify&&<>{!revision&&stage!=='REVISION_REQUIRED'?<button className="link-button" onClick={()=>setRevision(true)}>正文或主体需要修订</button>:<>{note('修订原因')}<button className="primary" onClick={()=>run(revisionCommand)}>返回合同修订</button>{stage!=='REVISION_REQUIRED'&&<button className="link-button" onClick={()=>setRevision(false)}>返回当前办理</button>}</>}</>}

 {stage==='AWAIT_VERIFICATION'&&!verify&&<p>签署证据已提交，正在等待有权人员核验，尚未确认签署完成。</p>}{stage==='PARTIAL'&&<p>已核验事项保留，请继续完成剩余签署要求和完整归档。</p>}{stage==='OWNER_EXCEPTION'&&!s.workflow.message&&<p>暂时没有合格责任人，请由有权主管处理责任安排；原期限和业务来源保留。</p>}{stage==='REVISION_REQUIRED'&&<p>原记录保留；新版本需要重新审查审批，旧签署结论不能沿用。</p>}{stage==='SIGNATURE_COMPLETE'&&<p>本版全部必需签署及完整归档已核验。当前不代表合同执行条件全部满足或已转案。</p>}{s.handoff&&<p role="status">{s.handoff.message}</p>}</>;
}





