import {useState} from 'react';
import type {ContractCommand,ContractContext} from './types';
/** The approved O purpose card; all writes share the parent receipt and authority boundary. */
export function ContractTermination({context,mode,locked,canReview,submit,onBack,onReload,onDirty,onMessage,onDocument}:{context:ContractContext;mode:'end'|'request'|null;locked:boolean;canReview:boolean;submit:(command:ContractCommand,values:Record<string,unknown>)=>Promise<boolean>;onBack:()=>void;onReload:()=>void;onDirty:()=>void;onMessage:(message:string)=>void;onDocument?:()=>void}){
 const [reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[decision,setDecision]=useState('');const termination=context.termination,stopped=termination?.state==='STOPPED',pending=termination?.state==='REVIEW_REQUIRED';
 const history=<details className="history"><summary>处理记录与历史依据</summary>{termination?.history.map(h=><p key={h.selector.id}>{({STOP_UNSIGNED:'未签结束',REQUEST_REVIEW:'申请主管核对',STOP_REVIEWED:'主管确认停止',CONTINUE:'主管退回继续'})[h.kind]} · {h.summary} · {new Date(h.occurredAt).toLocaleString('zh-CN')}</p>)}{context.history.map(h=><p key={h.id}>{h.label} · {h.summary}</p>)}</details>;
 if(stopped)return <><h2>本次销售办理已停止</h2><p>{termination.summary}</p><p>合同版本、批准、签署及核对记录均保留。已形成的财务、执行及转案责任继续按其状态处理。</p><p>此结果不表示合同解除。</p>{onDocument&&<button className="link-button" disabled={locked} onClick={onDocument}>查看准确合同正文</button>}{history}</>;
 if(pending&&!canReview)return <><h2>{termination.task?'已交主管核对':'等待安排合格责任人'}</h2><p>{termination.summary}</p><p>{termination.task?'相关签署办理已暂停，等待有权主管核对。':'当前暂无有权主管，申请和原期限保留；系统会在有合格任职后自动接续。销售不能代替主管核对。'}</p>{termination.dueAt&&<p>原办理期限：{new Date(termination.dueAt).toLocaleString('zh-CN')}</p>}<p>可从我的待办处理其他事项。</p><button className="link-button" disabled={locked} onClick={onReload}>重新读取责任安排</button>{history}</>;
 const review=pending&&canReview,command:ContractCommand=review?'RECORD_CONTRACT_TERMINATION_REVIEW':mode==='request'?'REQUEST_CONTRACT_TERMINATION_REVIEW':'END_CONTRACT_NEGOTIATION';
 function confirm(){if(!reason.trim()||!confirmed||review&&!decision){onMessage('请填写处理依据并确认已核对本次处理范围。');return;}void submit(command,{summary:reason.trim(),humanConfirmed:true,expectedTermination:termination?.selector??null,expectedSignatureWorkflow:context.signature?.workflow.selector??null,...(review?{decision,expectedIndependentBasis:termination?.independentBasis}:{})});}
 return <form onSubmit={e=>{e.preventDefault();confirm();}}><h2>{review?'核对事实并决定后续办理':mode==='request'?'交主管核对后处置':'核对未签署后结束办理'}</h2><dl className="detail-facts"><div><dt>合同版本</dt><dd>{context.contract?'第 '+context.contract.version+' 版':'尚未形成合同版本'}</dd></div><div><dt>{review?'销售申请':'处理范围'}</dt><dd>{review?termination?.summary:'本次销售签约办理及相关未完成责任'}</dd></div><div><dt>签署情况</dt><dd>{context.signature?.submissions.length?`已提交 ${context.signature.submissions.length} 项签署材料；核验结果请对照签署历史`:'本次无签署材料提交；提交时再次核对全部版本的签署依据'}</dd></div>{review&&<><div><dt>执行与转案</dt><dd>{termination?.independentState?(!termination.independentState.executionRecorded&&!termination.independentState.transferRecorded?'未形成执行或转案事实':[termination.independentState.executionRecorded?'已有执行事实':null,termination.independentState.transferRecorded?'已有转案事实':null].filter(Boolean).join('；')+'，继续按原状态处理'):'需结合独立记录核对'}</dd></div><div><dt>财务记录</dt><dd>{termination?.independentState?(termination.independentState.paymentRecorded?'已有收款记录，按财务原状态处理':'未记录收款事实'):'需结合财务记录核对'}</dd></div></>}</dl>{onDocument&&<button type="button" className="link-button" disabled={locked} onClick={onDocument}>查看准确合同正文</button>}{review&&<p>请一并核对执行、财务、转案及尚存责任；已有独立责任继续保留。</p>}<fieldset disabled={locked}><legend className="sr-only">本次办理处置</legend>{review&&<label className="field"><span className="field-label">本次决定</span><select value={decision} onChange={e=>{setDecision(e.target.value);onDirty();}}><option value="">请选择本次决定</option><option value="CONTINUE" disabled={termination?.resumeAvailable===false}>退回继续办理</option><option value="STOP">确认停止本次办理</option></select></label>}{review&&termination?.resumeAvailable===false&&<p>原办理责任当前不能接续，请有权主管先核对任职权限后重新读取。原申请及期限保留。</p>}<label className="field"><span className="field-label">{review?'核对依据与后续说明':'处理原因与依据'}</span><textarea rows={3} maxLength={4000} value={reason} onChange={e=>{setReason(e.target.value);onDirty();}}/></label><label className="checked-label contract-checkbox"><input type="checkbox" checked={confirmed} onChange={e=>{setConfirmed(e.target.checked);onDirty();}}/>{review?'已核对签署、执行、转案及尚存责任':'已核对处理范围，历史事实与独立责任保留'}</label><p>{mode==='end'?'提交时会再次核对；若出现签署事实，须交主管处理。':'停止本次办理不等于解除合同，已有签署事实及独立责任不会自动取消。'}</p><div className="ledger-detail-actions"><button className="primary" type="submit">{review?'记录本次核对结果':mode==='request'?'提交终止核对请求':'确认结束本次签约办理'}</button>{!review&&<button className="link-button" type="button" onClick={onBack}>返回原事项</button>}</div></fieldset></form>;
}
