import {ManagementViewSelect} from './ManagementViewSelect';
import type {ManagementView} from './ManagementLedger';
import {BusinessNavigation} from '../workcard/BusinessNavigation';
import {useEffect,useState} from 'react';
import master from '../opportunities/ledgerMaster.css?inline';
import type {ContractContext} from './types';
import {ContractFacts} from './ContractCard';
export type ContractLedgerRow={id:string;customerLabel:string;versionLabel:string;stateLabel:string;ownerLabel:string;dueAt?:string;canHandle:boolean};
/** Rows and detail must already be filtered by server authority. Detail is never inferred from list data. */
export function ContractLedger({rows,detail,selectedId,loading=false,error,permitted=true,onSelect,onHandle,onView,onTasks,onTeam,onLeads,onOverview,onReload,onOpportunities,onCorrectClassification,onManagementView,managementViews,filters,onFilter}:{filters?:{search:string;state:string};onFilter?:(search:string,state:string)=>void;managementViews?:readonly (ManagementView|'contracts')[];onManagementView?:(view:ManagementView|'contracts')=>void;rows:ContractLedgerRow[];detail:ContractContext|null;selectedId:string|null;loading?:boolean;error?:string;permitted?:boolean;onSelect:(id:string|null)=>void;onHandle:(context:ContractContext)=>void;onView?:(context:ContractContext)=>void;onTasks?:()=>void;onTeam?:()=>void;onLeads?:()=>void;onOverview?:()=>void;onReload:()=>void;onOpportunities?:()=>void;onCorrectClassification?:(id:string)=>void}){
 const [localSearch,setSearch]=useState(''),[localState,setState]=useState('');
 const {search,state}=filters??{search:localSearch,state:localState};
 useEffect(()=>{if(!permitted){setSearch('');setState('');}},[permitted]);
 useEffect(()=>{const style=document.createElement('style');style.textContent=master;document.head.append(style);return()=>style.remove();},[]);
 const filtered=permitted?(onFilter?rows:rows.filter(r=>r.customerLabel.includes(search)&&(!state||r.stateLabel===state))):[];
 const row=filtered.find(r=>r.id===selectedId),current=permitted&&row&&detail?.contract?.selector.id===selectedId?detail:null;
 function filter(q:string,s:string){setSearch(q);setState(s);onSelect(null);onFilter?.(q,s);}
 return <div className="admin-shell"><BusinessNavigation active="contracts" onTeam={onTeam} onLeads={onLeads} onOverview={onOverview} onOpportunities={onOpportunities} onTasks={onTasks}/><main className="admin-main"><h1>合同台账</h1><p>查看当前有权合同；业务办理回到工作卡。</p>{error&&<p role="alert">{error}</p>}{onManagementView&&<ManagementViewSelect views={managementViews} value="contracts" onChange={onManagementView}/>}<div className="ledger-split"><section className="list-pane"><div className="toolbar"><label className="field"><span className="field-label">搜索客户</span><input value={permitted?search:''} disabled={!permitted} onChange={e=>filter(e.target.value,state)}/></label><label className="field"><span className="field-label">筛选状态</span><select value={permitted?state:''} disabled={!permitted} onChange={e=>filter(search,e.target.value)}><option value="">全部状态</option>{[...new Set(permitted?(onFilter?contractStates:rows.map(r=>r.stateLabel)):[])].map(s=><option key={s}>{s}</option>)}</select></label>{(search||state)&&<button className="link-button" onClick={()=>filter('','')}>清除筛选</button>}</div>{filtered.length?<table className="record-table"><thead><tr><th>客户与合同</th><th>当前事项</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className={selectedId===r.id?'selected':''}><td><button aria-current={selectedId===r.id} onClick={()=>onSelect(r.id)}>{r.customerLabel}</button><small>{r.versionLabel}</small></td><td>{r.stateLabel}{r.ownerLabel&&<> · {r.ownerLabel}</>}</td></tr>)}</tbody></table>:<p role="status">{!permitted?'查看权限已变化，列表与详情已清除。':loading?'正在读取合同…':error||'暂无匹配的合同记录。'}</p>}<button className="link-button" disabled={!permitted||loading} onClick={onReload}>重新查询</button></section><section className="detail-pane" aria-label="合同详情">{current?<><h2>{current.customerName}</h2><dl className="detail-facts"><div><dt>当前事项</dt><dd>{row?.stateLabel}</dd></div>{row?.ownerLabel&&<div><dt>负责人</dt><dd>{row.ownerLabel}</dd></div>}{row?.dueAt&&<div><dt>期限</dt><dd>{new Date(row.dueAt).toLocaleString('zh-CN')}</dd></div>}</dl>{current.contract&&<ContractFacts document={current.contract.document}/>}<details className="history"><summary>查看合同历史</summary>{current.history.length?current.history.map(h=><p key={h.id}>{h.label} · {h.summary}</p>):<p>暂无可展示历史。</p>}</details><div className="ledger-detail-actions">{current.transfer?.stage==='COMPLETE'&&current.transfer.canCorrectClassification&&onCorrectClassification&&<button className="link-button" onClick={()=>onCorrectClassification(current.opportunity.id)}>更正分类及承接</button>}{current.contract&&onView&&<button className="link-button" onClick={()=>onView(current)}>查看合同内容</button>}{row?.canHandle&&(!current.readonly||!!current.selectedPayment?.allowedActions.length||current.transfer?.canHandle)&&<button className="primary" onClick={()=>onHandle(current)}>前往办理</button>}</div></>:<p>{selectedId&&loading?'正在读取准确合同详情…':'选择一条记录查看合同详情。'}</p>}</section></div></main></div>;
}

const contractStates=["待核对本笔收款", "待补充收款凭证", "本笔收款已核对", "待核对执行条件", "等待约定首款到账", "已具备转案条件", "本次销售办理已停止", "终止签约待主管核对", "待核对签署安排", "待提交签署材料", "待签署核验", "待补充签署材料", "部分签署完成", "待签署归档", "签署归档完成", "待修订合同", "合同责任待安排", "待申请准备", "待准备授权", "准备申请已退回", "待形成合同", "待提交签约前审查", "待签约前审查", "待补充审查资料", "审查阻断", "待提交审批", "待审批", "合同已退回", "签署准备已就绪", "待准备转案资料", "转案待补正", "待转案前独立审查", "待案管接收", "已接收，待案件分类", "案件分类及承接已确认", "转案责任待安排", "待核实办理状态"];
