import {render,screen,fireEvent} from '@testing-library/react';
import {describe,it,expect,vi} from 'vitest';
import {ManagementLedger,type ManagementLedgerProps} from './ManagementLedger';
const row={id:'request-1',customerLabel:'海宁实业',basisLabel:'第 2 版合同',stateLabel:'待核对本笔收款',ownerLabel:'财务核对责任人'};
function props():ManagementLedgerProps{return {view:'payments',rows:[row],detail:{id:row.id,customerLabel:row.customerLabel,facts:[['收款情况','本笔尚未确认']],history:[],canHandle:false},selectedId:row.id,search:'',state:'',states:['待核对本笔收款'],loading:false,permitted:true,onView:vi.fn(),onSearch:vi.fn(),onState:vi.fn(),onSelect:vi.fn(),onHandle:vi.fn(),onReload:vi.fn(),onTasks:vi.fn(),onOpportunities:vi.fn()};}
describe('M01 frozen management ledger',()=>{
 it('clears both rows and details on authority loss, including stale detail',()=>{const p=props();const r=render(<ManagementLedger {...p}/>);expect(screen.getByText('本笔尚未确认')).toBeTruthy();r.rerender(<ManagementLedger {...p} permitted={false}/>);expect(screen.queryByText('本笔尚未确认')).toBeNull();expect(screen.queryByRole('button',{name:'海宁实业'})).toBeNull();expect(screen.getByText('查看权限已变化，列表与详情已清除。')).toBeTruthy();});
 it('does not render a handle action for read-only or mismatched detail',()=>{const p=props();const r=render(<ManagementLedger {...p}/>);expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();r.rerender(<ManagementLedger {...p} detail={{...p.detail!,id:'different',canHandle:true}}/>);expect(screen.queryByText('本笔尚未确认')).toBeNull();expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();});
 it('passes the exact request to the existing workcard callback',()=>{const p=props();render(<ManagementLedger {...p} detail={{...p.detail!,canHandle:true}}/>);fireEvent.click(screen.getByRole('button',{name:'前往办理'}));expect(p.onHandle).toHaveBeenCalledWith(row.id);});
 it('delegates filters and view switching to the server-driven parent',()=>{const p=props();render(<ManagementLedger {...p}/>);fireEvent.change(screen.getByLabelText('查看内容'),{target:{value:'transfer'}});expect(p.onView).toHaveBeenCalledWith('transfer');fireEvent.change(screen.getByLabelText('搜索客户'),{target:{value:'甲'}});expect(p.onSearch).toHaveBeenCalledWith('甲');expect(screen.getByRole('button',{name:'海宁实业'})).toBeTruthy();});
 it('hides stale data during loading and failed reads',()=>{const p=props();const r=render(<ManagementLedger {...p} loading/>);expect(screen.queryByText('本笔尚未确认')).toBeNull();expect(screen.getByText('正在读取当前有权记录…')).toBeTruthy();r.rerender(<ManagementLedger {...p} error="读取失败，请重新查询。"/>);expect(screen.queryByText('本笔尚未确认')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'重新查询'}));expect(p.onReload).toHaveBeenCalledTimes(1);});
});
