import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {PaymentReview} from './PaymentReview';
const material={id:'material',sha256:'a'.repeat(64),fileName:'到账凭证.pdf'};
function setup(){const submit=vi.fn().mockResolvedValue(true);render(<PaymentReview accountLabel="基本户 · 尾号 1234" materials={[material]} submit={submit} onDirty={()=>{}}/>);return submit;}
it('returns for correction with reason alone and no invented receipt fields',async()=>{const submit=setup();fireEvent.change(screen.getByLabelText('核对结果'),{target:{value:'RETURN'}});expect(screen.queryByLabelText('本笔实收金额（元）')).toBeNull();fireEvent.change(screen.getByLabelText('核对说明'),{target:{value:'请补充完整流水'}});fireEvent.click(screen.getByRole('button',{name:'记录核对结果'}));await waitFor(()=>expect(submit).toHaveBeenCalledWith({decision:'RETURN',explanation:'请补充完整流水'}));});
it('requires accepted evidence and manual attribution before a receipt can be recorded',()=>{const submit=setup();fireEvent.click(screen.getByRole('button',{name:'记录核对结果'}));expect(submit).not.toHaveBeenCalled();expect(screen.getByText('基本户 · 尾号 1234')).toBeVisible();expect(screen.getByRole('checkbox')).not.toBeChecked();});
it('locks an uncertain submission instead of allowing a second financial write',async()=>{const submit=vi.fn().mockRejectedValue(new Error('network'));render(<PaymentReview accountLabel="基本户" materials={[]} submit={submit} onDirty={()=>{}}/>);fireEvent.change(screen.getByLabelText('核对结果'),{target:{value:'RETURN'}});fireEvent.change(screen.getByLabelText('核对说明'),{target:{value:'请补充流水'}});fireEvent.click(screen.getByRole('button',{name:'记录核对结果'}));expect(await screen.findByText('提交结果尚未确认，请通过当前工作卡核对原提交结果。')).toBeVisible();expect(screen.getByRole('button',{name:'记录核对结果'})).toBeDisabled();expect(submit).toHaveBeenCalledOnce();});
it('records exact cents and selected material without accepting an account from the form',async()=>{const submit=setup();fireEvent.change(screen.getByLabelText('本笔核对凭证'),{target:{value:'material'}});fireEvent.change(screen.getByLabelText('银行交易流水号'),{target:{value:' TX-01 '}});fireEvent.change(screen.getByLabelText('本笔实收金额（元）'),{target:{value:'123.45'}});fireEvent.change(screen.getByLabelText('实际到账时间'),{target:{value:'2026-09-20T10:30'}});fireEvent.change(screen.getByLabelText('核对说明'),{target:{value:'已对照银行流水'}});fireEvent.click(screen.getByRole('checkbox'));fireEvent.click(screen.getByRole('button',{name:'记录核对结果'}));await waitFor(()=>expect(submit).toHaveBeenCalledWith({decision:'CONFIRM',materialVersionId:'material',materialSha256:material.sha256,transactionReference:'TX-01',amountMinor:12345,currency:'CNY',receivedAt:new Date('2026-09-20T10:30').toISOString(),explanation:'已对照银行流水',attributionChecked:true}));});
