import {fireEvent,render,screen,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {App} from './App';
import {createWorkbenchApi} from './lib/api';
import {opportunityEnvelope} from './test/opportunityFixtures';
import {testSession,jsonResponse,selectorId} from './test/fixtures';
import {RecoveryStore} from './features/session/recoveryMarker';
import type {ContractsTransport} from './lib/contractsTransport';
import type {ContractContext} from './features/contracts/types';
it('contract task uses the workbench header, queue and dirty navigation protection',async()=>{
 history.replaceState(null,'','/workbench');
 const base=opportunityEnvelope(), selector={id:selectorId,revision:1};
 const card={...base.currentCard,taskType:'REQUEST_CONTRACT_PREPARATION',businessPurpose:{code:'REQUEST_CONTRACT_PREPARATION',label:'合同办理'},primaryCommand:{code:'REQUEST_CONTRACT_PREPARATION',label:'确认本次办理',enabled:true},expectedCompletionFact:'CONTRACT_PREPARATION_REQUEST',commandForm:{actionCode:'REQUEST_CONTRACT_PREPARATION',schemaVersion:1,values:{},fields:[]}};
 const context:ContractContext={opportunity:selector,responsibilityBasis:selector,customerConfirmation:selector,customerName:'框架验收客户',readonly:false,contract:null,draft:null,workflow:{selector,stage:'DIRECT_REQUEST',task:selector,ownerAppointmentId:selectorId},review:null,approvals:[],allowedActions:['REQUEST_CONTRACT_PREPARATION'],blockers:[],history:[],receiptBoundary:null};
 const contractsApi={recovery:new RecoveryStore(sessionStorage),taskContext:vi.fn().mockResolvedValue({opportunityId:selectorId,context}),context:vi.fn(),write:vi.fn(),receipt:vi.fn(),download:vi.fn(),list:vi.fn()} satisfies ContractsTransport;
 const session={...testSession(),canReadOpportunityLedger:true};
 const readWorkbench=vi.fn(async()=>jsonResponse({...base,currentCard:card,myTasks:[]}));
 render(<App session={session} contractsApi={contractsApi} api={createWorkbenchApi(readWorkbench)}/>);
 fireEvent.change(await screen.findByLabelText('服务范围'),{target:{value:'未保存内容'}});
 expect(screen.getAllByRole('main')).toHaveLength(1);
 expect(screen.getAllByRole('banner')).toHaveLength(1);
 expect(screen.getByText('我的待办（0）').closest('summary')).toHaveClass('workbench-control');
 expect(screen.getByRole('button',{name:'刷新当前责任'})).toBeDisabled();
 fireEvent.click(screen.getByRole('button',{name:'业务管理'}));
 expect(await screen.findByRole('dialog',{name:'离开当前待办？'})).toBeVisible();
 fireEvent.click(screen.getByRole('button',{name:'继续填写'}));
 await waitFor(()=>expect(screen.getByLabelText('服务范围')).toHaveValue('未保存内容'));
 contractsApi.write.mockResolvedValue({} as never);
 contractsApi.context.mockResolvedValue({...context,readonly:true,allowedActions:[],workflow:{...context.workflow!,stage:'DIRECT_REVIEW',task:null,ownerAppointmentId:'other'}});
 fireEvent.change(screen.getByLabelText('收费项目 1'),{target:{value:'固定费用'}});
 fireEvent.change(screen.getByLabelText('金额（元）1'),{target:{value:'100'}});
 fireEvent.change(screen.getByLabelText('付款安排'),{target:{value:'按约支付'}});
 fireEvent.change(screen.getByLabelText('申请原因与沟通依据'),{target:{value:'已确认客户要求'}});
 fireEvent.click(screen.getByRole('button',{name:'提交直接准备申请'}));
 await screen.findByRole('heading',{name:'查看合同历史'});
 const reads=readWorkbench.mock.calls.length;
 fireEvent.focus(window);
 expect(readWorkbench).toHaveBeenCalledTimes(reads);
 expect(screen.getByText('框架验收客户')).toBeVisible();

});
it('opens authorized taskless contract revision in the shared shell and protects unsaved changes',async()=>{
 history.replaceState(null,'','/management/opportunities');
 const selector={id:selectorId,revision:1}, base=opportunityEnvelope();
 const context:ContractContext={opportunity:selector,responsibilityBasis:selector,customerConfirmation:selector,customerName:'缺少签署配置的合同',readonly:false,contract:{selector,currentRevision:{id:'version',hash:'hash'},version:1,source:{kind:'DIRECT_AUTHORIZATION',selector},stage:'READY_FOR_SIGNATURE',document:{commercial:{currency:'CNY',scope:'合成范围',lines:[],conditionalFee:null,paymentTerms:'合成安排'},document:{evidenceVersionId:'file',bodySha256:'hash',templateVersionId:'template',clauseVersionIds:[]}}},draft:null,workflow:null,review:null,approvals:[],allowedActions:['RETURN_CONTRACT_FOR_REVISION'],blockers:[],history:[],receiptBoundary:null,signature:{workflow:{selector:null,stage:'OWNER_EXCEPTION',task:null,ownerAppointmentId:null,message:'本版模板未登记律所签署主体，请退回修订。'},parties:[],arrangements:[],submissions:[],draft:null,handoff:null}};
 const contractsApi={recovery:new RecoveryStore(sessionStorage),taskContext:vi.fn(),context:vi.fn().mockResolvedValue(context),write:vi.fn(),receipt:vi.fn(),download:vi.fn(),list:vi.fn().mockResolvedValue({items:[{id:selectorId,opportunityId:selectorId,customerLabel:context.customerName,versionLabel:'第1版',stateLabel:'合同责任待安排',ownerLabel:'',canHandle:true}],nextCursor:null})} satisfies ContractsTransport;
 const ledgerApi={list:vi.fn().mockResolvedValue({items:[],nextCursor:null}),detail:vi.fn()} as any;
 render(<App session={{...testSession(),canReadOpportunityLedger:true,canEnterWorkbench:true}} ledgerApi={ledgerApi} contractsApi={contractsApi} api={createWorkbenchApi(async()=>jsonResponse({...base,myTasks:[]}))}/>);
 fireEvent.click(screen.getByRole('button',{name:'合同台账'}));
 fireEvent.click(await screen.findByRole('button',{name:context.customerName}));
 fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));
 fireEvent.click(await screen.findByRole('button',{name:'正文或主体需要修订'}));
 expect(window.location.pathname).toBe('/workbench');
 expect(screen.getAllByRole('banner')).toHaveLength(1);
 expect(screen.getAllByRole('main')).toHaveLength(1);
 expect(contractsApi.context.mock.calls.length).toBeGreaterThanOrEqual(2);
 expect(contractsApi.taskContext).not.toHaveBeenCalled();
 expect(screen.queryByText('暂时没有合格责任人，请由有权主管处理责任安排；原期限和业务来源保留。')).toBeNull();
 expect(contractsApi.write).not.toHaveBeenCalled();
 fireEvent.change(screen.getByLabelText('修订原因'),{target:{value:'签署配置需要修订'}});
 fireEvent.click(screen.getByRole('button',{name:'业务管理'}));
 expect(await screen.findByRole('dialog',{name:'离开当前待办？'})).toBeVisible();
 expect(screen.queryByRole('button',{name:/保存草稿后/})).toBeNull();
});
