import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {FollowupAttemptCard} from './FollowupAttemptCard';
import {testSession,taskId,selectorId} from '../../test/fixtures';
import {RecoveryStore} from '../session/recoveryMarker';
import {TransportError} from '../../lib/sessionTransport';
const context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{type:'opportunity.opportunity',id:selectorId,revision:0},task:{id:taskId,revision:1},taskState:'WAITING',waitReceipt:{id:selectorId,hash:'a'.repeat(43)},expectedWorkflow:null,nextCheckAt:'2099-10-01T00:00:00Z',command:'RECORD_OPPORTUNITY_FOLLOWUP_ATTEMPT',history:[]};
function setup(){const api={recovery:new RecoveryStore(sessionStorage),context:vi.fn().mockResolvedValue(context),write:vi.fn().mockResolvedValue({outcome:'SUCCEEDED'}),receipt:vi.fn().mockResolvedValue({outcome:'SUCCEEDED'})},onBack=vi.fn(),onTasks=vi.fn();render(<FollowupAttemptCard session={testSession()} opportunityId={selectorId} customerLabel="合成客户" ownerLabel="销售" api={api as never} onBack={onBack} onTasks={onTasks}/>);return{api,onBack,onTasks};}
async function fill(){fireEvent.change(await screen.findByLabelText('本次情况'),{target:{value:'NO_REPLY'}});fireEvent.change(screen.getByLabelText('实际联系时间'),{target:{value:'2026-09-24T12:00'}});fireEvent.change(screen.getByLabelText('本次尝试与后续安排'),{target:{value:'本次尚未回复，明日联系'}});fireEvent.change(screen.getByLabelText('下次联系时间'),{target:{value:'2099-10-01T12:00'}});}
it('records once from a waiting task and displays the next appointment',async()=>{const {api}=setup();await fill();expect(document.querySelectorAll('.primary')).toHaveLength(1);const button=screen.getByRole('button',{name:'记录尝试并安排下次联系'});fireEvent.click(button);fireEvent.click(button);await screen.findByText('已记录本次尝试，等待约定联系时间。');expect(api.write).toHaveBeenCalledOnce();expect(api.write.mock.calls[0][1]).toMatchObject({command:'RECORD_OPPORTUNITY_FOLLOWUP_ATTEMPT',body:{waitReceipt:context.waitReceipt,values:{type:'NO_REPLY'}}});expect(screen.queryByRole('button',{name:'记录尝试并安排下次联系'})).toBeNull();});
it('a lost submission only checks its receipt and never sends again',async()=>{const {api}=setup();api.write.mockRejectedValue(Error('lost'));await fill();fireEvent.click(screen.getByRole('button',{name:'记录尝试并安排下次联系'}));fireEvent.click(await screen.findByRole('button',{name:'核对本次结果'}));await screen.findByText('已记录本次尝试，等待约定联系时间。');expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();});
it('guards leaving unsaved input and never records an attempt implicitly',async()=>{const {api,onBack}=setup();await fill();fireEvent.click(screen.getByRole('button',{name:'返回原事项'}));await screen.findByText('保留当前填写内容？');expect(onBack).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'放弃本次输入并返回'}));await waitFor(()=>expect(onBack).toHaveBeenCalledOnce());expect(api.write).not.toHaveBeenCalled();});
it('a failed refresh after confirmed success never reopens the submission form',async()=>{const {api}=setup();await fill();api.context.mockRejectedValueOnce(Error('read failed'));fireEvent.click(screen.getByRole('button',{name:'记录尝试并安排下次联系'}));fireEvent.click(await screen.findByRole('button',{name:'重新读取并核对'}));await screen.findByText('已记录本次尝试，等待约定联系时间。');expect(api.write).toHaveBeenCalledOnce();expect(screen.queryByLabelText('本次情况')).toBeNull();});
it('rejects a past next appointment before sending',async()=>{const {api}=setup();await fill();fireEvent.change(screen.getByLabelText('下次联系时间'),{target:{value:'2020-01-01T00:00'}});fireEvent.click(screen.getByRole('button',{name:'记录尝试并安排下次联系'}));await screen.findByRole('alert');expect(api.write).not.toHaveBeenCalled();});
it('clears private form and history when authority is revoked',async()=>{const {api}=setup();await fill();api.write.mockRejectedValue(new TransportError(403,'NOT_AUTHORIZED'));fireEvent.click(screen.getByRole('button',{name:'记录尝试并安排下次联系'}));await screen.findByText('当前事项已无权查看或办理，请返回工作台。');expect(screen.queryByDisplayValue('本次尚未回复，明日联系')).toBeNull();expect(screen.queryByText('合成客户')).toBeNull();});

it.each(['OPEN',null])('after receipt recovery the current %s state does not claim a future wait',async(taskState)=>{const {api}=setup();api.write.mockRejectedValue(Error('lost'));await fill();fireEvent.click(screen.getByRole('button',{name:'记录尝试并安排下次联系'}));await screen.findByRole('button',{name:'核对本次结果'});api.context.mockResolvedValue({...context,taskState,task:taskState?context.task:null,command:taskState?context.command:null,waitReceipt:null,nextCheckAt:null});fireEvent.click(screen.getByRole('button',{name:'核对本次结果'}));await screen.findByRole('heading',{name:'本次安排已记录'});expect(screen.queryByText('已记录本次尝试，等待约定联系时间。')).toBeNull();expect(screen.queryByText(/到期恢复.*待办/)).toBeNull();expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();});
