import {useEffect,useRef,useState,type ReactNode} from 'react';
import {CheckCircle,User} from '@phosphor-icons/react';
import type {WorkbenchSession} from '../../lib/api';
import {TransportError} from '../../lib/sessionTransport';
import type {AttemptContext,AttemptWrite,FollowupAttemptsTransport} from '../../lib/followupAttemptsTransport';
import {MyTasksControl} from '../workcard/MyTasksControl';
import master from './ledgerMaster.css?inline';
import scales from './assets/Scales-green.svg';
type Phase='loading'|'ready'|'sending'|'unknown'|'stale'|'failed'|'denied'|'leave'|'done';
const labels={NOT_CONNECTED:'未接通',NO_REPLY:'尚未回复',NO_EFFECTIVE_PROGRESS:'已联系，暂无有效进展'};
const time=(v:string|null)=>v?new Date(v).toLocaleString('zh-CN'):'暂无约定时间';
export function FollowupAttemptCard({session,opportunityId,customerLabel,ownerLabel,api,onBack,onTasks,sessionActions,onDenied}:{session:WorkbenchSession;opportunityId:string;customerLabel:string;ownerLabel:string;api:FollowupAttemptsTransport;onBack:()=>void;onTasks?:()=>void;sessionActions?:ReactNode;onDenied?:()=>void}){
 const [context,setContext]=useState<AttemptContext|null>(null),[phase,setPhase]=useState<Phase>('loading'),[kind,setKind]=useState(''),[at,setAt]=useState(''),[summary,setSummary]=useState(''),[next,setNext]=useState(''),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
 const alive=useRef(true),current=useRef(session),busy=useRef(false),committed=useRef(false),destination=useRef<(()=>void)|null>(null);current.current=session;
 const valid=()=>alive.current&&current.current===session&&session.isCurrent(),locked=['loading','sending','unknown'].includes(phase);
 const clear=()=>{setContext(null);setKind('');setAt('');setSummary('');setNext('');setDirty(false);};
 function failure(error:unknown,writing=false){if(!valid())return;if(error instanceof TransportError&&[401,403,404].includes(error.status)){clear();setPhase('denied');onDenied?.();return;}if(writing&&!(error instanceof TransportError&&error.provenOutcome)){setPhase('unknown');setMessage('结果尚未确认，请核对原操作，不重复记录。');return;}if(error instanceof TransportError&&[409,412,428].includes(error.status)){clear();setPhase('stale');setMessage('当前责任或办理依据已变化，请重新核对。');return;}setPhase(writing?'ready':'failed');setMessage(writing?'请核对本次情况、实际联系时间和未来的下次联系时间。':'当前安排读取失败，请重新读取。');}
 async function read(done=committed.current){setPhase('loading');try{const result=await api.context(session,opportunityId,new AbortController().signal);if(!valid())return;setContext(result);setPhase(done?'done':'ready');}catch(e){failure(e);}}
 useEffect(()=>{const style=document.createElement('style');style.textContent=master;document.head.append(style);return()=>style.remove();},[]);
 useEffect(()=>{alive.current=true;committed.current=false;clear();try{if(api.recovery.read())setPhase('unknown');else void read();}catch{setPhase('unknown');}return()=>{alive.current=false;};},[session,opportunityId,api]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||locked){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,locked]);
 function navigate(go:()=>void){if(locked)return;if(dirty){destination.current=go;setPhase('leave');}else go();}
 async function submit(recover=false){if(busy.current||!valid()||!recover&&(!context?.command||phase!=='ready'))return;
  let values:AttemptWrite['body']['values']|undefined;
  if(!recover){if(!Object.hasOwn(labels,kind)||!summary.trim()||!at||!next||!Number.isFinite(Date.parse(at))||!Number.isFinite(Date.parse(next))||Date.parse(at)>Date.now()||Date.parse(next)<=Date.now()){setMessage('请选择本次情况，填写实际联系时间、尝试说明和未来的下次联系时间。');return;}values={type:kind as keyof typeof labels,summary:summary.trim(),occurredAt:new Date(at).toISOString(),nextCheckAt:new Date(next).toISOString()};}
  busy.current=true;setPhase('sending');setMessage('');let confirmed=false;
  try{if(recover)await api.receipt(session,new AbortController().signal);else await api.write(session,{key:crypto.randomUUID(),opportunityId,command:context!.command!,body:{expectedOpportunityRevision:context!.opportunity.revision,responsibilityBasis:context!.responsibilityBasis,task:context!.task!,waitReceipt:context!.waitReceipt,expectedWorkflow:context!.expectedWorkflow,values:values!}},new AbortController().signal);confirmed=true;committed.current=true;if(!valid())return;setDirty(false);setKind('');setAt('');setSummary('');setNext('');await read(true);}catch(e){failure(e,!confirmed);}finally{busy.current=false;}
 }
 if(!session.isCurrent())return null;
 const quote=context?.command==='RECORD_QUOTE_FOLLOWUP_ATTEMPT'||!!context?.expectedWorkflow;
 const waiting=context?.taskState==='WAITING'&&!!context.nextCheckAt,awaiting=waiting&&Date.parse(context!.nextCheckAt!)>Date.now();
 let body:ReactNode;
 if(phase==='loading')body=<p role="status">正在核对当前联系安排…</p>;
 else if(phase==='denied')body=<p role="alert">当前事项已无权查看或办理，请返回工作台。</p>;
 else if(phase==='stale'||phase==='failed')body=<><p role="alert">{message}</p><div className="action-area"><button className="primary" onClick={()=>void read()}>重新读取并核对</button></div></>;
 else if(phase==='sending'||phase==='unknown')body=<><h2>核对本次结果</h2><p role="status">{message||'正在记录，请勿重复提交。'}</p>{phase==='unknown'&&<div className="action-area"><button className="primary" onClick={()=>void submit(true)}>核对本次结果</button></div>}</>;
 else if(phase==='leave')body=<><h2>保留当前填写内容？</h2><p>本次输入尚未记录，也未改变联系安排。</p><div className="action-area"><button className="primary" onClick={()=>{destination.current=null;setPhase('ready');}}>继续填写</button><button className="link-button" onClick={()=>{setDirty(false);destination.current?.();destination.current=null;}}>放弃本次输入并返回</button></div></>;
 else if(phase==='done')body=<><h2>本次安排已记录</h2><p role="status">{awaiting?'已记录本次尝试，等待约定联系时间。':context?.taskState==='OPEN'?'本次尝试已记录，当前待办已可继续办理。':waiting?'本次尝试已记录，约定时间已到，请查看当前待办恢复情况。':'本次尝试已记录，业务已转入后续安排，请查看当前事项。'}</p>{waiting&&<dl className="detail-facts"><div><dt>约定联系</dt><dd>{time(context?.nextCheckAt??null)}</dd></div>{awaiting&&<div><dt>后续责任</dt><dd>到期恢复{quote?'报价回复':'商机跟进'}待办</dd></div>}</dl>}<div className="action-area"><button className="primary" onClick={onTasks??onBack}>查看我的待办</button></div></>;
 else if(!context?.command)body=<><h2>查看联系尝试</h2><p>当前事项已由后续环节接管，或本任职无权记录新的联系安排。</p></>;
 else body=<><h2>{quote?'客户尚未回复本版报价':'记录本次联系尝试'}</h2><form onSubmit={e=>{e.preventDefault();void submit();}} noValidate><label className="field"><span className="field-label">本次情况</span><select value={kind} onChange={e=>{setKind(e.target.value);setDirty(true);}}><option value="">请选择</option>{Object.entries(labels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label className="field"><span className="field-label">实际联系时间</span><input type="datetime-local" value={at} onChange={e=>{setAt(e.target.value);setDirty(true);}}/></label><label className="field"><span className="field-label">本次尝试与后续安排</span><textarea maxLength={2000} value={summary} onChange={e=>{setSummary(e.target.value);setDirty(true);}}/></label><label className="field"><span className="field-label">下次联系时间</span><input type="datetime-local" value={next} onChange={e=>{setNext(e.target.value);setDirty(true);}}/></label><p>本次仅记录联系尝试，不计有效进展{quote?'，不生成客户接受或拒绝事实':''}。原到期时间和逾期历史保留。</p>{message&&<p role="alert">{message}</p>}<div className="action-area"><button className="primary" type="submit">记录尝试并安排下次联系</button></div></form></>;
 return <><header className="app-header"><div className="brand"><img className="icon" src={scales} alt=""/>律所工作助手</div><div className="session" inert={dirty||locked}>{sessionActions??session.displayName}</div></header><main className="workbench" aria-label="联系尝试与后续安排"><div className="today"><p className="today-copy"><CheckCircle className="icon"/><span>如实记录本次联系，按约定时间继续办理。</span></p>{onTasks&&<MyTasksControl disabled={locked} onClick={()=>navigate(onTasks)}/>}</div><article className="work-card"><div className="context"><p className="eyebrow">当前责任</p><h1>{quote?'安排报价后续联系':'记录本次联系尝试'}</h1>{phase!=='denied'&&<><p className="subject">{customerLabel}</p><p className="owner-line"><User className="icon"/>{ownerLabel}负责</p>{context?.nextCheckAt&&<p>当前约定时间：{time(context.nextCheckAt)}</p>}</>}{context&&<details className="history"><summary>历次联系尝试</summary>{context.history.length?context.history.map(r=><section key={r.selector.id}><h3>{labels[r.type]}</h3><p>{r.summary}</p><p>实际联系：{time(r.occurredAt)}</p><p>下次安排：{time(r.nextCheckAt)}</p><p>经授权人员记录 · {time(r.recordedAt)}</p></section>):<p>暂无联系尝试记录。</p>}</details>}</div><section className="card-action">{body}{phase!=='leave'&&<div className="secondary-line"><button className="link-button" disabled={locked} onClick={()=>navigate(onBack)}>返回原事项</button></div>}</section></article></main></>;
}
