import {AiCandidatePanel} from '../ai/AiCandidatePanel';
import type {AiCandidateTransport} from '../../lib/aiCandidateTransport';
import {CheckCircle,Clock,User} from '@phosphor-icons/react';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import type {WorkbenchSession} from '../../lib/api';
import {TransportError} from '../../lib/sessionTransport';
import type {MaterialContext,MaterialUpload,MaterialVersion,MaterialPurpose,MaterialsTransport,MaterialCommand} from '../../lib/materialsTransport';
import type {LedgerDetail} from '../../lib/opportunityLedgerTransport';
import scales from './assets/Scales-green.svg';
const fileType=(type?:string)=>type==='application/pdf'?'PDF':type==='image/jpeg'?'JPG':type==='image/png'?'PNG':'待检查';
export const materialPurposes:Record<MaterialPurpose,string>={CONTRACT_BUSINESS:'合同及业务资料',CORRESPONDENCE:'相关往来记录',OTHER:'其他材料'};
type Phase='loading'|'list'|'select'|'checking'|'review'|'sending'|'unknown'|'saved'|'stale'|'failed'|'rejected'|'leave'|'preview';
const unknownUpload=(u:MaterialUpload)=>['CHECKING','UNKNOWN'].includes(u.state);
export function MaterialsCard({session,detail,api,aiApi,sessionActions,onBack,onContinue,onDenied,backLabel='返回商机台账',continueLabel}:{aiApi?:AiCandidateTransport;session:WorkbenchSession;detail:LedgerDetail;api:MaterialsTransport;sessionActions?:ReactNode;onBack:()=>void;onContinue:()=>Promise<void>;onDenied:()=>void;backLabel?:string;continueLabel?:string}){
 const [context,setContext]=useState<MaterialContext|null>(null),[phase,setPhase]=useState<Phase>('loading'),[upload,setUpload]=useState<MaterialUpload|null>(null),[file,setFile]=useState<File|null>(null),[purpose,setPurpose]=useState<MaterialPurpose>('CONTRACT_BUSINESS'),[note,setNote]=useState(''),[previous,setPrevious]=useState<MaterialVersion|null>(null),[dirty,setDirty]=useState(false),[message,setMessage]=useState(''),[history,setHistory]=useState(false),[preview,setPreview]=useState<{version:MaterialVersion;url:string}|null>(null);
 const active=useRef(session);active.current=session;const alive=useRef(true),busy=useRef(false),pending=useRef<MaterialCommand|null>(null),blobUrl=useRef<string|null>(null),callbacks=useRef({onBack,onContinue,onDenied});callbacks.current={onBack,onContinue,onDenied};
 const valid=()=>alive.current&&active.current===session&&session.isCurrent();
 const locked=['loading','checking','sending','unknown'].includes(phase);
 function release(){if(blobUrl.current)URL.revokeObjectURL(blobUrl.current);blobUrl.current=null;setPreview(null);}
 function clear(){release();setContext(null);setUpload(null);setFile(null);setNote('');setPrevious(null);setDirty(false);}
 function fail(error:unknown,command=false){if(!valid())return;if(error instanceof TransportError&&[401,403,404].includes(error.status)){clear();callbacks.current.onDenied();return;}if(command&&!(error instanceof TransportError&&error.provenOutcome)){setPhase('unknown');setMessage('接收结果尚未确认，请勿重新上传或重复接收。');return;}if(error instanceof TransportError&&[409,412].includes(error.status)){pending.current=null;clear();setPhase('stale');setMessage('负责人、商机或所选版本已变化。请重新读取并核对。');return;}setMessage(command?'本次材料未通过核对，请重新读取后继续。':'本次读取失败，请重试。');setPhase(command?'stale':'failed');}
 async function read(){setPhase('loading');try{const data=await api.context(session,detail.opportunity.id,new AbortController().signal);if(!valid())return;setContext(data);setPhase('list');setMessage('');setDirty(false);}catch(e){fail(e);}}
 useEffect(()=>{alive.current=true;void read();return()=>{alive.current=false;if(blobUrl.current)URL.revokeObjectURL(blobUrl.current);};},[session,api,detail.opportunity.id]);
 useEffect(()=>{const guard=(e:BeforeUnloadEvent)=>{if(dirty||locked){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[dirty,locked]);
 const basis=()=>({expectedOpportunityRevision:context!.opportunity.revision,responsibilityBasis:context!.responsibilityBasis!,expectedConfirmation:upload?upload.confirmation:context?.confirmation??null,expectedPreviousVersion:upload?upload.previousVersion:previous?.selector??null});
 function receive(u:MaterialUpload){const prior=u.previousVersion?context?.versions.find(v=>v.selector.id===u.previousVersion!.id&&v.selector.revision===u.previousVersion!.revision):null;if(u.previousVersion&&!prior){clear();setPhase('stale');setMessage('原版本无法核对，请重新读取材料。');return;}setPrevious(prior??null);setUpload(u);setPurpose(u.purpose);setNote(u.note??'');setDirty(true);setMessage('');if(u.state==='PASSED')setPhase('review');else if(u.state==='OPEN')setPhase('select');else if(u.state==='ACCEPTED'){setDirty(false);setPhase('saved');}else if(unknownUpload(u))setPhase('checking');else{setFile(null);setDirty(false);setPhase('rejected');}}
 async function status(u=upload){if(!u||busy.current||!valid())return;busy.current=true;setUpload(u);setPhase('checking');try{const fresh=await api.status(session,detail.opportunity.id,u.selector.id,new AbortController().signal);if(valid())receive(fresh);}catch(e){if(e instanceof TransportError&&[401,403,404,409,412].includes(e.status))fail(e);else if(valid()){setPhase('checking');setMessage('上传状态尚未确认，请继续核对原上传，不要重新选择或发送文件。');}}finally{busy.current=false;}}
 async function sendBytes(u:MaterialUpload){if(!file)return;setUpload(u);setPhase('checking');try{const result=await api.upload(session,detail.opportunity.id,u.selector.id,file,new AbortController().signal);if(valid()){setFile(null);receive(result);}}catch(e){if(e instanceof TransportError&&[401,403,404,409,412].includes(e.status))fail(e);else if(valid()){setPhase('checking');setMessage('上传状态尚未确认，请核对原上传。');}}}
 async function finish(command:MaterialCommand,receipt:{resultFact:{factRef:string;revision?:number}}){pending.current=null;if(command==='ACCEPT_OPPORTUNITY_MATERIAL'){setDirty(false);setFile(null);setPhase('saved');setMessage('材料已接收；原事项与时限保持。');return;}const fresh=await api.context(session,detail.opportunity.id,new AbortController().signal);if(!valid())return;const opened=fresh.pendingUploads.find(u=>u.factRef===receipt.resultFact.factRef&&u.selector.revision===receipt.resultFact.revision);if(!opened){clear();setPhase('stale');setMessage('上传依据已变化，请重新读取。');return;}setContext(fresh);setUpload(opened);if(opened.state==='OPEN'&&file)await sendBytes(opened);else receive(opened);}
 async function command(type:MaterialCommand,recover=false){if(busy.current||!valid()||!recover&&(!context?.editable||context.closed))return;busy.current=true;setMessage('');setPhase('sending');if(!recover)pending.current=type;try{const receipt=recover?await api.receipt(session,new AbortController().signal):await api.write(session,{key:crypto.randomUUID(),opportunityId:detail.opportunity.id,command:type,body:type==='OPEN_OPPORTUNITY_MATERIAL_UPLOAD'?{...basis(),purpose,fileName:file!.name,note:note.trim()||null}:{...basis(),uploadSession:upload!.selector}},new AbortController().signal);if(valid())await finish(type,receipt as {resultFact:{factRef:string;revision?:number}});}catch(e){fail(e,pending.current!==null);}finally{busy.current=false;}}
 async function startUpload(){if(!file){setMessage('请先选择要接收的文件。');return;}if(file.size===0||file.size>20971520||!/[.](pdf|jpe?g|png)$/i.test(file.name)){setMessage('请选择不超过 20 MB 的 PDF、JPG 或 PNG 文件。');return;}if(upload){if(upload.state!=='OPEN'){void status();return;}if(file.name!==upload.fileName){setMessage('请重新选择本次上传原文件；文件名称应与原会话一致。');return;}if(busy.current)return;busy.current=true;try{await sendBytes(upload);}finally{busy.current=false;}}else await command('OPEN_OPPORTUNITY_MATERIAL_UPLOAD');}
 function choose(version:MaterialVersion|null=null){setPrevious(version);setUpload(null);setFile(null);setNote('');setPurpose(version?.purpose??'CONTRACT_BUSINESS');setPhase('select');setDirty(false);setMessage('');}
 async function content(v:MaterialVersion,inline:boolean){if(busy.current)return;busy.current=true;setMessage('');try{const blob=await api.content(session,detail.opportunity.id,v,inline,new AbortController().signal);if(!valid())return;release();const url=URL.createObjectURL(blob);if(inline){blobUrl.current=url;setPreview({version:v,url});setPhase('preview');}else{const a=document.createElement('a');a.href=url;a.download=v.fileName;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已下载所选准确版本。');}}catch(e){if(e instanceof TransportError&&[401,403,404].includes(e.status))fail(e);else if(valid())setMessage('此版本读取失败，可以重试；版本关系保持不变。');}finally{busy.current=false;}}
 const versionNumber=(v:MaterialVersion)=>{let n=1,previous=v.previousVersionId;const seen=new Set<string>();while(previous&&!seen.has(previous)){seen.add(previous);const prior=context?.versions.find(x=>x.selector.id===previous);if(!prior)break;n++;previous=prior.previousVersionId;}return n;};
 const latest=context?.versions.filter(v=>!context.versions.some(x=>x.previousVersionId===v.selector.id))??[];
 const summary=<dl className="detail-facts">{[['归属',detail.customerLabel],['文件',upload?.fileName??file?.name??'尚未选择'],['用途',materialPurposes[upload?.purpose??purpose]],...(upload?.sizeBytes?[['文件检查',fileType(upload.mediaType)+' · '+(upload.sizeBytes/1024).toFixed(1)+' KB']]:[]),['版本',upload?.previousVersion||previous?'补交新版；原版保留':'首次接收'],['客户资料',(upload?upload.confirmation:context?.confirmation)?'关联本次准确确认版本':'尚未确认，先归属当前商机'],['说明',(upload?.note??note)||'暂无补充']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl>;
 let body:ReactNode;
 if(phase==='loading')body=<p role="status">正在读取材料…</p>;
 else if(phase==='failed'||phase==='stale')body=<><h2>{phase==='stale'?'本次接收依据已变化':'材料读取失败'}</h2><p role="alert">{message}</p><button className="primary" onClick={()=>void read()}>重新读取材料</button></>;
 else if(phase==='leave')body=<><h2>本次有未确认的材料</h2><p>离开后不提交为商机材料，原已接收版本保留。已发出的上传会话仍可从本商机核对。</p><button className="primary" onClick={()=>setPhase(upload?.state==='PASSED'?'review':'select')}>继续核对</button><button onClick={()=>{clear();onBack();}}>放弃本次操作并返回</button></>;
 else if(phase==='sending'||phase==='unknown')body=<><h2>接收结果尚未确认</h2><p role="status">{message||'正在核对本次操作，请勿重复提交。'}</p>{summary}{phase==='unknown'&&<button className="primary" onClick={()=>void command(pending.current!,'unknown'===phase)}>核对本次结果</button>}</>;
 else if(phase==='checking')body=<><h2>正在检查文件</h2><p role="status">{message||'文件内容与安全检查中，当前尚未成为已接收材料。'}</p>{summary}<button className="primary" onClick={()=>void status()}>查看检查结果</button></>;
 else if(phase==='rejected')body=<><h2>本次文件未能接收</h2><p>{upload?.state==='SCAN_UNAVAILABLE'?'安全检查暂不可用，本次文件未保存；稍后重新选择文件。':'文件检查未通过或上传已过期。原已接收材料不受影响。'}</p><button className="primary" onClick={()=>choose(previous)}>重新选择文件</button><button onClick={()=>void read()}>返回材料清单</button></>;
 else if(phase==='saved')body=<><h2>材料已接收</h2>{summary}<p role="status">{detail.taskState==='WAITING'?'原约定联系时间不变，跟进不会提前恢复。':'原跟进事项和时限不变，可接着办理。'}</p><div className="action-area"><button className="primary" onClick={()=>{setPhase('loading');void onContinue().catch(e=>fail(e));}}>{continueLabel??(detail.taskState==='OPEN'&&detail.task?'继续原跟进事项':'返回商机台账')}</button><div className="secondary-line"><button className="link-button" onClick={()=>void read()}>查看材料清单</button></div></div></>;
 else if(phase==='review')body=<><h2>核对本次材料接收</h2>{summary}<p className="help">文件检查已通过。接收表示材料已登记，不代表内容属实、签署有效或款项到账。</p><div className="action-area"><button className="primary" onClick={()=>void command('ACCEPT_OPPORTUNITY_MATERIAL')}>确认接收材料</button><div className="secondary-line"><button className="link-button" onClick={()=>setPhase('leave')}>返回材料清单</button></div></div></>;
 else if(phase==='select')body=<><h2>{previous?'补交材料新版':'接收本次材料'}</h2><p className="help">归属当前商机；每次接收一个文件。</p>{previous&&<p className="feedback">原文件：{previous.fileName}。接收后保留原文件，已引用的旧版本不自动替换。</p>}{!context?.confirmation&&<p className="feedback">客户与需求尚未确认，材料先归属当前商机，不自动认定委托主体。</p>}<label className="field">材料用途<select disabled={!!upload} value={purpose} onChange={e=>{setPurpose(e.target.value as MaterialPurpose);setDirty(true);}}>{Object.entries(materialPurposes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">选择文件<input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={e=>{setFile(e.target.files?.[0]??null);setDirty(true);setMessage('');}}/></label><p>{file?.name??upload?.fileName??'尚未选择文件'}</p><p className="help">支持 PDF、JPG、PNG，单文件不超过 20 MB。</p><details className="history"><summary>材料说明（需要时填写）</summary><label className="field">材料说明<textarea disabled={!!upload} maxLength={500} value={note} onChange={e=>{setNote(e.target.value);setDirty(true);}}/></label></details>{message&&<p role="alert">{message}</p>}<div className="action-area"><button className="primary" onClick={()=>void startUpload()}>上传并核对</button><div className="secondary-line"><button className="link-button" onClick={()=>dirty?setPhase('leave'):void read()}>返回材料清单</button></div></div></>;
 else if(phase==='preview'&&preview)body=<><h2>{preview.version.fileName}</h2><div className="document-preview"><img src={preview.url} alt={preview.version.fileName} style={{maxWidth:'100%',height:'auto'}}/></div><button className="primary" onClick={()=>{release();setPhase('list');}}>返回材料</button><button onClick={()=>void content(preview.version,false)}>下载此版本</button>{message&&<p role="status">{message}</p>}</>;
 else body=<><h2>已接收材料</h2><p className="help">缺项仅作销售准备参考，不自动阻断报价、签约或转案。</p>{(['CONTRACT_BUSINESS','CORRESPONDENCE'] as MaterialPurpose[]).filter(p=>!latest.some(v=>v.purpose===p)).map(p=><p key={p}>{materialPurposes[p]}：待补充</p>)}{!latest.length&&<p>尚未接收材料。</p>}{(history?context?.versions:latest)?.map(v=><section className="compact-confirm" key={v.selector.id}><h3>{v.fileName}</h3><p>{materialPurposes[v.purpose]} · {fileType(v.mediaType)} · 第 {versionNumber(v)} 版 · {new Date(v.receivedAt).toLocaleString('zh-CN')} · {latest.includes(v)?'当前版本':'历史保留'}</p><p>接收人：{v.receivedByLabel??'接收人信息受限'}</p>{v.note&&<p>{v.note}</p>}{v.previewAllowed&&<button onClick={()=>void content(v,true)}>预览此版本</button>}<button onClick={()=>void content(v,false)}>下载此版本</button>{!v.previewAllowed&&<p className="help">此文件通过授权下载查看。</p>}{context?.editable&&latest.includes(v)&&!context.pendingUploads.some(unknownUpload)&&<button onClick={()=>choose(v)}>补交新版</button>}</section>)}{!!context?.versions.length&&<button className="link-button" onClick={()=>setHistory(!history)}>{history?'仅看当前版本':'查看历史版本'}</button>}{context?.pendingUploads.map(u=><section key={u.selector.id} className="compact-confirm"><p>{u.fileName} · 尚未接收</p><button onClick={()=>void status(u)}>{unknownUpload(u)?'核对上传状态':'继续核对本次材料'}</button></section>)}{context?.closed?<p className="help">商机已结束，仅可查看已接收材料。</p>:context?.editable?<div className="action-area"><button className="primary" disabled={context.pendingUploads.some(unknownUpload)} onClick={()=>choose()}>接收本次材料</button></div>:<p className="help">当前仅可查看已接收材料。</p>}{message&&<p role="status">{message}</p>}</>;
 if(!session.isCurrent())return null;
 return <><header className="app-header"><div className="brand"><img className="icon" src={scales} alt=""/>律所工作助手</div><div className="session"><button className="mode-button link-button" disabled={locked} onClick={()=>dirty?setPhase('leave'):onBack()}>{backLabel}</button><span inert={dirty||locked} aria-disabled={dirty||locked}>{sessionActions??session.displayName}</span></div></header><main className="workbench" aria-label="商机材料"><div className="today"><p className="today-copy"><CheckCircle className="icon"/><span>收好本次材料，接着办理原跟进事项。</span></p></div><article className="work-card" aria-label="商机材料卡"><div className="context"><p className="eyebrow">本次材料维护</p><h1>接收商机材料</h1><p className="subject">{context?detail.customerLabel:''}</p><p className="owner-line"><User className="icon"/>{context?.currentOwnerLabel??detail.ownerLabel}负责 · 原跟进安排不变</p><p className="known-title">已知信息</p><ul className="facts"><li><CheckCircle className="icon"/><span>客户资料：{context?.confirmation?'已有人工确认版本':'尚未确认'}</span></li><li><Clock className="icon"/><span>{detail.taskState==='WAITING'?'当前未到约定联系时间':detail.nextActionLabel??'暂无普通跟进事项'}</span></li></ul><p className="context-note">材料接收不代替报价、合同签署或到账确认。原文件及历史引用保留。</p><details className="history"><summary>来源与业务记录</summary><p>线索 → 有效首联 → 商机 → 客户与需求资料。</p></details></div><section className="card-action">{body}{context&&phase==='list'&&<AiCandidatePanel session={session} target={{opportunityId:detail.opportunity.id}} task="MATERIALS" api={aiApi} sourceVersion={JSON.stringify([context.opportunity,context.responsibilityBasis,context.confirmation,context.versions.map(v=>v.selector)])} draftVersion={JSON.stringify([purpose,note,previous?.selector])} disabled={locked||context.pendingUploads.some(unknownUpload)}/>}</section></article></main></>;
}
