import {useEffect,useRef,useState} from 'react';
import type {WorkbenchSession} from '../../lib/api';
import {TransportError} from '../../lib/sessionTransport';
import type {ClosureContext,ClosureReason,OpportunityClosureTransport} from '../../lib/opportunityClosureTransport';
import {formatIdentityInstant} from '../identity/identityLabels';
const reasons:Record<ClosureReason,string>={CLIENT_DECLINED:'客户明确拒绝',NEED_CANCELLED:'客户取消需求',OTHER:'其他明确结束原因'};
export function OpportunityClosure({session,opportunityId,opportunityRevision,taskState,api,blocked,onLock,onRefresh,onDenied}:{session:WorkbenchSession;opportunityId:string;opportunityRevision?:number;taskState:string;api:OpportunityClosureTransport;blocked:boolean;onLock:(locked:boolean)=>void;onRefresh:()=>void;onDenied:()=>void}){
 const [context,setContext]=useState<ClosureContext|null>(null),[phase,setPhase]=useState<'entry'|'edit'|'review'|'sending'|'unknown'|'stale'>('entry'),[reason,setReason]=useState<ClosureReason|''>(''),[summary,setSummary]=useState(''),[message,setMessage]=useState('');
 const current=useRef(session);current.current=session;const busy=useRef(false),alive=useRef(true),callbacks=useRef({onLock,onRefresh,onDenied});callbacks.current={onLock,onRefresh,onDenied};
 useEffect(()=>{alive.current=true;const c=new AbortController();api.context(session,opportunityId,c.signal).then(d=>{if(alive.current&&current.current===session&&session.isCurrent()){if(opportunityRevision!==undefined&&d.opportunity.revision!==opportunityRevision){setPhase('stale');return;}setContext(d);}}).catch(e=>{if(c.signal.aborted||current.current!==session)return;setContext(null);if(e instanceof TransportError&&[401,403,404].includes(e.status))callbacks.current.onDenied();else{setMessage('本次结束依据读取失败，请重新读取。');setPhase('stale');}});return()=>{alive.current=false;c.abort();callbacks.current.onLock(false);};},[session,api,opportunityId,opportunityRevision]);
 useEffect(()=>{callbacks.current.onLock(['edit','review','sending','unknown'].includes(phase));},[phase]);
 useEffect(()=>{const f=(e:BeforeUnloadEvent)=>{if(['edit','review','sending','unknown'].includes(phase)){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',f);return()=>window.removeEventListener('beforeunload',f);},[phase]);
 const valid=()=>alive.current&&current.current===session&&session.isCurrent();
 async function submit(receiptOnly=false){if(busy.current||!valid()||(!receiptOnly&&(blocked||phase!=='review'||context?.status!=='READY'||!context.expectedResponsibility||!reason)))return;busy.current=true;setPhase('sending');setMessage('');const controller=new AbortController();try{if(receiptOnly)await api.receipt(session,controller.signal);else await api.write(session,{key:crypto.randomUUID(),opportunityId,body:{expectedOpportunityRevision:context!.opportunity.revision,expectedResponsibility:context!.expectedResponsibility!,expectedTask:context!.expectedTask??null,expectedWait:context!.expectedWait??null,reasonCode:reason as ClosureReason,summary:summary.trim()}},controller.signal);if(valid()){setSummary('');setReason('');callbacks.current.onRefresh();}}
 catch(e){if(!valid())return;setContext(null);if(e instanceof TransportError&&([401,403].includes(e.status)||(e.status===404&&!receiptOnly))){setSummary('');setReason('');callbacks.current.onDenied();return;}if(e instanceof TransportError&&e.provenOutcome){setSummary('');setReason('');setPhase('stale');setMessage('当前事项已变化，原核对依据已失效，请重新读取后决定。');}else{setPhase('unknown');setMessage('结果尚未确认，请勿重复提交。请核对原操作结果。');}}finally{busy.current=false;}}
 if(!session.isCurrent())return null;
 if(phase==='sending'||phase==='unknown')return <div role="status"><h3>正在核对结束结果</h3><p>{message||'正在提交，请勿重复操作。'}</p>{reason&&<dl className="detail-facts"><div><dt>结束原因</dt><dd>{reasons[reason]}</dd></div><div><dt>说明</dt><dd>{summary}</dd></div></dl>}{phase==='unknown'&&<button className="primary" onClick={()=>void submit(true)}>核对本次结果</button>}</div>;
 if(phase==='stale')return <div role="status"><h3>当前事项已变化</h3><p>{message||'原核对依据已失效，请重新读取后决定。'}</p><button onClick={onRefresh}>重新读取</button></div>;
 if(!context)return null;
 if(context.status==='CLOSED')return <><dl className="detail-facts">{context.closure&&<><div><dt>结束原因</dt><dd>{reasons[context.closure.reasonCode]}</dd></div><div><dt>说明</dt><dd>{context.closure.summary??'当前权限无法查看结束说明'}</dd></div><div><dt>结束时间</dt><dd>{formatIdentityInstant(context.closure.closedAt)}</dd></div></>}<div><dt>处理结果</dt><dd>无普通跟进事项；历史记录保留</dd></div></dl></>;
 if(context.status==='READ_ONLY')return <p className="help">你可以查看此记录，没有结束商机的权限。</p>;
 if(context.status==='BLOCKED')return <p className="help">已有后续业务需要核对，当前不能从此处结束商机。请交由对应业务负责人处理。</p>;
 if(phase==='entry')return <details><summary>其他业务处理</summary><p className="help">仅在本次洽谈确已结束时使用。</p><button disabled={blocked} onClick={()=>setPhase('edit')}>结束本次商机</button></details>;
 if(phase==='review')return <><h3>核对本次结束</h3><dl className="detail-facts"><div><dt>结束原因</dt><dd>{reasons[reason as ClosureReason]}</dd></div><div><dt>说明</dt><dd>{summary}</dd></div><div><dt>影响</dt><dd>{taskState==='WAITING'?'取消等待中的普通跟进，不会提前办理':taskState==='NONE'?'当前无普通跟进事项；结束后不再生成普通跟进':'停止当前普通跟进，不记录虚假的完成进展'}</dd></div><div><dt>后续</dt><dd>不再自动生成普通跟进，已有历史保留</dd></div></dl><p className="help">结束商机不代表成交、合同签署或案件创建。</p><div className="compact-confirm"><button className="primary" disabled={blocked} onClick={()=>void submit()}>确认结束本次商机</button><button onClick={()=>setPhase('edit')}>返回修改</button></div></>;
 return <><h3>结束本次商机</h3><label className="field">结束原因 *<select aria-label="结束原因 *" value={reason} onChange={e=>setReason(e.target.value as ClosureReason|'')}><option value="">请选择原因</option>{Object.entries(reasons).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">情况说明 *<textarea rows={4} maxLength={1000} value={summary} onChange={e=>setSummary(e.target.value)}/></label><p className="help">暂时没有回复或等待材料，请继续原跟进安排。</p>{message&&<p role="alert">{message}</p>}<div className="compact-confirm"><button className="primary" disabled={blocked} onClick={()=>{if(!reason||!summary.trim()){setMessage('请填写结束原因和情况说明。');return;}setMessage('');setPhase('review');}}>核对结束影响</button><button onClick={()=>{setSummary('');setReason('');setMessage('');setPhase('entry');}}>继续原跟进安排</button></div></>;
}
