import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';
import {describe,it,expect,vi} from 'vitest';
import {OpportunityLedgerPage} from './OpportunityLedgerPage';
import {testSession} from '../../test/fixtures';
import type {LedgerDetail,OpportunityLedgerTransport} from '../../lib/opportunityLedgerTransport';
const row={opportunity:{id:'opp-a',revision:1},customerLabel:'海宁公司',ownerLabel:'林悦',taskState:'OPEN' as const,nextActionLabel:'记录本次进展'};
const detail:LedgerDetail={...row,canHandle:true,task:{id:'task-a',revision:2,etag:'"task-a"'}};
const session={...testSession(),canReadOpportunityLedger:true};
function fixture(){return {taskContext:vi.fn(),list:vi.fn().mockResolvedValue({items:[row]}),detail:vi.fn().mockResolvedValue(detail)} satisfies OpportunityLedgerTransport;}
describe('商机台账',()=>{
it('handles exactly the selected authorized task and keeps server search/filter authoritative',async()=>{const api=fixture(),handle=vi.fn();render(<OpportunityLedgerPage session={session} api={api} onHandle={handle}/>);fireEvent.click(await screen.findByRole('button',{name:'办理当前事项'}));expect(handle).toHaveBeenCalledWith(detail);api.list.mockResolvedValue({items:[]});fireEvent.change(screen.getByPlaceholderText('搜索客户'),{target:{value:'无匹配'}});await screen.findByText('没有匹配的记录');expect(screen.queryByText('海宁公司')).toBeNull();expect(api.list.mock.calls.at(-1)?.[1]).toMatchObject({search:'无匹配'});});
it('suppresses waiting handling and clears all old facts on detail read failure',async()=>{const api=fixture();api.detail.mockResolvedValue({...detail,taskState:'WAITING',canHandle:false,task:undefined});render(<OpportunityLedgerPage session={session} api={api} onHandle={vi.fn()}/>);await screen.findByText('尚未到约定时间。到时重新核对办理资格。');expect(screen.queryByRole('button',{name:'办理当前事项'})).toBeNull();api.detail.mockRejectedValue(Error('failed'));fireEvent.click(screen.getByText('重新查询'));await screen.findByText('本次读取失败，请重新查询。');expect(screen.queryByText('海宁公司')).toBeNull();});
it('clears immediately on revocation and ignores the prior identity late response',async()=>{const api=fixture();let resolve!:(d:LedgerDetail)=>void;api.detail.mockReturnValue(new Promise<LedgerDetail>(r=>resolve=r));const view=render(<OpportunityLedgerPage session={session} api={api} onHandle={vi.fn()}/>);await waitFor(()=>expect(api.detail).toHaveBeenCalled());view.rerender(<OpportunityLedgerPage session={{...testSession(2),canReadOpportunityLedger:false}} api={api} onHandle={vi.fn()}/>);await act(async()=>resolve(detail));expect(screen.queryByText('海宁公司')).toBeNull();expect(screen.queryByText('林悦')).toBeNull();});
it('shows an honest empty scan page with a next cursor and advances it',async()=>{const api=fixture();api.list.mockResolvedValue({items:[],nextCursor:'scan-next'});render(<OpportunityLedgerPage session={session} api={api} onHandle={vi.fn()}/>);await screen.findByText('本页暂无匹配记录');fireEvent.click(screen.getByText('下一页'));await waitFor(()=>expect(api.list.mock.calls.at(-1)?.[1]).toMatchObject({cursor:'scan-next'}));});
});

it('coalesces successive search keystrokes into one authorized server query',async()=>{const api=fixture();render(<OpportunityLedgerPage session={session} api={api} onHandle={vi.fn()}/>);await screen.findByRole('button',{name:'办理当前事项'});api.list.mockClear();const input=screen.getByPlaceholderText('搜索客户');fireEvent.change(input,{target:{value:'海'}});fireEvent.change(input,{target:{value:'海宁'}});fireEvent.change(input,{target:{value:'海宁公司'}});await waitFor(()=>expect(api.list).toHaveBeenCalled());expect(api.list).toHaveBeenCalledTimes(1);expect(api.list.mock.calls[0][1]).toMatchObject({search:'海宁公司'});});
