import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {QuoteCard} from './QuoteCard';
import {testSession,taskId,selectorId} from '../../test/fixtures';
import {RecoveryStore} from '../session/recoveryMarker';
import {TransportError} from '../../lib/sessionTransport';
const doc={currency:'CNY',scope:'服务范围',lines:[{description:'律师服务',amountMinor:10001,discount:false}],paymentTerms:'一次支付',validUntil:'2099-10-20T00:00:00Z',conditionalFee:null};
const quote={selector:{id:taskId,hash:'q'.repeat(43)},version:1,document:doc,totalMinor:10001,validUntil:doc.validUntil};
const context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{id:taskId,revision:0},customerConfirmation:{id:taskId,revision:0},draft:{selector:{id:taskId,revision:0},document:doc},quote:null,workflow:null,allowedActions:['SAVE_QUOTE_DRAFT','FORM_QUOTE'],history:[],recipients:[{selector:{id:selectorId,revision:0},name:'已确认委托方'}],materials:[{selector:{id:taskId,revision:0},fileName:'交付证明.png'}],approvers:[],customerName:'合成客户',readonly:false};
const detail={opportunity:context.opportunity,customerLabel:'合成客户',ownerLabel:'销售',taskState:'OPEN',canHandle:true,task:{id:taskId,revision:0},nextActionLabel:'跟进事项'};
function setup(overrides={}){const api={recovery:new RecoveryStore(sessionStorage),context:vi.fn().mockResolvedValue({...context,...overrides}),write:vi.fn().mockResolvedValue({resultFact:{factRef:'v'.repeat(43),revision:0}}),receipt:vi.fn(),download:vi.fn()},onBack=vi.fn(),onTasks=vi.fn(),onDenied=vi.fn(),onContract=vi.fn();render(<QuoteCard session={testSession()} detail={detail as never} api={api as never} onBack={onBack} onTasks={onTasks} onContract={onContract} onDenied={onDenied}/>);return {api,onBack,onTasks,onDenied,onContract};}
it('shows personal waiting below a quote and keeps its own draft guard',async()=>{
 const session=testSession(),row={id:taskId,customerLabel:'等待中的客户',purposeLabel:'再次联系',state:'WAIT_DUE' as const,reason:'约定已到',resumeAt:null};
 const waitingApi={list:vi.fn().mockResolvedValue({waitingItems:[row],totalCount:1,nextCursor:null,asOf:'2026-09-29T01:00:00Z'}),detail:vi.fn().mockResolvedValue({waitingDetail:{...row,state:'READY',ownerLabel:'本人',nextAction:'原卡办理',canHandle:true,history:[]},totalCount:0})},onSelect=vi.fn();
 const api={recovery:new RecoveryStore(sessionStorage),context:vi.fn().mockResolvedValue(context),write:vi.fn()};
 render(<QuoteCard session={session} detail={detail as never} api={api as never} onBack={vi.fn()} onDenied={vi.fn()} waiting={{session,api:waitingApi,count:1,next:[],onSelect}}/>);
 fireEvent.change(await screen.findByLabelText('拟服务范围'),{target:{value:'保留报价范围'}});fireEvent.click(screen.getByRole('button',{name:/查看等待事项/}));fireEvent.click(await screen.findByRole('button',{name:/等待中的客户/}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));
 expect(screen.getByText('保留当前填写内容？')).toBeVisible();expect(waitingApi.detail).toHaveBeenCalledTimes(1);fireEvent.click(screen.getByRole('button',{name:'继续填写'}));expect(screen.getByLabelText('拟服务范围')).toHaveValue('保留报价范围');
 fireEvent.click(screen.getByRole('button',{name:'前往办理'}));fireEvent.click(screen.getByRole('button',{name:'放弃本次输入并返回'}));await waitFor(()=>expect(onSelect).toHaveBeenCalledWith(taskId));expect(waitingApi.detail).toHaveBeenCalledTimes(2);expect(api.write).not.toHaveBeenCalled();
});
it('ends quoted negotiation through the approved reason card and retains readonly history',async()=>{
 const state={...context,quote,history:[quote],workflow:{selector:context.opportunity,stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['END_QUOTE_NEGOTIATION']};const {api}=setup(state);
 fireEvent.click(await screen.findByRole('button',{name:'结束本次报价办理'}));expect(api.write).not.toHaveBeenCalled();await screen.findByText('确认结束本次销售办理');expect(document.querySelectorAll('.primary')).toHaveLength(1);
 fireEvent.click(screen.getByRole('button',{name:'确认结束本次办理'}));expect(api.write).not.toHaveBeenCalled();
 fireEvent.change(screen.getByLabelText('处理原因'),{target:{value:'客户决定不再继续本次委托'}});fireEvent.click(screen.getByLabelText('已核对当前业务和准确版本'));expect(screen.queryByRole('combobox')).toBeNull();
 api.context.mockResolvedValue({...state,readonly:true,allowedActions:[],notice:'本次销售办理已结束；历史保留。'});
 const button=screen.getByRole('button',{name:'确认结束本次办理'});fireEvent.click(button);fireEvent.click(button);
 await screen.findByText('本次报价只可查看');expect(api.write).toHaveBeenCalledOnce();expect(api.write.mock.calls[0][1]).toMatchObject({command:'END_QUOTE_NEGOTIATION',body:{expectedWorkflow:context.opportunity,values:{reasonCode:'OTHER',summary:'客户决定不再继续本次委托'}}});expect(screen.getByRole('button',{name:'下载第 1 版'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'结束本次报价办理'})).toBeNull();
});
it('unknown quote termination checks original receipt without another write',async()=>{
 const state={...context,quote,workflow:{selector:context.opportunity,stage:'AWAIT_REPLY',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['END_QUOTE_NEGOTIATION']};const {api}=setup(state);api.write.mockRejectedValue(Error('lost response'));api.receipt.mockResolvedValue({outcome:'SUCCEEDED'});
 fireEvent.click(await screen.findByRole('button',{name:'结束本次报价办理'}));fireEvent.change(screen.getByLabelText('处理原因'),{target:{value:'本次办理停止的准确依据'}});fireEvent.click(screen.getByLabelText('已核对当前业务和准确版本'));fireEvent.click(screen.getByRole('button',{name:'确认结束本次办理'}));
 api.context.mockResolvedValue({...state,readonly:true,allowedActions:[]});fireEvent.click(await screen.findByRole('button',{name:'核对本次结果'}));await screen.findByText('本次报价只可查看');expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();
});
it('starts preparation only on explicit intent and preserves a saved draft',async()=>{
 const {api}=setup({allowedActions:['START_QUOTE_PREPARATION','SAVE_QUOTE_DRAFT','FORM_QUOTE']});
 const start=await screen.findByRole('button',{name:'开始报价准备'});
 expect(api.write).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'形成这份报价版本'})).toBeNull();
 expect(document.querySelectorAll('.primary')).toHaveLength(1);
 api.context.mockResolvedValue({...context,workflow:{selector:context.opportunity,stage:'PREPARE',task:context.opportunity,ownerAppointmentId:taskId},allowedActions:['SAVE_QUOTE_DRAFT','FORM_QUOTE']});
 fireEvent.click(start);fireEvent.click(start);
 await screen.findByRole('button',{name:'形成这份报价版本'});
 expect(api.write).toHaveBeenCalledOnce();expect(api.write.mock.calls[0][1]).toMatchObject({command:'START_QUOTE_PREPARATION',body:{values:{},expectedDraft:context.draft.selector,expectedWorkflow:null}});
 expect(screen.getByLabelText('拟服务范围')).toHaveValue(doc.scope);
});
it('leaving preparation preview does not write a business fact',async()=>{
 const {api,onBack}=setup({allowedActions:['START_QUOTE_PREPARATION']});
 await screen.findByRole('button',{name:'开始报价准备'});
 fireEvent.click(screen.getByRole('button',{name:'返回商机台账'}));expect(onBack).toHaveBeenCalledOnce();expect(api.write).not.toHaveBeenCalled();
});
it('unknown preparation outcome recovers the original command only',async()=>{
 const {api}=setup({allowedActions:['START_QUOTE_PREPARATION']});api.write.mockRejectedValue(Error('lost'));api.receipt.mockResolvedValue({outcome:'SUCCEEDED'});
 fireEvent.click(await screen.findByRole('button',{name:'开始报价准备'}));
 api.context.mockResolvedValue({...context,workflow:{selector:context.opportunity,stage:'PREPARE',task:context.opportunity,ownerAppointmentId:taskId}});
 fireEvent.click(await screen.findByRole('button',{name:'核对本次结果'}));await screen.findByRole('button',{name:'形成这份报价版本'});
 expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();
});
it('forms once and displays refreshed next responsibility in one card',async()=>{const {api}=setup();await screen.findByRole('button',{name:'形成这份报价版本'});api.context.mockResolvedValue({...context,quote,workflow:{selector:quote.selector,stage:'SUBMIT_APPROVAL',ownerAppointmentId:taskId,task:quote.selector},allowedActions:['REQUEST_QUOTE_APPROVAL']});const button=screen.getByRole('button',{name:'形成这份报价版本'});fireEvent.click(button);const confirm=screen.getByRole('button',{name:'确认形成报价版本'});fireEvent.click(confirm);fireEvent.click(confirm);await screen.findByText('本次结果已记录，请查看下一步安排。');expect(api.write).toHaveBeenCalledTimes(1);expect(api.write.mock.calls[0][1]).toMatchObject({command:'FORM_QUOTE',body:{values:doc,expectedDraft:context.draft.selector}});expect(screen.getByRole('button',{name:'提交这份报价审批'})).toBeInTheDocument();expect(document.querySelectorAll('.work-card')).toHaveLength(1);expect(document.querySelectorAll('.primary')).toHaveLength(1);});
it('unknown result only polls original receipt',async()=>{const {api}=setup();api.write.mockRejectedValue(Error('lost'));api.receipt.mockResolvedValue({resultFact:{factRef:'v'.repeat(43),revision:0}});fireEvent.click(await screen.findByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));fireEvent.click(await screen.findByRole('button',{name:'核对本次结果'}));await screen.findByText('本次结果已记录，请查看下一步安排。');expect(api.write).toHaveBeenCalledOnce();expect(api.receipt).toHaveBeenCalledOnce();});
it('stale basis clears input and requires refresh',async()=>{const {api}=setup();api.write.mockRejectedValue(new TransportError(412,'STALE_SUBJECT',true));fireEvent.click(await screen.findByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));await screen.findByRole('button',{name:'重新读取并核对'});expect(screen.queryByRole('button',{name:'形成这份报价版本'})).toBeNull();expect(screen.queryByDisplayValue('服务范围')).toBeNull();});
it('permission loss erases private content',async()=>{const {api,onDenied}=setup();api.write.mockRejectedValue(new TransportError(403));fireEvent.click(await screen.findByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));await waitFor(()=>expect(onDenied).toHaveBeenCalledOnce());expect(screen.queryByText('合成客户')).toBeNull();expect(screen.queryByDisplayValue('服务范围')).toBeNull();});
it('guards unsaved input without silently writing',async()=>{const {api,onBack}=setup();fireEvent.change(await screen.findByLabelText('拟服务范围'),{target:{value:'修改范围'}});fireEvent.click(screen.getByRole('button',{name:'返回商机台账'}));await screen.findByText('保留当前填写内容？');expect(onBack).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'放弃本次输入并返回'}));expect(onBack).toHaveBeenCalledOnce();expect(api.write).not.toHaveBeenCalled();});
it('manual delivery requires exact evidence without extra confirmation',async()=>{const {api}=setup({quote,draft:null,workflow:{selector:quote.selector,stage:'DELIVER',ownerAppointmentId:taskId,task:quote.selector},allowedActions:['RECORD_QUOTE_DELIVERY']});fireEvent.change(await screen.findByLabelText('实际接收人'),{target:{value:'客户联系人'}});fireEvent.change(screen.getByLabelText('实际交付时间'),{target:{value:'2026-09-20T10:00'}});fireEvent.click(screen.getByRole('button',{name:'记录本次报价交付'}));expect(api.write).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('本次交付证明'),{target:{value:taskId}});fireEvent.click(screen.getByRole('button',{name:'记录本次报价交付'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values.evidence).toEqual(context.materials[0].selector);});
it.each(['ACCEPTED','NOT_ACCEPTED','REJECTED','AMBIGUOUS'])('records explicit %s reply with evidence',async kind=>{const {api}=setup({quote,draft:null,workflow:{selector:quote.selector,stage:'AWAIT_REPLY',ownerAppointmentId:taskId,task:quote.selector},allowedActions:['RECORD_QUOTE_RESPONSE']});expect((await screen.findByLabelText('客户回复') as HTMLSelectElement).value).toBe('');fireEvent.change(screen.getByLabelText('客户回复'),{target:{value:kind}});fireEvent.change(screen.getByLabelText('客户原意与核对说明'),{target:{value:'客户实际回复'}});fireEvent.change(screen.getByLabelText('实际回复时间'),{target:{value:'2026-09-20T11:00'}});fireEvent.change(screen.getByLabelText('本次客户回复证据'),{target:{value:taskId}});if(kind!=='ACCEPTED')fireEvent.change(screen.getByLabelText('下次跟进时间'),{target:{value:'2099-09-23T10:00'}});fireEvent.click(screen.getByRole('button',{name:'记录客户报价回复'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values.kind).toBe(kind);});
it('readonly preserves downloadable history without mutations',async()=>{setup({quote,history:[quote],readonly:true,allowedActions:[]});await screen.findByRole('heading',{level:2,name:'本次报价只可查看'});expect(screen.queryByRole('button',{name:'形成这份报价版本'})).toBeNull();expect(screen.getByRole('button',{name:'下载第 1 版'})).toBeInTheDocument();});

it('ended quotation replaces the active stage title and keeps the terminal notice in the mobile action area',async()=>{
 const notice='本次销售办理已结束；报价、审批、交付及客户回复历史仍可查阅。';
 setup({quote,readonly:true,notice,allowedActions:[],workflow:{selector:quote.selector,stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:quote.selector}});
 expect(await screen.findByRole('heading',{level:1,name:'查看报价历史'})).toBeVisible();
 expect(document.querySelector('.card-action')).toHaveTextContent(notice);
 expect(screen.queryByRole('heading',{name:'查看报价审批进展'})).toBeNull();
});

it('approval requires explicit decision and explanation, then advances only after confirmed receipt',async()=>{const {api}=setup({quote,draft:null,workflow:{selector:context.opportunity,stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['RECORD_QUOTE_DECISION']});fireEvent.click(await screen.findByRole('button',{name:'确认本次报价决定'}));expect(api.write).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('本次决定'),{target:{value:'RETURNED'}});fireEvent.change(screen.getByLabelText('决定说明'),{target:{value:'明确付款条件'}});fireEvent.click(screen.getByRole('button',{name:'确认本次报价决定'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values).toEqual({decision:'RETURNED',reason:'明确付款条件'});});
it('expired version cannot be delivered or accepted and revision keeps exact predecessor',async()=>{const expired={...quote,document:{...doc,validUntil:'2020-01-01T00:00:00Z'},validUntil:'2020-01-01T00:00:00Z'};const {api}=setup({quote:expired,draft:null,workflow:{selector:context.opportunity,stage:'DELIVER',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['FORM_QUOTE','SAVE_QUOTE_DRAFT','RECORD_QUOTE_DELIVERY']});await screen.findByText('本次报价已过有效期');expect(screen.queryByRole('button',{name:'记录本次报价交付'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'准备新版本'}));fireEvent.change(screen.getByLabelText('有效期至'),{target:{value:'2099-10-21'}});fireEvent.click(screen.getByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.expectedQuote).toEqual(quote.selector);});
it('confirmed result followed by failed refresh never offers receipt replay or a new write',async()=>{const {api}=setup();await screen.findByRole('button',{name:'形成这份报价版本'});api.context.mockRejectedValue(Error('offline'));fireEvent.click(screen.getByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));await screen.findByText('结果已记录，请重新读取下一责任；不要重复提交。');expect(screen.queryByRole('button',{name:'核对本次结果'})).toBeNull();expect(screen.queryByRole('button',{name:'形成这份报价版本'})).toBeNull();expect(api.write).toHaveBeenCalledOnce();});


it('requires explicit recipient participation for a multi-client quote',async()=>{const recipients=[{selector:{id:selectorId,revision:0},name:'第一委托方'},{selector:{id:taskId,revision:0},name:'第二委托方'}];const {api}=setup({quote,draft:null,recipients,workflow:{selector:context.opportunity,stage:'DELIVER',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['RECORD_QUOTE_DELIVERY']});fireEvent.change(await screen.findByLabelText('实际接收人'),{target:{value:'接收联系人'}});fireEvent.change(screen.getByLabelText('实际交付时间'),{target:{value:'2026-09-20T10:00'}});fireEvent.change(screen.getByLabelText('本次交付证明'),{target:{value:taskId}});fireEvent.click(screen.getByRole('button',{name:'记录本次报价交付'}));expect(api.write).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('本次接收委托方'),{target:{value:taskId}});fireEvent.click(screen.getByRole('button',{name:'记录本次报价交付'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values.recipientParticipation).toEqual(recipients[1].selector);});
it('reviews the complete proposed package before forming with one final confirmation',async()=>{const {api}=setup();fireEvent.click(await screen.findByRole('button',{name:'形成这份报价版本'}));expect(api.write).not.toHaveBeenCalled();expect(screen.getByRole('heading',{name:'核对本次报价版本'})).toBeInTheDocument();expect(screen.getByText('¥100.01')).toBeInTheDocument();expect(screen.getByText('一次支付')).toBeInTheDocument();expect(document.querySelectorAll('.primary')).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'返回修改'}));expect(screen.getByLabelText('拟服务范围')).toHaveValue('服务范围');fireEvent.click(screen.getByRole('button',{name:'形成这份报价版本'}));fireEvent.click(screen.getByRole('button',{name:'确认形成报价版本'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());});
it('uses protocol channel codes with Chinese labels',async()=>{const {api}=setup({quote,draft:null,workflow:{selector:context.opportunity,stage:'DELIVER',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['RECORD_QUOTE_DELIVERY']});fireEvent.change(await screen.findByLabelText('实际接收人'),{target:{value:'联系人'}});fireEvent.change(screen.getByLabelText('实际交付时间'),{target:{value:'2026-09-20T10:00'}});fireEvent.change(screen.getByLabelText('本次交付证明'),{target:{value:taskId}});fireEvent.change(screen.getByLabelText('交付方式'),{target:{value:'MANUAL_ELECTRONIC'}});fireEvent.click(screen.getByRole('button',{name:'记录本次报价交付'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values.channel).toBe('MANUAL_ELECTRONIC');});
it('allows evidence-backed historical acceptance after expiry but rejects an acceptance occurring after validity',async()=>{const end='2026-01-20T00:00:00Z',q={...quote,validUntil:end,document:{...doc,validUntil:end}},{api}=setup({quote:q,draft:null,workflow:{selector:context.opportunity,stage:'AWAIT_REPLY',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['RECORD_QUOTE_RESPONSE','FORM_QUOTE']});fireEvent.change(await screen.findByLabelText('客户回复'),{target:{value:'ACCEPTED'}});fireEvent.change(screen.getByLabelText('客户原意与核对说明'),{target:{value:'客户有效期内接受'}});fireEvent.change(screen.getByLabelText('本次客户回复证据'),{target:{value:taskId}});fireEvent.change(screen.getByLabelText('实际回复时间'),{target:{value:'2026-02-01T10:00'}});fireEvent.click(screen.getByRole('button',{name:'记录客户报价回复'}));expect(api.write).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText('实际回复时间'),{target:{value:'2026-01-19T10:00'}});fireEvent.click(screen.getByRole('button',{name:'记录客户报价回复'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].body.values.kind).toBe('ACCEPTED');});

it('displays historic business records with original version, actor, time, reason and exact evidence',async()=>{setup({quote,readonly:true,allowedActions:[],history:[quote],records:[{kind:'APPROVAL',quote:quote.selector,version:1,selector:context.opportunity,actorAppointmentId:taskId,occurredAt:'2026-09-20T10:00:00Z',recordedAt:'2026-09-20T10:00:00Z',decision:'RETURNED',reason:'原版付款约定需修订'},{kind:'DELIVERY',quote:quote.selector,version:1,selector:context.opportunity,actorAppointmentId:taskId,occurredAt:'2026-09-20T11:00:00Z',recordedAt:'2026-09-20T11:00:00Z',recipient:'原接收联系人',channel:'IN_PERSON',evidence:{id:selectorId,revision:0}},{kind:'RESPONSE',quote:quote.selector,version:1,selector:quote.selector,actorAppointmentId:taskId,occurredAt:'2026-09-20T12:00:00Z',recordedAt:'2026-09-20T12:00:00Z',responseKind:'REJECTED',statement:'客户原始拒绝说明',evidence:{id:selectorId,revision:0}}]});await screen.findByText('原版付款约定需修订');expect(screen.getByText('原接收联系人')).toBeInTheDocument();expect(screen.getByText('客户原始拒绝说明')).toBeInTheDocument();expect(screen.getAllByText('关联当时材料版本')).toHaveLength(2);expect(screen.getAllByText('经授权人员记录')).toHaveLength(3);expect(screen.queryByText(taskId)).toBeNull();expect(screen.queryByText(selectorId+' · 修订 0')).toBeNull();expect(screen.getAllByText('第 1 版')).toHaveLength(5);});


it('continues a repaired supervisor exception through the existing approval card',async()=>{const {api}=setup({quote,draft:null,workflow:{selector:context.opportunity,stage:'OWNER_EXCEPTION',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['REQUEST_QUOTE_APPROVAL']});fireEvent.click(await screen.findByRole('button',{name:'提交这份报价审批'}));await waitFor(()=>expect(api.write).toHaveBeenCalledOnce());expect(api.write.mock.calls[0][1].command).toBe('REQUEST_QUOTE_APPROVAL');expect(document.querySelectorAll('.work-card')).toHaveLength(1);});

it.each([[['RECORD_QUOTE_DECISION'],'审批收费方案'],[[],'查看报价审批进展']] as const)('labels approval responsibility by authorized action %s',async(actions,label)=>{setup({quote,draft:null,workflow:{selector:context.opportunity,stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:[...actions]});expect(await screen.findByRole('heading',{level:1,name:label})).toBeVisible();});

it('accepted quotation continues to contract handling without creating another quote',async()=>{
 const {api,onContract}=setup({quote,draft:null,readonly:true,notice:'ACCEPTED',workflow:{selector:quote.selector,stage:'ACCEPTED',ownerAppointmentId:taskId,task:quote.selector},allowedActions:[]});
 fireEvent.click(await screen.findByRole('button',{name:'查看合同准备与办理'}));
 expect(onContract).toHaveBeenCalledOnce();expect(api.write).not.toHaveBeenCalled();expect(screen.queryByText(/合同准备功能尚未开放/)).toBeNull();
 expect(screen.queryByRole('button',{name:'形成这份报价版本'})).toBeNull();
});

it('handoff can record an attempt while the quote still requires a new approved version',async()=>{
 const attempt={opportunity:context.opportunity,responsibilityBasis:{type:'opportunity.responsibility_handoff',id:taskId,revision:0},task:{id:taskId,revision:0},taskState:'WAITING',waitReceipt:{id:selectorId,hash:'a'.repeat(43)},expectedWorkflow:{id:selectorId,revision:0},nextCheckAt:'2099-10-01T00:00:00Z',command:'RECORD_QUOTE_FOLLOWUP_ATTEMPT',history:[]};
 vi.stubGlobal('fetch',vi.fn().mockImplementation(async()=>new Response(JSON.stringify(attempt),{status:200})));
 try{const {api}=setup({quote,workflow:{selector:context.opportunity,stage:'RETURNED',ownerAppointmentId:taskId,task:context.opportunity},allowedActions:['SAVE_QUOTE_DRAFT','FORM_QUOTE']});
  fireEvent.click(await screen.findByRole('button',{name:'客户尚未回复，安排下次联系'}));await screen.findByRole('heading',{name:'客户尚未回复本版报价'});expect(api.write).not.toHaveBeenCalled();expect(document.querySelectorAll('.primary')).toHaveLength(1);
 }finally{vi.unstubAllGlobals();}
});
