import {RecoveryStore} from '../session/recoveryMarker';
import {render,screen,fireEvent} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {QuoteTaskCard} from './QuoteTaskCard';
import {testSession,taskId,selectorId} from '../../test/fixtures';
it('opens exact task context without requiring ledger access and returns to my tasks',async()=>{const context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{id:taskId,revision:0},customerConfirmation:{id:taskId,revision:0},draft:null,quote:null,workflow:{selector:{id:taskId,revision:0},stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:{id:taskId,revision:0}},allowedActions:[],history:[],materials:[],approvers:[],customerName:'合成客户',readonly:false},api={taskContext:vi.fn().mockResolvedValue({opportunityId:selectorId,context}),context:vi.fn().mockResolvedValue(context)},back=vi.fn();render(<QuoteTaskCard session={testSession()} taskId={taskId} api={api as never} onTasks={back}/>);await screen.findByText('报价等待审批');expect(api.context).not.toHaveBeenCalled();expect(api.taskContext.mock.calls[0][1]).toBe(taskId);fireEvent.click(screen.getByRole('button',{name:'返回我的待办'}));expect(back).toHaveBeenCalledOnce();});
import {App} from '../../App';
import {opportunityEnvelope} from '../../test/opportunityFixtures';
it('routes recommended quote task into actual quote card and retains MyTasks return',async()=>{const base=opportunityEnvelope(),c={...base.currentCard,taskType:'APPROVE_QUOTE',businessPurpose:{code:'APPROVE_QUOTE',label:'审批报价'},primaryCommand:{code:'RECORD_QUOTE_DECISION',label:'记录报价决定',enabled:true},expectedCompletionFact:'QUOTE_APPROVAL_DECISION',commandForm:{actionCode:'RECORD_QUOTE_DECISION',schemaVersion:1,values:{},fields:[]}},context={opportunity:{id:selectorId,revision:0},responsibilityBasis:{id:taskId,revision:0},customerConfirmation:{id:taskId,revision:0},draft:null,quote:null,workflow:{selector:{id:taskId,revision:0},stage:'AWAIT_APPROVAL',ownerAppointmentId:taskId,task:{id:taskId,revision:0}},allowedActions:[],history:[],materials:[],approvers:[],customerName:'审批客户',readonly:false},quotes={taskContext:vi.fn().mockResolvedValue({opportunityId:selectorId,context}),context:vi.fn().mockResolvedValue(context)},api={recovery:new RecoveryStore(sessionStorage),current:vi.fn().mockResolvedValue({status:200,data:{...base,currentCard:c,myTasks:[]},etag:'"wb.aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"'}),listDueTasks:vi.fn().mockResolvedValue({candidates:[]})};render(<App session={testSession()} api={api as never} quotesApi={quotes as never}/>);await screen.findByText('报价等待审批');expect(quotes.context).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'返回我的待办'}));await screen.findByRole('button',{name:'继续办理报价事项'});expect(quotes.taskContext).toHaveBeenCalledOnce();});


