package io.github.windyzhu3.ontologylaw.opportunity.internal.persistence;

import io.github.windyzhu3.ontologylaw.opportunity.*;
import io.github.windyzhu3.ontologylaw.identity.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import io.github.windyzhu3.ontologylaw.opportunity.QuoteWorkflowService.*;

import java.sql.*;import java.time.*;import java.util.*;import java.security.MessageDigest;

/** All mutations serialize on the original Opportunity; projections never replace original quote facts. */
public final class JdbcQuoteWorkflowService implements QuoteWorkflowService {
 private final OpportunityProgressProtection protection;private final QuoteDraftService.Codec codec;
 private final Ports tasks;private final OpportunityMaterials materials=OpportunityMaterials.databaseBacked();
 private final OpportunityOwnerExceptionAuthorityReader authority=OpportunityOwnerExceptionAuthorityReader.databaseBacked();
 private static final ZoneId ZONE=ZoneId.of("Asia/Shanghai");
 public JdbcQuoteWorkflowService(OpportunityProgressProtection p,QuoteDraftService.Codec codec,Ports ports){this.protection=Objects.requireNonNull(p);this.codec=Objects.requireNonNull(codec);this.tasks=Objects.requireNonNull(ports);}
 public static ReadScope lockedLedgerFacts(Connection c,UUID tenant)throws SQLException{return OpportunityReadRows.lockedLedgerFacts(c,tenant);}
 public static void prepareLedgerCandidates(Connection c,UUID tenant,List<UUID> ids,int batch)throws SQLException{OpportunityReadRows.prepareLedgerCandidates(c,tenant,ids,batch);}
 private void requireCommandScope()throws SQLException{OpportunityReadRows.requireCommandScope();}
 static List<Map<String,Object>> rows(Connection c,String query,Object...args)throws SQLException{return OpportunityReadRows.rows(c,query,args);}
 static Map<String,Object> row(Connection c,String query,Object...args)throws SQLException{return OpportunityReadRows.row(c,query,args);}
 private static int sql(Connection c,String sql,Object... args)throws SQLException{OpportunityReadRows.requireCommandScope();try(var p=c.prepareStatement(sql)){bind(p,args);return p.executeUpdate();}}
 private static void bind(PreparedStatement p,Object... args)throws SQLException{for(int i=0;i<args.length;i++)p.setObject(i+1,args[i] instanceof Instant at?at.atOffset(ZoneOffset.UTC):args[i]);}
 private static UUID id(Connection c)throws SQLException{return (UUID)row(c,"select uuidv7() id").get("id");}
 private static UUID uuid(Object o){return o==null?null:o instanceof UUID u?u:UUID.fromString((String)o);}
 private static long integer(Object o){if(!(o instanceof Byte||o instanceof Short||o instanceof Integer||o instanceof Long||o instanceof java.math.BigInteger))throw new IllegalArgumentException("Exact integer required");long n=new java.math.BigInteger(o.toString()).longValueExact();if(n< -9007199254740991L||n>9007199254740991L)throw new IllegalArgumentException("Unsafe integer");return n;}
 private static Instant instant(Object o){return o instanceof Timestamp t?t.toInstant():o instanceof OffsetDateTime t?t.toInstant():o==null?null:Instant.parse(o.toString());}
 private static Map<String,Object> selector(UUID id){return id==null?null:Map.of("id",id.toString(),"revision",0L);}
 private static Map<String,Object> selector(Subject s){return s==null?null:s.hash()!=null?Map.of("id",s.id().toString(),"hash",s.hash()):Map.of("id",s.id().toString(),"revision",s.revision());}
 private static Map<String,Object> quoteSelector(Map<String,Object> q){return Map.of("id",q.get("quote_revision_id").toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString((byte[])q.get("content_digest")));}
 private static Subject exact(String type,UUID id){return new Subject(type,id,0L,null);}
 private static void expected(Object input,UUID id,long revision){if(input==null){if(id!=null)throw stale();return;}if(!(input instanceof Map<?,?> m)||!Objects.equals(uuid(m.get("id")),id)||integer(m.get("revision"))!=revision)throw stale();}
 private static Blocked stale(){return new Blocked("STALE_SUBJECT");}
 @SuppressWarnings("unchecked") private static Map<String,Object> values(Map<String,Object> p){if(!(p.get("values") instanceof Map<?,?>))throw new IllegalArgumentException("Values required");return (Map<String,Object>)p.get("values");}
 private QuoteDraftService drafts(){return QuoteDraftService.databaseBacked(protection,codec);}
 private Map<String,Object> root(Connection c,UUID tenant,UUID id,boolean lock)throws SQLException{var r=row(c,"select * from opportunity.opportunity where tenant_id=? and opportunity_id=?"+(lock?" for update":""),tenant,id);if(r==null)throw new Blocked("NOT_FOUND");return r;}
 private Map<String,Object> workflow(Connection c,UUID tenant,UUID opportunity)throws SQLException{return row(c,"select w.* from opportunity.quote_workflow w where w.tenant_id=? and w.opportunity_id=? and not exists(select 1 from opportunity.quote_workflow n where n.tenant_id=w.tenant_id and n.previous_workflow_id=w.quote_workflow_id)",tenant,opportunity);}
 private Subject confirmation(Connection c,UUID tenant,UUID opportunity)throws SQLException{var r=row(c,"select c.customer_requirement_confirmation_id id from opportunity.customer_requirement_confirmation c where c.tenant_id=? and c.opportunity_id=? and not exists(select 1 from opportunity.customer_requirement_confirmation n where n.tenant_id=c.tenant_id and n.previous_confirmation_id=c.customer_requirement_confirmation_id)",tenant,opportunity);return r==null?null:exact(OpportunityCustomerRequirementsService.CONFIRMATION,(UUID)r.get("id"));}
 private Subject opportunity(Map<String,Object> r){return new Subject("opportunity.opportunity",(UUID)r.get("opportunity_id"),((Number)r.get("revision")).longValue(),null);}
 private OpportunityResponsibilityReader.Responsibility responsibility(Connection c,UUID tenant,Map<String,Object> r)throws SQLException{return OpportunityResponsibilityReader.databaseBacked().current(c,tenant,opportunity(r));}
 public List<Subject> protectedFacts(Connection c,UUID tenant,UUID opportunity)throws SQLException{
  var r=root(c,tenant,opportunity,false);var out=new LinkedHashSet<Subject>();out.add(opportunity(r));out.add(responsibility(c,tenant,r).basis());var conf=confirmation(c,tenant,opportunity);if(conf!=null){out.add(conf);for(var p:rows(c,"select party_id,party_revision from opportunity.customer_requirement_participant where tenant_id=? and confirmation_id=?",tenant,conf.id()))out.add(new Subject("party.party",(UUID)p.get("party_id"),((Number)p.get("party_revision")).longValue(),null));}
  for(var q:rows(c,"select quote_revision_id,content_digest from opportunity.quote_revision where tenant_id=? and opportunity_id=?",tenant,opportunity))out.add(new Subject("opportunity.quote_revision",(UUID)q.get("quote_revision_id"),null,Base64.getUrlEncoder().withoutPadding().encodeToString((byte[])q.get("content_digest"))));
  for(var b:rows(c,"select b.quote_package_basis_id from opportunity.quote_package_basis b join opportunity.quote_revision q on q.tenant_id=b.tenant_id and q.quote_revision_id=b.quote_revision_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity))out.add(exact("opportunity.quote_package_basis",uuid(b.get("quote_package_basis_id"))));
  for(var d:rows(c,"select quote_draft_id,opportunity_revision,responsibility_type,responsibility_id,responsibility_revision from opportunity.quote_draft where tenant_id=? and opportunity_id=?",tenant,opportunity)){out.add(exact("opportunity.quote_draft",uuid(d.get("quote_draft_id"))));out.add(new Subject("opportunity.opportunity",opportunity,((Number)d.get("opportunity_revision")).longValue(),null));out.add(new Subject((String)d.get("responsibility_type"),uuid(d.get("responsibility_id")),((Number)d.get("responsibility_revision")).longValue(),null));}
  for(var f:rows(c,"select quote_workflow_id from opportunity.quote_workflow where tenant_id=? and opportunity_id=?",tenant,opportunity))out.add(exact("opportunity.quote_workflow",uuid(f.get("quote_workflow_id"))));
  for(var a:rows(c,"select a.quote_approval_request_id,a.policy_id from opportunity.quote_approval_request a join opportunity.quote_revision q on q.tenant_id=a.tenant_id and q.quote_revision_id=a.quote_revision_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity)){out.add(exact("opportunity.quote_approval_request",uuid(a.get("quote_approval_request_id"))));out.add(exact("opportunity.quote_approval_policy",uuid(a.get("policy_id"))));}
  for(var d:rows(c,"select d.quote_approval_decision_id,m.quote_approval_member_id from opportunity.quote_approval_decision d join opportunity.quote_approval_member m on m.tenant_id=d.tenant_id and m.quote_approval_member_id=d.member_id join opportunity.quote_approval_request a on a.tenant_id=m.tenant_id and a.quote_approval_request_id=m.request_id join opportunity.quote_revision q on q.tenant_id=a.tenant_id and q.quote_revision_id=a.quote_revision_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity)){out.add(exact("opportunity.quote_approval_decision",uuid(d.get("quote_approval_decision_id"))));out.add(exact("opportunity.quote_approval_member",uuid(d.get("quote_approval_member_id"))));}
  for(var m:rows(c,"select m.quote_approval_member_id,a.appointment_id,a.revision appointment_revision,p.principal_id,p.revision principal_revision,o.organization_unit_id,o.revision organization_revision from opportunity.quote_approval_member m join opportunity.quote_approval_request r on r.tenant_id=m.tenant_id and r.quote_approval_request_id=m.request_id join opportunity.quote_revision q on q.tenant_id=r.tenant_id and q.quote_revision_id=r.quote_revision_id join identity.appointment a on a.tenant_id=m.tenant_id and a.appointment_id=m.appointment_id join identity.principal p on p.tenant_id=a.tenant_id and p.principal_id=a.principal_id join identity.organization_unit o on o.tenant_id=a.tenant_id and o.organization_unit_id=a.organization_unit_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity)){out.add(exact("opportunity.quote_approval_member",uuid(m.get("quote_approval_member_id"))));out.add(new Subject("identity.appointment",uuid(m.get("appointment_id")),((Number)m.get("appointment_revision")).longValue(),null));out.add(new Subject("identity.principal",uuid(m.get("principal_id")),((Number)m.get("principal_revision")).longValue(),null));out.add(new Subject("identity.organization_unit",uuid(m.get("organization_unit_id")),((Number)m.get("organization_revision")).longValue(),null));}
  for(var i:rows(c,"select i.quote_issue_id,i.revision,i.delivery_fact_id from opportunity.quote_issue i join opportunity.quote_revision q on q.tenant_id=i.tenant_id and q.quote_revision_id=i.quote_revision_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity)){out.add(new Subject("opportunity.quote_issue",uuid(i.get("quote_issue_id")),((Number)i.get("revision")).longValue(),null));out.add(exact("opportunity.quote_manual_delivery",uuid(i.get("delivery_fact_id"))));}
  for(var x:rows(c,"select x.quote_response_id,x.response_content_digest from opportunity.quote_response x join opportunity.quote_issue i on i.tenant_id=x.tenant_id and i.quote_issue_id=x.quote_issue_id join opportunity.quote_revision q on q.tenant_id=i.tenant_id and q.quote_revision_id=i.quote_revision_id where q.tenant_id=? and q.opportunity_id=?",tenant,opportunity)){if(x.get("response_content_digest")!=null)out.add(new Subject("opportunity.quote_response",uuid(x.get("quote_response_id")),null,Base64.getUrlEncoder().withoutPadding().encodeToString((byte[])x.get("response_content_digest"))));out.add(exact("opportunity.quote_response_basis",uuid(x.get("quote_response_id"))));}
  for(var f:rows(c,"select contract_preparation_source_id from opportunity.contract_preparation_source where tenant_id=? and opportunity_id=?",tenant,opportunity))out.add(exact("opportunity.contract_preparation_source",uuid(f.get("contract_preparation_source_id"))));
  for(var h:rows(c,"select customer_requirement_confirmation_id from opportunity.customer_requirement_confirmation where tenant_id=? and opportunity_id=?",tenant,opportunity)){UUID cid=uuid(h.get("customer_requirement_confirmation_id"));var cs=exact(OpportunityCustomerRequirementsService.CONFIRMATION,cid);out.add(cs);var cm=OpportunityCustomerRequirementsService.metadata(c,tenant,cs);if(cm!=null){out.add(cm.opportunity());out.add(cm.responsibility());if(cm.draft()!=null)out.add(cm.draft());}for(var p:rows(c,"select party_id,party_revision,profile_version_id from opportunity.customer_requirement_participant where tenant_id=? and confirmation_id=?",tenant,cid)){out.add(new Subject("party.party",uuid(p.get("party_id")),((Number)p.get("party_revision")).longValue(),null));out.add(exact("party.profile_version",uuid(p.get("profile_version_id"))));}}
  for(var m:materials.history(c,tenant,opportunity)){out.add(m.selector());out.add(exact("evidence.material_upload_basis",m.upload()));out.addAll(tasks.materialFacts(c,tenant,m));}
  for(var identity:rows(c,"select distinct a.appointment_id,a.revision appointment_revision,p.principal_id,p.revision principal_revision,o.organization_unit_id,o.revision organization_revision from opportunity.quote_workflow w left join responsibility.task_occurrence t on t.tenant_id=w.tenant_id and t.task_occurrence_id=w.task_id join identity.appointment a on a.tenant_id=w.tenant_id and a.appointment_id=coalesce(t.owner_appointment_id,w.owner_appointment_id) join identity.principal p on p.tenant_id=a.tenant_id and p.principal_id=a.principal_id join identity.organization_unit o on o.tenant_id=a.tenant_id and o.organization_unit_id=a.organization_unit_id where w.tenant_id=? and w.opportunity_id=?",tenant,opportunity)){out.add(new Subject("identity.appointment",uuid(identity.get("appointment_id")),((Number)identity.get("appointment_revision")).longValue(),null));out.add(new Subject("identity.principal",uuid(identity.get("principal_id")),((Number)identity.get("principal_revision")).longValue(),null));out.add(new Subject("identity.organization_unit",uuid(identity.get("organization_unit_id")),((Number)identity.get("organization_revision")).longValue(),null));}
  if(row(c,"select 1 from opportunity.quote_workflow where tenant_id=? and opportunity_id=? and quote_revision_id is null",tenant,opportunity)!=null){
   for(var i:rows(c,"select * from opportunity.quote_preparation_intent where tenant_id=? and opportunity_id=?",tenant,opportunity)){
    out.add(exact("opportunity.quote_preparation_intent",uuid(i.get("quote_preparation_intent_id"))));
    out.add(new Subject("opportunity.opportunity",opportunity,((Number)i.get("opportunity_revision")).longValue(),null));
    out.add(new Subject((String)i.get("responsibility_type"),uuid(i.get("responsibility_id")),((Number)i.get("responsibility_revision")).longValue(),null));
   }
  }
  if(r.get("closed_at")!=null){
   for(var z:rows(c,"select * from opportunity.quote_termination where tenant_id=? and opportunity_id=?",tenant,opportunity)){
    out.add(exact("opportunity.quote_termination",uuid(z.get("quote_termination_id"))));out.add(exact("opportunity.closure",uuid(z.get("closure_id"))));
    out.add(new Subject("opportunity.opportunity",opportunity,((Number)z.get("opportunity_revision")).longValue(),null));
    var closed=OpportunityClosureService.currentMetadata(c,tenant,opportunity);if(closed!=null)out.add(closed.responsibility());
    for(var m:rows(c,"select m.*,t.revision current_revision from opportunity.quote_termination_task m join responsibility.task_occurrence t on t.tenant_id=m.tenant_id and t.task_occurrence_id=m.task_id where m.tenant_id=? and m.quote_termination_id=?",tenant,z.get("quote_termination_id"))){out.add(exact("opportunity.quote_termination_task",uuid(m.get("quote_termination_task_id"))));out.add(new Subject("responsibility.task_occurrence",uuid(m.get("task_id")),((Number)m.get("task_revision")).longValue(),null));out.add(new Subject("responsibility.task_occurrence",uuid(m.get("task_id")),((Number)m.get("current_revision")).longValue(),null));if(m.get("wait_id")!=null)out.add(new Subject("responsibility.wait_receipt",uuid(m.get("wait_id")),null,Base64.getUrlEncoder().withoutPadding().encodeToString((byte[])m.get("wait_hash"))));}
   }
  }
  out.addAll(tasks.sourceFacts(c,tenant,opportunity));
  return List.copyOf(out);
 }
 private Map<String,Object> quote(Connection c,UUID tenant,UUID id)throws SQLException{return id==null?null:row(c,"select q.*,b.body_ciphertext,b.body_digest,b.customer_confirmation_id from opportunity.quote_revision q join opportunity.quote_package_basis b on b.tenant_id=q.tenant_id and b.quote_revision_id=q.quote_revision_id where q.tenant_id=? and q.quote_revision_id=?",tenant,id);}
 private Map<String,Object> document(UUID tenant,UUID opportunity,Map<String,Object> q){String clear=protection.decryptQuote(tenant,opportunity,(UUID)q.get("quote_revision_id"),false,(byte[])q.get("body_ciphertext"));if(!MessageDigest.isEqual(QuoteCanonicalJson.digest(clear),(byte[])q.get("body_digest")))throw new IllegalStateException("Quote integrity failure");return codec.decode(clear);}
 private String customerName(Connection c,UUID tenant,Subject confirmation)throws SQLException{if(confirmation==null)return "未确认客户";var svc=OpportunityCustomerRequirementsService.databaseBacked(protection,new OpportunityCustomerRequirementsService.Codec(){public String encode(Map<String,Object> d){return codec.encode(d);}public Map<String,Object> decode(String d){return codec.decode(d);}});var v=svc.read(c,tenant,confirmation);if(v==null)return "已确认客户";var clients=rows(c,"select party_id from opportunity.customer_requirement_participant where tenant_id=? and confirmation_id=? and role='CLIENT' order by party_id",tenant,confirmation.id());var names=new ArrayList<String>();for(var client:clients)v.partySnapshots().stream().filter(snapshot->snapshot.selector().id().equals(client.get("party_id"))).findFirst().ifPresent(snapshot->names.add(snapshot.name()));return names.isEmpty()?"已确认客户":String.join("、",names);}
 public Map<String,Object> acceptedPreparation(Connection c,UUID tenant,UUID opportunity)throws SQLException{var candidates=rows(c,"select q.*,r.quote_response_id from opportunity.contract_preparation_source s join opportunity.quote_response r on r.tenant_id=s.tenant_id and r.quote_response_id=s.quote_response_id and r.response_code='ACCEPTED' join opportunity.quote_issue i on i.tenant_id=r.tenant_id and i.quote_issue_id=r.quote_issue_id and i.issue_status_code='ACTIVE' join opportunity.quote_revision q on q.tenant_id=i.tenant_id and q.quote_revision_id=i.quote_revision_id where s.tenant_id=? and s.opportunity_id=? and s.source_kind='ACCEPTED_QUOTE' order by s.created_at desc,s.contract_preparation_source_id",tenant,opportunity);if(candidates.size()!=1)return null;var q=candidates.getFirst();return Map.of("responseId",q.get("quote_response_id").toString(),"commercial",document(tenant,opportunity,quote(c,tenant,(UUID)q.get("quote_revision_id"))));}
 public byte[] document(Connection c,Actor actor,UUID oid,UUID qid)throws SQLException{var q=quote(c,actor.tenantId(),qid);if(q==null||!oid.equals(q.get("opportunity_id")))throw new Blocked("NOT_FOUND");var body=document(actor.tenantId(),oid,q);return QuoteDocumentRenderer.render(commercial(body),actor.tenantId(),oid,uuid(q.get("customer_confirmation_id")),qid,((Number)q.get("quote_revision_no")).longValue(),uuid(q.get("predecessor_quote_revision_id")),customerName(c,actor.tenantId(),exact(OpportunityCustomerRequirementsService.CONFIRMATION,uuid(q.get("customer_confirmation_id")))));}
 public Map<String,Object> context(Connection c,Actor actor,UUID oid)throws SQLException{
  UUID tenant=actor.tenantId();var r=root(c,tenant,oid,false);var o=opportunity(r);var owner=responsibility(c,tenant,r);var conf=confirmation(c,tenant,oid);var d=drafts().latest(c,tenant,o,owner.basis(),owner.appointmentId());var q=quote(c,tenant,(UUID)r.get("current_quote_revision_id"));var w=workflow(c,tenant,oid);var result=new LinkedHashMap<String,Object>();
  result.put("opportunity",selector(o));result.put("responsibilityBasis",selector(owner.basis()));result.put("customerConfirmation",selector(conf));result.put("draft",d==null?null:Map.of("selector",selector(d.selector()),"document",d.document()));
  result.put("quote",q==null?null:Map.of("selector",quoteSelector(q),"version",q.get("quote_revision_no"),"document",document(tenant,oid,q),"totalMinor",q.get("total_minor"),"validUntil",instant(q.get("valid_until")).toString()));
  var work=w==null?null:new LinkedHashMap<String,Object>();if(w!=null){work.put("selector",selector((UUID)w.get("quote_workflow_id")));work.put("stage",w.get("stage"));work.put("ownerAppointmentId",w.get("owner_appointment_id").toString());var task=uuid(w.get("task_id"))==null?null:tasks.read(c,tenant,uuid(w.get("task_id")));if("AWAIT_APPROVAL".equals(w.get("stage"))){var mine=row(c,"select m.task_id from opportunity.quote_approval_member m join opportunity.quote_approval_request r on r.tenant_id=m.tenant_id and r.quote_approval_request_id=m.request_id join responsibility.task_occurrence t on t.tenant_id=m.tenant_id and t.task_occurrence_id=m.task_id where r.tenant_id=? and r.quote_revision_id=? and m.appointment_id=? and t.state='OPEN'",tenant,q.get("quote_revision_id"),actor.appointmentId());if(mine!=null)task=tasks.read(c,tenant,uuid(mine.get("task_id")));}work.put("task",task==null?null:selector(task.selector()));work.put("state",task==null?null:task.state());var appointment=row(c,"select p.display_name from identity.appointment a join identity.principal p on p.tenant_id=a.tenant_id and p.principal_id=a.principal_id where a.tenant_id=? and a.appointment_id=?",tenant,task==null?w.get("owner_appointment_id"):task.owner());work.put("ownerLabel",appointment==null?"负责人":appointment.get("display_name"));if(task!=null){var sla=row(c,"select original_sla_due_at from responsibility.task_occurrence where tenant_id=? and task_occurrence_id=?",tenant,task.selector().id());work.put("dueAt",instant(sla.get("original_sla_due_at")).toString());}if("RETURNED".equals(w.get("stage"))){var reason=row(c,"select d.quote_approval_decision_id,d.reason_ciphertext,d.reason_digest from opportunity.quote_approval_decision d join opportunity.quote_approval_member m on m.tenant_id=d.tenant_id and m.quote_approval_member_id=d.member_id join opportunity.quote_approval_request a on a.tenant_id=m.tenant_id and a.quote_approval_request_id=m.request_id where a.tenant_id=? and a.quote_revision_id=? and d.decision='RETURNED'",tenant,q.get("quote_revision_id"));if(reason!=null){String text=protection.decryptQuote(tenant,oid,uuid(reason.get("quote_approval_decision_id")),false,(byte[])reason.get("reason_ciphertext"));if(!MessageDigest.isEqual(QuoteCanonicalJson.digest(text),(byte[])reason.get("reason_digest")))throw new IllegalStateException("Decision integrity failure");work.put("message",text);}}if(w.get("next_check_at")!=null)work.put("nextCheckAt",instant(w.get("next_check_at")).toString());}
  var recipients=new ArrayList<Map<String,Object>>();if(q!=null){var customerSvc=OpportunityCustomerRequirementsService.databaseBacked(protection,new OpportunityCustomerRequirementsService.Codec(){public String encode(Map<String,Object> d){return codec.encode(d);}public Map<String,Object> decode(String d){return codec.decode(d);}});var customer=customerSvc.read(c,tenant,exact(OpportunityCustomerRequirementsService.CONFIRMATION,uuid(q.get("customer_confirmation_id"))));for(var rp:rows(c,"select opportunity_participation_id,party_id from opportunity.opportunity_participation where tenant_id=? and opportunity_id=? and participation_set_revision=? and context_role_code='CLIENT' order by participation_no",tenant,oid,q.get("participation_set_revision"))){String name=customer.partySnapshots().stream().filter(s->s.selector().id().equals(rp.get("party_id"))).map(OpportunityCustomerRequirementsService.Snapshot::name).findFirst().orElse("已确认客户");recipients.add(Map.of("selector",selector(uuid(rp.get("opportunity_participation_id"))),"name",name));}}result.put("recipients",recipients);
  result.put("workflow",work);boolean own=actor.appointmentId().equals(owner.appointmentId());boolean readonly=r.get("closed_at")!=null||tasks.contractTakenOver(c,tenant,oid);result.put("readonly",readonly);String stage=w==null?"PREPARE":(String)w.get("stage");var actions=new ArrayList<String>();if(!readonly){if(own&&(Set.of("PREPARE","RETURNED","SALES_DISPOSITION","OWNER_EXCEPTION").contains(stage)||(expired(q,tasks.now(c))||basisChanged(q,w,conf,owner.appointmentId())||approvalAuthorityLost(c,tenant,owner.appointmentId(),oid,q))&&!stage.equals("ACCEPTED"))){actions.add("SAVE_QUOTE_DRAFT");actions.add("FORM_QUOTE");}if(own&&stage.equals("SUBMIT_APPROVAL")&&!approvalAuthorityLost(c,tenant,owner.appointmentId(),oid,q))actions.add("REQUEST_QUOTE_APPROVAL");if(stage.equals("OWNER_EXCEPTION")&&task(c,tenant,w)!=null&&actor.appointmentId().equals(task(c,tenant,w).owner())){var repaired=policy(c,tenant,owner.appointmentId());if(repaired!=null&&"REQUIRE_APPROVAL".equals(repaired.get("mode"))&&!signers(c,tenant,owner.appointmentId(),oid,repaired).isEmpty())actions.add("REQUEST_QUOTE_APPROVAL");}if(stage.equals("AWAIT_APPROVAL")&&work.get("task")!=null)actions.add("RECORD_QUOTE_DECISION");if(own&&stage.equals("DELIVER")&&!expired(q,tasks.now(c))&&!approvalAuthorityLost(c,tenant,owner.appointmentId(),oid,q))actions.add("RECORD_QUOTE_DELIVERY");if(own&&Set.of("AWAIT_REPLY","FOLLOW_UP","CLARIFY_REPLY").contains(stage)&&Set.of("OPEN","WAITING").contains(work.get("state")))actions.add("RECORD_QUOTE_RESPONSE");}if(basisChanged(q,w,conf,owner.appointmentId()))actions.removeIf(a->!Set.of("SAVE_QUOTE_DRAFT","FORM_QUOTE").contains(a));if(!readonly&&own&&conf!=null&&q==null&&w==null)actions.add("START_QUOTE_PREPARATION");if(!readonly&&own&&w!=null&&permitted(c,actor,owner.appointmentId(),oid,"OPPORTUNITY_CLOSE"))actions.add("END_QUOTE_NEGOTIATION");result.put("allowedActions",actions);
  var history=new ArrayList<Map<String,Object>>();for(var item:rows(c,"select quote_revision_id from opportunity.quote_revision where tenant_id=? and opportunity_id=? order by quote_revision_no",tenant,oid)){var old=quote(c,tenant,uuid(item.get("quote_revision_id")));history.add(Map.of("selector",quoteSelector(old),"version",old.get("quote_revision_no"),"document",document(tenant,oid,old),"totalMinor",old.get("total_minor"),"validUntil",instant(old.get("valid_until")).toString()));}result.put("history",history);result.put("records",records(c,tenant,oid));

  var visibleMaterials=new ArrayList<Map<String,Object>>();for(var m:materials.history(c,tenant,oid)){if(!materials.current(c,tenant,m.selector().id()))continue;var md=tasks.materialBody(c,tenant,m.upload());visibleMaterials.add(Map.of("selector",selector(m.selector()),"purpose",m.purpose(),"fileName",md.get("fileName")));}result.put("materials",visibleMaterials);result.put("approvers",q==null?List.of():rows(c,"select m.appointment_id,m.task_id from opportunity.quote_approval_member m join opportunity.quote_approval_request r on r.tenant_id=m.tenant_id and r.quote_approval_request_id=m.request_id where r.tenant_id=? and r.quote_revision_id=? order by m.appointment_id",tenant,q.get("quote_revision_id")).stream().map(m->Map.of("appointmentId",m.get("appointment_id").toString(),"taskId",m.get("task_id").toString())).toList());result.put("customerName",customerName(c,tenant,conf));if(expired(q,tasks.now(c))&&!stage.equals("ACCEPTED")){result.put("notice","本版报价已过期，请修订报价或明确结束洽谈；仍可记录有效期内已发生的准确回复。");}
  if(Set.of("SUBMIT_APPROVAL","AWAIT_APPROVAL","DELIVER").contains(stage)&&approvalAuthorityLost(c,tenant,owner.appointmentId(),oid,q)){work.put("stage","OWNER_EXCEPTION");result.put("notice","本版审批任职或权限已失效，请主管修复审批配置后重新形成准确报价。");}
  if(basisChanged(q,w,conf,owner.appointmentId())&&!stage.equals("ACCEPTED")){if(work!=null)work.put("stage","RETURNED");result.put("notice","客户确认或责任归属已变更，请形成新版本；原审批与发送凭据不会复用。");}if(stage.equals("OWNER_EXCEPTION"))result.put("notice","报价审批依据缺失，请主管配置有权审批人后重新办理。");if(stage.equals("ACCEPTED"))result.put("notice","客户接受已记录，合同准备来源已保存。");if(r.get("closed_at")!=null)result.put("notice","本次销售办理已结束；报价、审批、交付及客户回复历史仍可查阅。");return result;
 }
 private String clearRecord(UUID tenant,UUID oid,UUID id,byte[] ciphertext,byte[] digest){String clear=protection.decryptQuote(tenant,oid,id,false,ciphertext);if(!MessageDigest.isEqual(QuoteCanonicalJson.digest(clear),digest))throw new IllegalStateException("Quote record integrity failure");return clear;}
 private List<Map<String,Object>> records(Connection c,UUID tenant,UUID oid)throws SQLException{
  var out=new ArrayList<Map<String,Object>>();
  for(var q:rows(c,"select quote_revision_id,content_digest,quote_revision_no from opportunity.quote_revision where tenant_id=? and opportunity_id=? order by quote_revision_no",tenant,oid)){
   UUID qid=uuid(q.get("quote_revision_id"));
   for(var a:rows(c,"select d.*,m.appointment_id from opportunity.quote_approval_decision d join opportunity.quote_approval_member m on m.tenant_id=d.tenant_id and m.quote_approval_member_id=d.member_id join opportunity.quote_approval_request r on r.tenant_id=m.tenant_id and r.quote_approval_request_id=m.request_id where r.tenant_id=? and r.quote_revision_id=? order by d.created_at",tenant,qid)){var record=recordBase(q,"APPROVAL",selector(uuid(a.get("quote_approval_decision_id"))),a.get("appointment_id"),a.get("created_at"),a.get("created_at"));record.put("decision",a.get("decision"));record.put("reason",clearRecord(tenant,oid,uuid(a.get("quote_approval_decision_id")),(byte[])a.get("reason_ciphertext"),(byte[])a.get("reason_digest")));out.add(record);}
   for(var d:rows(c,"select d.*,i.quote_issue_id from opportunity.quote_manual_delivery d join opportunity.quote_issue i on i.tenant_id=d.tenant_id and i.delivery_fact_id=d.quote_manual_delivery_id where d.tenant_id=? and d.quote_revision_id=? order by d.created_at",tenant,qid)){var record=recordBase(q,"DELIVERY",selector(uuid(d.get("quote_issue_id"))),d.get("recorded_by"),d.get("occurred_at"),d.get("created_at"));record.put("recipient",clearRecord(tenant,oid,uuid(d.get("quote_manual_delivery_id")),(byte[])d.get("recipient_ciphertext"),(byte[])d.get("body_digest")));record.put("channel",d.get("channel"));record.put("evidence",selector(uuid(d.get("material_version_id"))));out.add(record);}
   for(var r:rows(c,"select r.*,b.material_version_id from opportunity.quote_response r join opportunity.quote_issue i on i.tenant_id=r.tenant_id and i.quote_issue_id=r.quote_issue_id join opportunity.quote_response_basis b on b.tenant_id=r.tenant_id and b.quote_response_id=r.quote_response_id where r.tenant_id=? and i.quote_revision_id=? order by r.created_at",tenant,qid)){var record=recordBase(q,"RESPONSE",selector(new Subject("opportunity.quote_response",uuid(r.get("quote_response_id")),null,Base64.getUrlEncoder().withoutPadding().encodeToString((byte[])r.get("response_content_digest")))),r.get("recorded_by_appointment_id"),r.get("received_at"),r.get("created_at"));var body=codec.decode(clearRecord(tenant,oid,uuid(r.get("quote_response_id")),(byte[])r.get("response_content_ciphertext"),(byte[])r.get("response_content_digest")));record.put("responseKind",r.get("response_code"));record.put("statement",body.get("statement"));record.put("evidence",selector(uuid(r.get("material_version_id"))));out.add(record);}
  }return List.copyOf(out);
 }
 private static LinkedHashMap<String,Object> recordBase(Map<String,Object> quote,String kind,Map<String,Object> selector,Object actor,Object occurred,Object recorded){var out=new LinkedHashMap<String,Object>();out.put("kind",kind);out.put("quote",quoteSelector(quote));out.put("version",quote.get("quote_revision_no"));out.put("selector",selector);out.put("actorAppointmentId",actor.toString());out.put("occurredAt",instant(occurred).toString());out.put("recordedAt",instant(recorded).toString());return out;}
 public Subject execute(Connection c,String command,Actor actor,Map<String,Object> p)throws SQLException{
  requireCommandScope();
  if(c.getAutoCommit()||c.getTransactionIsolation()!=Connection.TRANSACTION_READ_COMMITTED)throw new SQLException("Quote command transaction required","25001");UUID tenant=actor.tenantId(),oid=uuid(p.get("opportunityId"));var r=root(c,tenant,oid,true);if(tasks.contractTakenOver(c,tenant,oid))throw stale();var o=opportunity(r);if(r.get("closed_at")!=null||integer(p.get("expectedOpportunityRevision"))!=o.revision())throw stale();var own=responsibility(c,tenant,r);expected(p.get("responsibilityBasis"),own.basis().id(),own.basis().revision());var conf=confirmation(c,tenant,oid);if(conf==null)throw new Blocked("CUSTOMER_CONFIRMATION_REQUIRED");expected(p.get("customerConfirmation"),conf.id(),0);var d=drafts().latest(c,tenant,o,own.basis(),own.appointmentId());expected(p.get("expectedDraft"),d==null?null:d.selector().id(),0);var q=quote(c,tenant,(UUID)r.get("current_quote_revision_id"));if(q==null){if(p.get("expectedQuote")!=null)throw stale();}else if(!quoteSelector(q).equals(p.get("expectedQuote")))throw stale();var w=workflow(c,tenant,oid);expected(p.get("expectedWorkflow"),w==null?null:(UUID)w.get("quote_workflow_id"),0);String type=command,stage=w==null?"PREPARE":(String)w.get("stage");Instant now=tasks.now(c);var identity=AuthorizationIdentityReader.databaseBacked().owner(c,tenant,actor.appointmentId(),now);if(identity==null||!identity.active()||!identity.principalId().equals(actor.principalId())||actor.onBehalfAppointmentId()!=null)throw new Blocked("NOT_AUTHORIZED");if(!type.equals("RECORD_QUOTE_DECISION")&&!actor.appointmentId().equals(own.appointmentId())&&!(type.equals("REQUEST_QUOTE_APPROVAL")&&stage.equals("OWNER_EXCEPTION")&&task(c,tenant,w)!=null&&actor.appointmentId().equals(task(c,tenant,w).owner())))throw new Blocked("NOT_AUTHORIZED");var v=values(p);
  if(type.equals("END_QUOTE_NEGOTIATION")){if(w==null)throw stale();if(!permitted(c,actor,own.appointmentId(),oid,"OPPORTUNITY_CLOSE"))throw new Blocked("NOT_AUTHORIZED");return JdbcQuoteTermination.end(c,actor,o,own.basis(),uuid(w.get("quote_workflow_id")),q==null?null:uuid(q.get("quote_revision_id")),v,now,protection,tasks);}
  if(type.equals("START_QUOTE_PREPARATION")){if(w!=null||q!=null)throw stale();if(!v.isEmpty())throw new IllegalArgumentException("Preparation intent has no commercial values");return startPreparation(c,actor,r,own,conf,now);}
  if(type.equals("SAVE_QUOTE_DRAFT")){if((!expired(q,now)&&!basisChanged(q,w,conf,own.appointmentId())&&!approvalAuthorityLost(c,tenant,own.appointmentId(),oid,q))||stage.equals("ACCEPTED"))requireStage(stage,"PREPARE","RETURNED","SALES_DISPOSITION","OWNER_EXCEPTION");return drafts().save(c,tenant,new QuoteDraftService.Input(o,own.basis(),own.appointmentId(),conf,d==null?null:d.selector(),v)).selector();}
  if(type.equals("FORM_QUOTE")){if((!expired(q,now)&&!basisChanged(q,w,conf,own.appointmentId())&&!approvalAuthorityLost(c,tenant,own.appointmentId(),oid,q))||stage.equals("ACCEPTED"))requireStage(stage,"PREPARE","RETURNED","SALES_DISPOSITION","OWNER_EXCEPTION");if(!v.isEmpty())d=drafts().save(c,tenant,new QuoteDraftService.Input(o,own.basis(),own.appointmentId(),conf,d==null?null:d.selector(),v));if(d==null)throw new IllegalArgumentException("Saved quote draft required");return form(c,actor,r,own,conf,d,q,w,now);}
  if(q==null||!conf.id().equals(q.get("customer_confirmation_id"))||w==null||!own.appointmentId().equals(uuid(w.get("owner_appointment_id"))))throw stale();if(row(c,"select 1 from opportunity.customer_requirement_participant p join party.party actual on actual.tenant_id=p.tenant_id and actual.party_id=p.party_id where p.tenant_id=? and p.confirmation_id=? and actual.revision<>p.party_revision limit 1",tenant,conf.id())!=null)throw stale();
  return switch(type){case "REQUEST_QUOTE_APPROVAL" -> request(c,actor,r,own,q,w,stage,now);case "RECORD_QUOTE_DECISION" -> decide(c,actor,r,own,q,w,stage,v,now);case "RECORD_QUOTE_DELIVERY" -> deliver(c,actor,r,own,q,w,stage,v,now);case "RECORD_QUOTE_RESPONSE" -> respond(c,actor,r,own,q,w,stage,v,now);default -> throw new IllegalArgumentException("Unsupported quote command");};
 }
 private static boolean basisChanged(Map<String,Object> q,Map<String,Object> w,Subject conf,UUID owner){return q!=null&&(conf==null||!conf.id().equals(q.get("customer_confirmation_id"))||w==null||!owner.equals(uuid(w.get("owner_appointment_id")))) ;}
 private static boolean expired(Map<String,Object> q,Instant now){return q!=null&&!instant(q.get("valid_until")).isAfter(now);}
 private static void requireStage(String actual,String... allowed){if(!Arrays.asList(allowed).contains(actual))throw new Blocked("STALE_TASK");}
 public static QuotePackage commercial(Map<String,Object> d){var lines=new ArrayList<QuotePackage.Line>();if(!(d.get("lines") instanceof List<?> ll))throw new IllegalArgumentException("Quote lines required");for(var raw:ll){if(!(raw instanceof Map<?,?> m)||!(m.get("discount") instanceof Boolean discount))throw new IllegalArgumentException("Quote line required");lines.add(new QuotePackage.Line((String)m.get("description"),integer(m.get("amountMinor")),discount));}QuotePackage.ConditionalFee conditional=null;if(d.get("conditionalFee")!=null){var f=(Map<?,?>)d.get("conditionalFee");conditional=new QuotePackage.ConditionalFee((String)f.get("basis"),Math.toIntExact(integer(f.get("rateBasisPoints"))),integer(f.get("capMinor")));}return new QuotePackage((String)d.get("currency"),(String)d.get("scope"),lines,(String)d.get("paymentTerms"),instant(d.get("validUntil")),conditional);}
 private Task create(Connection c,UUID tenant,String type,UUID owner,Subject opportunity,Instant now)throws SQLException{return tasks.create(c,tenant,type,owner,opportunity,ZONE,now);}
 private Task task(Connection c,UUID tenant,Map<String,Object> w)throws SQLException{return w==null||w.get("task_id")==null?null:tasks.read(c,tenant,uuid(w.get("task_id")));}
 private Subject transition(Connection c,UUID tenant,UUID oid,UUID quote,Map<String,Object> previous,String stage,UUID owner,Task task,UUID prior,Instant due,Instant now)throws SQLException{UUID id=id(c);sql(c,"insert into opportunity.quote_workflow(tenant_id,quote_workflow_id,revision,opportunity_id,quote_revision_id,previous_workflow_id,stage,owner_appointment_id,task_id,prior_task_id,next_check_at,created_at) values(?,?,0,?,?,?,?,?,?,?,?,?)",tenant,id,oid,quote,previous==null?null:previous.get("quote_workflow_id"),stage,owner,task==null?null:task.selector().id(),prior,due,now);return exact("opportunity.quote_workflow",id);}
 private void cancel(Connection c,UUID tenant,Task task,String reason,Instant now)throws SQLException{if(task==null)return;tasks.cancelForQuote(c,tenant,task,reason,now);}
 private Map<String,Object> policy(Connection c,UUID tenant,UUID owner)throws SQLException{UUID org=authority.historicalOrganization(c,tenant,owner);return row(c,"select p.* from opportunity.quote_approval_policy p where p.tenant_id=? and p.organization_unit_id=? and p.policy_code='R2_QUOTE_APPROVAL_V1' and not exists(select 1 from opportunity.quote_approval_policy n where n.tenant_id=p.tenant_id and n.organization_unit_id=p.organization_unit_id and n.policy_code=p.policy_code and n.policy_version>p.policy_version)",tenant,org);}
 private boolean permitted(Connection c,Actor actor,UUID owner,UUID oid,String code)throws SQLException{return authority.permitted(c,actor,authority.historicalOrganization(c,actor.tenantId(),owner),protectedFacts(c,actor.tenantId(),oid),code);}
 private boolean selfSigner(Connection c,Actor actor,Map<String,Object> policy)throws SQLException{return row(c,"select 1 from opportunity.quote_approval_policy_signer where tenant_id=? and policy_id=? and appointment_id=?",actor.tenantId(),policy.get("quote_approval_policy_id"),actor.appointmentId())!=null;}
 private boolean approvalAuthorityLost(Connection c,UUID tenant,UUID owner,UUID oid,Map<String,Object> q)throws SQLException{if(q==null)return false;var members=rows(c,"select m.appointment_id from opportunity.quote_approval_member m join opportunity.quote_approval_request a on a.tenant_id=m.tenant_id and a.quote_approval_request_id=m.request_id where a.tenant_id=? and a.quote_revision_id=?",tenant,q.get("quote_revision_id"));if(members.isEmpty()){var policy=policy(c,tenant,owner);if(policy==null)return true;if("REQUIRE_APPROVAL".equals(policy.get("mode")))return signers(c,tenant,owner,oid,policy).isEmpty();var reg=AuthorizationIdentityReader.databaseBacked().registration(c,tenant,owner);if(reg==null)return true;var actor=new Actor(tenant,reg.principalId(),owner,null,null);return !selfSigner(c,actor,policy)||!permitted(c,actor,owner,oid,"QUOTE_SELF_AUTHORIZE");}for(var m:members){UUID id=uuid(m.get("appointment_id"));var reg=AuthorizationIdentityReader.databaseBacked().registration(c,tenant,id);if(reg==null||!permitted(c,new Actor(tenant,reg.principalId(),id,null,null),owner,oid,"QUOTE_APPROVE"))return true;}return false;}
 private List<UUID> signers(Connection c,UUID tenant,UUID owner,UUID oid,Map<String,Object> policy)throws SQLException{if(policy==null)return List.of();var out=new ArrayList<UUID>();for(var row:rows(c,"select appointment_id from opportunity.quote_approval_policy_signer where tenant_id=? and policy_id=? order by appointment_id",tenant,policy.get("quote_approval_policy_id"))){UUID a=uuid(row.get("appointment_id"));var reg=AuthorizationIdentityReader.databaseBacked().registration(c,tenant,a);if(reg==null||!permitted(c,new Actor(tenant,reg.principalId(),a,null,null),owner,oid,"QUOTE_APPROVE"))return List.of();out.add(a);}return out;}
 private Subject startPreparation(Connection c,Actor actor,Map<String,Object> root,OpportunityResponsibilityReader.Responsibility owner,Subject conf,Instant now)throws SQLException{
  UUID tenant=actor.tenantId(),oid=uuid(root.get("opportunity_id"));
  if(!permitted(c,actor,owner.appointmentId(),oid,"QUOTE_PREPARE"))throw new Blocked("NOT_AUTHORIZED");
  if(row(c,"select 1 from opportunity.customer_requirement_participant p join party.party actual on actual.tenant_id=p.tenant_id and actual.party_id=p.party_id where p.tenant_id=? and p.confirmation_id=? and actual.revision<>p.party_revision limit 1",tenant,conf.id())!=null)throw stale();
  var active=tasks.activeForLead(c,tenant,opportunity(root));
  if(active.size()>1||active.stream().anyMatch(t->!t.type().equals("PROGRESS_OPPORTUNITY")||!t.owner().equals(owner.appointmentId())))throw new Blocked("STALE_TASK");
  Task old=active.isEmpty()?null:active.getFirst();cancel(c,tenant,old,"QUOTE_WORKFLOW_TAKEOVER",now);
  var prep=create(c,tenant,"PREPARE_QUOTE",owner.appointmentId(),opportunity(root),now);
  var w=transition(c,tenant,oid,null,null,"PREPARE",owner.appointmentId(),prep,old==null?null:old.selector().id(),null,now);
  UUID intent=id(c);sql(c,"insert into opportunity.quote_preparation_intent(tenant_id,quote_preparation_intent_id,revision,opportunity_id,opportunity_revision,customer_confirmation_id,responsibility_type,responsibility_id,responsibility_revision,workflow_id,task_id,prior_task_id,requested_by,created_at) values(?,?,0,?,?,?,?,?,?,?,?,?,?,?)",tenant,intent,oid,root.get("revision"),conf.id(),owner.basis().type(),owner.basis().id(),owner.basis().revision(),w.id(),prep.selector().id(),old==null?null:old.selector().id(),actor.appointmentId(),now);
  return exact("opportunity.quote_preparation_intent",intent);
 }
 private Subject form(Connection c,Actor actor,Map<String,Object> root,OpportunityResponsibilityReader.Responsibility owner,Subject conf,QuoteDraftService.Version draft,Map<String,Object> prior,Map<String,Object> w,Instant now)throws SQLException{
  UUID tenant=actor.tenantId(),oid=uuid(root.get("opportunity_id")),qid=id(c);var pkg=commercial(draft.document());pkg.validateAt(now);long version=prior==null?1:((Number)prior.get("quote_revision_no")).longValue()+1;UUID previous=prior==null?null:uuid(prior.get("quote_revision_id"));var body=pkg.body(tenant,oid,conf.id(),version,previous);String clear=codec.encode(body);byte[] digest=QuoteCanonicalJson.digest(clear);
  Task old=task(c,tenant,w);if(old!=null&&!Set.of("OPEN","WAITING").contains(old.state()))old=null;if(old==null){var active=tasks.activeForLead(c,tenant,opportunity(root));if(active.size()>1){if(!expired(prior,now)&&!basisChanged(prior,w,conf,owner.appointmentId())&&!approvalAuthorityLost(c,tenant,owner.appointmentId(),oid,prior))throw new IllegalStateException("Ambiguous active responsibility");for(var pending:active)cancel(c,tenant,pending,"QUOTE_WORKFLOW_TAKEOVER",now);old=null;}else old=active.isEmpty()?null:active.getFirst();}boolean reuse=old!=null&&old.owner().equals(owner.appointmentId())&&old.type().equals("PREPARE_QUOTE")&&"OPEN".equals(old.state());if(!reuse)cancel(c,tenant,old,"QUOTE_WORKFLOW_TAKEOVER",now);
  var prep=reuse?old:create(c,tenant,"PREPARE_QUOTE",owner.appointmentId(),opportunity(root),now);var av=Map.<String,Object>of("quoteDraftId",draft.selector().id().toString(),"quoteDigest",Base64.getUrlEncoder().withoutPadding().encodeToString(digest));UUID actionDraft=tasks.confirmAction(c,tenant,prep,av,actor.appointmentId(),now);
  var participants=rows(c,"select p.party_id,p.party_revision,p.role,p.profile_version_id from opportunity.customer_requirement_participant p join party.party party on party.tenant_id=p.tenant_id and party.party_id=p.party_id where p.tenant_id=? and p.confirmation_id=? and party.revision=p.party_revision order by p.role,p.party_id",tenant,conf.id());var total=row(c,"select count(*) n from opportunity.customer_requirement_participant where tenant_id=? and confirmation_id=?",tenant,conf.id());if(participants.isEmpty()||participants.size()!=((Number)total.get("n")).intValue())throw stale();byte[] participationDigest=QuoteCanonicalJson.digest(QuoteCanonicalJson.encode(participants.stream().map(p->Map.of("partyId",p.get("party_id").toString(),"revision",p.get("party_revision"),"role",p.get("role"),"profileVersionId",p.get("profile_version_id").toString())).toList()));
  sql(c,"insert into opportunity.quote_revision(tenant_id,quote_revision_id,opportunity_id,quote_revision_no,predecessor_quote_revision_id,confirmed_action_draft_id,participation_set_revision,participation_set_digest,package_contract_code,package_contract_version,currency_code,total_minor,content_digest,valid_until,created_by_appointment_id,created_at) values(?,?,?,?,?,?,?,?,'R2_QUOTE_PACKAGE_V1',1,?,?,?,?,?,?)",tenant,qid,oid,version,previous,actionDraft,Math.toIntExact(version),participationDigest,pkg.currency(),pkg.totalMinor(),digest,pkg.validUntil(),actor.appointmentId(),now);
  sql(c,"insert into opportunity.quote_package_basis(tenant_id,quote_package_basis_id,revision,quote_revision_id,quote_draft_id,customer_confirmation_id,body_ciphertext,body_digest,created_at) values(?,?,0,?,?,?,?,?,?)",tenant,qid,qid,draft.selector().id(),conf.id(),protection.encryptQuote(tenant,oid,qid,false,clear),digest,now);
  sql(c,"insert into opportunity.quote_service_scope(tenant_id,quote_service_scope_id,quote_revision_id,scope_no,service_code,scope_summary,included,scope_hash,created_at) values(?,?,?,1,'SERVICE','受保护报价范围',true,?,?)",tenant,id(c),qid,QuoteCanonicalJson.digest(pkg.scope()),now);int line=0;for(var item:pkg.lines())sql(c,"insert into opportunity.quote_line(tenant_id,quote_line_id,quote_revision_id,line_no,line_type_code,line_summary,amount_minor,currency_code,created_at) values(?,?,?,?,?,'受保护计价说明',?,?,?)",tenant,id(c),qid,++line,item.discount()?"DISCOUNT":"FIXED",item.amountMinor(),pkg.currency(),now);
  sql(c,"insert into opportunity.quote_payment_term(tenant_id,quote_payment_term_id,quote_revision_id,term_no,due_basis_code,due_offset_days,amount_minor,currency_code,term_summary,created_at) values(?,?,?,1,'AGREED_TERMS',0,?,?,'详见准确受保护报价条款',?)",tenant,id(c),qid,pkg.totalMinor(),pkg.currency(),now);int no=0;for(var p:participants)sql(c,"insert into opportunity.opportunity_participation(tenant_id,opportunity_participation_id,opportunity_id,participation_set_revision,participation_no,participation_set_size,participation_set_digest,party_id,party_revision,party_snapshot_digest,context_role_code,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?)",tenant,id(c),oid,Math.toIntExact(version),++no,participants.size(),participationDigest,p.get("party_id"),p.get("party_revision"),QuoteCanonicalJson.digest(p.get("profile_version_id").toString()),p.get("role"),now);
  sql(c,"update opportunity.opportunity set current_quote_revision_id=?,revision=revision+1 where tenant_id=? and opportunity_id=? and revision=?",qid,tenant,oid,root.get("revision"));var fact=new Subject("opportunity.quote_revision",qid,null,Base64.getUrlEncoder().withoutPadding().encodeToString(digest));tasks.complete(c,tenant,prep,fact,now);
  var policy=policy(c,tenant,owner.appointmentId());var nextOpportunity=new Subject("opportunity.opportunity",oid,opportunity(root).revision()+1,null);String stage="OWNER_EXCEPTION",type="RESOLVE_QUOTE_AUTHORITY";if(policy!=null){if("SELF_AUTHORIZED".equals(policy.get("mode"))&&selfSigner(c,actor,policy)&&permitted(c,actor,owner.appointmentId(),oid,"QUOTE_SELF_AUTHORIZE")){stage="DELIVER";type="DELIVER_QUOTE";}else if("REQUIRE_APPROVAL".equals(policy.get("mode"))&&!signers(c,tenant,owner.appointmentId(),oid,policy).isEmpty()){stage="SUBMIT_APPROVAL";type="SUBMIT_QUOTE_APPROVAL";}}
  UUID taskOwner=owner.appointmentId();if(stage.equals("OWNER_EXCEPTION")){var supervisors=authority.supervisors(c,tenant,authority.historicalOrganization(c,tenant,owner.appointmentId()),protectedFacts(c,tenant,oid));if(supervisors.size()==1)taskOwner=supervisors.getFirst();}var next=create(c,tenant,type,taskOwner,nextOpportunity,now);transition(c,tenant,oid,qid,w,stage,owner.appointmentId(),next,old==null?null:old.selector().id(),null,now);return fact;
 }
 private Subject request(Connection c,Actor actor,Map<String,Object> r,OpportunityResponsibilityReader.Responsibility owner,Map<String,Object> q,Map<String,Object> w,String stage,Instant now)throws SQLException{
  requireStage(stage,"SUBMIT_APPROVAL","OWNER_EXCEPTION");if(task(c,actor.tenantId(),w)==null||!actor.appointmentId().equals(task(c,actor.tenantId(),w).owner()))throw new Blocked("NOT_AUTHORIZED");UUID tenant=actor.tenantId(),oid=uuid(r.get("opportunity_id")),qid=uuid(q.get("quote_revision_id"));if(!instant(q.get("valid_until")).isAfter(now))throw new IllegalArgumentException("Quote expired");var policy=policy(c,tenant,owner.appointmentId());if(policy==null||!"REQUIRE_APPROVAL".equals(policy.get("mode")))throw new Blocked("NOT_AUTHORIZED");var signers=signers(c,tenant,owner.appointmentId(),oid,policy);if(signers.isEmpty())throw new Blocked("NOT_AUTHORIZED");
  UUID id=id(c);sql(c,"insert into opportunity.quote_approval_request(tenant_id,quote_approval_request_id,revision,quote_revision_id,policy_id,policy_code,policy_version,requested_by,created_at) values(?,?,0,?,?,'R2_QUOTE_APPROVAL_V1',?,?,?)",tenant,id,qid,policy.get("quote_approval_policy_id"),policy.get("policy_version"),actor.appointmentId(),now);var fact=exact("opportunity.quote_approval_request",id);tasks.complete(c,tenant,task(c,tenant,w),fact,now);for(UUID signer:signers){var approve=create(c,tenant,"APPROVE_QUOTE",signer,opportunity(r),now);sql(c,"insert into opportunity.quote_approval_member(tenant_id,quote_approval_member_id,revision,request_id,appointment_id,task_id) values(?,?,0,?,?,?)",tenant,id(c),id,signer,approve.selector().id());}transition(c,tenant,oid,qid,w,"AWAIT_APPROVAL",owner.appointmentId(),null,null,null,now);return fact;
 }
 private Subject decide(Connection c,Actor actor,Map<String,Object> r,OpportunityResponsibilityReader.Responsibility owner,Map<String,Object> q,Map<String,Object> w,String stage,Map<String,Object> v,Instant now)throws SQLException{
  requireStage(stage,"AWAIT_APPROVAL");UUID tenant=actor.tenantId(),oid=uuid(r.get("opportunity_id")),qid=uuid(q.get("quote_revision_id"));if(!permitted(c,actor,owner.appointmentId(),oid,"QUOTE_APPROVE"))throw new Blocked("NOT_AUTHORIZED");String decision=(String)v.get("decision"),reason=(String)v.get("reason");if(!Set.of("APPROVED","RETURNED").contains(decision)||reason==null||reason.isBlank()||reason.length()>4000)throw new IllegalArgumentException("Decision and reason required");var member=row(c,"select m.* from opportunity.quote_approval_member m join opportunity.quote_approval_request r on r.tenant_id=m.tenant_id and r.quote_approval_request_id=m.request_id where m.tenant_id=? and r.quote_revision_id=? and m.appointment_id=?",tenant,qid,actor.appointmentId());if(member==null)throw new Blocked("NOT_AUTHORIZED");var task=tasks.read(c,tenant,uuid(member.get("task_id")));if(!"OPEN".equals(task.state()))throw stale();UUID id=id(c);sql(c,"insert into opportunity.quote_approval_decision(tenant_id,quote_approval_decision_id,revision,member_id,decision,reason_ciphertext,reason_digest,created_at) values(?,?,0,?,?,?,?,?)",tenant,id,member.get("quote_approval_member_id"),decision,protection.encryptQuote(tenant,oid,id,false,reason),QuoteCanonicalJson.digest(reason),now);var fact=exact("opportunity.quote_approval_decision",id);tasks.complete(c,tenant,task,fact,now);
  if(decision.equals("RETURNED")){for(var other:rows(c,"select task_id from opportunity.quote_approval_member where tenant_id=? and request_id=? and appointment_id<>?",tenant,member.get("request_id"),actor.appointmentId())){var t=tasks.read(c,tenant,uuid(other.get("task_id")));if(Set.of("OPEN","WAITING").contains(t.state()))cancel(c,tenant,t,"QUOTE_RETURNED",now);}var next=create(c,tenant,"PREPARE_QUOTE",owner.appointmentId(),opportunity(r),now);transition(c,tenant,oid,qid,w,"RETURNED",owner.appointmentId(),next,null,null,now);
  }else{var pending=row(c,"select count(*) n from opportunity.quote_approval_member m where m.tenant_id=? and m.request_id=? and not exists(select 1 from opportunity.quote_approval_decision d where d.tenant_id=m.tenant_id and d.member_id=m.quote_approval_member_id and d.decision='APPROVED')",tenant,member.get("request_id"));if(((Number)pending.get("n")).longValue()==0){var next=create(c,tenant,"DELIVER_QUOTE",owner.appointmentId(),opportunity(r),now);transition(c,tenant,oid,qid,w,"DELIVER",owner.appointmentId(),next,null,null,now);}}
  return fact;
 }
 private OpportunityMaterials.Version evidence(Connection c,UUID tenant,UUID oid,Object raw)throws SQLException{if(!(raw instanceof Map<?,?> m))throw new IllegalArgumentException("Evidence required");var e=materials.version(c,tenant,uuid(m.get("id")));if(e==null||!e.opportunity().equals(oid)||integer(m.get("revision"))!=e.selector().revision()||!materials.current(c,tenant,e.selector().id()))throw new Blocked("STALE_EVIDENCE");return e;}
 private Subject deliver(Connection c,Actor actor,Map<String,Object> r,OpportunityResponsibilityReader.Responsibility owner,Map<String,Object> q,Map<String,Object> w,String stage,Map<String,Object> v,Instant now)throws SQLException{
  requireStage(stage,"DELIVER");UUID tenant=actor.tenantId(),oid=uuid(r.get("opportunity_id")),qid=uuid(q.get("quote_revision_id"));Instant occurred=instant(v.get("occurredAt"));if(occurred==null||occurred.getNano()%1000!=0||occurred.isAfter(now)||occurred.isBefore(instant(q.get("created_at")))||!instant(q.get("valid_until")).isAfter(now))throw new IllegalArgumentException("Invalid delivery time or expired quote");var e=evidence(c,tenant,oid,v.get("evidence"));String recipient=(String)v.get("recipient"),channel=(String)v.get("channel");if(recipient==null||recipient.isBlank()||recipient.length()>1000||channel==null||!channel.matches("[A-Z][A-Z0-9_]{0,63}"))throw new IllegalArgumentException("Recipient and channel required");var policy=policy(c,tenant,owner.appointmentId());var approval=row(c,"select * from opportunity.quote_approval_request where tenant_id=? and quote_revision_id=?",tenant,qid);byte[] authDigest;
  if(approval==null){if(policy==null||!"SELF_AUTHORIZED".equals(policy.get("mode"))||!selfSigner(c,actor,policy)||!permitted(c,actor,owner.appointmentId(),oid,"QUOTE_SELF_AUTHORIZE"))throw new Blocked("NOT_AUTHORIZED");authDigest=QuoteCanonicalJson.digest(policy.get("quote_approval_policy_id")+":"+actor.appointmentId()+":"+qid);
  }else{var members=rows(c,"select m.appointment_id,d.quote_approval_decision_id,d.decision from opportunity.quote_approval_member m left join opportunity.quote_approval_decision d on d.tenant_id=m.tenant_id and d.member_id=m.quote_approval_member_id where m.tenant_id=? and m.request_id=? order by m.appointment_id",tenant,approval.get("quote_approval_request_id"));if(members.isEmpty())throw new Blocked("NOT_AUTHORIZED");for(var m:members){var reg=AuthorizationIdentityReader.databaseBacked().registration(c,tenant,uuid(m.get("appointment_id")));if(!"APPROVED".equals(m.get("decision"))||reg==null||!permitted(c,new Actor(tenant,reg.principalId(),uuid(m.get("appointment_id")),null,null),owner.appointmentId(),oid,"QUOTE_APPROVE"))throw new Blocked("NOT_AUTHORIZED");}authDigest=QuoteCanonicalJson.digest(QuoteCanonicalJson.encode(members.stream().map(m->m.get("quote_approval_decision_id").toString()).toList()));}
  UUID mid=id(c),issue=id(c);sql(c,"insert into opportunity.quote_manual_delivery(tenant_id,quote_manual_delivery_id,revision,quote_revision_id,material_version_id,recipient_ciphertext,body_digest,channel,occurred_at,recorded_by,created_at) values(?,?,0,?,?,?,?,?,?,?,?)",tenant,mid,qid,e.selector().id(),protection.encryptQuote(tenant,oid,mid,false,recipient),QuoteCanonicalJson.digest(recipient),channel,occurred,actor.appointmentId(),now);var clients=rows(c,"select opportunity_participation_id from opportunity.opportunity_participation where tenant_id=? and opportunity_id=? and participation_set_revision=? and context_role_code='CLIENT' order by participation_no",tenant,oid,q.get("participation_set_revision"));if(!(v.get("recipientParticipation") instanceof Map<?,?> selected)||integer(selected.get("revision"))!=0)throw new IllegalArgumentException("Exact recipient participation required");var client=clients.stream().filter(candidate->Objects.equals(candidate.get("opportunity_participation_id"),uuid(selected.get("id")))).findFirst().orElseThrow(()->new Blocked("STALE_SUBJECT"));sql(c,"insert into opportunity.quote_issue(tenant_id,quote_issue_id,quote_revision_id,recipient_participation_id,recipient_context_digest,authorization_set_digest,delivery_channel_code,issued_at,issue_status_code,revision,created_at,delivery_fact_type,delivery_fact_id,delivery_fact_revision) values(?,?,?,?,?,?,?,?,'ACTIVE',0,?,'opportunity.quote_manual_delivery',?,0)",tenant,issue,qid,client.get("opportunity_participation_id"),QuoteCanonicalJson.digest(recipient),authDigest,channel,occurred,now,mid);var fact=exact("opportunity.quote_issue",issue);tasks.complete(c,tenant,task(c,tenant,w),fact,now);var next=create(c,tenant,"RECORD_QUOTE_REPLY",owner.appointmentId(),opportunity(r),now);transition(c,tenant,oid,qid,w,"AWAIT_REPLY",owner.appointmentId(),next,null,null,now);return fact;
 }
 private Subject respond(Connection c,Actor actor,Map<String,Object> r,OpportunityResponsibilityReader.Responsibility owner,Map<String,Object> q,Map<String,Object> w,String stage,Map<String,Object> v,Instant now)throws SQLException{
  requireStage(stage,"AWAIT_REPLY","FOLLOW_UP","CLARIFY_REPLY");UUID tenant=actor.tenantId(),oid=uuid(r.get("opportunity_id")),qid=uuid(q.get("quote_revision_id"));var issue=row(c,"select * from opportunity.quote_issue where tenant_id=? and quote_revision_id=? and issue_status_code='ACTIVE'",tenant,qid);if(issue==null)throw stale();var e=evidence(c,tenant,oid,v.get("evidence"));var reply=new QuoteReply(QuoteReply.Kind.valueOf((String)v.get("kind")),qid,uuid(issue.get("quote_issue_id")),e.selector().id(),(String)v.get("statement"),instant(v.get("occurredAt")),instant(v.get("nextCheckAt")));reply.validate(qid,uuid(issue.get("quote_issue_id")),instant(issue.get("issued_at")),instant(q.get("valid_until")),now);var current=task(c,tenant,w);if(current==null||!Set.of("OPEN","WAITING").contains(current.state()))throw new Blocked("STALE_TASK");UUID id=id(c);String clear=codec.encode(v);byte[] digest=QuoteCanonicalJson.digest(clear);var seq=row(c,"select coalesce(max(response_no),0)+1 n from opportunity.quote_response where tenant_id=? and quote_issue_id=?",tenant,issue.get("quote_issue_id"));sql(c,"insert into opportunity.quote_response(tenant_id,quote_response_id,quote_issue_id,response_no,response_code,response_content_ciphertext,response_content_digest,evidence_submission_id,recorded_by_appointment_id,received_at,created_at) values(?,?,?,?,?,?,?,?,?,?,?)",tenant,id,issue.get("quote_issue_id"),seq.get("n"),reply.kind().name(),protection.encryptQuote(tenant,oid,id,false,clear),digest,e.submission(),actor.appointmentId(),reply.occurredAt(),now);sql(c,"insert into opportunity.quote_response_basis(tenant_id,quote_response_basis_id,revision,quote_response_id,material_version_id,next_check_at) values(?,?,0,?,?,?)",tenant,id,id,e.selector().id(),reply.nextCheckAt());var fact=new Subject("opportunity.quote_response",id,null,Base64.getUrlEncoder().withoutPadding().encodeToString(digest));tasks.complete(c,tenant,current,fact,now);
  String nextStage=switch(reply.kind()){case ACCEPTED->"ACCEPTED";case NOT_ACCEPTED->"FOLLOW_UP";case REJECTED->"SALES_DISPOSITION";case AMBIGUOUS->"CLARIFY_REPLY";};Task next=null;if(reply.kind()==QuoteReply.Kind.ACCEPTED){sql(c,"insert into opportunity.contract_preparation_source(tenant_id,contract_preparation_source_id,revision,opportunity_id,quote_response_id,source_kind,created_at) values(?,?,0,?,?,'ACCEPTED_QUOTE',?)",tenant,id(c),oid,id,now);if(permitted(c,actor,owner.appointmentId(),oid,"CONTRACT_PREPARE"))next=create(c,tenant,"PREPARE_CONTRACT",owner.appointmentId(),opportunity(r),now);}else{next=create(c,tenant,reply.kind()==QuoteReply.Kind.REJECTED?"PREPARE_QUOTE":"RECORD_QUOTE_REPLY",owner.appointmentId(),opportunity(r),now);if(reply.kind()!=QuoteReply.Kind.REJECTED){tasks.waitUntil(c,tenant,next,actor.appointmentId(),reply.nextCheckAt(),now,fact);next=tasks.read(c,tenant,next.selector().id());}}
  transition(c,tenant,oid,qid,w,nextStage,owner.appointmentId(),next,current.selector().id(),reply.nextCheckAt(),now);return fact;
 }
}
