package io.github.windyzhu3.ontologylaw.opportunity.internal.persistence;
import io.github.windyzhu3.ontologylaw.opportunity.OpportunityMaterials;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.sql.*;import java.time.*;import java.util.*;
public final class JdbcOpportunityMaterials implements OpportunityMaterials {
 public List<Version> currentVersions(Connection c,UUID tenant,UUID opportunity,int limit)throws SQLException{
  if(limit<1||limit>51)throw new IllegalArgumentException("Invalid bound");
  return OpportunityReadRows.rows(c,"select v.* from opportunity.material_version v where v.tenant_id=? and v.opportunity_id=? and not exists(select 1 from opportunity.material_version n where n.tenant_id=v.tenant_id and n.opportunity_id=v.opportunity_id and n.previous_version_id=v.material_version_id) order by v.received_at desc,v.material_version_id desc limit ?",tenant,opportunity,limit).stream().map(JdbcOpportunityMaterials::row).toList();
 }
 private static Version row(Map<String,Object> r){var prev=(UUID)r.get("previous_version_id");return new Version(new Subject(VERSION,(UUID)r.get("material_version_id"),0L,null),(UUID)r.get("opportunity_id"),(UUID)r.get("material_item_id"),prev==null?null:new Subject(VERSION,prev,0L,null),(UUID)r.get("upload_basis_id"),(UUID)r.get("received_source_object_id"),(UUID)r.get("evidence_submission_id"),(UUID)r.get("evidence_binding_id"),(String)r.get("purpose_code"),(UUID)r.get("received_by_appointment_id"),OpportunityReadRows.instant(r.get("received_at")));}
 public Version version(Connection c,UUID tenant,UUID id)throws SQLException{var r=OpportunityReadRows.row(c,"select * from opportunity.material_version where tenant_id=? and material_version_id=?",tenant,id);return r==null?null:row(r);}
 public List<Version> history(Connection c,UUID tenant,UUID opportunity)throws SQLException{return OpportunityReadRows.rows(c,"select * from opportunity.material_version where tenant_id=? and opportunity_id=? order by received_at desc,material_version_id desc",tenant,opportunity).stream().map(JdbcOpportunityMaterials::row).toList();}
 public boolean current(Connection c,UUID tenant,UUID id)throws SQLException{return Boolean.TRUE.equals(OpportunityReadRows.row(c,"select not exists(select 1 from opportunity.material_version where tenant_id=? and previous_version_id=?) as current",tenant,id).get("current"));}
 public Version accept(Connection c,UUID tenant,UUID opportunity,UUID previous,UUID upload,UUID source,UUID submission,UUID binding,String purpose,UUID actor,Instant at,byte[] ciphertext,byte[] digest)throws SQLException{OpportunityReadRows.requireCommandScope();var id=UUID.randomUUID();UUID item=id;if(previous!=null){var old=version(c,tenant,previous);if(old==null||!old.opportunity().equals(opportunity)||!old.purpose().equals(purpose)||!current(c,tenant,previous))throw new SQLException("Stale material predecessor","40001");item=old.item();}try(var p=c.prepareStatement("insert into opportunity.material_version(tenant_id,material_version_id,revision,material_item_id,previous_version_id,upload_basis_id,upload_session_id,received_source_object_id,evidence_submission_id,evidence_binding_id,opportunity_id,purpose_code,body_ciphertext,body_digest,received_by_appointment_id,received_at) values(?,?,0,?,?,?,?,?,?,?,?,?,?,?,?,?)")){Object[] values={tenant,id,item,previous,upload,upload,source,submission,binding,opportunity,purpose,ciphertext,digest,actor,OffsetDateTime.ofInstant(at,ZoneOffset.UTC)};for(int i=0;i<values.length;i++)p.setObject(i+1,values[i]);p.executeUpdate();}return version(c,tenant,id);}
}

