package io.github.windyzhu3.ontologylaw.opportunity.internal.persistence;
import io.github.windyzhu3.ontologylaw.opportunity.*;

import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;

import java.sql.*;import java.time.*;import java.util.*;import java.security.MessageDigest;
public final class JdbcOpportunityCustomerRequirements implements OpportunityCustomerRequirementsService {
 private final OpportunityProgressProtection cipher;private final Codec codec;
 public JdbcOpportunityCustomerRequirements(OpportunityProgressProtection cipher,Codec codec){this.cipher=Objects.requireNonNull(cipher);this.codec=Objects.requireNonNull(codec);}
 private static String table(Subject s){if(s==null||!Long.valueOf(0).equals(s.revision())||!Set.of(DRAFT,CONFIRMATION).contains(s.type()))throw new IllegalArgumentException("Exact customer version required");return s.type();}
 private static String idColumn(String table){return table.substring(table.indexOf('.')+1)+"_id";}
 private static Metadata row(ResultSet r,String table)throws SQLException{boolean draft=table.equals(DRAFT);var prior=r.getObject(draft?"previous_draft_id":"previous_confirmation_id",UUID.class);return new Metadata(new Subject(table,r.getObject(idColumn(table),UUID.class),0L,null),new Subject("opportunity.opportunity",r.getObject("opportunity_id",UUID.class),r.getLong("opportunity_revision"),null),new Subject(r.getString("responsibility_type"),r.getObject("responsibility_id",UUID.class),r.getLong("responsibility_revision"),null),r.getObject("owner_appointment_id",UUID.class),draft?null:new Subject(DRAFT,r.getObject("draft_id",UUID.class),0L,null),prior==null?null:new Subject(table,prior,0L,null),r.getObject(draft?"created_at":"confirmed_at",OffsetDateTime.class).toInstant());}
 private static Metadata row(Map<String,Object> r,String table){boolean draft=table.equals(DRAFT);var prior=(UUID)r.get(draft?"previous_draft_id":"previous_confirmation_id");return new Metadata(new Subject(table,(UUID)r.get(idColumn(table)),0L,null),new Subject("opportunity.opportunity",(UUID)r.get("opportunity_id"),((Number)r.get("opportunity_revision")).longValue(),null),new Subject((String)r.get("responsibility_type"),(UUID)r.get("responsibility_id"),((Number)r.get("responsibility_revision")).longValue(),null),(UUID)r.get("owner_appointment_id"),draft?null:new Subject(DRAFT,(UUID)r.get("draft_id"),0L,null),prior==null?null:new Subject(table,prior,0L,null),OpportunityReadRows.instant(r.get(draft?"created_at":"confirmed_at")));}
 public static Metadata metadata(Connection c,UUID tenant,Subject exact)throws SQLException{String t=table(exact);var r=OpportunityReadRows.row(c,"select * from "+t+" where tenant_id=? and "+idColumn(t)+"=?",tenant,exact.id());return r==null?null:row(r,t);}
 public Metadata latestDraft(Connection c,UUID tenant,UUID opportunity,Subject basis,UUID owner)throws SQLException{try(var p=c.prepareStatement("select * from "+DRAFT+" where tenant_id=? and opportunity_id=? and responsibility_type=? and responsibility_id=? and responsibility_revision=? and owner_appointment_id=? order by created_at desc,customer_requirement_draft_id desc limit 1")){Object[] a={tenant,opportunity,basis.type(),basis.id(),basis.revision(),owner};for(int i=0;i<a.length;i++)p.setObject(i+1,a[i]);try(var r=p.executeQuery()){return r.next()?row(r,DRAFT):null;}}}
 public List<Metadata> history(Connection c,UUID tenant,UUID opportunity)throws SQLException{return OpportunityReadRows.rows(c,"select * from "+CONFIRMATION+" where tenant_id=? and opportunity_id=? order by confirmed_at desc,customer_requirement_confirmation_id desc limit 100",tenant,opportunity).stream().map(r->row(r,CONFIRMATION)).toList();}
 @SuppressWarnings("unchecked") public Version read(Connection c,UUID tenant,Subject exact)throws SQLException{String t=table(exact);var r=OpportunityReadRows.row(c,"select * from "+t+" where tenant_id=? and "+idColumn(t)+"=?",tenant,exact.id());if(r==null)return null;var m=row(r,t);String clear;try{clear=cipher.decryptCustomerRequirements(tenant,m.opportunity().id(),exact.id(),t.equals(DRAFT),(byte[])r.get("body_ciphertext"));if(!MessageDigest.isEqual(digest(clear),(byte[])r.get("body_digest")))throw new IllegalArgumentException();var body=codec.decode(clear);var snapshots=new ArrayList<Snapshot>();for(var obj:(List<Map<String,Object>>)body.get("partySnapshots")){var ref=(Map<String,Object>)obj.get("selector");snapshots.add(new Snapshot(new Subject("party.party",UUID.fromString((String)ref.get("id")),((Number)ref.get("revision")).longValue(),null),(String)obj.get("kind"),(String)obj.get("name")));}var lead=(Map<String,Object>)body.get("sourceLead");return new Version(m,(Map<String,Object>)body.get("document"),List.copyOf(snapshots),new Subject("lead.lead",UUID.fromString((String)lead.get("id")),((Number)lead.get("revision")).longValue(),null));}catch(RuntimeException invalid){throw new SQLException("Invalid protected customer version","22000");}}
 public Metadata save(Connection c,UUID tenant,Input in,Subject lead,List<Snapshot> snapshots)throws SQLException{validate(c,tenant,in);CustomerRequirementDocument.validate(in.document(),false);var m=insert(c,tenant,in,DRAFT,in.document(),snapshots,lead);for(var ref:snapshots){try(var p=c.prepareStatement("insert into opportunity.customer_requirement_draft_party(tenant_id,customer_requirement_draft_party_id,revision,draft_id,party_id,party_revision) values(?,?,0,?,?,?)")){p.setObject(1,tenant);p.setObject(2,UUID.randomUUID());p.setObject(3,m.selector().id());p.setObject(4,ref.selector().id());p.setLong(5,ref.selector().revision());p.executeUpdate();}}return m;}
 public Metadata confirm(Connection c,UUID tenant,Input in,Map<String,Object> document,List<Participant> participants,Subject lead)throws SQLException{validate(c,tenant,in);if(in.expectedDraft()==null)throw new Blocked("STALE_DRAFT");var draft=metadata(c,tenant,in.expectedDraft());if(draft==null||!draft.opportunity().equals(in.opportunity())||!draft.responsibility().equals(in.responsibility())||!draft.owner().equals(in.owner()))throw new Blocked("STALE_DRAFT");CustomerRequirementDocument.validate(document,true);var m=insert(c,tenant,in,CONFIRMATION,document,participants.stream().map(p->p.party()).toList(),lead);for(var p:participants){try(var q=c.prepareStatement("insert into opportunity.customer_requirement_participant(tenant_id,customer_requirement_participant_id,revision,confirmation_id,party_id,party_revision,role,profile_version_id) values(?,?,0,?,?,?,?,?)")){Object[] a={tenant,UUID.randomUUID(),m.selector().id(),p.party().selector().id(),p.party().selector().revision(),p.role(),p.profileVersion().id()};for(int i=0;i<a.length;i++)q.setObject(i+1,a[i]);q.executeUpdate();}}return m;}
 private void validate(Connection c,UUID tenant,Input in)throws SQLException{OpportunityReadRows.requireCommandScope();if(c.getAutoCommit()||c.getTransactionIsolation()!=Connection.TRANSACTION_READ_COMMITTED)throw new SQLException("Customer versions require transaction","25001");OpportunityCommandReader.databaseBacked(cipher).lock(c,tenant,in.opportunity().id());var h=OpportunityCommandReader.databaseBacked(cipher).header(c,tenant,in.opportunity().id());if(h==null||!h.selector().equals(in.opportunity()))throw new Blocked("STALE_SUBJECT");if(h.closed())throw new Blocked("OPPORTUNITY_CLOSED");var owner=OpportunityResponsibilityReader.databaseBacked().current(c,tenant,h.selector());if(!owner.basis().equals(in.responsibility())||!owner.appointmentId().equals(in.owner()))throw new Blocked("STALE_SUBJECT");var latest=latestDraft(c,tenant,in.opportunity().id(),in.responsibility(),in.owner());if(!Objects.equals(latest==null?null:latest.selector(),in.expectedDraft()))throw new Blocked("STALE_DRAFT");var history=history(c,tenant,in.opportunity().id());if(!Objects.equals(history.isEmpty()?null:history.getFirst().selector(),in.expectedConfirmation()))throw new Blocked("STALE_SUBJECT");}
 private Metadata insert(Connection c,UUID tenant,Input in,String t,Map<String,Object> document,List<Snapshot> snapshots,Subject lead)throws SQLException{boolean draft=t.equals(DRAFT);var id=UUID.randomUUID();var body=codec.encode(Map.of("document",document,"partySnapshots",snapshots.stream().map(p->Map.of("selector",selector(p.selector()),"kind",p.kind(),"name",p.name())).toList(),"sourceLead",selector(lead)));var values=new ArrayList<Object>(Arrays.asList(tenant,id,in.opportunity().id(),in.opportunity().revision(),in.responsibility().type(),in.responsibility().id(),in.responsibility().revision(),in.owner()));if(!draft)values.add(in.expectedDraft().id());var previous=draft?in.expectedDraft():in.expectedConfirmation();values.add(previous==null?null:previous.id());values.add(cipher.encryptCustomerRequirements(tenant,in.opportunity().id(),id,draft,body));values.add(digest(body));String cols=draft?"previous_draft_id":"draft_id,previous_confirmation_id";try(var p=c.prepareStatement("insert into "+t+"(tenant_id,"+idColumn(t)+",revision,opportunity_id,opportunity_revision,responsibility_type,responsibility_id,responsibility_revision,owner_appointment_id,"+cols+",body_ciphertext,body_digest,"+(draft?"created_at":"confirmed_at")+") values(?,?,0,"+String.join(",",Collections.nCopies(values.size()-2,"?"))+",clock_timestamp())")){for(int i=0;i<values.size();i++)p.setObject(i+1,values.get(i));p.executeUpdate();}return metadata(c,tenant,new Subject(t,id,0L,null));}
 public List<Subject> participants(Connection c,UUID tenant,Subject confirmation)throws SQLException{
  var out=new LinkedHashSet<Subject>();
  if(DRAFT.equals(confirmation.type())){
   for(var r:OpportunityReadRows.rows(c,"select customer_requirement_draft_party_id,party_id,party_revision from opportunity.customer_requirement_draft_party where tenant_id=? and draft_id=? order by party_id",tenant,confirmation.id())){out.add(new Subject("opportunity.customer_requirement_draft_party",(UUID)r.get("customer_requirement_draft_party_id"),0L,null));out.add(new Subject("party.party",(UUID)r.get("party_id"),((Number)r.get("party_revision")).longValue(),null));}
  }else for(var r:OpportunityReadRows.rows(c,"select customer_requirement_participant_id,party_id,party_revision,profile_version_id from opportunity.customer_requirement_participant where tenant_id=? and confirmation_id=? order by party_id,role",tenant,confirmation.id())){out.add(new Subject("opportunity.customer_requirement_participant",(UUID)r.get("customer_requirement_participant_id"),0L,null));out.add(new Subject("party.party",(UUID)r.get("party_id"),((Number)r.get("party_revision")).longValue(),null));out.add(new Subject("party.profile_version",(UUID)r.get("profile_version_id"),0L,null));}
  return List.copyOf(out);
 }
 private static byte[] digest(String value){try{return java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8));}catch(java.security.NoSuchAlgorithmException impossible){throw new IllegalStateException(impossible);}}
 private static Map<String,Object> selector(Subject s){return Map.of("id",s.id().toString(),"revision",s.revision());}
}
