package io.github.windyzhu3.ontologylaw.identity;

import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppointmentCommandsIT extends IdentityAdminFixture {
    @org.junit.jupiter.params.ParameterizedTest @org.junit.jupiter.params.provider.ValueSource(strings={"OPEN","WAITING"}) void open_responsibility_prevents_end_and_preserves_exact_task_and_identity_facts(String state)throws Exception {
        UUID app=appointment(principal(),organization()),task=UUID.randomUUID();
        mutate("insert into responsibility.task_occurrence (tenant_id,task_occurrence_id,owner_appointment_id,business_purpose_code,primary_command_code,expected_completion_fact_type,original_sla_code,original_sla_seconds,original_sla_due_at,state,created_at,subject_type,subject_id,subject_revision) values (?,?,?,'CONTACT_LEAD','RECORD_CONTACT_RESULT','lead.lead_contact_result','R1_CONTACT_30M_V1',1800,clock_timestamp()+interval '30 minutes','OPEN',clock_timestamp(),'lead.lead',?,0)",seed.tenant(),task,app,UUID.randomUUID());
        if(state.equals("WAITING"))mutate("update responsibility.task_occurrence set state='WAITING',revision=revision+1 where tenant_id=? and task_occurrence_id=?",seed.tenant(),task);
        var before=counts();rejected("IDENTITY_RESPONSIBILITY_DEPENDENCY",change("END_APPOINTMENT",app));delta(before,-1);assertEquals("ACTIVE",scalar("select state from identity.appointment where tenant_id=? and appointment_id=?",seed.tenant(),app));assertEquals(state,scalar("select state from responsibility.task_occurrence where tenant_id=? and task_occurrence_id=?",seed.tenant(),task));
    }
    @Test void appointment_lifecycle_does_not_grant_authority_or_mutate_frozen_term()throws Exception {UUID p=principal(),org=organization();var before=counts();UUID app=appointment(p,org);delta(before,2);String frozen=scalar("select principal_id||'/'||organization_unit_id||'/'||role_code||'/'||effective_from from identity.appointment where tenant_id=? and appointment_id=?",seed.tenant(),app);success(change("SUSPEND_APPOINTMENT",app));success(change("RESUME_APPOINTMENT",app));success(change("END_APPOINTMENT",app));rejected("IDENTITY_STATE_CONFLICT",change("END_APPOINTMENT",app));rejected("IDENTITY_STATE_CONFLICT",change("RESUME_APPOINTMENT",app));assertEquals(frozen,scalar("select principal_id||'/'||organization_unit_id||'/'||role_code||'/'||effective_from from identity.appointment where tenant_id=? and appointment_id=?",seed.tenant(),app));assertEquals("0",scalar("select count(*) from identity.authority_grant where tenant_id=? and grantee_appointment_id=?",seed.tenant(),app));}
    @Test void end_own_appointment_or_suspend_last_founder_is_refused()throws Exception {rejected("IDENTITY_SELF_LOCKOUT",change("END_APPOINTMENT",seed.appointment()));rejected("IDENTITY_LAST_ADMIN",change("SUSPEND_APPOINTMENT",seed.appointment()));}
    @Test void malformed_missing_null_end_or_frozen_fields_never_occupy_a_slot()throws Exception {UUID p=principal(),org=organization();var before=counts();assertThrows(IdentityCommands.Failure.class,()->execute("CREATE_APPOINTMENT",null,null,Map.of("principalId",p.toString(),"organizationId",org.toString(),"roleCode","CONTACT_OPERATOR","effectiveFrom","2026-01-01T00:00:00Z")));assertThrows(IdentityCommands.Failure.class,()->execute("CREATE_APPOINTMENT",null,null,body("principalId",p.toString(),"organizationId",org.toString(),"roleCode","IDENTITY_ADMIN","effectiveFrom","2026-01-01T00:00:00Z","effectiveUntil",null)));assertEquals(before,counts());}
    @Test void inactive_principal_cannot_receive_new_appointment()throws Exception {UUID p=principal(),org=organization();success(change("SUSPEND_IDENTITY_PRINCIPAL",p));rejected("IDENTITY_STATE_CONFLICT",execute("CREATE_APPOINTMENT",null,null,body("principalId",p.toString(),"organizationId",org.toString(),"roleCode","CONTACT_OPERATOR","effectiveFrom","2026-01-01T00:00:00Z","effectiveUntil",null)));}
}
