package io.github.windyzhu3.ontologylaw.identity;

import io.github.windyzhu3.ontologylaw.execution.*;
import java.util.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class OrganizationCommandsIT extends IdentityAdminFixture {
    @Test void create_rename_close_and_replay_have_exact_metadata_deltas()throws Exception {var before=counts();UUID id=organization();delta(before,1);String tag=tag("RENAME_ORGANIZATION_UNIT",id);success(execute("RENAME_ORGANIZATION_UNIT",id,tag,Map.of("displayName","Renamed")));UUID key=UUID.randomUUID();var reason=Map.<String,Object>of("reasonCode","ADMINISTRATIVE_ACTION");String closingTag=tag("CLOSE_ORGANIZATION_UNIT",id);var closed=execute(key,"CLOSE_ORGANIZATION_UNIT",id,closingTag,reason);success(closed);before=counts();var replay=assertDoesNotThrow(()->execute(key,"CLOSE_ORGANIZATION_UNIT",id,closingTag,reason),"A parent administrator retains current permission after closing its child");assertTrue(replay.replay());assertEquals(before,counts());}
    @Test void child_or_current_appointment_blocks_close_without_partial_state_change()throws Exception {UUID org=organization();success(execute("CREATE_ORGANIZATION_UNIT",null,null,Map.of("parentOrganizationId",org.toString(),"code","NESTED","displayName","Nested")));var before=counts();rejected("IDENTITY_ORGANIZATION_DEPENDENCY",change("CLOSE_ORGANIZATION_UNIT",org));delta(before,-1);UUID staffed=organization();appointment(principal(),staffed);rejected("IDENTITY_ORGANIZATION_DEPENDENCY",change("CLOSE_ORGANIZATION_UNIT",staffed));}
    @Test void unknown_frozen_fields_are_preslot_and_missing_if_match_never_occupies()throws Exception {UUID org=organization();var before=counts();assertThrows(IdentityCommands.Failure.class,()->execute("RENAME_ORGANIZATION_UNIT",org,tag("RENAME_ORGANIZATION_UNIT",org),Map.of("displayName","Rename","code","MOVED")));assertThrows(IdentityCommandRuntime.Precondition.class,()->execute("RENAME_ORGANIZATION_UNIT",org,null,Map.of("displayName","Rename")));assertEquals(before,counts());}
    @Test void local_scope_cannot_create_under_ancestor_or_manage_tenant_principals()throws Exception {UUID local=organization();localGrants(local);var before=counts();assertThrows(IdentityCommands.Failure.class,()->organization());assertThrows(IdentityCommands.Failure.class,()->principal());assertEquals(before,counts());}
    @Test void returned_update_etag_can_be_used_for_the_next_exact_revision()throws Exception {UUID org=organization();var first=execute("RENAME_ORGANIZATION_UNIT",org,tag("RENAME_ORGANIZATION_UNIT",org),Map.of("displayName","First"));success(first);success(execute("RENAME_ORGANIZATION_UNIT",org,first.etag(),Map.of("displayName","Second")));}
    @Test void closed_local_scope_cannot_recover_by_widening_to_its_parent()throws Exception {UUID org=organization();localGrants(org);UUID key=UUID.randomUUID();String tag=tag("CLOSE_ORGANIZATION_UNIT",org);var body=Map.<String,Object>of("reasonCode","ADMINISTRATIVE_ACTION");success(execute(key,"CLOSE_ORGANIZATION_UNIT",org,tag,body));assertThrows(IdentityCommands.Failure.class,()->execute(key,"CLOSE_ORGANIZATION_UNIT",org,tag,body));}
    void localGrants(UUID org)throws Exception {mutate("update identity.authority_grant set state='REVOKED',revoked_at=clock_timestamp(),revocation_reason_code='FIXTURE',revision=revision+1 where tenant_id=?",seed.tenant());for(String code:IdentityCommands.MANAGEMENT)mutate("insert into identity.authority_grant (tenant_id,authority_grant_id,grantee_appointment_id,granted_by_appointment_id,scope_organization_unit_id,authority_code,valid_from,state,created_at) values (?,?,?,?,?,?,clock_timestamp()-interval '1 day','ACTIVE',clock_timestamp())",seed.tenant(),UUID.randomUUID(),seed.appointment(),seed.appointment(),org,code);}
}
