package io.github.windyzhu3.ontologylaw.contract.internal.persistence;

import io.github.windyzhu3.ontologylaw.contract.*;
import io.github.windyzhu3.ontologylaw.contract.ContractWorkflowService.*;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.security.MessageDigest;
import static io.github.windyzhu3.ontologylaw.contract.internal.persistence.JdbcContractWorkflowService.*;

/** Manual evidence is never a signature until an authorized verifier records exact persisted evidence. */
final class JdbcManualSignatureWorkflow {
 static final Set<String> COMMANDS=Set.of("SAVE_CONTRACT_SIGNATURE_DRAFT","CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT","SUBMIT_CONTRACT_SIGNATURE","RECORD_CONTRACT_SIGNATURE_VERIFICATION","ARCHIVE_CONTRACT_SIGNATURE","RETURN_CONTRACT_FOR_REVISION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION");
 static final List<String> TABLES=List.of("signature_arrangement","signature_draft","signature_submission","signature_verification","signature_archive","signature_revision_return","signature_workflow","signature_handoff");
 private final JdbcContractWorkflowService owner; private final Ports ports;private final ContractProtection protection;private final ContractPreparationRepository.Codec codec;
 JdbcManualSignatureWorkflow(JdbcContractWorkflowService owner,Ports ports,ContractProtection protection,ContractPreparationRepository.Codec codec){this.owner=owner;this.ports=ports;this.protection=protection;this.codec=codec;}
 static void requireDigest(String value){if(value==null||!value.matches("[a-f0-9]{64}"))throw new Blocked("VALIDATION_FAILED");}
 static void requireVerification(Map<String,Object> v,boolean signature,boolean seal){for(String key:List.of("contentCorresponds","arrangementComplete","authorityVerified","materialComplete"))if(!Boolean.TRUE.equals(v.get(key)))throw new Blocked("VALIDATION_FAILED");if(signature&&!Boolean.TRUE.equals(v.get("signatureVerified"))||seal&&!Boolean.TRUE.equals(v.get("sealVerified")))throw new Blocked("VALIDATION_FAILED");}
 static void validateValues(String action,Map<String,Object> values){
  var keys=new HashSet<String>(Set.of("expectedSignatureWorkflow","expectedTermination"));
  switch(action){
   case "SAVE_CONTRACT_SIGNATURE_DRAFT"->keys.addAll(Set.of("expectedSignatureDraft","slots","slotNumber","materialVersionId","materialSha256","authorityMaterialVersionId","authorityMaterialSha256","signerName","signedAt","reason"));
   case "CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT"->{keys.addAll(Set.of("slots","humanConfirmed"));if(!Boolean.TRUE.equals(values.get("humanConfirmed")))throw new Blocked("VALIDATION_FAILED");}
   case "SUBMIT_CONTRACT_SIGNATURE"->keys.addAll(Set.of("slotNumber","materialVersionId","materialSha256","authorityMaterialVersionId","authorityMaterialSha256","signerName","signedAt"));
   case "RECORD_CONTRACT_SIGNATURE_VERIFICATION"->keys.addAll(Set.of("decision","reason","contentCorresponds","arrangementComplete","authorityVerified","signatureVerified","sealVerified","materialComplete"));
   case "ARCHIVE_CONTRACT_SIGNATURE"->{keys.addAll(Set.of("materialVersionId","materialSha256","reason","archiveComplete"));if(!Boolean.TRUE.equals(values.get("archiveComplete")))throw new Blocked("VALIDATION_FAILED");}
   case "RETURN_CONTRACT_FOR_REVISION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION"->keys.add("reason");
   default->throw new Blocked("VALIDATION_FAILED");
  }
  if(!keys.containsAll(values.keySet()))throw new Blocked("VALIDATION_FAILED");
  boolean draft=action.equals("SAVE_CONTRACT_SIGNATURE_DRAFT");
  for(String key:List.of("materialVersionId","materialSha256","authorityMaterialVersionId","authorityMaterialSha256","signerName","signedAt","reason","decision"))if(values.containsKey(key)&&(!(values.get(key) instanceof String text)||text.length()>4000))throw new Blocked("VALIDATION_FAILED");
  for(String key:List.of("contentCorresponds","arrangementComplete","authorityVerified","signatureVerified","sealVerified","materialComplete"))if(values.containsKey(key)&&!(values.get(key) instanceof Boolean))throw new Blocked("VALIDATION_FAILED");
  if(values.containsKey("slotNumber")&&!(values.get("slotNumber") instanceof Integer||values.get("slotNumber") instanceof Long))throw new Blocked("VALIDATION_FAILED");
  for(String key:List.of("expectedSignatureWorkflow","expectedSignatureDraft","expectedTermination"))if(values.get(key)!=null){if(!(values.get(key) instanceof Map<?,?> selector)||!selector.keySet().equals(Set.of("id","revision"))||!(selector.get("id") instanceof String)||!(selector.get("revision") instanceof Integer||selector.get("revision") instanceof Long))throw new Blocked("VALIDATION_FAILED");}
  if(values.containsKey("slots")){if(!(values.get("slots") instanceof List<?> slots)||slots.size()>100)throw new Blocked("VALIDATION_FAILED");for(Object raw:slots){if(!(raw instanceof Map<?,?> slot)||!Set.of("slotNumber","partyId","participationId","templateSigningPartyId","authoritySlot","required","signatureRequired","sealRequired","clauseBasis").containsAll(slot.keySet()))throw new Blocked("VALIDATION_FAILED");for(String key:List.of("partyId","participationId","templateSigningPartyId","authoritySlot","clauseBasis"))if(slot.containsKey(key)&&!(Set.of("participationId","templateSigningPartyId").contains(key)&&slot.get(key)==null)&&(!(slot.get(key) instanceof String text)||text.length()>2000))throw new Blocked("VALIDATION_FAILED");for(String key:List.of("required","signatureRequired","sealRequired"))if((!draft||slot.containsKey(key))&&!(slot.get(key) instanceof Boolean))throw new Blocked("VALIDATION_FAILED");if((!draft||slot.containsKey("slotNumber"))&&!(slot.get("slotNumber") instanceof Integer||slot.get("slotNumber") instanceof Long))throw new Blocked("VALIDATION_FAILED");if(!draft&&List.of("partyId","authoritySlot","clauseBasis").stream().anyMatch(key->!(slot.get(key) instanceof String text)||text.isBlank()))throw new Blocked("VALIDATION_FAILED");}}
  var required=switch(action){case "SUBMIT_CONTRACT_SIGNATURE"->List.of("materialVersionId","materialSha256","authorityMaterialVersionId","authorityMaterialSha256","signerName","signedAt");case "RECORD_CONTRACT_SIGNATURE_VERIFICATION"->List.of("decision","reason");case "ARCHIVE_CONTRACT_SIGNATURE"->List.of("materialVersionId","materialSha256","reason");case "RETURN_CONTRACT_FOR_REVISION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION"->List.of("reason");default->List.<String>of();};
  if(required.stream().anyMatch(key->!(values.get(key) instanceof String text)||text.isBlank()))throw new Blocked("VALIDATION_FAILED");
  if(action.equals("SUBMIT_CONTRACT_SIGNATURE"))try{Instant.parse((String)values.get("signedAt"));}catch(java.time.DateTimeException invalid){throw new Blocked("VALIDATION_FAILED");}
 }
 static UUID id(Connection c)throws SQLException{return uuid(row(c,"select uuidv7() id").get("id"));}
 static byte[] digest(String s){requireDigest(s);return HexFormat.of().parseHex(s);}
 static String reason(Map<String,Object> v){return new ContractPreparationRepository.Comment((String)v.get("reason")).value();}
 Map<String,Object> readiness(Connection c,UUID tenant,Map<String,Object> v)throws SQLException{return v==null?null:row(c,"select * from contract.signature_readiness where tenant_id=? and contract_revision_id=?",tenant,v.get("contract_revision_id"));}
 Map<String,Object> workflow(Connection c,UUID tenant,UUID readiness)throws SQLException{return row(c,"select w.* from contract.signature_workflow w where w.tenant_id=? and w.readiness_id=? and not exists(select 1 from contract.signature_workflow n where n.tenant_id=w.tenant_id and n.previous_workflow_id=w.signature_workflow_id)",tenant,readiness);}
 Map<String,Object> body(UUID tenant,UUID oid,String table,Map<String,Object> fact){String clear=protection.open(tenant,oid,uuid(fact.get(table+"_id")),ContractProtection.Kind.SIGNATURE,(byte[])fact.get("body_ciphertext"));if(!MessageDigest.isEqual(ContractCanonicalJson.digest(clear),(byte[])fact.get("body_digest")))throw new IllegalStateException("Signature body integrity failure");return codec.decode(clear);}
 Subject save(Connection c,Actor actor,UUID oid,String table,Map<String,Object> values,Map<String,Object> columns)throws SQLException{UUID id=id(c);String clear=ContractCanonicalJson.encode(values);var all=new LinkedHashMap<String,Object>();all.put("tenant_id",actor.tenantId());all.put(table+"_id",id);all.put("opportunity_id",oid);all.putAll(columns);all.put("body_ciphertext",protection.seal(actor.tenantId(),oid,id,ContractProtection.Kind.SIGNATURE,clear));all.put("body_digest",ContractCanonicalJson.digest(clear));all.put("created_at",ports.now(c));write(c,"insert into contract."+table+"("+String.join(",",all.keySet())+") values("+String.join(",",Collections.nCopies(all.size(),"?"))+")",all.values().toArray());return fact("contract."+table,id);}
 static Map<String,Object> columns(Object...pairs){var m=new LinkedHashMap<String,Object>();for(int i=0;i<pairs.length;i+=2)m.put((String)pairs[i],pairs[i+1]);return m;}
 List<Map<String,Object>> templateParties(Connection c,UUID tenant,Object template)throws SQLException{return rows(c,"select * from contract.template_signing_party where tenant_id=? and template_version_id=? order by template_signing_party_id",tenant,template);}
 List<Subject> templateFacts(Connection c,UUID tenant,Object template)throws SQLException{var out=new ArrayList<Subject>();for(var p:templateParties(c,tenant,template)){out.add(fact("contract.template_signing_party",uuid(p.get("template_signing_party_id"))));out.add(new Subject("party.party",uuid(p.get("party_id")),number(p.get("party_revision")),null));out.add(fact("party.profile_version",uuid(p.get("profile_version_id"))));}return List.copyOf(out);}
 String generationParties(Connection c,UUID tenant,UUID oid,Object template)throws SQLException{var labels=new ArrayList<String>();labels.add(ports.generationParties(c,tenant,oid));for(var party:templateParties(c,tenant,template))labels.add("律所："+ports.signingPartyName(c,tenant,uuid(party.get("profile_version_id"))));return String.join("\n",labels);}
 List<Subject> facts(Connection c,UUID tenant,UUID oid)throws SQLException{var out=new LinkedHashSet<Subject>();out.addAll(referenceFacts(c,tenant,"opportunity_id",oid,TABLES));for(var r:rows(c,"select material_version_id,authority_material_version_id from contract.signature_submission where tenant_id=? and opportunity_id=?",tenant,oid)){out.addAll(ports.documentFacts(c,tenant,uuid(r.get("material_version_id"))));out.addAll(ports.documentFacts(c,tenant,uuid(r.get("authority_material_version_id"))));}for(var r:rows(c,"select material_version_id from contract.signature_archive where tenant_id=? and opportunity_id=?",tenant,oid))out.addAll(ports.documentFacts(c,tenant,uuid(r.get("material_version_id"))));for(var v:rows(c,"select v.template_version_id from contract.contract_revision v join contract.contract r on r.tenant_id=v.tenant_id and r.contract_id=v.contract_id where v.tenant_id=? and r.opportunity_id=?",tenant,oid))for(var p:templateParties(c,tenant,v.get("template_version_id"))){out.add(fact("contract.template_signing_party",uuid(p.get("template_signing_party_id"))));out.add(new Subject("party.party",uuid(p.get("party_id")),number(p.get("party_revision")),null));out.add(fact("party.profile_version",uuid(p.get("profile_version_id"))));}return List.copyOf(out);}
 void current(Connection c,Actor actor,Responsibility responsibility,Subject confirmation,Map<String,Object> root,Map<String,Object> version,Map<String,Object> ready,List<Subject> facts)throws SQLException{
  if(root==null||version==null||ready==null||!Objects.equals(root.get("approved_revision_id"),version.get("contract_revision_id")))throw new Blocked("CONTRACT_VERSION_BASIS_CHANGED");
  var firms=templateParties(c,actor.tenantId(),version.get("template_version_id"));if(firms.isEmpty())throw new Blocked("CONTRACT_TEMPLATE_SIGNING_PARTY_REQUIRED");for(var firm:firms)if(!ports.signingPartyCurrent(c,actor.tenantId(),uuid(firm.get("party_id")),number(firm.get("party_revision"))))throw new Blocked("CONTRACT_VERSION_BASIS_CHANGED");
  owner.requireCurrentVersion(c,actor,responsibility,confirmation,version,facts);owner.requireSource(c,actor.tenantId(),uuid(root.get("opportunity_id")));
  if(!ports.reviewScopeComplete(c,actor.tenantId(),uuid(root.get("opportunity_id"))))throw new Blocked("CONTRACT_REVIEW_REQUIRED");
  var approvals=rows(c,"select q.approver_appointment_id,d.decision_code from contract.revision_approval_requirement q left join contract.revision_approval_decision d on d.tenant_id=q.tenant_id and d.requirement_id=q.revision_approval_requirement_id where q.tenant_id=? and q.contract_revision_id=?",actor.tenantId(),version.get("contract_revision_id"));
  var eligible=ports.eligible(c,actor.tenantId(),responsibility.organization(),facts,"CONTRACT_APPROVE");if(approvals.isEmpty()||approvals.stream().anyMatch(a->!"APPROVED".equals(a.get("decision_code"))||!eligible.contains(uuid(a.get("approver_appointment_id")))))throw new Blocked("CONTRACT_APPROVAL_POLICY_CHANGED");
  var review=row(c,"select d.decided_by_appointment_id,d.decision_code from contract.revision_review_binding b join contract.revision_review_decision d on d.tenant_id=b.tenant_id and d.revision_review_decision_id=b.review_decision_id where b.tenant_id=? and b.revision_review_binding_id=?",actor.tenantId(),ready.get("review_binding_id"));
  var preview=ContractReviewRepository.databaseBacked(protection,codec,ports::blockFinding,ports::reviewScopeComplete).preview(c,actor.tenantId(),uuid(version.get("contract_revision_id")));if(!preview.scopeComplete()||preview.candidateCount()!=0)throw new Blocked("CONTRACT_REVIEW_REQUIRED");
  if(review==null||!Set.of("CLEAR","WAIVED").contains(review.get("decision_code"))||!ports.eligible(c,actor.tenantId(),responsibility.organization(),facts,"CONTRACT_REVIEW").contains(uuid(review.get("decided_by_appointment_id"))))throw new Blocked("CONTRACT_REVIEW_REQUIRED");
 }
 List<String> actions(Connection c,Actor actor,Subject o,Responsibility responsibility,Subject confirmation,Map<String,Object> root,Map<String,Object> version)throws SQLException{
  if(responsibility==null||confirmation==null)return List.of();var ready=readiness(c,actor.tenantId(),version);if(ready==null)return List.of();var w=workflow(c,actor.tenantId(),uuid(ready.get("signature_readiness_id")));if(w==null)return responsibility.owner().equals(actor.appointmentId())&&ports.permitted(c,actor,responsibility.organization(),owner.protectedFacts(c,actor.tenantId(),o.id()),"CONTRACT_PREPARE")?List.of("RETURN_CONTRACT_FOR_REVISION"):List.of();if(w.get("task_id")==null)return "OWNER_EXCEPTION".equals(w.get("stage_code"))&&responsibility.owner().equals(actor.appointmentId())&&ports.permitted(c,actor,responsibility.organization(),owner.protectedFacts(c,actor.tenantId(),o.id()),"CONTRACT_PREPARE")?List.of("RETURN_CONTRACT_FOR_REVISION"):List.of();var task=ports.currentTask(c,actor.tenantId(),uuid(w.get("task_id")));if(task==null||!task.state().equals("OPEN")||!task.owner().equals(actor.appointmentId()))return List.of();String stage=(String)w.get("stage_code");var fs=owner.protectedFacts(c,actor.tenantId(),o.id());String auth=stage.equals("AWAIT_VERIFICATION")||stage.equals("ARCHIVE")?"CONTRACT_SIGNATURE_VERIFY":"CONTRACT_PREPARE";if(!ports.permitted(c,actor,responsibility.organization(),fs,auth))return List.of();
  try{current(c,actor,responsibility,confirmation,root,version,ready,fs);}catch(Blocked|ContractPreparationSources.Unavailable stale){return Set.of("AWAIT_VERIFICATION","ARCHIVE").contains(stage)?List.of("RETURN_CONTRACT_SIGNATURE_FOR_REVISION"):Set.of("ARRANGE","COLLECT","SUPPLEMENT","PARTIAL").contains(stage)?List.of("RETURN_CONTRACT_FOR_REVISION"):List.of();}
  return switch(stage){case "ARRANGE"->List.of("SAVE_CONTRACT_SIGNATURE_DRAFT","CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT","RETURN_CONTRACT_FOR_REVISION");case "COLLECT","SUPPLEMENT","PARTIAL"->List.of("SAVE_CONTRACT_SIGNATURE_DRAFT","SUBMIT_CONTRACT_SIGNATURE","RETURN_CONTRACT_FOR_REVISION");case "AWAIT_VERIFICATION"->List.of("RECORD_CONTRACT_SIGNATURE_VERIFICATION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION");case "ARCHIVE"->List.of("ARCHIVE_CONTRACT_SIGNATURE","RETURN_CONTRACT_SIGNATURE_FOR_REVISION");default->List.of();};
 }
 Map<String,Object> summary(Connection c,Actor actor,Map<String,Object> version)throws SQLException{
  var ready=readiness(c,actor.tenantId(),version);if(ready==null)return null;var w=workflow(c,actor.tenantId(),uuid(ready.get("signature_readiness_id")));var work=new LinkedHashMap<String,Object>();work.put("selector",w==null?null:selector("contract.signature_workflow",w.get("signature_workflow_id")));work.put("stage",w==null?"OWNER_EXCEPTION":w.get("stage_code"));work.put("ownerAppointmentId",w==null||w.get("owner_appointment_id")==null?null:w.get("owner_appointment_id").toString());work.put("dueAt",w==null?null:time(w.get("due_at")).toString());work.put("task",null);if(w!=null&&w.get("task_id")!=null){var task=ports.currentTask(c,actor.tenantId(),uuid(w.get("task_id")));if(task!=null){work.put("task",selector(task.selector()));work.put("ownerAppointmentId",task.owner().toString());}}return Map.of("workflow",work);
 }
 Map<String,Object> context(Connection c,Actor actor,UUID oid,Map<String,Object> version)throws SQLException{
  var ready=readiness(c,actor.tenantId(),version);if(ready==null)return null;UUID tenant=actor.tenantId();var result=new LinkedHashMap<String,Object>();var w=workflow(c,tenant,uuid(ready.get("signature_readiness_id")));var work=new LinkedHashMap<String,Object>();work.put("selector",w==null?null:selector("contract.signature_workflow",w.get("signature_workflow_id")));work.put("stage",w==null?"OWNER_EXCEPTION":w.get("stage_code"));work.put("task",null);work.put("ownerAppointmentId",w==null||w.get("owner_appointment_id")==null?null:w.get("owner_appointment_id").toString());work.put("ownerLabel",w==null||w.get("owner_appointment_id")==null?null:Set.of("AWAIT_VERIFICATION","ARCHIVE").contains(w.get("stage_code"))?"当前授权核验人":"当前销售责任人");work.put("dueAt",w==null||w.get("due_at")==null?null:time(w.get("due_at")).toString());work.put("message",w==null?"签署责任正在可靠接续，请稍后刷新。":"OWNER_EXCEPTION".equals(w.get("stage_code"))?"请有权主管在现有任职与权限管理中恢复签署核验权限；系统将按原期限自动接续。":"SIGNATURE_COMPLETE".equals(w.get("stage_code"))?"签署与归档完成；等待后续执行条件办理能力。":"");if(w!=null&&w.get("task_id")!=null){var task=ports.currentTask(c,tenant,uuid(w.get("task_id")));if(task!=null){work.put("task",selector(task.selector()));work.put("ownerAppointmentId",task.owner().toString());}}
  result.put("workflow",work);var partyLabels=new HashMap<String,Object>();for(var named:ports.signingParties(c,actor,oid))partyLabels.put((String)named.get("id"),named.get("label"));result.put("parties",rows(c,"select contract_participation_id,party_id,context_role_code from contract.contract_participation where tenant_id=? and contract_revision_id=? order by participation_no",tenant,version.get("contract_revision_id")).stream().map(p->Map.of("id",p.get("party_id").toString(),"participationId",p.get("contract_participation_id").toString(),"label",partyLabels.getOrDefault(p.get("party_id").toString(),"已批准参与主体"))).toList());
  var allParties=new ArrayList<Map<String,Object>>();for(Object raw:(List<?>)result.get("parties"))allParties.add(map(raw));for(var party:templateParties(c,tenant,version.get("template_version_id")))allParties.add(Map.of("id",party.get("party_id").toString(),"templateSigningPartyId",party.get("template_signing_party_id").toString(),"label",ports.signingPartyName(c,tenant,uuid(party.get("profile_version_id")))));result.put("parties",allParties);
  if(templateParties(c,tenant,version.get("template_version_id")).isEmpty())work.put("message","本版模板未登记律所签署主体，无法确认完整签署安排。请退回修订并选择已批准签署主体的模板。");
  var arrangement=w==null||w.get("arrangement_id")==null?null:row(c,"select * from contract.signature_arrangement where tenant_id=? and signature_arrangement_id=?",tenant,w.get("arrangement_id"));result.put("arrangements",arrangement==null?List.of():body(tenant,oid,"signature_arrangement",arrangement).get("slots"));
  var draft=row(c,"select d.* from contract.signature_draft d where tenant_id=? and readiness_id=? and not exists(select 1 from contract.signature_draft n where n.tenant_id=d.tenant_id and n.previous_draft_id=d.signature_draft_id)",tenant,ready.get("signature_readiness_id"));result.put("draftSelector",draft==null?null:selector("contract.signature_draft",draft.get("signature_draft_id")));result.put("draft",draft==null||w==null||!Objects.equals(draft.get("arrangement_id"),w.get("arrangement_id"))||time(draft.get("created_at")).isBefore(time(w.get("created_at")))?null:body(tenant,oid,"signature_draft",draft));
  var submissions=new ArrayList<Map<String,Object>>();for(var s:rows(c,"select * from contract.signature_submission where tenant_id=? and arrangement_id=? order by created_at",tenant,w==null?null:w.get("arrangement_id"))){var b=new LinkedHashMap<>(body(tenant,oid,"signature_submission",s));b.put("selector",selector("contract.signature_submission",s.get("signature_submission_id")));var verification=row(c,"select * from contract.signature_verification where tenant_id=? and submission_id=?",tenant,s.get("signature_submission_id"));b.put("decision",verification==null?"PENDING":verification.get("decision_code"));if(verification!=null)b.put("reason",body(tenant,oid,"signature_verification",verification).get("reason"));submissions.add(b);}result.put("submissions",submissions);var handoff=row(c,"select state_code from contract.signature_handoff where tenant_id=? and readiness_id=?",tenant,ready.get("signature_readiness_id"));result.put("handoff",handoff==null?null:Map.of("state",handoff.get("state_code"),"message","签署及归档完成；等待后续执行条件办理能力，尚未确认合同执行。"));return result;
 }
 List<Map<String,Object>> allHistory(Connection c,UUID tenant,UUID oid)throws SQLException{
  var result=new ArrayList<Map<String,Object>>();for(var readiness:rows(c,"select s.signature_readiness_id,v.revision_no from contract.signature_readiness s join contract.contract_revision v on v.tenant_id=s.tenant_id and v.contract_revision_id=s.contract_revision_id join contract.contract r on r.tenant_id=v.tenant_id and r.contract_id=v.contract_id where s.tenant_id=? and r.opportunity_id=? order by v.revision_no",tenant,oid))for(var entry:history(c,tenant,oid,uuid(readiness.get("signature_readiness_id")))){var versioned=new LinkedHashMap<>(entry);versioned.put("label","第 "+readiness.get("revision_no")+" 版 · "+entry.get("label"));result.add(versioned);}result.sort(Comparator.comparing(e->(String)e.get("occurredAt")));return List.copyOf(result);
 }
 List<Map<String,Object>> history(Connection c,UUID tenant,UUID oid,UUID readiness)throws SQLException{
  var entries=new ArrayList<Map<String,Object>>();
  for(var a:rows(c,"select * from contract.signature_arrangement where tenant_id=? and readiness_id=? order by created_at",tenant,readiness)){var e=historyEntry(a,"signature_arrangement","签署安排登记","已按批准正文登记明确签署安排",a.get("registered_by_appointment_id"),"销售登记人");e.put("slots",body(tenant,oid,"signature_arrangement",a).get("slots"));entries.add(e);}
  for(var u:rows(c,"select u.* from contract.signature_submission u join contract.signature_arrangement a on a.tenant_id=u.tenant_id and a.signature_arrangement_id=u.arrangement_id where u.tenant_id=? and a.readiness_id=? order by u.created_at",tenant,readiness)){var b=body(tenant,oid,"signature_submission",u);var e=historyEntry(u,"signature_submission","签署材料提交","第 "+b.get("slotNumber")+" 项材料已提交；等待授权核验",u.get("submitted_by_appointment_id"),"销售提交人");e.putAll(b);e.put("arrangementId",u.get("arrangement_id").toString());entries.add(e);var verification=row(c,"select * from contract.signature_verification where tenant_id=? and submission_id=?",tenant,u.get("signature_submission_id"));if(verification!=null){var v=historyEntry(verification,"signature_verification","授权核验结论",String.valueOf(verification.get("decision_code")),verification.get("verified_by_appointment_id"),"授权核验人");v.put("reason",body(tenant,oid,"signature_verification",verification).get("reason"));v.put("materialVersionId",u.get("material_version_id").toString());v.put("authorityMaterialVersionId",u.get("authority_material_version_id").toString());v.put("submissionId",u.get("signature_submission_id").toString());entries.add(v);}}
  for(var a:rows(c,"select x.* from contract.signature_archive x join contract.signature_arrangement a on a.tenant_id=x.tenant_id and a.signature_arrangement_id=x.arrangement_id where x.tenant_id=? and a.readiness_id=?",tenant,readiness)){var e=historyEntry(a,"signature_archive","完整归档","完整签署材料已归档；等待后续执行条件办理",a.get("archived_by_appointment_id"),"授权归档人");e.putAll(body(tenant,oid,"signature_archive",a));entries.add(e);}
  for(var r:rows(c,"select * from contract.signature_revision_return where tenant_id=? and readiness_id=?",tenant,readiness)){var e=historyEntry(r,"signature_revision_return","签署退回修订","保留旧版签署记录，重新形成合同版本",r.get("created_by_appointment_id"),"退回办理人");e.put("reason",body(tenant,oid,"signature_revision_return",r).get("reason"));entries.add(e);}
  entries.sort(Comparator.comparing(e->(String)e.get("occurredAt")));return List.copyOf(entries);
 }
 Map<String,Object> historyEntry(Map<String,Object> fact,String table,String label,String summary,Object actor,String actorLabel){var e=new LinkedHashMap<String,Object>();e.put("id",fact.get(table+"_id").toString());e.put("label",label);e.put("summary",summary);e.put("occurredAt",time(fact.get("created_at")).toString());e.put("actorAppointmentId",actor.toString());e.put("actorLabel",actorLabel);return e;}
 void material(Connection c,Actor actor,UUID oid,UUID org,List<Subject> fs,UUID id,String sha,String authority)throws SQLException{requireDigest(sha);var selected=ports.documentFacts(c,actor.tenantId(),id);if(selected.stream().noneMatch(f->f.type().equals("opportunity.opportunity")&&f.id().equals(oid)))throw new Blocked("STALE_EVIDENCE");var exact=new ArrayList<>(fs);exact.addAll(selected);if(!ports.permitted(c,actor,org,exact,authority)||!ports.permitted(c,actor,org,exact,"CONTRACT_READ"))throw new Blocked("NOT_AUTHORIZED");if(!ports.documentUsable(c,actor.tenantId(),id,sha))throw new Blocked("STALE_EVIDENCE");}
 ManualSignaturePlan plan(Connection c,UUID tenant,Map<String,Object> version,Map<String,Object> ready,Map<String,Object> arrangement)throws SQLException{
  var binding=row(c,"select * from contract.revision_review_binding where tenant_id=? and revision_review_binding_id=?",tenant,ready.get("review_binding_id"));
  var approvals=rows(c,"select d.revision_approval_decision_id from contract.revision_approval_requirement q join contract.revision_approval_decision d on d.tenant_id=q.tenant_id and d.requirement_id=q.revision_approval_requirement_id where q.tenant_id=? and q.contract_revision_id=? order by q.requirement_code",tenant,version.get("contract_revision_id"));
  var basis=new ManualSignaturePlan.Basis(tenant,uuid(version.get("contract_id")),uuid(version.get("contract_revision_id")),uuid(ready.get("signature_readiness_id")),hex(version.get("body_sha256")),hex(version.get("party_snapshot_digest")),HexFormat.of().formatHex(ContractCanonicalJson.digest(binding.get("revision_review_binding_id").toString())),HexFormat.of().formatHex(ContractCanonicalJson.digest(ContractCanonicalJson.encode(approvals.stream().map(a->a.get("revision_approval_decision_id").toString()).toList()))));
  var b=body(tenant,uuid(arrangement.get("opportunity_id")),"signature_arrangement",arrangement);var slots=new ArrayList<ManualSignaturePlan.Slot>();for(Object raw:(List<?>)b.get("slots")){var s=map(raw);slots.add(new ManualSignaturePlan.Slot(Math.toIntExact(number(s.get("slotNumber"))),uuid(s.get("participationId")!=null?s.get("participationId"):s.get("templateSigningPartyId")),uuid(s.get("partyId")),(String)s.get("authoritySlot"),(Boolean)s.get("required"),(Boolean)s.get("signatureRequired"),(Boolean)s.get("sealRequired"),(String)s.get("clauseBasis")));}return new ManualSignaturePlan(basis,hex(arrangement.get("body_digest")),slots);
 }
 List<ManualSignaturePlan.VerifiedSlot> verified(Connection c,UUID tenant,Map<String,Object> arrangement,ManualSignaturePlan plan)throws SQLException{
  var list=new ArrayList<ManualSignaturePlan.VerifiedSlot>();for(var r:rows(c,"select p.slot_no,s.contract_signature_id,s.signed_content_digest,u.material_sha256,p.signature_required,p.seal_required from contract.signature_plan p join contract.contract_signature s on s.tenant_id=p.tenant_id and s.signature_plan_id=p.signature_plan_id join contract.signature_verification v on v.tenant_id=s.tenant_id and v.signature_verification_id=s.verification_id join contract.signature_submission u on u.tenant_id=v.tenant_id and u.signature_submission_id=v.submission_id where p.tenant_id=? and p.arrangement_id=? and s.revoked_at is null and v.decision_code='VERIFIED' order by p.slot_no",tenant,arrangement.get("signature_arrangement_id")))list.add(new ManualSignaturePlan.VerifiedSlot(plan.digest(),Math.toIntExact(number(r.get("slot_no"))),uuid(r.get("contract_signature_id")),hex(r.get("signed_content_digest")),hex(r.get("material_sha256")),Boolean.TRUE.equals(r.get("signature_required")),Boolean.TRUE.equals(r.get("seal_required"))));return list;
 }
 Subject execute(Connection c,String action,Actor actor,UUID oid,Subject o,Responsibility responsibility,Subject confirmation,Map<String,Object> root,Map<String,Object> version,Map<String,Object> preparation,Map<String,Object> values)throws SQLException{
  validateValues(action,values);UUID tenant=actor.tenantId();var ready=readiness(c,tenant,version);if(ready==null)throw stale();var w=workflow(c,tenant,uuid(ready.get("signature_readiness_id")));expect(values.get("expectedSignatureWorkflow"),w==null?null:fact("contract.signature_workflow",uuid(w.get("signature_workflow_id"))));if(!actions(c,actor,o,responsibility,confirmation,root,version).contains(action))throw new Blocked("NOT_AUTHORIZED");var fs=owner.protectedFacts(c,tenant,oid);boolean returning=Set.of("RETURN_CONTRACT_FOR_REVISION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION").contains(action)||action.equals("RECORD_CONTRACT_SIGNATURE_VERIFICATION")&&"REVISION_REQUIRED".equals(values.get("decision"));if(!returning)current(c,actor,responsibility,confirmation,root,version,ready,fs);else if(root==null||!Objects.equals(root.get("current_revision_id"),ready.get("contract_revision_id")))throw stale();String stage=w==null?"ARRANGE":(String)w.get("stage_code"),next=stage;Subject result;UUID arrangementId=w==null?null:uuid(w.get("arrangement_id")),submissionId=w==null?null:uuid(w.get("submission_id"));var arrangement=arrangementId==null?null:row(c,"select * from contract.signature_arrangement where tenant_id=? and signature_arrangement_id=?",tenant,arrangementId);
  var clean=new LinkedHashMap<>(values);clean.remove("expectedSignatureWorkflow");clean.remove("expectedSignatureDraft");clean.remove("expectedTermination");
  switch(action){
   case "SAVE_CONTRACT_SIGNATURE_DRAFT"->{var prior=row(c,"select d.signature_draft_id from contract.signature_draft d where tenant_id=? and readiness_id=? and not exists(select 1 from contract.signature_draft n where n.tenant_id=d.tenant_id and n.previous_draft_id=d.signature_draft_id)",tenant,ready.get("signature_readiness_id"));expect(values.get("expectedSignatureDraft"),prior==null?null:fact("contract.signature_draft",uuid(prior.get("signature_draft_id"))));return save(c,actor,oid,"signature_draft",clean,columns("readiness_id",ready.get("signature_readiness_id"),"arrangement_id",arrangementId,"previous_draft_id",prior==null?null:prior.get("signature_draft_id"),"saved_by_appointment_id",actor.appointmentId()));}
   case "CONFIRM_CONTRACT_SIGNATURE_ARRANGEMENT"->{var slots=(List<?>)values.get("slots");if(slots==null||slots.isEmpty()||slots.size()>100)throw new Blocked("VALIDATION_FAILED");var participants=rows(c,"select contract_participation_id,party_id from contract.contract_participation where tenant_id=? and contract_revision_id=?",tenant,version.get("contract_revision_id"));var firms=templateParties(c,tenant,version.get("template_version_id"));for(Object raw:slots){var s=map(raw);boolean participation=s.get("participationId")!=null,firm=s.get("templateSigningPartyId")!=null;if(participation==firm)throw new Blocked("VALIDATION_FAILED");boolean matches=participation?participants.stream().anyMatch(p->Objects.equals(p.get("contract_participation_id"),uuid(s.get("participationId")))&&Objects.equals(p.get("party_id"),uuid(s.get("partyId")))):firms.stream().anyMatch(p->Objects.equals(p.get("template_signing_party_id"),uuid(s.get("templateSigningPartyId")))&&Objects.equals(p.get("party_id"),uuid(s.get("partyId"))));if(!matches)throw new Blocked("CONTRACT_VERSION_BASIS_CHANGED");}for(var firm:firms)if(slots.stream().map(JdbcContractWorkflowService::map).noneMatch(s->Objects.equals(uuid(s.get("templateSigningPartyId")),uuid(firm.get("template_signing_party_id")))&&Boolean.TRUE.equals(s.get("required"))))throw new Blocked("SIGNATURE_INCOMPLETE");
    result=save(c,actor,oid,"signature_arrangement",Map.of("slots",slots),columns("readiness_id",ready.get("signature_readiness_id"),"contract_revision_id",version.get("contract_revision_id"),"previous_arrangement_id",arrangementId,"registered_by_appointment_id",actor.appointmentId(),"slot_count",slots.size()));arrangementId=result.id();arrangement=row(c,"select * from contract.signature_arrangement where tenant_id=? and signature_arrangement_id=?",tenant,arrangementId);var plan=plan(c,tenant,version,ready,arrangement);for(var s:plan.slots()){var raw=slots.stream().map(JdbcContractWorkflowService::map).filter(slot->number(slot.get("slotNumber"))==s.number()).findFirst().orElseThrow();write(c,"insert into contract.signature_plan(tenant_id,signature_plan_id,contract_revision_id,slot_no,authority_slot_code,contract_participation_id,template_signing_party_id,signer_party_id,signature_method_code,seal_required,required,signature_required,plan_digest,arrangement_id,created_at) values(?,?,?,?,?,?,?,?,'MANUAL',?,?,?,?,?,clock_timestamp())",tenant,id(c),version.get("contract_revision_id"),s.number(),s.authoritySlot(),uuid(raw.get("participationId")),uuid(raw.get("templateSigningPartyId")),s.partyId(),s.sealRequired(),s.required(),s.signatureRequired(),arrangement.get("body_digest"),arrangementId);}next="COLLECT";submissionId=null;}
   case "SUBMIT_CONTRACT_SIGNATURE"->{var plan=plan(c,tenant,version,ready,arrangement);int slot=Math.toIntExact(number(values.get("slotNumber")));var p=row(c,"select * from contract.signature_plan where tenant_id=? and arrangement_id=? and slot_no=?",tenant,arrangementId,slot);if(p==null||verified(c,tenant,arrangement,plan).stream().anyMatch(s->s.slotNumber()==slot))throw stale();if(stage.equals("SUPPLEMENT")){var previousSubmission=row(c,"select signature_plan_id from contract.signature_submission where tenant_id=? and signature_submission_id=?",tenant,submissionId);if(previousSubmission==null||!Objects.equals(previousSubmission.get("signature_plan_id"),p.get("signature_plan_id")))throw stale();}var input=new ManualSignaturePlan.Submission(plan.basis(),plan.digest(),slot,uuid(values.get("materialVersionId")),(String)values.get("materialSha256"),uuid(values.get("authorityMaterialVersionId")),(String)values.get("authorityMaterialSha256"),(String)values.get("signerName"),Instant.parse((String)values.get("signedAt")));input.requireCurrent(plan,plan.basis(),ports.now(c));material(c,actor,oid,responsibility.organization(),fs,input.materialVersionId(),input.materialSha256(),"CONTRACT_PREPARE");material(c,actor,oid,responsibility.organization(),fs,input.authorityMaterialVersionId(),input.authorityMaterialSha256(),"CONTRACT_PREPARE");result=save(c,actor,oid,"signature_submission",clean,columns("arrangement_id",arrangementId,"signature_plan_id",p.get("signature_plan_id"),"previous_submission_id",stage.equals("SUPPLEMENT")?submissionId:null,"submitted_by_appointment_id",actor.appointmentId(),"material_version_id",input.materialVersionId(),"authority_material_version_id",input.authorityMaterialVersionId(),"material_sha256",digest(input.materialSha256()),"authority_material_sha256",digest(input.authorityMaterialSha256()),"approved_body_sha256",version.get("body_sha256"),"signed_at",input.signedAt()));submissionId=result.id();next="AWAIT_VERIFICATION";}
   case "RECORD_CONTRACT_SIGNATURE_VERIFICATION"->{var submission=row(c,"select * from contract.signature_submission where tenant_id=? and signature_submission_id=?",tenant,submissionId);if(submission==null||!Objects.equals(submission.get("arrangement_id"),arrangementId))throw stale();String decision=(String)values.get("decision");if(!Set.of("VERIFIED","NEED_INFO","ARRANGEMENT_CORRECTION","REVISION_REQUIRED").contains(decision))throw new Blocked("VALIDATION_FAILED");reason(values);var p=row(c,"select * from contract.signature_plan where tenant_id=? and signature_plan_id=?",tenant,submission.get("signature_plan_id"));var plan=plan(c,tenant,version,ready,arrangement);
    if(decision.equals("VERIFIED")){requireVerification(values,(Boolean)p.get("signature_required"),(Boolean)p.get("seal_required"));material(c,actor,oid,responsibility.organization(),fs,uuid(submission.get("material_version_id")),hex(submission.get("material_sha256")),"CONTRACT_SIGNATURE_VERIFY");material(c,actor,oid,responsibility.organization(),fs,uuid(submission.get("authority_material_version_id")),hex(submission.get("authority_material_sha256")),"CONTRACT_SIGNATURE_VERIFY");if(!MessageDigest.isEqual((byte[])submission.get("approved_body_sha256"),(byte[])version.get("body_sha256")))throw stale();}
    result=save(c,actor,oid,"signature_verification",clean,columns("submission_id",submissionId,"verified_by_appointment_id",actor.appointmentId(),"decision_code",decision));
    if(decision.equals("VERIFIED")){var submitted=body(tenant,oid,"signature_submission",submission);write(c,"insert into contract.contract_signature(tenant_id,contract_signature_id,contract_revision_id,signature_plan_id,signature_no,signer_party_id,signer_identity_digest,signer_authority_digest,signed_content_digest,verification_method_code,signed_at,verified_at,created_at,changed_at,verification_id) values(?,?,?,?,1,?,?,?,?,'MANUAL',?,clock_timestamp(),clock_timestamp(),clock_timestamp(),?)",tenant,id(c),version.get("contract_revision_id"),p.get("signature_plan_id"),p.get("signer_party_id"),ContractCanonicalJson.digest((String)submitted.get("signerName")),submission.get("authority_material_sha256"),version.get("body_sha256"),time(submission.get("signed_at")),result.id());next=plan.remainingRequired(verified(c,tenant,arrangement,plan)).isEmpty()?"ARCHIVE":"PARTIAL";}else next=switch(decision){case "NEED_INFO"->"SUPPLEMENT";case "ARRANGEMENT_CORRECTION"->"ARRANGE";default->"REVISION_REQUIRED";};}
   case "ARCHIVE_CONTRACT_SIGNATURE"->{var plan=plan(c,tenant,version,ready,arrangement);if(!plan.remainingRequired(verified(c,tenant,arrangement,plan)).isEmpty())throw new Blocked("SIGNATURE_INCOMPLETE");for(var evidence:rows(c,"select u.* from contract.signature_plan p join contract.contract_signature s on s.tenant_id=p.tenant_id and s.signature_plan_id=p.signature_plan_id join contract.signature_verification v on v.tenant_id=s.tenant_id and v.signature_verification_id=s.verification_id join contract.signature_submission u on u.tenant_id=v.tenant_id and u.signature_submission_id=v.submission_id where p.tenant_id=? and p.arrangement_id=? and p.required and s.revoked_at is null",tenant,arrangementId)){material(c,actor,oid,responsibility.organization(),fs,uuid(evidence.get("material_version_id")),hex(evidence.get("material_sha256")),"CONTRACT_SIGNATURE_VERIFY");material(c,actor,oid,responsibility.organization(),fs,uuid(evidence.get("authority_material_version_id")),hex(evidence.get("authority_material_sha256")),"CONTRACT_SIGNATURE_VERIFY");}UUID material=uuid(values.get("materialVersionId"));material(c,actor,oid,responsibility.organization(),fs,material,(String)values.get("materialSha256"),"CONTRACT_SIGNATURE_VERIFY");reason(values);result=save(c,actor,oid,"signature_archive",clean,columns("arrangement_id",arrangementId,"material_version_id",material,"archived_by_appointment_id",actor.appointmentId()));save(c,actor,oid,"signature_handoff",Map.of("reason","等待后续执行条件办理能力"),columns("readiness_id",ready.get("signature_readiness_id"),"arrangement_id",arrangementId,"archive_id",result.id(),"state_code","AWAITING_EXECUTION_CONDITIONS"));next="SIGNATURE_COMPLETE";}
   case "RETURN_CONTRACT_FOR_REVISION","RETURN_CONTRACT_SIGNATURE_FOR_REVISION"->{reason(values);result=save(c,actor,oid,"signature_revision_return",clean,columns("readiness_id",ready.get("signature_readiness_id"),"contract_revision_id",version.get("contract_revision_id"),"created_by_appointment_id",actor.appointmentId()));next="REVISION_REQUIRED";}
   default->throw new IllegalArgumentException("Unknown signature action");
  }
  advance(c,actor,o,responsibility,ready,w,next,arrangementId,submissionId,result,false);
  if(next.equals("REVISION_REQUIRED"))owner.transition(c,actor,o,responsibility,root,preparation,"RETURNED","PREPARE_CONTRACT",responsibility.owner(),result,action);
  return result;
 }
 String authority(String stage){return Set.of("AWAIT_VERIFICATION","ARCHIVE").contains(stage)?"CONTRACT_SIGNATURE_VERIFY":"CONTRACT_PREPARE";}
 String taskType(String stage){return switch(stage){case "ARRANGE"->"ARRANGE_CONTRACT_SIGNATURE";case "COLLECT","PARTIAL","SUPPLEMENT"->"COLLECT_CONTRACT_SIGNATURE";case "AWAIT_VERIFICATION"->"VERIFY_CONTRACT_SIGNATURE";case "ARCHIVE"->"ARCHIVE_CONTRACT_SIGNATURE";default->null;};}
 UUID qualified(Connection c,UUID tenant,Responsibility responsibility,List<Subject> facts,String stage)throws SQLException{var eligible=ports.eligible(c,tenant,responsibility.organization(),facts,authority(stage));if(authority(stage).equals("CONTRACT_PREPARE"))return eligible.contains(responsibility.owner())?responsibility.owner():null;return eligible.stream().sorted(Comparator.comparing(UUID::toString)).findFirst().orElse(null);}
 Subject advance(Connection c,Actor actor,Subject o,Responsibility responsibility,Map<String,Object> ready,Map<String,Object> previous,String target,UUID arrangement,UUID submission,Subject result,boolean recovery)throws SQLException{
  UUID tenant=actor.tenantId();Instant now=ports.now(c);Task prior=previous==null||previous.get("task_id")==null?null:ports.currentTask(c,tenant,uuid(previous.get("task_id")));if(prior!=null){if(recovery)ports.cancelForContract(c,tenant,prior,"CONTRACT_AUTHORITY_MISSING",now);else{if(!prior.owner().equals(actor.appointmentId())||!prior.state().equals("OPEN"))throw stale();if(result.type().equals("contract.signature_revision_return"))ports.cancelForContract(c,tenant,prior,"CONTRACT_RETURNED",now);else ports.complete(c,tenant,prior,result,now);}}
  Instant due=previous==null?ports.signatureDue(time(ready.get("created_at")),ZoneId.of("Asia/Shanghai")):time(previous.get("due_at"));String type=taskType(target);UUID nextOwner=type==null?null:qualified(c,tenant,responsibility,owner.protectedFacts(c,tenant,o.id()),target);Task next=type==null||nextOwner==null?null:ports.createSignatureTask(c,tenant,type,nextOwner,o,ZoneId.of("Asia/Shanghai"),now,due);UUID newId=id(c);write(c,"insert into contract.signature_workflow(tenant_id,signature_workflow_id,opportunity_id,readiness_id,contract_revision_id,previous_workflow_id,stage_code,owner_appointment_id,task_id,prior_task_id,arrangement_id,submission_id,created_by_appointment_id,due_at,recovery_resume_stage,created_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",tenant,newId,o.id(),ready.get("signature_readiness_id"),ready.get("contract_revision_id"),previous==null?null:previous.get("signature_workflow_id"),type!=null&&nextOwner==null?"OWNER_EXCEPTION":target,nextOwner,next==null?null:next.selector().id(),prior==null?previous==null?null:previous.get("prior_task_id"):prior.selector().id(),arrangement,submission,actor.appointmentId(),due,type!=null&&nextOwner==null?target:null,now);return fact("contract.signature_workflow",newId);
 }
 boolean recoverable(Connection c,UUID tenant,UUID oid,Responsibility responsibility,Map<String,Object> ready,Map<String,Object> w)throws SQLException{if(w==null)return true;String stage=(String)w.get("stage_code");if(stage.equals("OWNER_EXCEPTION"))return qualified(c,tenant,responsibility,owner.protectedFacts(c,tenant,oid),(String)w.get("recovery_resume_stage"))!=null;if(taskType(stage)==null||w.get("task_id")==null)return false;var task=ports.currentTask(c,tenant,uuid(w.get("task_id")));return task!=null&&Set.of("OPEN","WAITING").contains(task.state())&&!ports.eligible(c,tenant,responsibility.organization(),owner.protectedFacts(c,tenant,oid),authority(stage)).contains(task.owner());}
 Subject reconcile(Connection c,Actor actor,Map<String,Object> payload,Subject o,Responsibility responsibility,Subject confirmation,Map<String,Object> root,Map<String,Object> version)throws SQLException{var ready=readiness(c,actor.tenantId(),version);if(ready==null)throw stale();var w=workflow(c,actor.tenantId(),uuid(ready.get("signature_readiness_id")));expect(payload.get("expectedWorkflow"),w==null?null:fact("contract.signature_workflow",uuid(w.get("signature_workflow_id"))));expect(payload.get("source"),w==null?fact("contract.signature_readiness",uuid(ready.get("signature_readiness_id"))):fact("contract.signature_workflow",uuid(w.get("signature_workflow_id"))));var fs=owner.protectedFacts(c,actor.tenantId(),o.id());if(!ports.permitted(c,actor,responsibility.organization(),fs,"CONTRACT_TASK_RECOVER"))throw new Blocked("NOT_AUTHORIZED");current(c,actor,responsibility,confirmation,root,version,ready,fs);if(!recoverable(c,actor.tenantId(),o.id(),responsibility,ready,w))throw stale();String target=w==null?"ARRANGE":"OWNER_EXCEPTION".equals(w.get("stage_code"))?(String)w.get("recovery_resume_stage"):(String)w.get("stage_code");return advance(c,actor,o,responsibility,ready,w,target,w==null?null:uuid(w.get("arrangement_id")),w==null?null:uuid(w.get("submission_id")),fact("contract.signature_readiness",uuid(ready.get("signature_readiness_id"))),true);}
}
