package io.github.windyzhu3.ontologylaw.contract.internal.persistence;
import io.github.windyzhu3.ontologylaw.contract.*;import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.sql.*;import java.util.*;import java.security.MessageDigest;
import static io.github.windyzhu3.ontologylaw.contract.internal.persistence.JdbcContractWorkflowService.*;
/** T08 bounded exact-identity review. No alias/fuzzy matching and no automatic waiver. */
public final class JdbcContractReviewRepository implements ContractReviewRepository {
 private static final String RULE="R2_PARTY_ID_ROLE_CONFLICT_V1";
 private static final byte[] RULE_HASH=ContractCanonicalJson.digest("R2_PARTY_ID_ROLE_CONFLICT_V1|exact party identity across opposing CLIENT and OPPONENT roles|every other opportunity latest participation and every other contract version including transferred matters|same role is not a candidate; OTHER or SIGNER scope or matching corpus role requires more information|human confirmation; no automatic waiver");
 private final ContractProtection protection;private final ContractPreparationRepository.Codec codec;private final BlockingDecision decisions;private final Completeness completeness;
 public JdbcContractReviewRepository(ContractProtection p,ContractPreparationRepository.Codec codec,BlockingDecision decisions,Completeness completeness){this.protection=Objects.requireNonNull(p);this.codec=Objects.requireNonNull(codec);this.decisions=Objects.requireNonNull(decisions);this.completeness=Objects.requireNonNull(completeness);}
 private static void transaction(Connection c)throws SQLException{if(c.getAutoCommit()||c.getTransactionIsolation()!=Connection.TRANSACTION_READ_COMMITTED)throw new IllegalStateException("Review requires READ COMMITTED transaction");}
 private static UUID id(Connection c)throws SQLException{return uuid(row(c,"select uuidv7() id").get("id"));}
 private static String reason(String value){if(value==null||value.isBlank()||value.codePointCount(0,value.length())>4000)throw new IllegalArgumentException("Explicit bounded review reason required");return value;}
 private static Map<String,Object> versionRow(Connection c,UUID tenant,UUID version)throws SQLException{var v=row(c,"select v.*,r.opportunity_id,o.legal_need_digest from contract.contract_revision v join contract.contract r on r.tenant_id=v.tenant_id and r.contract_id=v.contract_id join opportunity.opportunity o on o.tenant_id=r.tenant_id and o.opportunity_id=r.opportunity_id where v.tenant_id=? and v.contract_revision_id=? and r.current_revision_id=v.contract_revision_id and r.contract_execution_id is null and r.contract_termination_id is null for update of r",tenant,version);if(v==null)throw stale();return v;}
 private static List<Map<String,Object>> scope(Connection c,UUID tenant,UUID version)throws SQLException{return rows(c,"select p.contract_participation_id id,p.party_id,p.party_revision,p.party_snapshot_digest,p.context_role_code role from contract.contract_participation p where p.tenant_id=? and p.contract_revision_id=? order by p.participation_no",tenant,version);}
 private static List<Map<String,Object>> canonical(List<Map<String,Object>> rows){return rows.stream().map(r->Map.<String,Object>of("id",r.get("id").toString(),"party",r.get("party_id").toString(),"revision",number(r.get("party_revision")),"hash",hex(r.get("party_snapshot_digest")),"role",r.get("role"))).toList();}
 private static byte[] scopeHash(List<Map<String,Object>> scope){return ContractCanonicalJson.digest(ContractCanonicalJson.encode(Map.of("profile","R2_CONTRACT_REVIEW_SCOPE_V1","parties",canonical(scope))));}
 private static List<Map<String,Object>> corpus(Connection c,UUID tenant,UUID opportunity)throws SQLException{return rows(c,"select p.opportunity_participation_id id,p.party_id,p.party_revision,p.party_snapshot_digest,p.context_role_code role,'opportunity.opportunity_participation' source_type from opportunity.opportunity_participation p where p.tenant_id=? and p.opportunity_id<>? and p.participation_set_revision=(select max(n.participation_set_revision) from opportunity.opportunity_participation n where n.tenant_id=p.tenant_id and n.opportunity_id=p.opportunity_id) union all select p.contract_participation_id,p.party_id,p.party_revision,p.party_snapshot_digest,p.context_role_code,'contract.contract_participation' from contract.contract_participation p join contract.contract_revision v on v.tenant_id=p.tenant_id and v.contract_revision_id=p.contract_revision_id join contract.contract r on r.tenant_id=v.tenant_id and r.contract_id=v.contract_id where p.tenant_id=? and r.opportunity_id<>? order by id",tenant,opportunity,tenant,opportunity);}
 public Preview preview(Connection c,UUID tenant,UUID version)throws SQLException{var v=row(c,"select r.opportunity_id from contract.contract_revision v join contract.contract r on r.tenant_id=v.tenant_id and r.contract_id=v.contract_id where v.tenant_id=? and v.contract_revision_id=? and r.current_revision_id=v.contract_revision_id",tenant,version);if(v==null)throw stale();UUID opportunity=uuid(v.get("opportunity_id"));var parties=scope(c,tenant,version).stream().map(JdbcContractReviewRepository::party).toList();var corpusParties=corpus(c,tenant,opportunity).stream().map(JdbcContractReviewRepository::party).toList();boolean complete=ContractConflictSnapshot.complete(parties,corpusParties,!completeness.complete(c,tenant,opportunity));int count=ContractConflictSnapshot.candidates(parties,corpusParties).size();var outcomes=new ArrayList<String>();outcomes.add("NEED_INFO");if(complete&&count==0)outcomes.add("CLEAR");if(count>0)outcomes.add("BLOCKED");return new Preview(complete,count,outcomes);}
 public Subject request(Connection c,UUID tenant,UUID version,UUID actor,UUID previous,String reason)throws SQLException{transaction(c);reason(reason);var v=versionRow(c,tenant,version);var parties=scope(c,tenant,version);if(parties.isEmpty())throw new ContractWorkflowService.Blocked("CONTRACT_REVIEW_SCOPE_REQUIRED");UUID id=id(c);String clear=codec.encode(Map.of("reason",reason));write(c,"insert into contract.revision_review_request(tenant_id,revision_review_request_id,revision,contract_revision_id,scope_hash,requested_by_appointment_id,previous_request_id,body_ciphertext,body_digest,created_at) values(?,?,0,?,?,?,?,?,?,clock_timestamp())",tenant,id,version,scopeHash(parties),actor,previous,protection.seal(tenant,uuid(v.get("opportunity_id")),id,ContractProtection.Kind.REVIEW,clear),ContractCanonicalJson.digest(clear));return fact("contract.revision_review_request",id);}
 public Subject decide(Connection c,UUID tenant,UUID request,UUID actor,String outcome,String comment)throws SQLException{
  transaction(c);reason(comment);if(!Set.of("CLEAR","NEED_INFO","BLOCKED").contains(outcome))throw new ContractWorkflowService.Blocked("CONTRACT_REVIEW_WAIVER_UNAVAILABLE");var req=row(c,"select * from contract.revision_review_request where tenant_id=? and revision_review_request_id=?",tenant,request);if(req==null)throw stale();UUID version=uuid(req.get("contract_revision_id"));var v=versionRow(c,tenant,version);UUID opportunity=uuid(v.get("opportunity_id"));
  // Caller holds the tenant exclusive business fence before root locks and this complete corpus scan.
  var scope=scope(c,tenant,version);byte[] scopeDigest=scopeHash(scope);if(!MessageDigest.isEqual(scopeDigest,(byte[])req.get("scope_hash")))throw stale();
  var corpus=corpus(c,tenant,opportunity);
  var transferred=rows(c,"select transfer_request_id,matter_id,contract_id,accepted_snapshot_id,revision from transfer.transfer_request where tenant_id=? order by transfer_request_id",tenant).stream().map(r->{var m=new TreeMap<String,Object>();r.forEach((k,val)->m.put(k,val==null?null:val.toString()));return m;}).toList();
  byte[] corpusDigest=ContractCanonicalJson.digest(ContractCanonicalJson.encode(Map.of("profile","R2_CONTRACT_PARTY_CORPUS_V1","parties",canonical(corpus),"transferredMatters",transferred)));
  var scopeParties=scope.stream().map(JdbcContractReviewRepository::party).toList();var corpusParties=corpus.stream().map(JdbcContractReviewRepository::party).toList();var candidates=ContractConflictSnapshot.candidates(scopeParties,corpusParties);
  boolean complete=ContractConflictSnapshot.complete(scopeParties,corpusParties,!completeness.complete(c,tenant,opportunity));if(outcome.equals("CLEAR")&&(!complete||!candidates.isEmpty()))throw new ContractWorkflowService.Blocked("CONTRACT_REVIEW_NOT_CLEAR");if(outcome.equals("BLOCKED")&&candidates.isEmpty())throw new ContractWorkflowService.Blocked("CONTRACT_REVIEW_FINDING_REQUIRED");
  String initial=outcome.equals("NEED_INFO")?"NEED_INFO":candidates.isEmpty()?"CLEAR":"FINDINGS";UUID review=id(c);int findings=initial.equals("FINDINGS")?candidates.size():0;
  write(c,"insert into conflict.conflict_review(tenant_id,conflict_review_id,review_type_code,legal_need_digest,review_contract_code,review_contract_version,scope_hash,rule_set_code,rule_set_revision,rule_set_hash,corpus_code,corpus_revision,corpus_hash,initial_conclusion_code,finding_count,reviewed_at,revision,created_at,trigger_fact_type,trigger_fact_id,trigger_fact_hash) values(?,?,'PRE_CONTRACT',?,'R2_PRE_CONTRACT_ID_REVIEW_V1',1,?,?,1,?,'R2_CONTRACT_PARTY_CORPUS_V1',0,?,?,?,clock_timestamp(),0,clock_timestamp(),'contract.contract_revision',?,?)",tenant,review,v.get("legal_need_digest"),scopeDigest,RULE,RULE_HASH,corpusDigest,initial,findings,version,v.get("content_digest"));
  var partyIds=new HashMap<UUID,UUID>();for(var p:scope){UUID pid=id(c);partyIds.put(uuid(p.get("id")),pid);write(c,"insert into conflict.conflict_review_party(tenant_id,conflict_review_party_id,conflict_review_id,party_id,scope_role_code,party_snapshot_hash,created_at,source_item_type,source_item_id,source_item_hash) values(?,?,?,?,?,?,clock_timestamp(),'contract.contract_participation',?,?)",tenant,pid,review,p.get("party_id"),p.get("role"),p.get("party_snapshot_digest"),p.get("id"),p.get("party_snapshot_digest"));}
  byte[] resolution=null;if(initial.equals("FINDINGS")){var found=new ArrayList<Subject>();int sequence=0;for(var candidate:candidates){var matched=corpus.stream().filter(p->uuid(p.get("id")).equals(candidate.matched().sourceId())).findFirst().orElseThrow();UUID fid=id(c);byte[] digest=ContractCanonicalJson.digest(ContractCanonicalJson.encode(Map.of("review",review.toString(),"scope",candidate.scope().sourceId().toString(),"match",candidate.matched().sourceId().toString(),"rule",RULE)));write(c,"insert into conflict.conflict_finding(tenant_id,conflict_finding_id,conflict_review_id,finding_no,conflict_review_party_id,rule_code,rule_revision,risk_classification_code,finding_summary,finding_digest,created_at,matched_fact_type,matched_fact_id,matched_fact_hash) values(?,?,?,?,?,?,1,'EXACT_OPPOSING_PARTY_ROLE','Exact identity has an opposing role in another protected context',?,clock_timestamp(),?,?,?)",tenant,fid,review,++sequence,partyIds.get(candidate.scope().sourceId()),RULE,digest,matched.get("source_type"),matched.get("id"),matched.get("party_snapshot_digest"));found.add(new Subject("conflict.conflict_finding",fid,null,Base64.getUrlEncoder().withoutPadding().encodeToString(digest)));}
   var decision=decisions.block(c,tenant,opportunity,actor,found.getFirst(),comment);resolution=ContractCanonicalJson.digest(ContractCanonicalJson.encode(Map.of("review",review.toString(),"scope",HexFormat.of().formatHex(scopeDigest),"findings",found.stream().map(f->Map.of("id",f.id().toString(),"hash",f.hash())).toList(),"blockingDecision",Map.of("id",decision.id().toString(),"hash",decision.hash()))));write(c,"update conflict.conflict_review set resolution_code='BLOCKED',resolution_digest=?,resolved_at=clock_timestamp(),revision=revision+1 where tenant_id=? and conflict_review_id=? and revision=0 and resolution_code is null",resolution,tenant,review);
  }else if(initial.equals("CLEAR"))resolution=ContractCanonicalJson.digest("R2_CONTRACT_REVIEW_CLEAR_V1|"+review+"|"+HexFormat.of().formatHex(scopeDigest)+"|"+HexFormat.of().formatHex(RULE_HASH)+"|"+HexFormat.of().formatHex(corpusDigest)+"|"+hex(v.get("content_digest")));
  UUID result=id(c);String clear=codec.encode(Map.of("reason",comment,"scopeComplete",complete,"rule",RULE,"findingCount",findings,"actualCandidateCount",candidates.size()));write(c,"insert into contract.revision_review_decision(tenant_id,revision_review_decision_id,revision,request_id,conflict_review_id,decision_code,scope_hash,resolution_digest,decided_by_appointment_id,body_ciphertext,body_digest,created_at) values(?,?,0,?,?,?,?,?,?,?,?,clock_timestamp())",tenant,result,request,review,outcome,scopeDigest,resolution,actor,protection.seal(tenant,opportunity,result,ContractProtection.Kind.REVIEW,clear),ContractCanonicalJson.digest(clear));
  if(outcome.equals("CLEAR"))write(c,"insert into contract.revision_review_binding(tenant_id,revision_review_binding_id,revision,contract_revision_id,review_decision_id,conflict_review_id,scope_hash,resolution_digest,created_at) values(?,?,0,?,?,?,?,?,clock_timestamp())",tenant,id(c),version,result,review,scopeDigest,resolution);return fact("contract.revision_review_decision",result);
 }
 private static ContractConflictSnapshot.Party party(Map<String,Object> p){return new ContractConflictSnapshot.Party(uuid(p.get("id")),uuid(p.get("party_id")),(String)p.get("role"),hex(p.get("party_snapshot_digest")));}
}
