package io.github.windyzhu3.ontologylaw.execution;
import io.github.windyzhu3.ontologylaw.api.R2QuoteInput;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.*;
import io.github.windyzhu3.ontologylaw.audit.ReceiptRecoveryMetadata;
import java.util.*;import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;
class QuoteScopeTest {
 final Actor actor=new Actor(UUID.randomUUID(),UUID.randomUUID(),UUID.randomUUID(),null,null,PrincipalKind.HUMAN);
 Map<String,Object> payload(){var p=new TreeMap<String,Object>();var id=UUID.randomUUID().toString();p.put("opportunityId",id);p.put("expectedOpportunityRevision",2);p.put("responsibilityBasis",Map.of("id",id,"revision",2));p.put("customerConfirmation",null);p.put("expectedDraft",null);p.put("expectedQuote",Map.of("id",UUID.randomUUID().toString(),"hash",Base64.getUrlEncoder().withoutPadding().encodeToString(new byte[32])));p.put("expectedWorkflow",null);p.put("values",Map.of());return p;}
 CommandEnvelope envelope(Map<String,Object> p){return new CommandEnvelope(CommandEnvelope.Type.FORM_QUOTE,UUID.randomUUID(),UUID.randomUUID(),actor,p);}
 @Test void exactQuoteHashAndWorkflowAreBoundAndRecoveryRoundTrips(){var e=envelope(payload());var b=R2QuoteInput.parse(e).binding();var scope=CommandScope.quotes(e,b);assertNull(scope.taskId());assertEquals(b.quote().hash(),((Map<?,?>)scope.fields().get("quote")).get("hash"));var m=new ReceiptRecoveryMetadata(e.type().name(),Map.of("profile","R1_COMMAND_RECEIPT_RECOVERY_V1","scope",scope.fields(),"binding",Map.of("kind","QUOTES")));assertEquals(scope.fields(),m.quotesScope());var changed=new CommandAuthorizationBinding.Quotes(b.opportunity(),b.basis(),b.confirmation(),b.draft(),b.quote(),new Subject("opportunity.quote_workflow",UUID.randomUUID(),0L,null));assertNotEquals(scope.canonical(),CommandScope.quotes(e,changed).canonical());}
 @Test void rejectUnknownFieldsAndFabricatedQuoteRevision(){var p=payload();p.put("approve",true);assertThrows(CommandHandler.Rejected.class,()->R2QuoteInput.parse(envelope(p)));p.remove("approve");p.put("expectedQuote",Map.of("id",UUID.randomUUID().toString(),"revision",0));assertThrows(CommandHandler.Rejected.class,()->R2QuoteInput.parse(envelope(p)));}
 @Test void serviceAndDelegationNeverAuthorQuoteCommands(){for(var type:CommandEnvelope.Type.values())if(type.quotes()){assertThrows(IllegalArgumentException.class,()->new CommandEnvelope(type,UUID.randomUUID(),UUID.randomUUID(),new Actor(actor.tenantId(),actor.principalId(),actor.appointmentId(),null,null,PrincipalKind.SERVICE),payload()));var e=new CommandEnvelope(type,UUID.randomUUID(),UUID.randomUUID(),new Actor(actor.tenantId(),actor.principalId(),actor.appointmentId(),UUID.randomUUID(),UUID.randomUUID(),PrincipalKind.HUMAN),payload());assertThrows(CommandHandler.Rejected.class,()->R2QuoteInput.parse(e));}}
}
