package io.github.windyzhu3.ontologylaw.testing;

import java.nio.file.*;
import java.security.*;
import java.security.cert.X509Certificate;
import java.util.*;
import javax.net.ssl.*;

/** Real short-lived credentials generated by the pinned JDK, test scope only. */
public final class TlsFixture {
    public final char[] password=UUID.randomUUID().toString().toCharArray();
    private final Path directory;
    public record Key(String alias,Path path,KeyStore store) {}
    public TlsFixture(Path directory){this.directory=directory;}
    public Key key(String alias)throws Exception {
        var path=directory.resolve(alias+".p12");var bin=Path.of(System.getProperty("java.home"),"bin");var keytool=Files.exists(bin.resolve("keytool.exe"))?bin.resolve("keytool.exe"):bin.resolve("keytool");
        var process=new ProcessBuilder(keytool.toString(),"-genkeypair","-alias",alias,"-keystore",path.toString(),"-storepass",new String(password),"-keypass",new String(password),"-dname","CN="+alias,"-keyalg","RSA","-keysize","2048","-validity","2","-ext","SAN=dns:localhost,ip:127.0.0.1","-noprompt").redirectErrorStream(true).start();
        try(var output=process.getInputStream()){output.transferTo(java.io.OutputStream.nullOutputStream());}if(process.waitFor()!=0)throw new IllegalStateException("TEST_KEYTOOL_FAILED");
        var store=KeyStore.getInstance("PKCS12");try(var input=Files.newInputStream(path)){store.load(input,password);}return new Key(alias,path,store);
    }
    public Key trust(String name,Key... trusted)throws Exception {
        var store=KeyStore.getInstance("PKCS12");store.load(null,password);for(var key:trusted)store.setCertificateEntry(key.alias(),key.store().getCertificate(key.alias()));
        var path=directory.resolve(name+".p12");try(var output=Files.newOutputStream(path)){store.store(output,password);}return new Key(name,path,store);
    }
    public SSLContext client(Key key,Key trust)throws Exception {
        KeyManager[] managers=null;if(key!=null){var km=KeyManagerFactory.getInstance(KeyManagerFactory.getDefaultAlgorithm());km.init(key.store(),password);managers=km.getKeyManagers();}
        var tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(trust.store());var context=SSLContext.getInstance("TLS");context.init(managers,tm.getTrustManagers(),null);return context;
    }
    /** Forces presentation so the negative test reaches server trust verification, not client alias filtering. */
    public SSLContext forcedClient(Key key,Key trust)throws Exception {
        var certificates=chain(key);var privateKey=(PrivateKey)key.store().getKey(key.alias(),password);
        var manager=new X509ExtendedKeyManager(){
            public String[] getClientAliases(String type,java.security.Principal[] issuers){return new String[]{key.alias()};}
            public String chooseClientAlias(String[] types,java.security.Principal[] issuers,java.net.Socket socket){return key.alias();}
            public String chooseEngineClientAlias(String[] types,java.security.Principal[] issuers,SSLEngine engine){return key.alias();}
            public String[] getServerAliases(String type,java.security.Principal[] issuers){return null;}
            public String chooseServerAlias(String type,java.security.Principal[] issuers,java.net.Socket socket){return null;}
            public X509Certificate[] getCertificateChain(String alias){return certificates.clone();}
            public PrivateKey getPrivateKey(String alias){return privateKey;}
        };
        var tm=TrustManagerFactory.getInstance(TrustManagerFactory.getDefaultAlgorithm());tm.init(trust.store());var context=SSLContext.getInstance("TLS");context.init(new KeyManager[]{manager},tm.getTrustManagers(),null);return context;
    }
    public String sha256(Key key)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(key.store().getCertificate(key.alias()).getEncoded()));}
    public X509Certificate[] chain(Key key)throws Exception{return new X509Certificate[]{(X509Certificate)key.store().getCertificate(key.alias())};}
}
