package io.github.windyzhu3.ontologylaw.transfer.internal.persistence;
import io.github.windyzhu3.ontologylaw.transfer.TransferWorkflowReader;
import io.github.windyzhu3.ontologylaw.identity.AuthorizationService.Subject;
import java.sql.*;import java.util.UUID;
public final class JdbcTransferWorkflowReader implements TransferWorkflowReader {
 public java.util.List<History> history(Connection c,UUID tenant,UUID request)throws SQLException{
  var result=new java.util.ArrayList<History>();
  for(String table:java.util.List.of("submission","review","intake","classification")){
   String outcome=table.equals("submission")?"'SUBMITTED'":table.equals("classification")?"category_code":"outcome_code";
   try(var p=c.prepareStatement("select "+table+"_id,revision,"+outcome+",created_at from transfer."+table+" where tenant_id=? and transfer_request_id=? order by created_at,"+table+"_id")){p.setObject(1,tenant);p.setObject(2,request);try(var r=p.executeQuery()){while(r.next())result.add(new History(new Subject("transfer."+table,r.getObject(1,UUID.class),r.getLong(2),null),table,r.getString(3),r.getTimestamp(4).toInstant()));}}
  }
  result.sort(java.util.Comparator.comparing(History::occurredAt).thenComparing(h->h.selector().id()));return java.util.List.copyOf(result);
 }
 public ProtectedFact body(Connection c,UUID tenant,Subject fact)throws SQLException{
  if(fact==null||!Long.valueOf(0).equals(fact.revision())||!java.util.Set.of("transfer.submission","transfer.review","transfer.intake","transfer.classification").contains(fact.type()))return null;
  String table=fact.type().substring(9);try(var p=c.prepareStatement("select opportunity_id,body_ciphertext,body_digest from transfer."+table+" where tenant_id=? and "+table+"_id=?")){p.setObject(1,tenant);p.setObject(2,fact.id());try(var r=p.executeQuery()){return r.next()?new ProtectedFact(fact,r.getObject(1,UUID.class),r.getBytes(2),r.getBytes(3)):null;}}
 }
 public java.util.List<ReturnItem> returnItems(Connection c,UUID tenant,State state)throws SQLException{
  if(!"SUPPLEMENT".equals(state.stage()))return java.util.List.of();var result=new java.util.ArrayList<ReturnItem>();
  String sql=state.intake()==null?"select review_return_item_id,requirement_code,null::bytea from transfer.review_return_item where tenant_id=? and review_id=? order by review_return_item_id":"select r.transfer_return_item_id,r.requirement_code,r.item_digest from transfer.transfer_return_item r join transfer.intake i on i.tenant_id=r.tenant_id and i.decision_record_id=r.return_decision_record_id where i.tenant_id=? and i.intake_id=? order by r.item_no";
  try(var p=c.prepareStatement(sql)){p.setObject(1,tenant);p.setObject(2,state.intake()==null?state.review().id():state.intake().id());try(var r=p.executeQuery()){while(r.next()){var fact=state.intake()==null?new Subject("transfer.review_return_item",r.getObject(1,UUID.class),0L,null):new Subject("transfer.transfer_return_item",r.getObject(1,UUID.class),null,java.util.Base64.getUrlEncoder().withoutPadding().encodeToString(r.getBytes(3)));result.add(new ReturnItem(fact,r.getString(2)));}}}return java.util.List.copyOf(result);
 }
 public java.util.List<Subject> facts(Connection c,UUID tenant,UUID request)throws SQLException{
  var result=new java.util.ArrayList<Subject>();for(String table:java.util.List.of("workflow","submission","review","review_return_item","intake","classification"))try(var p=c.prepareStatement("select "+table+"_id,revision from transfer."+table+" where tenant_id=? and transfer_request_id=? order by "+table+"_id")){p.setObject(1,tenant);p.setObject(2,request);try(var r=p.executeQuery()){while(r.next())result.add(new Subject("transfer."+table,r.getObject(1,UUID.class),r.getLong(2),null));}}return java.util.List.copyOf(result);
 }
 public Result result(Connection c,UUID tenant,Subject fact)throws SQLException{
  if(fact!=null&&Long.valueOf(0).equals(fact.revision())&&"transfer.workflow".equals(fact.type())){try(var p=c.prepareStatement("select opportunity_id,transfer_request_id,previous_workflow_id,recorded_by,created_in_transaction=pg_current_xact_id() from transfer.workflow where tenant_id=? and workflow_id=?")){p.setObject(1,tenant);p.setObject(2,fact.id());try(var r=p.executeQuery()){return !r.next()?null:new Result(fact,r.getObject(1,UUID.class),r.getObject(2,UUID.class),fact.id(),r.getObject(3,UUID.class),r.getObject(4,UUID.class),r.getBoolean(5));}}}
  if(fact==null||!Long.valueOf(0).equals(fact.revision())||!java.util.Set.of("transfer.submission","transfer.review","transfer.intake","transfer.classification").contains(fact.type()))return null;String table=fact.type().substring(9);
  try(var p=c.prepareStatement("select f.opportunity_id,f.transfer_request_id,f.workflow_id,w.previous_workflow_id,f.recorded_by,f.created_in_transaction=pg_current_xact_id() from transfer."+table+" f join transfer.workflow w on w.tenant_id=f.tenant_id and w.workflow_id=f.workflow_id where f.tenant_id=? and f."+table+"_id=?")){p.setObject(1,tenant);p.setObject(2,fact.id());try(var r=p.executeQuery()){return !r.next()?null:new Result(fact,r.getObject(1,UUID.class),r.getObject(2,UUID.class),r.getObject(3,UUID.class),r.getObject(4,UUID.class),r.getObject(5,UUID.class),r.getBoolean(6));}}
 }
 private static final String SELECT="select w.workflow_id,w.revision workflow_revision,r.transfer_request_id,r.revision request_revision,w.opportunity_id,o.revision opportunity_revision,r.contract_id,r.from_organization_unit_id,r.to_organization_unit_id,w.stage_code,w.target_stage_code,w.owner_appointment_id,w.task_id,w.submission_id,w.review_id,w.intake_id,w.classification_id,r.matter_id,r.matter_no,c.category_code,c.recipient_appointment_id,w.due_at from transfer.workflow w join transfer.transfer_request r on r.tenant_id=w.tenant_id and r.transfer_request_id=w.transfer_request_id join opportunity.opportunity o on o.tenant_id=w.tenant_id and o.opportunity_id=w.opportunity_id left join transfer.classification c on c.tenant_id=w.tenant_id and c.classification_id=w.classification_id where w.tenant_id=? and ";
 private static final String CURRENT=" and not exists(select 1 from transfer.workflow n where n.tenant_id=w.tenant_id and n.previous_workflow_id=w.workflow_id)";
 public State workflow(Connection c,UUID tenant,UUID workflow)throws SQLException{return read(c,tenant,workflow,"w.workflow_id=?");}
 public State forContract(Connection c,UUID tenant,UUID contract)throws SQLException{return read(c,tenant,contract,"r.contract_id=?"+CURRENT);}
 public java.util.List<State> forOpportunity(Connection c,UUID tenant,UUID opportunity)throws SQLException{var ids=new java.util.ArrayList<UUID>();try(var p=c.prepareStatement("select transfer_request_id from transfer.transfer_request where tenant_id=? and opportunity_id=? order by transfer_request_id")){p.setObject(1,tenant);p.setObject(2,opportunity);try(var r=p.executeQuery()){while(r.next())ids.add(r.getObject(1,UUID.class));}}var states=new java.util.ArrayList<State>();for(var id:ids){var state=current(c,tenant,id);if(state!=null)states.add(state);}return java.util.List.copyOf(states);}
 public State current(Connection c,UUID tenant,UUID request)throws SQLException{return read(c,tenant,request,"w.transfer_request_id=?"+CURRENT);}
 public State forTask(Connection c,UUID tenant,UUID task)throws SQLException{return read(c,tenant,task,"w.task_id=?"+CURRENT);}
 public State lastForTask(Connection c,UUID tenant,UUID task)throws SQLException{return read(c,tenant,task,"w.task_id=? and not exists(select 1 from transfer.workflow n where n.tenant_id=w.tenant_id and n.previous_workflow_id=w.workflow_id and n.task_id=w.task_id)");}
 private static Subject fact(ResultSet r,String column,String type)throws SQLException{UUID id=r.getObject(column,UUID.class);return id==null?null:new Subject("transfer."+type,id,0L,null);}
 private static State read(Connection c,UUID tenant,UUID id,String predicate)throws SQLException{
  try(var p=c.prepareStatement(SELECT+predicate)){p.setObject(1,tenant);p.setObject(2,id);try(var r=p.executeQuery()){if(!r.next())return null;var result=new State(new Subject("transfer.workflow",r.getObject("workflow_id",UUID.class),r.getLong("workflow_revision"),null),new Subject("transfer.transfer_request",r.getObject("transfer_request_id",UUID.class),r.getLong("request_revision"),null),new Subject("opportunity.opportunity",r.getObject("opportunity_id",UUID.class),r.getLong("opportunity_revision"),null),r.getObject("contract_id",UUID.class),r.getObject("from_organization_unit_id",UUID.class),r.getObject("to_organization_unit_id",UUID.class),r.getString("stage_code"),r.getString("target_stage_code"),r.getObject("owner_appointment_id",UUID.class),r.getObject("task_id",UUID.class),fact(r,"submission_id","submission"),fact(r,"review_id","review"),fact(r,"intake_id","intake"),fact(r,"classification_id","classification"),r.getObject("matter_id",UUID.class),r.getString("matter_no"),r.getString("category_code"),r.getObject("recipient_appointment_id",UUID.class),r.getTimestamp("due_at").toInstant());if(r.next())throw new SQLException("Ambiguous transfer responsibility","21000");return result;}}
 }
}
