"""类型化准确引用的静态允许列表。

类型代码统一采用未加引号的 ``schema.table``，Resolver必须按本文件中的准确槽位
选择目标Fact Owner，禁止由请求动态指定表名、Schema或解析器。
"""

APPLICATION_FACT_TYPES = (
    "identity.tenant",
    "identity.principal",
    "identity.organization_unit",
    "identity.appointment",
    "identity.authority_grant",
    "identity.delegation_grant",
    "identity.object_access_grant",
    "audit.audit_entry",
    "responsibility.task_occurrence",
    "responsibility.decision_record",
    "responsibility.wait_receipt",
    "responsibility.action_draft",
    "execution.command_execution_slot",
    "execution.command_receipt",
    "execution.domain_event",
    "execution.domain_event_outbox",
    "external_action.external_action",
    "external_action.external_action_outbox",
    "external_action.provider_inbox",
    "evidence.upload_session",
    "evidence.received_source_object",
    "evidence.evidence_submission",
    "evidence.evidence_binding",
    "party.party",
    "lead.lead",
    "lead.lead_assignment",
    "lead.lead_contact_result",
    "opportunity.opportunity",
    "opportunity.opportunity_participation",
    "opportunity.opportunity_progress",
    "opportunity.quote_revision",
    "opportunity.quote_service_scope",
    "opportunity.quote_line",
    "opportunity.quote_payment_term",
    "opportunity.quote_issue",
    "opportunity.quote_response",
    "conflict.conflict_review",
    "conflict.conflict_review_party",
    "conflict.conflict_finding",
    "contract.contract",
    "contract.contract_revision",
    "contract.contract_participation",
    "contract.contract_fee_term",
    "contract.payment_gate",
    "contract.signature_plan",
    "contract.contract_signature",
    "contract.contract_execution",
    "contract.payment_confirmation",
    "contract.contract_termination",
    "transfer.transfer_request",
    "transfer.transfer_snapshot",
    "transfer.transfer_return_item",
)

BUSINESS_SUBJECT_TYPES = (
    "party.party",
    "lead.lead",
    "lead.lead_assignment",
    "opportunity.opportunity",
    "opportunity.opportunity_participation",
    "opportunity.quote_revision",
    "opportunity.quote_issue",
    "conflict.conflict_review",
    "conflict.conflict_finding",
    "contract.contract",
    "contract.contract_revision",
    "contract.payment_gate",
    "contract.signature_plan",
    "contract.contract_signature",
    "contract.contract_execution",
    "contract.payment_confirmation",
    "contract.contract_termination",
    "transfer.transfer_request",
    "transfer.transfer_snapshot",
    "transfer.transfer_return_item",
    "evidence.evidence_submission",
    "evidence.evidence_binding",
    "responsibility.task_occurrence",
    "responsibility.decision_record",
    "external_action.external_action",
)

RESULT_FACT_TYPES = tuple(
    fact_type
    for fact_type in APPLICATION_FACT_TYPES
    if fact_type not in {
        "audit.audit_entry",
        "execution.command_execution_slot",
        "execution.command_receipt",
        "execution.domain_event",
        "execution.domain_event_outbox",
        "external_action.external_action_outbox",
    }
)

TYPED_REFERENCE_ALLOWED_TARGETS = {
    "identity.object_access_grant.object_subject": BUSINESS_SUBJECT_TYPES,
    "audit.audit_entry.subject": APPLICATION_FACT_TYPES,
    "audit.audit_entry.correction_target": ("audit.audit_entry",),
    "audit.audit_entry.authorization_fact": (
        "identity.appointment",
        "identity.authority_grant",
        "identity.delegation_grant",
        "identity.object_access_grant",
        "responsibility.decision_record",
    ),
    "responsibility.task_occurrence.subject": BUSINESS_SUBJECT_TYPES,
    "responsibility.task_occurrence.completion_fact": RESULT_FACT_TYPES,
    "responsibility.decision_record.decision_subject": BUSINESS_SUBJECT_TYPES,
    "responsibility.wait_receipt.awaited_fact": RESULT_FACT_TYPES,
    "execution.command_receipt.result_fact": RESULT_FACT_TYPES,
    "execution.domain_event.source_fact": RESULT_FACT_TYPES,
    "external_action.external_action.subject": BUSINESS_SUBJECT_TYPES,
    "external_action.external_action.resolution_source": (
        "external_action.provider_inbox",
        "responsibility.decision_record",
    ),
    "evidence.upload_session.target": BUSINESS_SUBJECT_TYPES,
    "evidence.evidence_binding.target": BUSINESS_SUBJECT_TYPES,
    "opportunity.opportunity_progress.source_fact": (
        "lead.lead_contact_result",
        "opportunity.quote_issue",
        "opportunity.quote_response",
        "responsibility.decision_record",
        "external_action.external_action",
        "external_action.provider_inbox",
        "evidence.evidence_submission",
    ),
    "opportunity.quote_issue.delivery_fact": (
        "external_action.external_action",
        "external_action.provider_inbox",
    ),
    "conflict.conflict_review.trigger_fact": (
        "opportunity.quote_revision",
        "opportunity.quote_response",
        "contract.contract_revision",
        "transfer.transfer_request",
        "responsibility.action_draft",
    ),
    "conflict.conflict_review_party.source_item": (
        "party.party",
        "opportunity.opportunity_participation",
        "contract.contract_participation",
        "transfer.transfer_snapshot",
    ),
    "conflict.conflict_finding.matched_fact": (
        "party.party",
        "opportunity.opportunity_participation",
        "contract.contract_participation",
        "conflict.conflict_review_party",
        "transfer.transfer_request",
    ),
    "conflict.conflict_finding.source_fact": (
        "party.party",
        "opportunity.opportunity_participation",
        "contract.contract_participation",
        "transfer.transfer_snapshot",
        "evidence.evidence_submission",
    ),
    "contract.contract.activation_source": (
        "contract.payment_gate",
        "responsibility.decision_record",
    ),
    "transfer.transfer_return_item.required_target": (
        "party.party",
        "evidence.evidence_submission",
        "evidence.evidence_binding",
        "contract.contract_revision",
        "conflict.conflict_review",
        "transfer.transfer_request",
        "transfer.transfer_snapshot",
    ),
}
