import {render,screen,fireEvent,waitFor,act} from '@testing-library/react';
import {it,expect,vi} from 'vitest';
import {TeamManagementPage} from './TeamManagementPage';
import {testSession,selectorId,taskId} from '../../test/fixtures';
const row={id:selectorId,customerLabel:'团队合成客户',purposeLabel:'核对收款',stateLabel:'待办理',ownerLabel:'财务',timeLabel:'今天17:00'};
const detail={id:selectorId,customerLabel:row.customerLabel,facts:[],history:[],nextAction:'核对',action:{kind:'task',label:'前往办理'},taskId,exceptionId:null};
it('rechecks the exact current action before entering the original task',async()=>{const api={list:vi.fn().mockResolvedValue({items:[row],nextCursor:null}),detail:vi.fn().mockResolvedValue(detail)},task=vi.fn();render(<TeamManagementPage session={testSession()} api={api} view="tasks" onView={vi.fn()} onTask={task} onException={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:row.customerLabel}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));await waitFor(()=>expect(task).toHaveBeenCalledWith(taskId));expect(api.detail).toHaveBeenCalledTimes(2);});
it('clears the action if the task changed after selection',async()=>{const api={list:vi.fn().mockResolvedValue({items:[row],nextCursor:null}),detail:vi.fn().mockResolvedValueOnce(detail).mockResolvedValue({...detail,action:null,taskId:null})},task=vi.fn();render(<TeamManagementPage session={testSession()} api={api} view="tasks" onView={vi.fn()} onTask={task} onException={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:row.customerLabel}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));await screen.findByText('当前事项已变化，请重新查询后办理。');expect(task).not.toHaveBeenCalled();});
it('routes exception actions to the original exception flow rather than a task',async()=>{const api={list:vi.fn().mockResolvedValue({items:[row],nextCursor:null}),detail:vi.fn().mockResolvedValue({...detail,action:{kind:'exception',label:'查看原异常处置'},taskId:null,exceptionId:taskId})},task=vi.fn(),exception=vi.fn();render(<TeamManagementPage session={testSession()} api={api} view="exceptions" onView={vi.fn()} onTask={task} onException={exception}/>);fireEvent.click(await screen.findByRole('button',{name:row.customerLabel}));fireEvent.click(await screen.findByRole('button',{name:'查看原异常处置'}));await waitFor(()=>expect(exception).toHaveBeenCalledWith(taskId));expect(task).not.toHaveBeenCalled();});
it('restarts an expired cursor while retaining filters and clears detail',async()=>{const api={list:vi.fn().mockResolvedValueOnce({items:[row],nextCursor:'expired'}).mockRejectedValueOnce(Error('expired')).mockResolvedValue({items:[],nextCursor:null}),detail:vi.fn()},s=testSession();render(<TeamManagementPage session={s} api={api} view="tasks" onView={vi.fn()} onTask={vi.fn()} onException={vi.fn()}/>);fireEvent.click(await screen.findByRole('button',{name:'下一页'}));await screen.findByText('本次读取失败，请重新查询。');fireEvent.click(screen.getByRole('button',{name:'重新查询'}));await screen.findByText('当前筛选下没有事项，不代表全部业务已完成。');expect(api.list).toHaveBeenLastCalledWith(s,'tasks',expect.objectContaining({cursor:undefined}),expect.any(AbortSignal));});
it('does not show an old response after identity changes',async()=>{let resolve!:(value:unknown)=>void;const old=testSession(),fresh={...testSession(),actorScopeKey:'new-scope'},api={list:vi.fn().mockReturnValueOnce(new Promise(r=>{resolve=r;})).mockResolvedValue({items:[],nextCursor:null}),detail:vi.fn()};const props={api,view:'tasks' as const,onView:vi.fn(),onTask:vi.fn(),onException:vi.fn()};const r=render(<TeamManagementPage {...props} session={old}/>);await waitFor(()=>expect(api.list).toHaveBeenCalledTimes(1));old.isCurrent=()=>false;r.rerender(<TeamManagementPage {...props} session={fresh}/>);await screen.findByText('当前筛选下没有事项，不代表全部业务已完成。');resolve({items:[row],nextCursor:null});await waitFor(()=>expect(screen.queryByRole('button',{name:row.customerLabel})).toBeNull());});
it('clears query text when changing identity so prior client names are not retained',async()=>{const api={list:vi.fn().mockResolvedValue({items:[],nextCursor:null}),detail:vi.fn()},s=testSession(),other={...testSession(),actorScopeKey:'other-identity',identityEpoch:s.identityEpoch+1};const props={api,view:'tasks' as const,onView:vi.fn(),onTask:vi.fn(),onException:vi.fn()};const r=render(<TeamManagementPage {...props} session={s}/>);fireEvent.change(screen.getByLabelText('搜索客户或责任人'),{target:{value:'原任职客户'}});r.rerender(<TeamManagementPage {...props} session={other}/>);expect(screen.getByLabelText('搜索客户或责任人')).toHaveValue('');});

it('does not navigate when a pending action check returns after switching views',async()=>{let resolve!:(value:unknown)=>void;const api={list:vi.fn().mockResolvedValue({items:[row],nextCursor:null}),detail:vi.fn().mockResolvedValueOnce(detail).mockImplementationOnce(()=>new Promise(r=>{resolve=r;}))},session=testSession(),onTask=vi.fn(),props={session,api,onView:vi.fn(),onTask,onException:vi.fn()};const r=render(<TeamManagementPage {...props} view="tasks"/>);fireEvent.click(await screen.findByRole('button',{name:row.customerLabel}));fireEvent.click(await screen.findByRole('button',{name:'前往办理'}));await waitFor(()=>expect(api.detail).toHaveBeenCalledTimes(2));r.rerender(<TeamManagementPage {...props} view="waiting"/>);await act(async()=>{resolve(detail);await Promise.resolve();});expect(onTask).not.toHaveBeenCalled();});
