import {render,screen,fireEvent} from '@testing-library/react';
import {describe,it,expect,vi} from 'vitest';
import {TeamLedger,type TeamLedgerProps} from './TeamLedger';
const row={id:'one',customerLabel:'合成客户',purposeLabel:'核对本笔收款',stateLabel:'已逾期',ownerLabel:'合成财务任职',timeLabel:'原期限昨天17:00'};
function props():TeamLedgerProps{return {view:'tasks',rows:[row],detail:{id:'one',customerLabel:row.customerLabel,facts:[['原期限','昨天17:00']],history:[{id:'event',label:'当时确认人 · 退回原因'}],nextAction:'本笔收款独立核对',action:null},selectedId:'one',search:'',state:'',states:['已逾期'],loading:false,permitted:true,onView:vi.fn(),onSearch:vi.fn(),onState:vi.fn(),onSelect:vi.fn(),onHandle:vi.fn(),onReload:vi.fn(),onClear:vi.fn()};}
describe('S frozen team ledger',()=>{
 it('presents deadlines and history in Beijing time across a UTC date boundary',()=>{const p=props();p.rows=[{...row,timeLabel:'2026-09-20T16:00:00Z（原期限）'}];p.detail={...p.detail!,facts:[['原办理期限','2026-09-20T16:00:00Z'],['原因或说明','保留原说明']],history:[{id:'time',label:'2026-09-20T16:00:00Z · 形成责任'}]};render(<TeamLedger {...p}/>);expect(screen.getByText('2026/09/21 00:00（原期限）')).toBeTruthy();expect(screen.getByText('2026/09/21 00:00')).toBeTruthy();expect(screen.getByText('2026/09/21 00:00 · 形成责任')).toBeTruthy();expect(screen.getByText(/时间按北京时间显示/)).toBeTruthy();expect(screen.queryByText(/2026-09-20T16/)).toBeNull();});
 it('shows authorized detail and collapsible history without inventing a command',()=>{render(<TeamLedger {...props()}/>);expect(screen.getByRole('heading',{name:'团队待办'})).toBeTruthy();expect(screen.getByText('本笔收款独立核对')).toBeTruthy();expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();expect(screen.getByText('查看处理记录与依据').closest('details')?.open).toBe(false);});
 it('clears rows and detail during loading, failure or revocation',()=>{const p=props(),r=render(<TeamLedger {...p}/>);for(const state of [{loading:true},{error:'读取失败'},{permitted:false}]){r.rerender(<TeamLedger {...p} {...state}/>);expect(screen.queryByText('本笔收款独立核对')).toBeNull();expect(screen.queryByRole('button',{name:row.customerLabel})).toBeNull();}});
 it('only delegates a supplied original-task action and respects stale selection',()=>{const p=props();p.detail={...p.detail!,action:{kind:'task',label:'前往办理'}};const r=render(<TeamLedger {...p}/>);fireEvent.click(screen.getByRole('button',{name:'前往办理'}));expect(p.onHandle).toHaveBeenCalledWith('one');r.rerender(<TeamLedger {...p} selectedId="another"/>);expect(screen.queryByRole('button',{name:'前往办理'})).toBeNull();});
 it('delegates view and filter reads without transforming business state',()=>{const p=props();render(<TeamLedger {...p}/>);fireEvent.change(screen.getByLabelText('查看内容'),{target:{value:'waiting'}});expect(p.onView).toHaveBeenCalledWith('waiting');fireEvent.change(screen.getByLabelText('搜索客户或责任人'),{target:{value:'财务'}});expect(p.onSearch).toHaveBeenCalledWith('财务');expect(p.onHandle).not.toHaveBeenCalled();});
});
